### ISSUE TITLE
[HL1] Half-life Double graphic card - low fps after update.

### ISSUE THREAD

**Issue by Paradauskas** [ValveSoftware/halflife#10]
Hello,
I got a laptop with integrated and Nvidia 525 MX graphic cards.
After the update I cant edit my graphic options and use nvidia. Cant change prefered graphic card.
Half-life stays from 10-50 fps with 2gb graphic card.

![Untitled](https://f.cloud.github.com/assets/3597622/158701/e0ace46a-76f0-11e2-851e-99b2f5d776ac.png)

**Comment by shawns-valve** [comment]
Closing due to age. Please reopen / create a new issue if this still occurs with the 25th anniversary update (December 2023 Steam build) and current graphics drivers.
