### ISSUE TITLE
[HL:OF] Grapple Problems

### ISSUE THREAD

**Issue by x414e** [ValveSoftware/halflife#1025]
The grapple makes a ladder climbing sound when you use it.
Also the alternate fire does not seem to work, I press it and instead of hanging I just drop down. This means I cannot get down from anywhere without taking fall damage.

**Comment by SamVanheer** [comment]
This happens because the player physics code plays ladders sounds if the player's movetype is MOVETYPE_FLY. The grapple sets the player's movetype to that when it latches onto something that it pulls players towards.

The second issue is probably just the difference between OP4's grapple and Sven Co-op's: the latter has the behavior that you describe, the former does not.

**Comment by SamVanheer** [comment]
@mikela-valve seems like an easy fix, and it restores original behavior.

**Comment by mikela-valve** [comment]
Fixed, will be included in the next update. I grep'ed the code base for FL_IMMUNE_LAVA and it looks like CS:CZ's zipline also uses it for the same purpose as the barnacle grapple so this should fix any problems with that as well.

**Comment by mikela-valve** [comment]
Fixed in beta 'Exe build: 11:12:36 May 21 2019 (8244)',

**Comment by agrastiOs** [comment]
Retested, it's fixed.

**Comment by BlackShadow306** [comment]
@mikela-valve What about this? 🤔 This issue happens when you try grapple wall very close.

Here's a footage regarding bug:

https://streamable.com/yu8hs

**Comment by SamVanheer** [comment]
That's a preexisting bug and should be reported separately.

**Comment by BlackShadow306** [comment]
Yeah, this bug is there since first release of the game. But didn't wanted to spam Issues tab so just posted here.

**Comment by mikela-valve** [comment]
Closing as fixed.
@BlackShadow306 Thanks for trying to keep down the issue count but it's better to open that as another bug.

**Comment by djearthquake** [comment]
Alternate fire still does not work. I did not even know there was one!

**Comment by SamVanheer** [comment]
Like i said before:

> The second issue is probably just the difference between OP4's grapple and Sven Co-op's: the latter has the behavior that you describe, the former does not.

There is code for a secondary attack but all it does is detach the grapple, which should happen automatically when you release primary attack.
