### ISSUE TITLE
[HL:OF] Desert Eagle Bug

### ISSUE THREAD

**Issue by serfreeman1337** [ValveSoftware/halflife#1042]
Desert Eagle won't fire after im tryed to shoot from it in water:
If you try to shoot from eagle in water its jam and no longer you can to fire from ANY eagles (if you drop and pickup another its still didnt work). Its fixing only by reconnect.

Desert Eagle recoil laser system bug:
Sometimes eagle got confused if you twice turn on and turn off his laser. You can shoot more accuracy and faster without laser and more randomly and slower with laser.

**Comment by Toybasher** [comment]
Sorry to bump this, but I'm hoping Valve is still working on this (The update to Blue Shift a few years ago gives me hope.) 

I'm doing a OP4 playthrough and the desert eagle accuracy/laser bug is really causing me problems.

As serfreeman1337 said, sometimes (rather often if you ask me.) the accuracy for the two modes gets swapped, making the slow firing laser sighted mode inaccurate, and the fast firing non-laser sighted mode accurate.

Sometimes it goes away, but it's hard to really test. I don't know exactly what causes it. I was thinking it might have to do with toggling the laser sight on and off quickly.

 (If you right click quickly, you'll notice you can only turn the laser on and off maybe once every second. Maybe if you right click twice quickly, you turn the laser off, but when you click the second time, the game thinks you set it back to laser sighted mode, but you were too quick for the gun to set the laser back on, so you keep the fast firing rate with perfect accuracy.) 

That's what I was thinking it might be, but when I've had the bug, I've tried double right clicking in an attempt to swap the functions back to normal again but I couldn't seem to fix it, so it might be something else.

I'm hoping Valve is still supporting the old HL1 series. They're old but great, and a bug like this is almost game breaking. You can have "Accurate Mode" be extremely inaccurate and waste your ammo, and on the other hand you can have a literally perfectly accurate machine-magnum that mows down enemies.

**Comment by SamVanheer** [comment]
This happens because the Desert Eagle uses the game time variable to set the next attack time when underwater:

```
if ( m_pPlayer->waterlevel == 3 )
  {
    PlayEmptySound();
    m_flNextPrimaryAttack = gpGlobals->time + 0.15;
  }
```

The Desert Eagle uses client side prediction, so it should be using CBasePlayerWeapon::UTIL_WeaponTimeBase here.

**Comment by SamVanheer** [comment]
@mikela-valve This is an easy fix.

**Comment by Solokiller** [comment]
@kisak-valve this can be labeled `fix proposed`.
