### ISSUE TITLE
[CS 1.6] Fatal Error = Failed to create SDL Window

### ISSUE THREAD

**Issue by Ezsouth** [ValveSoftware/halflife#109]
![Untitled](https://f.cloud.github.com/assets/3606136/162351/cf492c36-77b5-11e2-9414-5977c099f406.png)

Tried re installing cs 1.6 and steam
deleted registry involving valve and cs 1.6
restarting computer
Maybe it has to do something with the driver i currently have?
cs 1.6 ran fine before the feb 14 update

**Comment by Bhupesh7** [comment]
You have to change some settings if you want to fix fatal error in CS1.6
Read Here : http://www.techpayee.com/fix-counter-strike-1-6-fatal-error/
