### ISSUE TITLE
[CS 1.6] .wav files missing when joining a New Game

### ISSUE THREAD

**Issue by healthycs16** [ValveSoftware/halflife#1113]
Usage:
Setmaster unavailable, start a server first.
maxplayers cannot be changed while a server is running.

BUILD 5999 SERVER (0 CRC)
Server # 4
Warning:  Unable to open sound/misc/kenny1.wav for transfer
Warning:  Unable to open sound/misc/cracker1.wav for transfer
Warning:  Unable to open sound/misc/shot1.wav for transfer
Warning:  Unable to open sound/misc/revenge1.wav for transfer
Warning:  Unable to open sound/misc/doh.wav for transfer
Warning:  Unable to open sound/misc/nam1.wav for transfer
Warning:  Unable to open sound/misc/kickass1.wav for transfer
Warning:  Unable to open sound/misc/comeagain.wav for transfer
Warning:  Unable to open sound/misc/awwcrap2.wav for transfer
Warning:  Unable to open sound/misc/awwman.wav for transfer
Warning:  Unable to open sound/misc/woohoo2.wav for transfer
Warning:  Unable to open sound/misc/dohoo.wav for transfer
Warning:  Unable to open sound/misc/dohnuts.wav for transfer
Warning:  Unable to open sound/misc/doh2.wav for transfer
Warning:  Unable to open sound/misc/doh3.wav for transfer
Warning:  Unable to open sound/misc/doh4.wav for transfer
Warning:  Unable to open sound/misc/doh5.wav for transfer
Warning:  Unable to open sound/misc/doh7.wav for transfer
Error: server failed to transmit file 'sound/misc/kenny1.wav'
Error: server failed to transmit file 'sound/misc/cracker1.wav'
Error: server failed to transmit file 'sound/misc/shot1.wav'
Error: server failed to transmit file 'sound/misc/revenge1.wav'
Error: server failed to transmit file 'sound/misc/doh.wav'
Error: server failed to transmit file 'sound/misc/nam1.wav'
Error: server failed to transmit file 'sound/misc/kickass1.wav'
Error: server failed to transmit file 'sound/misc/comeagain.wav'
Error: server failed to transmit file 'sound/misc/awwcrap2.wav'
Error: server failed to transmit file 'sound/misc/awwman.wav'
Error: server failed to transmit file 'sound/misc/woohoo2.wav'
Error: server failed to transmit file 'sound/misc/dohoo.wav'
Error: server failed to transmit file 'sound/misc/dohnuts.wav'
Error: server failed to transmit file 'sound/misc/doh2.wav'
Error: server failed to transmit file 'sound/misc/doh3.wav'
Error: server failed to transmit file 'sound/misc/doh4.wav'
Error: server failed to transmit file 'sound/misc/doh5.wav'
Error: server failed to transmit file 'sound/misc/doh7.wav'
healthycs16 connected
healthycs16 is joining the Terrorist force
   VAC secure mode disabled.
Scoring will not start until both teams have players

**Comment by elmatadour** [comment]
Error: server failed to transmit file 'sound/misc/dohoo.wav'
Error: server failed to transmit file 'sound/misc/dohnuts.wav'
Error: server failed to transmit file 'sound/misc/doh2.wav'
Error: server failed to transmit file 'sound/misc/doh3.wav'
Error: server failed to transmit file 'sound/misc/doh4.wav'
Error: server failed to transmit file 'sound/misc/doh5.wav'
Error: server failed to transmit file 'sound/misc/doh7.wav'

**Comment by tschumann** [comment]
Do you have a plugin installed locally?
