### ISSUE TITLE
[HL1] Impossible go through gates in lambda core chapter (lambda reactor core a)

### ISSUE THREAD

**Issue by tarvitz** [ValveSoftware/halflife#1120]
After proceeding several portals near "Lambda reactor core A" there is a room with locked door gate, which  should be open with help of scientist. But it didn't happen, action scene , which should open the door, plays only a half so the door is locked.

Tried to make restart, reload the game but it didn't help.
Here is the taken video of the bug:

http://youtu.be/arrYVc24OwE

**Comment by Maxi605** [comment]
@kisak-valve Maybe this should be closed, it's been a long time since, probably the author found a solution to the issue.

**Comment by tarvitz** [comment]
I found indeed, I thought it was closed already 😅
