### ISSUE TITLE
[HL1 Client] room_type stuck and stopsound needed applied

### ISSUE THREAD

**Issue by APGRoboCop** [ValveSoftware/halflife#1144]
Hello when I play any HL1 mod with a echo Sound environment where the map goes to room_type 1 or 9 it stays like that where the sounds echo a bit but won't go back to the default room_type 0 for some reason, when I load nextmap on my HLDM SteamCMD server when datacore map gave me that room_type 9. Now I vaguely remember this occurs on some of the CS 1.6 and TFC like that shutdown2 train sound where I had to stop the annoy train noise repeating by typing "stopsound" in console.

Is there a way of execing the cfg automatically like autoexec.cfg "stopsound" or "room_type 0" used when loading nextmap?

**Comment by SamVanheer** [comment]
Was this actually fixed? I tested this with a dedicated server (vanilla HL and CS) and the `room_type` cvar did not reset. I also can't find anything sending a `room_type 0` command or equivalent user message.

There is this line:
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/dlls/world.cpp#L491

But that's always been there. It resets the setting in singleplayer as expected. It does not work when connected to a dedicated server.
