### ISSUE TITLE
Animation synching issue in Blast Pit scripted sequence

### ISSUE THREAD

**Issue by UndeadScottsman** [ValveSoftware/halflife#1148]
During Blast Pit, the tentacle will burst through a window, pick up a scientist and carry him away; but the animations don't synch up so the scientist trails behind a little bit instead of being carried directly.  Looks like he's floating.
EDIT: Occurs on map c1a4i

https://www.youtube.com/watch?v=wnwuIOSefSs

OS: Windows 7
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 17:47:17 Apr 25 2013 (6027)

**Comment by Switchbreak** [comment]
It looks like this problem was introduced by the HD models from Blue Shift. If you turn HD models on the scene plays correctly, but with original models (which is now the default), it's broken.

**Comment by lightningterror** [comment]
This was fixed on 22 November.

**Comment by kisak-valve** [comment]
Closing per the last comment and "Fixed timing for the sequence where a tentacle grabs a scientist in Blast Pit." in the [2023-11-22](https://steamcommunity.com/games/70/announcements/detail/3877098283535054952) Half-Life update.
