### ISSUE TITLE
Half-life based titles installed to wrong location

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/halflife#1157]
I notice that on my steam, if I have Half-Life installed to alternate location eg /mnt/games/SteamApps, then install any HL based titles such as cstrike/op force etc they will not be installed inside Half-life dir in that alt location but they are installed in SteamApps in steam base dir

**Comment by SamVanheer** [comment]
The issue on the steam-for-linux tracker was closed as fixed, so this one should also be closed.
