### ISSUE TITLE
cl_crosshair_size and cl_crosshair_translucent problem

### ISSUE THREAD

**Issue by Maksim48** [ValveSoftware/halflife#1202]
resulution 640x480 cl_crosshair_size medium or small

cl_crosshair_translucent 0
![pic1](https://f.cloud.github.com/assets/4633925/625115/79722b9e-cf96-11e2-9046-a9f2ffba2fbf.png)
cl_crosshair_translucent 1
![pic2](https://f.cloud.github.com/assets/4633925/625140/34fee992-cf97-11e2-9839-4fe3e42fd177.png)

**Comment by djdallmann** [comment]
I experience this too, seems like an easy fix @mikela-valve if you have time.

**Comment by mikela-valve** [comment]
@djdallmann This should be fixed in the current CS beta.

**Comment by di57inct** [comment]
@mikela-valve thank you. For everything.
I also noticed that the crosshair is a bit off-center. Can you look into that and fix it too?

**Comment by djdallmann** [comment]
**Fixed in current beta** now, woohoo. @mikela-valve we all appreciate your current work on this.

**Comment by mikela-valve** [comment]
@di57inct Could possibly you post a couple of screenshots like the ones above? Also, is it off center for both crosshair types?

**Comment by mikela-valve** [comment]
I'm going to close this issue as fixed. @di57inct if you still find that the crosshair is off-center, please make a new issue for tracking it.
