### ISSUE TITLE
[CS 1.6] Custom sprays - still not working??

### ISSUE THREAD

**Issue by Im2bz2p345** [ValveSoftware/halflife#1219]
Why are custom sprays _still_ NOT working with CS 1.6 after the "big update" a few months back?

Lack of Valve thinking things through all the way has shown a countless number of times - seems like they just like to release stuff & then play "repairman" afterwards with updates/patches/etc.

Please response if you know how to make custom CS 1.6 work like they used? By that I mean, I still have my "tempdecal.wad" file from before the update (when custom sprays actually worked). I just want to be able to put it back in my cstrike folder and the servers show the spray in-game.

Thank you!

**Comment by nicogaldo** [comment]
dont work for me :(
