### ISSUE TITLE
[OP4] Game tries to display missing chapter title in of3a1b

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/halflife#1243]
https://drive.google.com/file/d/0B8l-2_JREU9IOVVleFg3U2NOdVE/edit?usp=sharing
(Patched BSP)

If you try to follow Freeman through the portal from of3a1, the next map displays "C4A1TITLE" since the chapter keyvalue was never removed from worldspawn when the map was made.

**Comment by SamVanheer** [comment]
As noted this is a duplicate.
