### ISSUE TITLE
No chinese characters, only squares.

### ISSUE THREAD

**Issue by Tehmal** [ValveSoftware/halflife#1269]
locale
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:en
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC=zh_CN.UTF-8
LC_TIME=zh_CN.UTF-8
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY=zh_CN.UTF-8
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER=zh_CN.UTF-8
LC_NAME=zh_CN.UTF-8
LC_ADDRESS=zh_CN.UTF-8
LC_TELEPHONE=zh_CN.UTF-8
LC_MEASUREMENT=zh_CN.UTF-8
LC_IDENTIFICATION=zh_CN.UTF-8
LC_ALL=

System info:
处理器信息：
    供应商：AuthenticAMD
    速度：2900 Mhz
    2 个逻辑处理器
    2 个物理处理器
    超线程：不支持
    FCMOV：支持
    SSE2：支持
    SSE3：支持
    SSSE3：不支持
    SSE4a：支持
    SSE41：不支持
    SSE42：不支持

网络信息：
    网络速度：

操作系统版本：
    Ubuntu 13.04（64 位）
    内核名称：Linux
    内核版本：3.8.0-27-generic
    X 服务器供应商：The X.Org Foundation
    X 服务器发布：11303000
    X Window 管理器：Xfwm4
    Steam 运行时刻版本：steam-runtime-release-i386_2013-06-28

显卡：
    驱动程序：NVIDIA Corporation GeForce GTS 250/PCIe/SSE2

```
驱动程序版本：3.3.0 NVIDIA 325.08
桌面色深：每像素 24 位
显示器刷新率：60 Hz
供应商 ID：0x10de
设备 ID：0x615
显示器数：1
逻辑显卡数：1
主显示分辨率：1280 x 1024
桌面分辨率：1280 x 1024
主显示大小：14,80" x 11,85"（尺寸 18,94"）
```

 37,6cm x 30,1cm（尺寸 48,1cm）
    主总线：PCI Express 16x
    主 VRAM：1024 MB
    支持的 MSAA 模式：2x 4x 8x 16x 

声卡：
    音频设备：Realtek ALC889A

内存：
    RAM：3950 Mb

其他：
    用户界面语言：简体中文
    LANG:  zh_CN.UTF-8
    麦克风：Not set
    可用的硬盘空间总大小：548656 Mb
    最大的空余硬盘区块：106383 Mb

已安装软件：

近期故障报告：
    Sun Aug  4 15:08:40 2013 GMT: file ''/tmp/dumps/crash_20130804170624_1.dmp'', upload yes: ''CrashID=bp-2e427742-2d1e-4eb1-bffe-6c41c2130804''

Steam language: chinese

And cannot write at chinese, im using fcitx (ibus sucks) (i must copy and paste text)

**Comment by leonpano2006** [comment]
> This is fixed in the Half-Life beta update.

are you sure is that fixed?
now is even worse 
is showing nothing insted of showing squares for chinese letthers(english is showing)
