### ISSUE TITLE
[TFC] Holster weapon & func_tank use

### ISSUE THREAD

**Issue by tehORiON** [ValveSoftware/halflife#1276]
When you use a func_tank and your current weapon is e.g. the crowbar, it appears to holster the weapon, but when you hit your attack button it will bring the weapon back and you will attack with it whilest attacking with the func_tank. This appears to be a client issue only.

Testmap: http://www.sendspace.com/file/mk6598

**Comment by Demon1986** [comment]
dear Valve. can you fix this while ur in the process of updating the game? seeing as it isn't fixed in the current beta. (all platforms)

**Comment by mikela-valve** [comment]
Fixed, this will be included in the next beta update.

**Comment by mikela-valve** [comment]
Fixed in 'Exe build: 11:12:36 May 21 2019 (8244)'.

**Comment by mikela-valve** [comment]
Closing as fixed.
