### ISSUE TITLE
CS 1.6 4 fps in menu and in game on OpenGL

### ISSUE THREAD

**Issue by eXpressionist** [ValveSoftware/halflife#1353]
CS worked fine like couple of days ago, and today 4 fps in menu and in game (OpenGL). I'm not sure is there any updates before that. 
Reinstalled CS from scratch (removed all Half-Life or CS folders from Steam), cleaned registry - doesn't help. Tried beta - no difference. 
Tried -nofbo and GL_NEAREST_MIPMAP_NEAREST - doesn't help at all. 
Software mode runs pretty fast, but quality rather bad.

p.s. W7 x64, i3 2120, 12Gb ram, GTX 760 2Gb. All drivers and DX are latest.

**Comment by sjain882** [comment]
Same issue
