### ISSUE TITLE
[GoldSRC] [Feature Request] Half-Life Decay for official Steam release?

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/halflife#1382]
It's been 12 years since Decay has been released on the Sony Playstation 2, and Decay hasn't made it's own PC release, excluding a Fan Made port of it. It would also be neat to have it for the Steam Machine since it was a Co-Op Game.

Close this is if you guys don't have a source code for it.

**Comment by Hubbenobo** [comment]
> This is way beyond the scope of our current updates (and the whole I have no idea where the code is :)

https://www.moddb.com/mods/half-life-decay-v102/downloads/half-life-decay-v1021-full
