### ISSUE TITLE
[HL1|MODDING] "dlfile" command doesn't work

### ISSUE THREAD

**Issue by cfjiw** [ValveSoftware/halflife#1404]
Hey there, me and a friend are developing a mod for HL1. We're trying to get server generated scripts in our mod to be requested and downloaded by each client. The only way we've been informed this is possible is with using the "dlfile" command. However we've been attempting to use this command to no avail. We've made sure the cvars: "sv_allowdownload" and "sv_allow_dlfile" are enabled by the server and "cl_allowdownload" and "cl_download_ingame" are also enabled by the client, but we still are having no success with this command. We're wondering if there's any way possible if not possible with the "dlfile" command, that we can get clients to request and download specific server-generated files for our mod.

Thanks,
Jay

PS: if the "dlfile" command has been disabled in any shape or form, may I request that it may be restored? (Perhaps as an engine function if not a console command)

**Comment by SamVanheer** [comment]
The `dlfile` command was disabled to prevent downloading of malicious files. For security reasons it can't be enabled again, so this issue can be closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
