### ISSUE TITLE
[DoD] Scoreboard height

### ISSUE THREAD

**Issue by serfreeman1337** [ValveSoftware/halflife#1407]
When there is too much players, you see some players cant be fit into scoreboard.

Image:
Spectators are out of the scoreboard.
![dod_saints0001](https://f.cloud.github.com/assets/2133936/1491262/53fbdd56-47aa-11e3-81ae-2c083f5d49bf.JPG)

DoD version:

```
Protocol version 48
Exe version 1.1.2.6/Stdio (dod)
Exe build: 13:14:12 Aug 29 2013 (6153)
```

Screen size: 1280x1024

**Comment by BlackShadow** [comment]
@mikela-valve Can confirm, this issue is still present.

![20190724112619_1](https://user-images.githubusercontent.com/30868395/61777687-034e2300-ae06-11e9-99b4-6b96bd66ab16.jpg)
