### ISSUE TITLE
[Goldsrc] Add -high command line parameter

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/halflife#1410]
Source games have a command line parameter to automatically set the process priority to high by using the -high command line parameter. Could you also add the -high command line parameter to Goldsrc games too? It gets annoying having to open the task manager and find the hl.exe and switch the priority to high everytime you play.

**Comment by SamVanheer** [comment]
Duplicate of #709

**Comment by kisak-valve** [comment]
Closing as a duplicate.
