### ISSUE TITLE
r_cullsequencebox?

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/halflife#1411]
What does this command do? I have searched the internet, and have found no legit definition. I know what culling does, but what is the sequence box? If I set this to "0", will it disable culling on the sequence box, or is it the other way around?

**Comment by tschumann** [comment]
I'm not completely sure what the sequence box is but it's probably the bounding box for a model's sequence (animation).
Does changing the cvar have any visible effect?

**Comment by shoober420** [comment]
No, i can't notice a difference
