### ISSUE TITLE
[GoldSrc] _set_vid_level

### ISSUE THREAD

**Issue by M3KA125** [ValveSoftware/halflife#1423]
all required information about the issue is inside the file
https://mega.co.nz/#!nN9WXYaC!FwzZTRweDj_w5uptF_SNhG33ZFpYad6k1nUWAj4hrzE

**Comment by SamVanheer** [comment]
File no longer exists, so this issue has no useful information.

**Comment by kisak-valve** [comment]
Closing per the last comment.
