### ISSUE TITLE
[TFC] Suggestion: class config exec for civilian

### ISSUE THREAD

**Issue by Demon1986** [ValveSoftware/halflife#1426]
many of us who still play tfc are likely to play civilian in many of the maps that has it, what i would like is, that theres a possibility for a civilian.cfg like we have for all the 9 other classes, instead of having the civi use the last executed, as some of us who use class configs actually have binds with the class name included, not a big deal, but it would certainly be usefull.

**Comment by mikela-valve** [comment]
Added, will be in next update.

**Comment by mikela-valve** [comment]
Added in 'Exe build: 11:12:36 May 21 2019 (8244)'.

**Comment by mikela-valve** [comment]
Closing as fixed.
