### ISSUE TITLE
GoldSrc and Source Games Won't Launch

### ISSUE THREAD

**Issue by mmstick** [ValveSoftware/halflife#1467]
==== Terminal Log =======
Focused window is now 0, 0
OnFocusWindowChanged to unknown window type: k_EWindowTypeNonSteamDesktop, 0
Installing breakpad exception handler for appid(steam)/version(1389129507_client)
Focused window is now 1, 0
OnFocusWindowChanged to unknown window type: k_EWindowTypeSteamDesktop, 0
Game update: AppID 70 "Half-Life", ProcID 5375, IP 0.0.0.0:0
ERROR: ld.so: object '/home/mmstick/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/home/mmstick/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
CGameStreamThread: Added instance ID 5375 for appid 70
CGameStreamThread: Set render instance ID 5375 for appid 70
CGameStreamThread: Added instance ID 5376 for appid 70
pid 5378 != 5377, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/mmstick/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/home/mmstick/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
CGameStreamThread: Added instance ID 5377 for appid 70
CGameStreamThread: Added instance ID 5379 for appid 70
CGameStreamThread: Added instance ID 5380 for appid 70
Using breakpad crash handler
Setting breakpad minidump AppID = 70
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197993228382 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561197993228382
ERROR: ld.so: object '/home/mmstick/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20140120121149_1.dmp
/home/mmstick/.steam/steam/SteamApps/common/Half-Life/hl.sh: line 38:  5380 Segmentation fault      ${DEBUGGER} "${GAMEROOT}"/${GAMEEXE} $@
CGameStreamThread: Added instance ID 5386 for appid 70

Game removed: AppID 70 "Half-Life", ProcID 5380 

Focused window is now 0, 0
OnFocusWindowChanged to unknown window type: k_EWindowTypeNonSteamDesktop, 0
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-a6fac5b6-056d-496e-8366-9bdbe2140120
pid 5387 != 5386, skipping destruction (fork without exec?)

==== Crash Dump ====
http://www.mediafire.com/download/w62jhhdloc08p31/crash_20140120121149_1.dmp

==== System Information ====
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x1
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3900 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu Trusty Tahr (development branch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-031300rc8-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11405000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD TAHITI

```
Driver Version:  3.0 Mesa 10.1.0-devel (git-05da4a7 saucy-oibaf-ppa+curaga)
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x679a
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1200
Desktop Resolution: 1920 x 1200
Primary Display Size: 23.35" x 14.61"  (27.52" diag)
                                        59.3cm x 37.1cm  (69.9cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  15994 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  668866 Mb
    Largest Free Hard Disk Block:  432586 Mb

**Comment by SamVanheer** [comment]
Per Kisak's last comment in https://github.com/ValveSoftware/Source-1-Games/issues/1548 this issue should probably be closed as well.

**Comment by kisak-valve** [comment]
Looks like this was resolved on the OpenGL driver side back in January 2014.
