### ISSUE TITLE
[HL] (UTF-8/UNICODE bug) Doesn't show text in the HUD when play as TChinese 

### ISSUE THREAD

**Issue by deept-mods** [ValveSoftware/halflife#1520]
TChinese Version Doesn't show text in the HUD
You can test in training room.

See normal example link:
http://i1.ytimg.com/vi/JCEtxaTTcxE/maxresdefault.jpg

I mean it should show out something  like "HAZARD COURSE".
or
"按下向前移動鍵以向前移動
按下向後移動鍵以向後移動
按下向左移動鍵以向左移動
按下向右移動鍵以向右移動"

But now it shows such as "T0A0TITLE" , "HZMOVE".

you can search "HZMOVE" it in "X:\Steam\steamapps\common\Half-Life\valve_tchinese\titlee.txt"
I think the problem is in the file.

It shows perfect i remeber is build 4554... or 3939
now, the all GoldSrc engine game have problem like this

Even the use the command "exec xxx.cfg" in UTF-8, (it can let you show chinese or japanese by using utf8 out put in chat),
Now, it is not working....

**Comment by deept-mods** [comment]
I found this DOD sample on some web:
http://www.99danji.com/upload/20117/2011070834850753.jpg
In DOD or CS1.6 or CZ, the White or Green words shows fine.
But in HL1 it shows "T0A0TITLE" , "HZMOVE".

**Comment by alfred-valve** [comment]
Half Life does not have support for non-latin characters in its main HUD.

**Comment by deept-mods** [comment]
If HL does not support it.
So why is the file translate for? "X:\Steam\steamapps\common\Half-Life\valve_tchinese\title.txt"
Should keep this file english without translate!!
Not just showing the "T0A0TITLE" , "HZMOVE".

Many thanks
