### ISSUE TITLE
[HL1] [REQUEST] Add viewroll and old viewmodel bob

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/halflife#1544]
After version 1.1.1.0 (i think), the viewroll when strafing left and right was removed, alongside the old viewmodel bob. Video demonstration (0.38-0.50s): http://youtu.be/uKkJPFmDW9Q?t=38s

**Comment by JoelTroch** [comment]
@L453rh4wk Did you find that yourself or have you made a Google search and came accross this : http://am.half-lifecreations.com/forums/index.php?topic=288.0 ?

**Comment by SABIAN56** [comment]
@L453rh4wk I can't find hud.cpp plz help

**Comment by DiseCoding-or-DiseGames** [comment]
@L453rh4wk I can't find .cpp files?

**Comment by tschumann** [comment]
https://github.com/ValveSoftware/halflife/blob/master/cl_dll/hud.cpp

**Comment by JessicoG** [comment]
How can I do that ? I don't understand nothing of programming.

**Comment by JessicoG** [comment]
1>c:\users\geninho\desktop\src_dll\cl_dll\hud.cpp(323): error C2065: 'cl_viewrollangle' : undeclared identifier
1>c:\users\geninho\desktop\src_dll\cl_dll\hud.cpp(324): error C2065: 'cl_viewrollspeed' : undeclared identifier

**Comment by tschumann** [comment]
Looks like the lines starting with extern are missing.

**Comment by speedvoltage** [comment]
```
cvar_t *cl_rollangle;
cvar_t *cl_rollspeed;
```

They don't match with
```
**cl_viewrollangle** = CVAR_CREATE ( "cl_viewrollangle", "0.65", FCVAR_CLIENTDLL | FCVAR_ARCHIVE );
**cl_viewrollspeed** = CVAR_CREATE ( "cl_viewrollspeed", "300", FCVAR_CLIENTDLL | FCVAR_ARCHIVE );
```
That's why you are having an error when attempting to build the solution.
The fix is to simply change **cl_rollangle** and **cl_rollspeed** to **cl_viewrollangle** and **cl_viewrollspeed**.

**Comment by BlackShadow306** [comment]
I'm bumping this with hopes.

**Comment by barney-heatwave** [comment]
> I'm bumping this with hopes. It would be a great addition in my opinion. With a simple command such as:
> 
> cl_bob_old "1"

@BlackShadow This feature is in my PR #2900

**Comment by BlackShadow** [comment]
No need to promote your own mod. Bringing old bob is a simple trick.  What we want is bringing old bob in official version.

**Comment by barney-heatwave** [comment]
That's why I opened the PR

**Comment by Solokiller** [comment]
@kisak-valve small note about this issue: it seems that it doesn't show up when you search for it using Github's issue filter system. That might have something to do with the issue creator's account having been deleted.

**Comment by JazzyLazz** [comment]
Is there a way to get this working under the Mac version?

**Comment by hiIexistlol** [comment]
> Is there a way to get this working under the Mac version?

not at all in the official version yet (and maybe never)

**Comment by sabianroberts** [comment]
For the Mac version you need to get Xcode and compile it yourself, I’m afraid I do not have a Mac to compile the dylib files ☹

**Comment by solidi** [comment]
@sabianroberts - [my recent github actions pull request](https://github.com/ValveSoftware/halflife/pull/3113) may be useful in building macOS dylibs without the hardware. I hope it helps!

**Comment by sabianroberts** [comment]
> @sabianroberts - [my recent github actions pull request](https://github.com/ValveSoftware/halflife/pull/3113) may be useful in building macOS dylibs without the hardware. I hope it helps!

That's awesome dude, thanks! Will help with getting Mac support on my own mod

**Comment by DrFerret** [comment]
Does this work on WON v1.1.1.2 or just the steam version?

**Comment by sabianroberts** [comment]
Steam only
________________________________

**Comment by DrFerret** [comment]
> Steam only
> […](#)

Do you know how to get the viewbobbing working on WON?

**Comment by BlackShadow** [comment]
@kisak-valve This can be closed since this is added in latest update
