### ISSUE TITLE
DLC Soundtrack contains popping errors at end of tracks. 

### ISSUE THREAD

**Issue by thegreatprophetzarquon** [ValveSoftware/halflife#1552]
I didn't know where to put this, as it isn't directly related to the engine, but I guess the soundtrack is released with the game.
The new DLC soundtrack contains the standard two seconds of silence at the end of each track, but it also contains a a loud click. This is not present in the in-game audio files. The screenshot shows the problem. (The DLC track is the bottom one.)
![issue](https://cloud.githubusercontent.com/assets/3487466/4433194/d0533002-46c3-11e4-9017-84d4d2bff374.png)

**Comment by SamVanheer** [comment]
The current public version doesn't have this so if somebody else can confirm that, this issue can be closed.

**Comment by thegreatprophetzarquon** [comment]
I can confirm that this was fixed at some point. The current files show no issue.
