### ISSUE TITLE
Corrupted textures on c1a1c

### ISSUE THREAD

**Issue by s0r00t** [ValveSoftware/halflife#1581]
When entering the map, some textures are corrupted.
Pictures : 
- http://steamcommunity.com/sharedfiles/filedetails/?id=365116916
- http://steamcommunity.com/sharedfiles/filedetails/?id=365117244 (see the barrel)
- http://steamcommunity.com/sharedfiles/filedetails/?id=365117289

Additionnal informations : https://gist.github.com/s0r00t/134472a1fa8cd7bac77d
Restarting the game fixes the problem.

**Comment by SamVanheer** [comment]
All of the links are dead and the second command indicates that this is a problem with the driver. It may have been fixed by now.

**Comment by s0r00t** [comment]
Indeed, I deleted those screenshots. I completely forgot about this issue...  
Here's a leftover : https://steamcommunity.com/sharedfiles/filedetails/?id=484967052

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
