### ISSUE TITLE
[HL:OF] Spectator mode does not work

### ISSUE THREAD

**Issue by andrewgillich** [ValveSoftware/halflife#1589]
For a very long time I am worried about this problem. In modes DM / TDM does not work spectator mode, in CTF mode works but not fully as in the original Half-Life.

**Comment by tschumann** [comment]
Yes I think has been an issue forever. I think that those features were introduced into Half-Life in a major update but they weren't entirely backported into Opposing Force. I think Opposing Force also uses an older style scoreboard too.

**Comment by djearthquake** [comment]
Yes please do add spec mode for Deathmatch. OP4 Capture the Flag already has Counter-Strike 1999 spec mode. Metamod eye will tie you over. I was going to make an Amxx overlay for it but have had many other projects to do. Something official would be more beneficial. it already has Cloud Sync and Cstrike does not even do that! This is not too much to ask. If I can already do it with Eye how much trouble is it over all these seemingly trivial bug updates please?

**Comment by teasouse** [comment]
I tried using the Eye plugin, but it crashes my server.
