### ISSUE TITLE
OpenGL or Direct3D?

### ISSUE THREAD

**Issue by Rst-7** [ValveSoftware/halflife#1594]
Counter-Strike 1.6 uses DirectX 7,8,9 or OpenGL? 
Does the launch options - dxlevel 70,80,90?

**Comment by FrenchMan** [comment]
GoldSrc supports OpenGL and software rendering. The _dxlevel_ option is valid only for Source powered games.

**Comment by kriswema** [comment]
And just for the sake of completeness: GoldSrc used to support DirectX, but doesn't anymore since it was made available for Unix-like systems.

**Comment by treetoon** [comment]
Direct3D runs way better on older systems which is why some people are currently forced to run on older versions to get a consistent FPS.

**Comment by SamVanheer** [comment]
This is more a question than a report, and it was answered. This can be closed.
