### ISSUE TITLE
HL: Opposing Force from Steam - Fatal error - Failed to create SDL Window

### ISSUE THREAD

**Issue by JamesDunne** [ValveSoftware/halflife#1606]
Today (2015-04-06), I purchased `Half-Life: Opposing Force` on Steam and installed it fresh without any modifications. Immediately upon opening I get the popup window with this "Failed to create SDL Window" error. On subsequent runs I get another warning dialog about disabling hardware acceleration and falling back to software mode, but it still dies with the fatal error from SDL.

I have searched for a solution to this problem already and found suggestions about adding `-sw`, `-soft`, `-32bpp`, `-dev`, `-w and -h`, `-gl`, `-nofbo` to the launch options and none of those have had any effect on removing the fatal error dialog. SDL simply cannot create a window on my system. I've also tried setting compatibility mode to Windows XP SP2 to no avail. I've tried ticking other compatibility options such as 640x480, 256 colors, disable themes, disable compositing, etc. and none of those have had any effect either.

I paid $5 USD for this game and can't seem to be able to run it at all. I have a relatively modern (2-3yo) system and it should definitely not have any trouble whatsoever running such an old game like this.

My Steam client is up to date, the game content is up to date, integrity of game cache is validated, and my graphics drivers are up to date.

System specs (mostly from nVidia GeForce Experience UI):

Microsoft Windows 7 Ultimate, x64
nVidia GeForce GTX 570
Driver version: 347.88
Intel Core i7-4770K CPU @ 3.50 GHz
8.00 GB RAM
1920 x 1080, 60Hz, 32bpp

Happy to provide any other information.

**Comment by alfred-valve** [comment]
The Steam support team will be able to help you get your game running, you can start a ticket here:
https://support.steampowered.com/

This bug report forum is for clearly defined issues with the game and tracking fixes for them.

**Comment by JamesDunne** [comment]
I will file a ticket there then, but I would also consider this a "clearly defined issue" since the game will not start. :) Thanks!
