### ISSUE TITLE
particleman purpose

### ISSUE THREAD

**Issue by a1batross** [ValveSoftware/halflife#1607]
I am working with HLSDK and stucked with particleman library. What is the particleman in client dlls?

There is no sources of it?

**Comment by tschumann** [comment]
It's a particle system library which was written for Counter-Strike I think.
There's an interface for it somewhere in the source if you want to use it.

**Comment by a1batross** [comment]
Proprietary? Sad.

**Comment by tschumann** [comment]
Hm, oddly there's no Mac or Linux version (I'm checking from Windows but Linux and Mac versions of the other libraries are present).

**Comment by a1batross** [comment]
Why? I am remember that particleman.so is present on my Linux PC.

16:00, вт, 02.06.2015, tschumann <notifications@github.com>:
