### ISSUE TITLE
[Windows] Right click on the taskbar always shows "Half-Life Blue Shift"

### ISSUE THREAD

**Issue by JoelTroch** [ValveSoftware/halflife#1619]
Right clicking on "Half-Life" in the taskbar will always display "Half-Life Blue Shift", even if the game is a mod or vanilla.

See screenshot here :
![hl_win_bug](https://cloud.githubusercontent.com/assets/4483707/7798601/2aabc524-02fc-11e5-92e3-049caaa6d9eb.jpg)

Here I was running Half-Life without mods, ``version`` output :

    Protocol version 48
    Exe version 1.1.2.2/Stdio (valve)
    Exe build: 13:14:12 Aug 29 2013 (6153)

**Comment by gurka** [comment]
This is seems to be a bug (or feature) of Windows. I got multiple shortcuts to hl.exe on my desktop and I get the same text "Half-Life (WON Only)" in my taskbar with all shortcuts, but only one of the shortcuts are named "Half-Life (WON Only)". Also, same thing happens to other programs as well.

**Comment by JoelTroch** [comment]
In this case, I'm closing this, thanks @gurka
