### ISSUE TITLE
director.dll in Half-life?

### ISSUE THREAD

**Issue by tschumann** [ValveSoftware/halflife#1626]
In steamapps/common/valve/dlls/
Anyone know what it's for? I don't remember it being there before.

**Comment by JoelTroch** [comment]
According to IDA, it's a sort of utility library that contains methods for various things about the game, events, console and more stuff.

**Comment by ripieces** [comment]
@JoelTroch that's a bit generic what you said :-D

@tschumann This seems to be a "Director" module that is used by proxy.dll which is used by HLTV (hltv.exe). From the strings I'd guess it allows to direct the demo using certain director events like CAMPATHS, WAYPOINTS and so on, which are replicated/implemented in the client.dll in [CHudSpectator::DirectorMessage](https://github.com/ValveSoftware/halflife/blob/a800ff8246039a6f154cddbe1fb534f60a69729f/cl_dll/hud_spectator.cpp#L681). It might have more functions than that, depending on the director001 interface it exposes, but I didn't look only a few minutes into that director.dll tbh, so I don't know.

**Comment by SamVanheer** [comment]
This question has a valid answer so it can be closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
