### ISSUE TITLE
Problem with building the source code

### ISSUE THREAD

**Issue by Hergan5** [ValveSoftware/halflife#1628]
I have a problem with building the code using Visual C++ 2010 Express, I get the warnings as always, but I also get an error "'p4' is not recognized as an internal or external command, operable program or batch file.".
There's probably a fix for it that's super obvious, but since I'm a super beginner and I don't know how to fix it

**Comment by JoelTroch** [comment]
It's not really an error, the binaries are still built (unless there is a true C++ error). Right click on the projects and remove the post build event where it call "filecopy.bat", "p4" is the shortcut for Perforce, the revision control system that Valve is using.

**Comment by Hergan5** [comment]
@JoelTroch It works, thank you so much!
