### ISSUE TITLE
pfnCreateNamedEntity usage?

### ISSUE THREAD

**Issue by johnstt** [ValveSoftware/halflife#1640]
Hi all,

I'm running into some trouble using the engine function pfnCreateNamedEntity.
I'm getting back a pointer to 0x0 from it when I pass in the string offset of my new entity. I guess this means it doesn't allocate my new entity (although I haven't found any documentation for it).

What is the bare minimum I need for this to work with a new entity type I am adding?
Can anyone provide an example?

Any advice/references would be appreciated!

**Comment by kungfulon** [comment]
Have you linked your new entity with a c++ class through LINK_ENTITY_TO_CLASS?

**Comment by johnstt** [comment]
Yes. 

All my code for this new weapon is reused from an existing one, with the class and entity names changed. Maybe I missed something along the way? Not sure yet..

**Comment by johnstt** [comment]
New info!

If I build a Linux server binary, the new item works (I can create them and pull them out as a player).
If I run a dedicated server off my Windows binary, it works the same.

If I run a listen server off my Windows binary, it doesn't work (can't create the entity).

Any ideas? Maybe it's something about my server and client DLL projects in Visual Studio not being synced correctly?

**Comment by kungfulon** [comment]
hmmm, it's strange. do you have metamod on your listen server?

**Comment by johnstt** [comment]
Aha! I don't use metamod, but I've got gravebot running by default.
If I take that out, my new stuff spawns. I guess gravebot must be trampling on some memory that's tied into my new entities (since they weren't in the game years ago when gravebot was last updated).

Thanks a ton for the help! Closing this now..
