### ISSUE TITLE
[OSX] Buggy GUI (regardless of language)

### ISSUE THREAD

**Issue by VladWinner** [ValveSoftware/halflife#1644]
OS X 10.10.4, Clear Install
Games (On others not tested):
Counter-Strike
Day of Defeat
Half-Life 
![01](https://cloud.githubusercontent.com/assets/13555921/8980837/2f892804-36bc-11e5-8a87-a87ae462acc5.jpg)
![02](https://cloud.githubusercontent.com/assets/13555921/8980839/2f8d3b06-36bc-11e5-9e2a-446e8a093f64.jpg)
![03](https://cloud.githubusercontent.com/assets/13555921/8980838/2f8cbe10-36bc-11e5-906a-7594036f7915.jpg)

**Comment by JoelTroch** [comment]
Probably related to #1656
