### ISSUE TITLE
github.com/dreamstalker/rehlds. Reverse-engineered HLDS on C/C++. It's very nice!

### ISSUE THREAD

**Issue by phantoooooom** [ValveSoftware/halflife#1669]
:)

**Comment by johnstt** [comment]
This raises an obvious question - why isn't hlds open sourced like the client/server binaries? I'd rather use something official from Valve than this other project.

Has anyone else run a CPU profiler on a server and seen all their hotspots inside hlds code?

**Comment by openglhk** [comment]
:+1: good for reference!

**Comment by SamVanheer** [comment]
This isn't a bug report or question, so it can be closed. Other issues cover open sourcing already.
