### ISSUE TITLE
using a different player class

### ISSUE THREAD

**Issue by tschumann** [ValveSoftware/halflife#1679]
Is there any trick to using a different class to CBasePlayer as the player class?
I commented out LINK_ENTITY_TO_CLASS( player, CBasePlayer ); and added LINK_ENTITY_TO_CLASS( player, CModPlayer ); in another file but that alone doesn't seem to be enough.

**Comment by tschumann** [comment]
Anyone? My code is at https://github.com/tschumann/basis/blob/master/dlls/mod/modplayer.cpp and https://github.com/tschumann/basis/blob/master/dlls/mod/modplayer.h if it helps.

**Comment by johnstt** [comment]
I haven't read through much of your stuff yet, but.. does your mod still have lots of leftover code that instantiates CBasePlayer (or casts to it)? 

Does your game crash or do certain features not work? What happens when you try this?

**Comment by tschumann** [comment]
It's mostly the default SDK and it doesn't look like anything directly instantiates a CBasePlayer. There are lots of casts but my class is a sub-class of CBasePlayer so I think it should work.

There are no crashes - I had debug printing in my sub-class that didn't get printed (but debug code in the CBasePlayer methods did).

Maybe my new player class needs its own Spawn method...

**Comment by JoelTroch** [comment]
Since your CModPlayer extends the CBasePlayer class, overriding the Spawn method shouldn't be needed (unless you have to do stuff in it).

It should work because we have something similar in ARRANGEMENT, we have a "CBaseAmWeapon" that is a sub-class of "CBasePlayerWeapon" and all of our weapons are coded with the "CBaseAmWeapon".

I don't see where the problem could be, but just for curiosity, why using a sub-class of CBasePlayer ?

**Comment by tschumann** [comment]
Yes I didn't think I'd need to override Spawn but it was the only thing I could think of. I haven't tested it yet though.
As for why, I've got a mod that changed a lot of Valve code which I'm now trying to update and I don't want to make that mistake again so I'm subclassing new functionality where possible.

**Comment by SamVanheer** [comment]
You can only link one C++ class to a given entity. It will internally dllexport a function with the name of the entity that the engine will then use to create it. In the case of players, your own code is usually going to be responsible for creating it, probably in ClientConnect or ClientPutInServer (look for GetClassPtr((CBasePlayer *)pev)). 

If you want multiple player classes, either use composition for specific behaviors in CBasePlayer, or use a base class for players and subclass it. Then instantiate the correct class when the player connects. Making the instantiation more explicit will help if you ever need to work on that code again (e.g. put it into its own function).

**Comment by tschumann** [comment]
I am LINK_ENTITY_TO_CLASS'ing the right class but I'll take a look in ClientConnect and ClientPutInServer (I looked at one a few weeks ago but nothing obvious stood out).

**Comment by tschumann** [comment]
And you may well be right - looking at Natural Selection's source, the spawn method is called like so: GetClassPtr( (AvHPlayer *)pev)->Spawn( );

**Comment by tschumann** [comment]
Well changing the GetClassPtr cast seems to have worked so I'll go ahead and close this. Thanks for all the help.
