### ISSUE TITLE
add cl_autowepswitch to half-life

### ISSUE THREAD

**Issue by crustypig** [ValveSoftware/halflife#169]
adding a cl_autowepswitch cvar would be a useful feature for multiplayer, im rather surprised it hasn't been added in previous updates, as cs1.6 and many hl-mods include this cvar.

for example, you are in the process of reloading the crossbow (5sec reload time) only to accidentally run over a weapon box left behind by a dead player, causing your weapon to automatically change, you have to switch back weapons and begin the reload process all over again.

**Comment by Redundanz** [comment]
yes please!
QoL improvement

**Comment by mikela-valve** [comment]
Hi @Redundanz, I've added this to the latest HL1 beta as cl_autowepswitch. 0 to never switch and 1 (default) to have the regular behaviour.

**Comment by Redundanz** [comment]
thank you so much for taking time to implement it mikela!
