### ISSUE TITLE
Crash issue - serious

### ISSUE THREAD

**Issue by HARDSTYLEBG** [ValveSoftware/halflife#1694]
Well there was a bunny hopping tournament in counter-strike and HLTV was streaming it,but here is the issue:
Someone was crashing the clients in HLTV (not ingame) so after a while i got information on how this was done:
1.Start a game
2.Connect HLTV to the game
3.Open HLTV chat and write this "#spec_help_text #spec_help_text"
4.Crashing your client + all others in HLTV

Thats it.Exacly as you see it writing #spec_help_text two times in HLTV chat crashes everyone in HLTV.
This can be prevented when HLTV chat is disabled.

Please fix this ASAP.

**Comment by HARDSTYLEBG** [comment]
BUMP....

**Comment by Maxi605** [comment]
@alfred-valve This is fixed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
