### ISSUE TITLE
Counter Strike and Condition Zero have recoil lags

### ISSUE THREAD

**Issue by erdemtekin** [ValveSoftware/halflife#1735]
I have Half Life Anthology and Counter Strike Anthology on Steam.

I have lag problem for Counter Strike and Counter Strike Condition Zero

LAG appears in online servers and LAN server

I didn't change settings and cfg files.I am using default files.Also,I am using default rate commands(rate 100000,cl_cmdrate 60,cl_updaterate 60)

I can play smoothly in singleplayer (with bots)

I tried disabling firewall,disabling DEP etc. but they didn't fix problem

I formatted my PC,I installed hamachi, and I changed my router.I couldn't fix still.

I am using notebook.İt has İ5 3317U processor,6GB ram,2GB GT635m and 60hz screen.

Games have animation lag.

So,when I jump,duck or shoot, lag appears in game.

I recorded a gameplay video in LAN game.

http://www.youtube.com/watch?v=3z3Cy4Ciexo

İf you watch video please set quality to 720p and fullscreen for see lag.

Also,everything(game files and game settings) is default

"cl_lw 0" fixes lag problem but it isn't legal in tournaments and matches

I tried:

1-Disabled antivirus
2-Disabled firewall
3-Tested LAN game with HLDS.exe
4-Disabled v-sync
5-Set nvidia graphic card in "Global Settings" from "Nvidia Control Panel"
6-Tested game with "Hamachi"
7-Added -freq , -nomsaa and -refresh commands to Counter Strike launch options
8-Tested game with D3D Overrider
9-Tested game with all windows compatibility modes
10-Added "hl.exe" to DEP
11-İnstalled another antivirus program
12-Priority settings for "hl.exe" from task manager 
13-Changed router
14-Reset router
15-Formatted PC

So, Counter Strike and Condition Zero may have BUGS.

Because other GOLDSRC games(half life,day of defeat,opposing force,deathmatch classic etc.) works fine with steam.

**Comment by erdemtekin** [comment]
bump

**Comment by djdallmann** [comment]
This is most likely caused by this update:
"Improved firing behavior in Counter-Strike, Counter-Strike:Condition Zero and Half-Life Deathmatch, it is no longer dependant on client or server frame rate. This change needs both your client and server updates to see the improvements. "

**Comment by erdemtekin** [comment]
@djdallmann  Same in older versions(6132,4554 etc.)

**Comment by CloudHaze** [comment]
@djdallmann Then, how can we fix  it? any  suggestions? 

I've tried everything like Erdemteking mentioned before..
Also I've tweaking REGEDIT like disabling . Nagle's algorithm, 
Network Throttling Index 
Plus disabling windows media player, internet 11, firmware updates from evertyhing, modify ethernet adapter ipv4 options....... 
I've disable all drivers from mouse, I've turn off power features in all device manager
Wow tons of things that i've tested.. lol ...............

I'm only have a 75lcd monitor 2mes and g9 logitech mouse wish i can have a better monitor ....... or mouse...

**Comment by djdallmann** [comment]
I think most of us have tried everything under the sun from operating system, network and graphic optimizations but I personally haven't found a solution which fixes it completely. I wish I had older version of the hlds engine prior to these updates because according to the update both server and client require the update for it to work so maybe if we had older server it would be fine.

**Comment by erdemtekin** [comment]
I still can't play smooth.Since 2014.. lol

**Comment by Svyatpro** [comment]
I confirm, this is because of 2013th updates
