### ISSUE TITLE
Deathmatch Classic PlayerModel Color bug

### ISSUE THREAD

**Issue by shytzedaka** [ValveSoftware/halflife#1738]
There is this Bug In which there is No preview of the Color you Select of your Player model In Multiplayer.

IE. When you pick a playermodel in lets say Deathmatch Classic Or Half life 1 (Multiplayer) The Color Slide Does not Show a Change Of Color in the Preview. altho In-game it Changes. 

Please fix?

**Comment by SamVanheer** [comment]
Duplicate of #1477

**Comment by kisak-valve** [comment]
Closing per the last comment.
