### ISSUE TITLE
[CS:CZ - DS] GL_LoadTexture: too big

### ISSUE THREAD

**Issue by TheJanzap** [ValveSoftware/halflife#1741]
I get this error whenever I start a new game in Counter-Strike: Condition Zero Deleted Scenes. 
The game works fine in software mode, but I don't want to play in it, because I think it looks ugly.

How can I fix this?

**Comment by SamVanheer** [comment]
Check the value of the cvar gl_max_size. If it's larger than 512, set it to 512.

**Comment by TheJanzap** [comment]
It worked! Thanks man!

**Comment by SamVanheer** [comment]
Great :)

Glad to help
