### ISSUE TITLE
Screen flickers

### ISSUE THREAD

**Issue by fapescalation** [ValveSoftware/halflife#175]
Hey guys,

if i start cs and get to the overlay to press find server etc it briefly begins to flicker 5 times.
It happens again if i join a team or even if i go into the buymenu( every button i try to press in the menu causes the flickering screen again). Pressing Esc causes the problem too.

Did all things as said like fps max , vsync, fps override, async etc., nothing helps.

greetz..

**Comment by BlackShadow306** [comment]
@kisak-valve This issue can be closed.

**Comment by CS-PRO1** [comment]
I remember having the exact same issue with my previous Toshiba laptop, here are the specs:
Cpu: Intel Pentium M 2.00GHz
GPU: Nvidia Geforce Go 6600  w/ 128MB VRam
Ram: 1GB DDR2
I actually found a solution which was installing an older GPU driver, but this led to several issues cuz it was built for WinXP and I was using Win7
Currently the laptop is broken a bit but I'll most likely get to fix it soon and give further info.

**Comment by Ruedii** [comment]
Is this a hybrid graphics laptop?

If so it is a known upstream issue in the nVidia Prime setup for Linux on the nVidia proprietary drivers that hits the old Source engine games VERY bad.

**Comment by CS-PRO1** [comment]
@Ruedii I don't think so, the model name is Toshiba Qosmio F20
Reverting back to an older driver worked. But since it wasn't built for Win7 I got several other issues and performance hits.

**Comment by shawns-valve** [comment]
Closing due to age. Please reopen / create a new issue if this still occurs with the 25th anniversary update (December 2023 Steam build) and current graphics drivers.
