### ISSUE TITLE
Question about triangle API drawing sprites

### ISSUE THREAD

**Issue by johnstt** [ValveSoftware/halflife#1756]
I'm trying to use the triangle API to draw sprites that show up 'through walls' (like the hivesight in Natural Selection). 

So far I'm getting some sprites to show up, but only in the visible part of the world (from my player's view).

I have a feeling this has something to do with render modes or culling, but I'm really green about all this stuff.

edit: [Here ](https://github.com/unknownworlds/NS/blob/master/dev/3.2-LUA/source/mod/AvHVisibleBlipList.cpp#L103-L158) is an example of how ns does it (but I don't fully understand this code yet so I don't know which part prevents the sprite being culled...)

Any suggestions?

**Comment by tschumann** [comment]
I had in my mind that it depends on whether you call the TriangleAPI from HUD_DrawNormalTriangles or HUD_DrawTransparentTriangles but as I look at the code I'm not so sure now.

**Comment by SamVanheer** [comment]
According to the NS source code, this code should be called either from HUD_DrawTransparentTriangles (https://github.com/unknownworlds/NS/blob/36f159b53325461bdc649f5fc32c8ecc537d60ef/dev/3.2-LUA/source/cl_dll/tri.cpp#L423)(when the player has no view model, like when they're commanding) or after the view model has been rendered: https://github.com/unknownworlds/NS/blob/36f159b53325461bdc649f5fc32c8ecc537d60ef/dev/3.2-LUA/source/mod/AvHHudRender.cpp#L1810

No Z Buffering is being performed at either time which allows it to render. If the view model is being rendered, the model is rendered on top of everything else.

The engine calls glDepthRange while rendering the view model (https://www.opengl.org/sdk/docs/man/html/glDepthRange.xhtml), the default min and max being 0 and 1 respectively while rendering everything else, it calculates max as ( max - min ) * 0.3 + min, while min stays the same.

If you assume that only OpenGL is used, you can disable depth testing using glDisable( GL_DEPTH_TEST ) to ensure that no depth testing is ever performed.

That said, HUD_DrawTransparentTriangles should work. It's called after all entities have rendered, so it should be fine to call triangle API code there. Dynamic lights, particles and the view model are rendered after the call, everything else should already be done.

HUD_Redraw is called after all of this is done, but the OpenGL settings are changed to draw the GUI stuff, and it's not called all the time like the rest. If you want to risk breaking things like the viewport settings, then you can try rendering it here.

You could always ask for a new client dll function to render stuff like this at the very end, but that's unlikely to happen :P

**Comment by johnstt** [comment]
glDisable( GL_DEPTH_TEST ) is the secret sauce apparently.

Seems to work now, so I'll continue based on that.
Thanks for the help!
