### ISSUE TITLE
 [Netcode Problem] Default client and server rate values are too low and make GoldSrc games unplayable.

### ISSUE THREAD

**Issue by erdemtekin** [ValveSoftware/halflife#1764]
@alfred-valve @jljusten @johndrinkwater @johnv-valve @tycho @ripieces @JoelTroch @Jengerer @thefoofighter @DanielOaks 

Default client and server rates of Goldsrc games are too low. They need to be modernized for todays computers. 

When I connect to online servers with default rates , lag appears.
**Also, lag appears on LAN (Dedicated Server) too  :/**

**_Valve updated cl_cmdrate and cl_updaterate to "60" in 2013. This is low value. Also, valve didn't update server rate values._**

## **COMPARISION 1:**

Here is my net_graph comparisions.

Look: http://prnt.sc/det725

As you can see, when I use default values red dots appear. This means the rates are bad. 

**Please fix this issue. This makes GoldSrc games unplayable. (Especially Counter Strike and Counter Strike Condition Zero) **

## **COMPARISION 2:**

Here is my gameplay on LAN (With Default Rates):
https://www.youtube.com/watch?v=3z3Cy4Ciexo

Here is my gameplay video on LAN (With My Rates):
https://www.youtube.com/watch?v=XEMZZ0u8YY0

**Comment by HARDSTYLEBG** [comment]
I agree they have to be changed.

**Comment by basuritashka** [comment]
@mikela-valve this should be addressed too, actual values are too low.

**Comment by erdemtekin** [comment]
@mikela-valve @alfred-valve @kisak-valve 
I wrote this issue 2-3 years ago and the problem still didn't fixed. 

I say again, client and server rates are too low and make games unplayable in Online servers and LAN.

I guess it is most important issue for me because it affects gameplay.

Also I uploded net graphs. You can see red dots with default rates. 

Shortly, GoldSrc games are unplayable because of netcodes.. Especially Counter Strike and Counter Strike Condition Zero.

They need to be fixed Immediately.

**Comment by erdemtekin** [comment]
@basuritashka Im going to update this thread
