### ISSUE TITLE
Counterstrike 1.6 Linux extreme fps dips on powerful machine

### ISSUE THREAD

**Issue by calexil** [ValveSoftware/halflife#1766]
Sys specs:
http://pastebin.com/NCZRDnNU

fps seems to drop to and lock at 30 fps under smoke load(sometimes, and regardless of smoke quality selected) or in free look.
_it happens in wide open areas, or in free look travelling thru walls... not just smoke._

also during regular gameplay when a lot of stuff is happening on the screen

started last summer randomly, cant figure out why might be related to mesa/amdgpu since I switched from pro

I am running marco+compton for compositing, but unredir on fullscreen is on, so the vsync is handled by the game. This is also no good cause if I turn it off it tears like crazy and mouse wheel lags like crazy when switching weapons which can ruin games.

**Comment by di57inct** [comment]
Same here but you're wasting your time. They don't care.

**Comment by calexil** [comment]
@di57inct so I don't waste any more time, what have you tried that has not worked?

**Comment by di57inct** [comment]
It's because of gl_vsync. Disable it and you won't have the problem anymore.

**Comment by calexil** [comment]
if you turn vsync off, I get awful tearing, and more importantly mousewheel fails to cycle weapons properly.

which can get you killed a lot, and is super annoying

**Comment by di57inct** [comment]
Try forcing it on from your gpu's control pannel. Waiting for a fix from valve gets u less chances than winning the lottery.

**Comment by calexil** [comment]
the open source amdgpu drivers have no "control panel"

and vsync aka tearfree is enabled by default

**Comment by calexil** [comment]
SOLVED: dri 3 was not enabled on amdgpu, closing
