### ISSUE TITLE
CS.SERPARIE.RO / 89.40.104.79:27015

### ISSUE THREAD

**Issue by novaguardia** [ValveSoftware/halflife#1790]
Nume : CS.SERPARIE.RO
IP : 89.40.104.79:27015
Anticheat : VAC SECURE
Jucatori : 32
Addons: amxmodx
Serverul ruleaza la 1000 FPS
Ping scazut
Forum : http://www.serparie.ro 

*Pentru sloturi/admine îmi puteti da add la YM: novaguardia@yahoo.com , ori pe forum-ul nostru : http://www.serparie.ro

* Add la fav CS.SERPARIE.RO / 89.40.104.79:27015 , cu timpul poate ne strangem si noi mai multi.

*Nu uitati, cautam Admini pentru server si staff pentru forum http://www.serparie.ro . 
Multumim si va asteptam pe CS.SERPARIE.RO

**Comment by kisak-valve** [comment]
Hello @novaguardia, this issue tracker is not a general use forum.
