### ISSUE TITLE
Texture corruption on mesa 17.0.4 after indeterminate amount of time Counter Strike 1.6

### ISSUE THREAD

**Issue by calexil** [ValveSoftware/halflife#1794]
![20170420004921_1](https://cloud.githubusercontent.com/assets/3487071/25214241/1eabb45a-2564-11e7-9e97-d5c9eedc70a0.jpg)
![20170420004944_1](https://cloud.githubusercontent.com/assets/3487071/25214245/21bf6b1e-2564-11e7-9a1a-d4b0bfea1475.jpg)
![20170420004953_1](https://cloud.githubusercontent.com/assets/3487071/25214248/23e09d8c-2564-11e7-8ca2-442357a50454.jpg)

**Comment by kisak-valve** [comment]
Hello @calexil, this issue should also be brought to the attention of the video driver vendor.

**Comment by calexil** [comment]
@kisak-valve done ^^

https://bugs.freedesktop.org/show_bug.cgi?id=100789
