### ISSUE TITLE
Maximum allowed rate setting for all goldsrc games?

### ISSUE THREAD

**Issue by erdemtekin** [ValveSoftware/halflife#1799]
Half Life updated in Feb 2013 and
we can see "Increased maximum allowed rate setting to 100,000" in log.

This update for all goldsrc games? or only HL1?
I asked because other goldsrc games are mods of HL1 and use same engine
@alfred-valve

**Comment by SamVanheer** [comment]
Yes, this update affects all GoldSource games. The minimum rate is 1000 and the maximum rate is 100000.
