### ISSUE TITLE
Linux SteamCMD HL1 content missing

### ISSUE THREAD

**Issue by MindfulProtons** [ValveSoftware/halflife#1807]
Seems to be lacking all of the .so files in the root directory and the valve and cstrike content.

Log:

proton@electron:~/.servers$ steamcmd
Redirecting stderr to '/home/proton/.steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Steam>login anonymous

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK

Steam>force_install_dir /home/proton/.servers/hl1server

Steam>app_update 90
 Update state (0x5) validating, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 6.74 (4476800 / 66393415)
 Update state (0x61) downloading, progress: 38.66 (25666967 / 66393415)
 Update state (0x61) downloading, progress: 87.37 (58004807 / 66393415)
Success! App '90' fully installed.

Steam>exit

Steam>proton@electron:~/.servers$ cd hl1server
proton@electron:~/.servers/hl1server$ l
-bash: l: command not found
proton@electron:~/.servers/hl1server$ s
-bash: s: command not found
proton@electron:~/.servers/hl1server$ ls
core.so              hltv             libvstdlib.so   vgui.so
crashhandler.so      libgcc_s.so.1    linux64         voice_miles.so
demoplayer.so        libSDL2.so       proxy.so        voice_silk.so
engine_i486.so       libstdc++.so.6   steamapps       voice_speex.so
filesystem_stdio.so  libsteam_api.so  steamclient.so
hlds_linux           libsteam.so      valve
hlds_run             libtier0.so      vgui2.so
proton@electron:~/.servers/hl1server$ ls valve
dlls
proton@electron:~/.servers/hl1server$

**Comment by Freeman-AM** [comment]
Same shit on windows, you can edit your title...

**Comment by kisak-valve** [comment]
Hello @MindfulProtons, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/4950. Closing in favor of the existing report.
