### ISSUE TITLE
Portal crash when launch

### ISSUE THREAD

**Issue by YangtseSu** [ValveSoftware/halflife#1808]
Archlinux.

 ##### swap interval = 0     swap limit = 1 #####
Could not load program cache file glbaseshaders.cfg
Could not find base GL shader cache file
Could not load program cache file glshaders.cfg
Could not find user GL shader cache file
Precache: Took 0 ms, Vertex 0, Pixel 0
ConVarRef mat_dxlevel doesn't point to an existing ConVar
Game.so loaded for "Half-Life 2"
Installing breakpad exception handler for appid(steam)/version(1495583454)
ERROR: ld.so: object '/home/yangtse/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20170525175036_1.dmp[28076]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170525175036_1.dmp
>>> Adding process 28075 for game ID 400
/home/yangtse/.local/share/Steam/SteamApps/common/Portal/hl2.sh: 行 67: 28036 段错误               (核心已转储)${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 400 "Portal", ProcID 28036 
No cached sticky mapping in ActivateActionSet.crash_20170525175036_1.dmp[28076]: Finished uploading minidump (out-of-process): success = yes
crash_20170525175036_1.dmp[28076]: response: CrashID=bp-00b7325f-bb21-4715-a492-adc2d2170525
crash_20170525175036_1.dmp[28076]: file ''/tmp/dumps/crash_20170525175036_1.dmp'', upload yes: ''CrashID=bp-00b7325f-bb21-4715-a492-adc2d2170525''
pid 28076 != 28075, skipping destruction (fork without exec?)

**Comment by SamVanheer** [comment]
This repository is meant for Half-Life 1 games, for Portal either use the Portal 2 repository (https://github.com/ValveSoftware/portal2/issues) or the Source 1 games repository (https://github.com/ValveSoftware/Source-1-Games/issues).

That said, given that it says it loaded "Half-Life 2" you should verify the integrity of the Portal installation, it might be missing some files.

If the issue persists, check if you're running a 64 bit operating system. If so, this issue maybe of help: https://github.com/ValveSoftware/portal2/issues/227
