### ISSUE TITLE
Fastdownload not working for non steam players

### ISSUE THREAD

**Issue by Ehabz** [ValveSoftware/halflife#1811]
Hi guys i have cs 1.6 zombie server and fun server i have fastdownload it works fine for steam players and download fast 
but i joined with my non steam cs 1.6 it shows that it downloaded fast and when it finish it download everything again but slow as if that fastdownload did nothing any ideas?? 

BUILD 4554 SERVER (0 CRC)
Server # 7
Serverinfo packet received.
Clearing memory
Remote host:  Zombie Mod | VIP+JetPack | FreeVIP | 1000 FPS
Spooling demo header.
SteamWaitForResources() time: 0.000 seconds
Using http://pke-team.000webhostapp.com/cstrike/ as primary download location
Verifying and downloading resources...
Compressing split packet (161 -> 130 bytes)
Netchan_Clear() : reliable length not 0, reliable_sequence: 11, incoming_reliable_ackn

Here is some info too

**Comment by SamVanheer** [comment]
No-Steam is not supported by Valve.

**Comment by shelru** [comment]
@SamVanheer steam also have 4554 build.

**Comment by SamVanheer** [comment]
Since this issue is about no-Steam clients failing to use fastdl it can probably be closed.
