### ISSUE TITLE
Team Fortress Classic access violation crash after loading screen.

### ISSUE THREAD

**Issue by Darkvapour** [ValveSoftware/halflife#1820]
So I've been having a problem with Team Fortress Classic and Half-Life Rally.

I've been unable to play Team Fortress Classic on Steam for quite some time.
The game just crashes after the loading screen when I join/create a server with the error code 0xc0000005  (obtained via event viewer) just as the MOTD shows itself and before the world is rendered.

The way it crashes changes a tiny bit depending on what map I'm loading, 2-Fort always makes the Windows error reporter show whilst some other maps just silently CTD, but it does seem to be the same problem and crash dumps are still made.

The problem I have only seems to happen on my Laptop and it doesn't matter which Operating System I use, it'll crash the same way every time.

I've tried replacing the RAM, using the original RAM that came with this laptop, restoring an original BIOS backup, resetting bios, updating drivers, using original drivers, processor diagnostics software, various command line parameters for HL/TFC, switching between OpenGL and Software rendering, running the game using either the Intel HD Graphics 4000 chip or Nvidia Geforce GT 650M chip, running the game in Windows Safe Mode...nothing worked.
Yet if I were to take this hard disk out of the laptop and pop it into my desktop PC and run the game there it'll most likely work fine.

Old WON/WON2 versions of TFC work perfectly fine, Old (pre-steampipe?) Steam Versions of TFC work fine too, it's just the latest version on Steam that doesn't work on this hardware.
I get the same problem with the mod Half-Life Rally, crashing at the same point on the latest Steam version of HL and just like TFC it does not crash on older Steam versions of the engine.

Also of interest, I copied the TFC folder from Half-Life's folder to Sven-Coop's folder and started TFC using Sven-Coop's version of the engine to see if it would behave differently...and it actually worked.
I could spectate and fly around, however when I went into the spawn rooms it crashed with the error code 0xc0000005 again. 
Though Sven-Coop is not really supposed to be running TFC so any crashes there are sort of expected.

I've already contacted Steam support about this problem I was having a while ago but it didn't get anywhere as they didn't know what the problem was.

Pretty much everything else works fine, Half-Life itself, expansions and mods. 
There doesn't seem to be any problems with this laptop outside of Half-Life.
Memory testing had no errors either.

Steps that I do to reproduce it every time:
1. Launch Team Fortress Classic
2. Create a server on any map.
3. Observe the loading screen
4. See the MOTD come up as the loading screen finishes, but the background is completely black.
5. Game crashes.

Version Output:

`Protocol version 48
Exe version 1.1.2.2/Stdio (tfc)
Exe build: 09:10:05 Jul  7 2017 (7561)`

System Information:
```
Computer Information:
    Manufacturer:  NOVATECH LTD*
    Model:  A35FE/FB
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:        Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2295 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Supported

Operating System Version:
    Windows 10 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  Intel(R) HD Graphics 4000
    DirectX Driver Name:  nvldumd.dll
    Driver Version:  10.18.10.4425
    DirectX Driver Version:  22.21.13.8205
    Driver Date: 4 4 2016
    OpenGL Version: 4.5
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 59 Hz
    DirectX Card: NVIDIA GeForce GT 650M
    VendorID:  0x10de
    DeviceID:  0xfd1
    Revision:  0xa1
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 13.54" x 7.64" (15.51" diag)
                                            34.4cm x 19.4cm (39.4cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2047 MB
    Supported MSAA Modes:  2x 4x 8x 

Sound card:
    Audio device: Speakers (Realtek High Definiti

Memory:
    RAM:  12184 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  714901 Mb
    Largest Free Hard Disk Block:  61024 Mb
    OS Install Date: Jan 01 1970
    Game Controller: None detected
    VR Headset: None detected

```
** This is actually a Pegatron A35 Laptop.

Crash dumps with all 4 attempts, 2 attempts to load 2fort and 2 attempts to load well:

http://puu.sh/wGWjE.dmp
http://puu.sh/wGWjZ.dmp
http://puu.sh/wGWkm.dmp
http://puu.sh/wGWkG.dmp

**Edit** - Here is a screenshot of the crash happening:
http://puu.sh/wH9YF.png

**Comment by Darkvapour** [comment]
Hi thanks for the response, 

I usually play any Half-Life 1 engine game or mod in 1024 x 768 rather than any widescreen resolution because I don't like the default field of view in widescreen, so it seems that the TFC crash isn't affected by the display resolution as it is still crashing.

I did experiment with the Half-Life Dedicated Server and tried to run a TFC server as a test to see if it would work and that seems to work fine, so it does seem the problem has something to do with the client.dll as I guess that doesn't get loaded when running a dedicated server.

I tried HL Rally again and that actually works now but I'm pretty sure the last time I tried it wasn't in widescreen and it was crashing in the same way TFC was. So either I really was running in widescreen in that instance or perhaps maybe the very recent Half-Life update actually fixed the problem I was having with HL Rally somehow.

**Comment by yelper** [comment]
Try disabling HD models in TFC: Options > Video > Enable HD Models (uncheck)... related to #960.

What are your video settings in-game?

**Comment by Darkvapour** [comment]
Disabled the HD models in options and it still crashed. Also tried the low quality video option, does not work with that either.

Currently my video settings are set to the following:
Renderer: OpenGL
Resolution: 1024 x 768 - Full Screen
Wait for VSync is on
Low quality video options is on.
HD models is off.
Custom Addon Content is off.
