### ISSUE TITLE
Fix cmd protector & other shit

### ISSUE THREAD

**Issue by shelru** [ValveSoftware/halflife#1821]
https://github.com/ValveSoftware/halflife/issues/1497  (https://github.com/shelru/ExtraMirror/blob/master/MiniBase/enginemsg.cpp#L129) fix
There is a lot of useless in updating, but the main problem was not corrected - bypassing the protector, I propose to port some of the fixes from the already finished products, or to come up with their own implementations of these fixes.

Also, I propose to prohibit the server from getting the value of client values, the servers will not be able to regulate the rules for the game.

2) Port avatar fixes from https://github.com/shelru/ExtraMirror/blob/master/MiniBase/main.cpp#L614

**Comment by shelru** [comment]
@alfred-valve wake up

**Comment by shelru** [comment]
If it is possible - to forbid to check hashes of files and their presence at the client (except for the standard files provided in hlds)

**Comment by shelru** [comment]
About files. I just create keys.txt at game dir, going to server and instantly get banned. Also im playing from the linux client, going to the server and get ban.

**Comment by All-github-usernames-taken** [comment]
This is still a fucking issue. @alfred-valve WAKE UP bro

**Comment by sjain882** [comment]
Why is this closed? The cl_filterstuffcmd 1 is still easily bypassable

**Comment by SamVanheer** [comment]
@sjain882 Can you give some examples?
