### ISSUE TITLE
[CounterStrike] OpenGL Hud Problems.

### ISSUE THREAD

**Issue by BlackShadow** [ValveSoftware/halflife#1834]
I'm not sure if @alfred-valve still around but, in-game hud causing massive FPS drops and sadly OpenGL renderer can't fully adapt modern hardwares since it's outdated. It would be nice to if Valve can get touch with this issue...

Simple test i just tried:

With hud_draw 0: Average 500-600FPS
With hud_draw 1: Average 180-200 FPS

**Comment by shytzedaka** [comment]
The OpenGL that is being Used on CS 1.6 is Outdated. however New OpenGL versions are released. the latest being i think 4.5. and i think gldsource uses OpenGL 2.1 from the 2013 SteamPipe update. 
Maybe what you are saying is true. But then again this is Gold source. i dont think it was even Designed to run above 60FPS.

**Comment by BlackShadow306** [comment]
Actually Counter-Strike can run very well at higher FPS rates without any bugs. And for another example, people with 144Hz monitors will not be pleased playing at 60FPS. But again CS has no problems with +100 FPS. Since it doesn't have any AI related stuff.

**Comment by shytzedaka** [comment]
Well. whatever the issue is. I dont think you'll get a responce from alfred. or anyone since Valve's neglection of half life 1 games.
