### ISSUE TITLE
Will This Repo be Updated with the 2017 Patches?

### ISSUE THREAD

**Issue by mmillar-bolis** [ValveSoftware/halflife#1839]
Hey ValveSoftware,

I was wondering if you were planning to merge the July and August 2017 patches into this repository?

It looks like there were several crash and security fixes as noted in the release notes here:
https://steamcommunity.com/games/70/announcements/detail/1439314053820431619

And here:
https://steamcommunity.com/games/70/announcements/detail/1453952496382173411

I am sure we would all love to see this repo updated, if possible.

Thanks for your time and consideration!

**Comment by SamVanheer** [comment]
Most of those are engine level changes, the fix i provided for the exhaustible weapons crash can be found here: https://github.com/ValveSoftware/halflife/issues/1815

**Comment by mmillar-bolis** [comment]
Well I see my ignorance is showing. Thank you for letting me know! I guess I'll save this as a patch for now. Should I close this topic then, do you think?

**Comment by SamVanheer** [comment]
No, they should still merge the changes.

**Comment by mikela-valve** [comment]
Closing this in favour of #2110 where I’ll be adding updates as I add commits updating the SDK. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
