### ISSUE TITLE
[CounterStrike] Find Server is full of bad servers

### ISSUE THREAD

**Issue by BlackShadow306** [ValveSoftware/halflife#1847]
Well, title is self explanatory. Master Server List is full of bad servers. Whenever you click them, it's redirects you to another server and slowhacking the game. (Placing configs, editing menus etc...)

The current Server list:

![20171118192502_1](https://user-images.githubusercontent.com/30868395/32982504-d1d7100e-cc96-11e7-8c6f-e8bd66408cfc.jpg)

These servers aren't legit. All of them are fake. It's a serious security issue.

**Comment by di57inct** [comment]
Editing files isnt possible anymore because motd_write command is disabled. Also you're wasting time posting. Valve doesn't care about anything that doesn't bring them cash.

**Comment by BlackShadow306** [comment]
They can still do that with AMXX plugins. I can even slowhack user commands with AMXX plugin. It's so easy. It doesn't matter Valve doesn't care or not. Everyone posting this issues just in case.

**Comment by RuedigerDieter** [comment]
Well, you can set the config files to read-only, but I still get what's your problem

**Comment by 0nurky** [comment]
I think that Counter-Strike can still change the permissions of read-only files? If you're running the game in Administrator-mode I think it is possible, but I am not confirming it!

What I want you to try is uninstall Counter-Strike, remove any <tt>config</tt> and <tt>platform/config</tt> folders inside Counter-Strike folder.<br>
Now do a install again, and set those same folders as Read-Only.
I hope this makes a fix for you, good luck!
