### ISSUE TITLE
setting mouth bone controller from server

### ISSUE THREAD

**Issue by tschumann** [ValveSoftware/halflife#1851]
Anyone tried setting the mouth bone controller from the server side? It looks like bone controllers 0 through 3 can be set okay (and the code sets them to 0 by default) but bone controller 4 (the mouth) doesn't seem to work.
The mouth bone controller can be set on the client though (one of the client-side entity structs has a mouth attribute).

**Comment by SamVanheer** [comment]
The server side only has 4 controllers, there's no 5th one. controller[4] is actually blending[0] in entvars_t. 

The engine controls mouth movement on its own based on sounds played on specific channels, the server doesn't have anything to do with it.

**Comment by tschumann** [comment]
Ah you're right - entvars_t.controller is only 4 long - I thought there were more because MAXSTUDIOCONTROLLERS is 8 and in studiomdl the bonecontroller array is MAXSTUDIOSRCBONES (512!) long.
I want to set the mouth, ideally from the server code so I'll have a look at entvars_t.blending[0]

Thanks!

**Comment by SamVanheer** [comment]
Blending doesn't have anything to do with the mouth, what i meant is that accessing controller[4] is equivalent to accessing blending[0]. Blending handles animation blending for things like looking up and down, it won't affect the mouth either.

I'm afraid you'll have to make do with network messages and user variables with client side code for handling it (and network messages won't work if the engine resets to an older state due to prediction).

**Comment by tschumann** [comment]
Alright so I got this working with server to client messages - only thing was that you apparently can't send a message to MSG_ALL if one of the message items in an entity (somehow the engine guesses that an ENTINDEX sent with WRITE_LONG is an entity - it fatals with "Invalid message; cannot use broadcast message with a target entity"), though for me it's not the end of the world.

**Comment by SamVanheer** [comment]
That error occurs when the following conditions are met:
```
if ( msg_dest != 1 && msg_dest != 8 && ed )
    Sys_Error("Invalid message;  cannot use broadcast message with a target entity");
```

If you pass in an entity (player edict) it'll only work if you try to send to that specific player. A MSG_ALL doesn't need that.

**Comment by tschumann** [comment]
Ah right - need to read my code closer. Thanks.
