### ISSUE TITLE
Mouse Glitches in Deathmatch Classic

### ISSUE THREAD

**Issue by shytzedaka** [ValveSoftware/halflife#1852]
Mouse:Steelseries Rival 100 i noticed a bug that If you try to move your Mouse in lets say Deathmatch Classic you'll suddenly have your mouse jumping to the Corners of the screen.

Just as said in this disscussion: http://steamcommunity.com/app/40/discussions/0/2906376154333759753/

So The Solution is 'Raw mouse Input' But honestly i think this should be enabled by default.

**Comment by JoelTroch** [comment]
Can be fixed if #1559 is merged
