### ISSUE TITLE
steamclient.dll Problem Event Name: BEX (Running CS 1.6, Windows 8.1 x64)

### ISSUE THREAD

**Issue by theNurky** [ValveSoftware/halflife#1856]
So this is getting a bit awful to be honest.

So I was on Windows 7 right, and I had this issue when I start a program the error message pops out saying "KernelBase.DLL" error and such stuff, I couldn't run any programs that I needed the most, such as XAMPP and so on. So I've used Windows 8.1 before and decided to give it a go because it's faster! (now don't complain, for me it is faster).
So I did that and everything was good until I tried Counter-Strike. It crashed with steamclient.dll...
<pre>
<b>Problem signature</b>:
  Problem Event Name:	BEX
  Application Name:	hl.exe
  Application Version:	1.1.1.1
  Application Timestamp:	48feaf5a
  Fault Module Name:	steamclient.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	4aa7bb95
  Exception Offset:	000268d3
  Exception Code:	c0000417
  Exception Data:	00000000
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	2a2f
  Additional Information 2:	2a2f94d122e8414803e51562d7fb27ea
  Additional Information 3:	4b85
  Additional Information 4:	4b85661061aab4784ea622999b14fb1b
</pre><br>... So I've decided to record it using Bandicam and guess what happened next? The game engine did kinda get initialized at startup but got crashed with a different error, now being steam.dll !
<a href="https://www.youtube.com/watch?v=Rpc5IWtitxc&feature=youtu.be">Here is the video.</a>
and the information about steam.dll:
<pre>
<b>Problem signature</b>:
Problem Event Name:		BEX
Application Name:		hl.exe
Application Version:		1.1.1.1
Application Timestamp:		48feaf51
Fault Module Name:		steam.dll
Fault Module Version:		2.0.0.0
Fault MOdule Timestamp:		4a0fe93e
Exception Offset:		0001d4bd
</pre> Now I can't get the steam.dll while I'm recording with Bandicam because I think that was the issue here for a second, but maybe it's not.. I'm not sure!<br><br><h2>So...</h2>It was working the other time I've used Windows 8.1, like 9 months ago! The same version of Windows 8.1!

<h1>My PC Information [systeminfo]</h1>
<details><summary>Click me</summary>
<pre>
Host Name:                 NURKY-PC
OS Name:                   Microsoft Windows 8.1 Pro
OS Version:                6.3.9600 N/A Build 9600
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Nurky
Registered Organization:   
Product ID:                00261-50000-00000-AA302
Original Install Date:     1/17/2018, 7:49:29 PM
System Boot Time:          1/21/2018, 5:20:11 PM
System Manufacturer:       Acer
System Model:              Aspire 5820T
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 37 Stepping 2 GenuineIntel ~2133 Mhz
BIOS Version:              INSYDE V1.06, 4/7/2010
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              hr;Croatian
Time Zone:                 (UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb
Total Physical Memory:     3,895 MB
Available Physical Memory: 1,393 MB
Virtual Memory: Max Size:  5,175 MB
Virtual Memory: Available: 2,160 MB
Virtual Memory: In Use:    3,015 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\NURKY-PC
Hotfix(s):                 35 Hotfix(s) Installed.
                           [01]: KB2959936
                           [02]: KB2919355
                           [03]: KB2920189
                           [04]: KB2931358
                           [05]: KB2931366
                           [06]: KB2937220
                           [07]: KB2938772
                           [08]: KB2939153
                           [09]: KB2949621
                           [10]: KB2954879
                           [11]: KB2958262
                           [12]: KB2958263
                           [13]: KB2961072
                           [14]: KB2962140
                           [15]: KB2965142
                           [16]: KB2965500
                           [17]: KB2966407
                           [18]: KB2967917
                           [19]: KB2968599
                           [20]: KB2971203
                           [21]: KB2973351
                           [22]: KB2975061
                           [23]: KB2976627
                           [24]: KB2976978
                           [25]: KB2977629
                           [26]: KB2978002
                           [27]: KB2981580
                           [28]: KB2987107
                           [29]: KB2989647
                           [30]: KB2998527
                           [31]: KB2999226
                           [32]: KB3000850
                           [33]: KB3001237
                           [34]: KB3003057
                           [35]: KB3014442
Network Card(s):           5 NIC(s) Installed.
                           [01]: Qualcomm Atheros AR5B93 Wireless Network Adapter
                                 Connection Name: Wi-Fi
                                 Status:          Hardware not present
                           [02]: Qualcomm Atheros AR8151 PCI-E Gigabit Ethernet Controller (NDIS 6.30)
                                 Connection Name: Ethernet
                                 Status:          Hardware not present
                           [03]: TP-LINK Wireless USB Adapter
                                 Connection Name: Wi-Fi 2
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.0.1
                                 IP address(es)
                                 [01]: 192.168.0.101
                                 [02]: fe80::8440:8eb5:ebce:bac5
                           [04]: VirtualBox Host-Only Ethernet Adapter
                                 Connection Name: VirtualBox Host-Only Network
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.56.1
                                 [02]: fe80::2df3:c1b6:c452:f33b
                           [05]: TAP-Windows Adapter V9
                                 Connection Name: Ethernet 2
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
</pre>
</details>

<h1>Signature of files within Counter-Strike [sigcheck]</h1>
<details><summary>Click me</summary>
<pre>
D:\Games\Counter-Strike 1.6\a3dapi.dll:
	Verified:	Unsigned
	Link date:	4:02 AM 11/18/1998
	Publisher:	n/a
	Company:	Aureal Semiconductor
	Description:	Aureal A3D API DLL
	Product:	A3D Interactive API DLL
	Prod version:	2.02
	File version:	2.02
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\Core.dll:
	Verified:	Unsigned
	Link date:	8:57 PM 10/18/2008
	Publisher:	n/a
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\crashhandler.dll:
	Verified:	A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file.
	Link date:	6:28 PM 7/20/2011
	Publisher:	Valve
	Company:	Valve Corporation
	Description:	Steam Crash Handler Library (alfred_work_steam3_rel_client@alfred)
	Product:	Steam Crash Handler Library
	Prod version:	01.00.00.01
	File version:	01.14.18.64
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\dbg.dll:
	Verified:	Unsigned
	Link date:	11:17 PM 1/13/2004
	Publisher:	n/a
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\DemoPlayer.dll:
	Verified:	Unsigned
	Link date:	12:06 AM 10/29/2003
	Publisher:	n/a
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\FileSystem_Stdio.dll:
	Verified:	Unsigned
	Link date:	3:12 AM 3/9/2007
	Publisher:	n/a
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\FileSystem_Steam.dll:
	Verified:	Unsigned
	Link date:	3:12 AM 3/9/2007
	Publisher:	n/a
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\hw.dll:
	Verified:	The digital signature of the object did not verify.
	Link date:	12:05 AM 6/16/2009
	Publisher:	n/a
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\hwpatcher.dll:
	Verified:	Unsigned
	Link date:	1:42 AM 11/1/2009
	Publisher:	n/a
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\Mss32.dll:
	Verified:	Unsigned
	Link date:	12:12 AM 11/14/2000
	Publisher:	n/a
	Company:	RAD Game Tools, Inc.
	Description:	Miles Sound System
	Product:	Miles Sound System
	Prod version:	6.0m
	File version:	6.0m
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\msvcr100.dll:
	Verified:	Signed
	Signing date:	9:50 AM 6/11/2011
	Publisher:	Microsoft Corporation
	Company:	Microsoft Corporation
	Description:	MicrosoftÂ® C Runtime Library
	Product:	MicrosoftÂ® Visual StudioÂ® 2010
	Prod version:	10.00.40219.325
	File version:	10.00.40219.325
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\proxy.dll:
	Verified:	Unsigned
	Link date:	9:08 PM 10/18/2008
	Publisher:	n/a
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\revSrvBrowser.dll:
	Verified:	Unsigned
	Link date:	11:25 PM 9/13/2009
	Publisher:	n/a
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\Steam.dll:
	Verified:	Unsigned
	Link date:	11:38 AM 5/17/2009
	Publisher:	n/a
	Company:	Valve Corporation
	Description:	Steam Client Engine
	Product:	Steam
	Prod version:	1.0.0.0
	File version:	2.0.0.0
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\steamclient.dll:
	Verified:	Unsigned
	Link date:	3:28 PM 9/9/2009
	Publisher:	n/a
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\steamclient_orig.dll:
	Verified:	Signed
	Signing date:	7:31 PM 8/27/2009
	Publisher:	Valve
	Company:	Valve Corporation
	Description:	Steamclient.dll
	Product:	Steam
	Prod version:	3, 0, 0, 1
	File version:	3, 0, 0, 1
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\steam_api.dll:
	Verified:	Unsigned
	Link date:	7:00 PM 6/2/2008
	Publisher:	n/a
	Company:	Valve Corporation
	Description:	Steam Client API
	Product:	Steam Client API
	Prod version:	1, 0, 0, 1
	File version:	1, 0, 0, 1
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\steam_api_c.dll:
	Verified:	Unsigned
	Link date:	12:28 AM 6/3/2008
	Publisher:	n/a
	Company:	Valve Corporation
	Description:	Steam Client API
	Product:	Steam Client API
	Prod version:	1, 0, 0, 1
	File version:	1, 0, 0, 1
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\Steam_orig.dll:
	Verified:	Signed
	Signing date:	12:35 AM 8/29/2009
	Publisher:	Valve
	Company:	Valve Corporation
	Description:	Steam Client Engine 723485
	Product:	Steam
	Prod version:	1.0.0.0
	File version:	2.0.0.723485
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\sw.dll:
	Verified:	Signed
	Signing date:	12:07 AM 6/16/2009
	Publisher:	Valve
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\swds.dll:
	Verified:	The digital signature of the object did not verify.
	Link date:	12:22 AM 3/9/2010
	Publisher:	n/a
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\tier0.dll:
	Verified:	Unsigned
	Link date:	6:55 PM 9/23/2008
	Publisher:	n/a
	Company:	n/a
	Description:	tier0_s Dynamic Link Library
	Product:	 tier0_s Dynamic Link Library
	Prod version:	1, 0, 0, 1
	File version:	1, 0, 0, 1
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\tier0_s.dll:
	Verified:	Signed
	Signing date:	7:31 PM 8/27/2009
	Publisher:	Valve
	Company:	Valve Corporation
	Description:	tier0_s Dynamic Link Library
	Product:	 tier0_s Dynamic Link Library
	Prod version:	1, 0, 0, 1
	File version:	1, 0, 0, 1
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\upatch.dll:
	Verified:	Unsigned
	Link date:	11:11 AM 1/16/2010
	Publisher:	n/a
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\vgui.dll:
	Verified:	Unsigned
	Link date:	10:05 PM 6/6/2003
	Publisher:	n/a
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\vgui2.dll:
	Verified:	Unsigned
	Link date:	7:07 PM 9/17/2008
	Publisher:	n/a
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\voice_miles.dll:
	Verified:	Unsigned
	Link date:	10:06 PM 7/17/2003
	Publisher:	n/a
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\voice_speex.dll:
	Verified:	Unsigned
	Link date:	10:07 PM 7/17/2003
	Publisher:	n/a
	Company:	n/a
	Description:	n/a
	Product:	n/a
	Prod version:	n/a
	File version:	n/a
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\vstdlib.dll:
	Verified:	Unsigned
	Link date:	1:29 AM 6/3/2008
	Publisher:	n/a
	Company:	Valve Corporation
	Description:	vstdlib_ s.dll
	Product:	Steam
	Prod version:	3, 0, 0, 1
	File version:	3, 0, 0, 1
	MachineType:	32-bit
D:\Games\Counter-Strike 1.6\vstdlib_s.dll:
	Verified:	Signed
	Signing date:	7:31 PM 8/27/2009
	Publisher:	Valve
	Company:	Valve Corporation
	Description:	vstdlib_ s.dll
	Product:	Steam
	Prod version:	3, 0, 0, 1
	File version:	3, 0, 0, 1
	MachineType:	32-bit
</pre>
</details>

<h1>Information from DebugView [dbgview] (steam.dll)</h1>
<details><summary>Click me</summary>
<pre>
00000001	0.00000000	[<b>3432</b>] SHIMVIEW: ShimInfo(Complete) 	
00000002	0.27499107	[<b>3432</b>] AppActive: active	
00000003	0.82477880	[<b>3432</b>] Wrapper: Unable to find 5551 texture.	
00000004	0.82752025	[<b>3432</b>] AppActive: not active	
00000005	0.82982433	[<b>3432</b>] Shutdown function FileSystem_Shutdown() not in list!!!	
00000006	0.82997203	[<b>3432</b>] Missing shutdown function for Sys_InitLauncherInterface() : Sys_ShutdownLauncherInterface()	
00000007	0.83003551	[<b>3432</b>] Missing shutdown function for Sys_InitMemory() : Sys_ShutdownMemory()	
00000008	0.83007061	[<b>3432</b>] Missing shutdown function for Sys_Init() : Sys_Shutdown()	
</pre>
</details><br><hr>
What I'm doing now is uninstalling all the Microsoft Visual C++ installations. I'm having a feeling that AIO installer didn't exactly install them correctly, gonna try that as administrator but here's a list of what I've done so far:
<ol>
  <li>Setting Data Execution Prevention for hl.exe ✅</li>
  <li>Running <tt>sfc /scannow</tt> while logged in as User ✅</li>
  <li>Running <tt>sfc /scannow</tt> while in safe-mode (logged in as Administrator) ✅</li>
  <li>Running <tt>chkdsk</tt> on both partitions (C: and D:) ✅</li>
  <li>Re-Installing Counter-Strike (completely, removing folder and installing again) ✅</li>
  <li>Re-Installing DirectX ✅</li>
  <li>Re-Installing GPU Driver ✅</li>
  <li>Re-Installing actual RAM, it sometimes dropped [Access violation at address] ✅</li>
  <cite>It wasn't the case with RAM obviously.</cite>
  <li>Re-Installing Steam ✅</li>
  <cite>Reason I did this is because the process wrote <b>SteamClientDll</b> with path to <b>steamclient.dll</b> in <b>ActiveProcess</b> key which is stored in <b>HKEY_CURRENT_USER\Software\Valve\Steam</b></cite>
  <li>Download another version of Counter-Strike ✅</li>
  <li>Tried all compatibility layers ✅</li>
  <li>Tried original <b>steamclient.dll</b> from Steam ✅</li>
  <cite>It needs the cracked one, original doesn't seem to work, just like <b>steamclient_orig.dll</b></cite>
</ol><br><hr>Oh god... this is really frustrating. Now I'm gonna be honest, I'm very good with computers even though I'm a 15 year old, but this one problem is really kicking my head... I had the issue in Windows 7 where some programs couldn't run and now this in Windows 8.1? No way.. Never had such issue before.

**Comment by SamVanheer** [comment]
I sent an email to Alfred about this, got a reply:

> Hi Solokiller, why are these people running cracked Steam binaries? Why are they unsigned? HL1 and Steam do not require any 3rd party libraries to run, so by design the MSVC redist won't be installed.
>
> - Alfred

**Comment by 0nurky** [comment]
@SamVanheer That's weird.. I actually refreshed my Windows installation and the game did work though, but then when I installed .NET Framework 3.5 and Microsoft Visual C++ 2013 and 2015 x86 the game drops the same error now? I was so excited and tried running the game again and doesn't work at all... it did work 4 hours ago, I didn't reboot my computer by then :(

**Comment by 0nurky** [comment]
OKAY I might be the first one to actually solve this infamous "BEX error". So what I have found out is the problem within the Windows itself, it's not the Programs issue as far as I can tell, so what's the issue here is that the game creates a key in the registry telling the game to which pid the steamclient.dll should be pointed, I know it sounds weird but maybe it's just Windows 8.1 acting crazy. So as you run the program again, the pid number changes, maybe not always but clearly does. So after spending 3 god damn days I've finally managed to fix it. It's simple.

Log out and Log in the Windows and THAT'S IT!!
So I'm sorry for wasting your time and I hope you find this helpful too if you encounter such issue (which I hope you won't!! It was kicking my head for some time.. uggr)

Have a nice day guys :)

**Comment by 0nurky** [comment]
False alarm I guess. So I've found some issue within Windows I guess.
What I did was I Log out of the system and Log back in and the game did work, but when I close it and try to open it, the same error pops out!! I'm starting to think it has to do something with drivers or some kind of service...
