### ISSUE TITLE
'min' / 'max' was not declared in this scope

### ISSUE THREAD

**Issue by CalmBit** [ValveSoftware/halflife#1859]
I'm trying to build the hldll/hl_cdll on Arch Linux, but I'm encountering the following error:

```
../dlls/apache.cpp: In member function ‘BOOL CApache::FireGun()’:
../dlls/apache.cpp:815:16: error: ‘min’ was not declared in this scope
   m_angGun.x = min( angles.x, m_angGun.x + 12 );
                ^~~
../dlls/apache.cpp:815:16: note: suggested alternative: ‘sin’
   m_angGun.x = min( angles.x, m_angGun.x + 12 );
                ^~~
                sin
../dlls/apache.cpp:817:16: error: ‘max’ was not declared in this scope
   m_angGun.x = max( angles.x, m_angGun.x - 12 );
                ^~~
../dlls/apache.cpp:817:16: note: suggested alternative: ‘fmax’
   m_angGun.x = max( angles.x, m_angGun.x - 12 );
                ^~~
                fmax
../dlls/apache.cpp:819:16: error: ‘min’ was not declared in this scope
   m_angGun.y = min( angles.y, m_angGun.y + 12 );
                ^~~
../dlls/apache.cpp:819:16: note: suggested alternative: ‘sin’
   m_angGun.y = min( angles.y, m_angGun.y + 12 );
                ^~~
                sin
../dlls/apache.cpp:821:16: error: ‘max’ was not declared in this scope
   m_angGun.y = max( angles.y, m_angGun.y - 12 );
                ^~~
../dlls/apache.cpp:821:16: note: suggested alternative: ‘fmax’
   m_angGun.y = max( angles.y, m_angGun.y - 12 );
                ^~~
                fmax
make[1]: *** [Makefile.hldll:161: release/obj/hldll/apache.o] Error 1
make[1]: *** Waiting for unfinished jobs....
../dlls/client.cpp: In function ‘int GetWeaponData(edict_s*, weapon_data_s*)’:
../dlls/client.cpp:1625:35: error: ‘max’ was not declared in this scope
       item->m_flTimeWeaponIdle  = max( gun->m_flTimeWeaponIdle, -0.001 );
                                   ^~~
../dlls/client.cpp:1625:35: note: suggested alternative: ‘fmax’
       item->m_flTimeWeaponIdle  = max( gun->m_flTimeWeaponIdle, -0.001 );
                                   ^~~
                                   fmax
make[1]: *** [Makefile.hldll:161: release/obj/hldll/client.o] Error 1
```

GCC Version: 7.2.1 20180116

**Comment by SamVanheer** [comment]
It should be defined in `extdll.h`, but only if `_WIN32` is not defined. Are you sure that definition is not present?

**Comment by CalmBit** [comment]
Another compilation test confirms that it's not defined, and even removing the `#ifdef` blocks from `extdll.h` doesn't seem to fix it.

**Comment by SamVanheer** [comment]
Try adding this to both `extdll.h` and `client.cpp` (after the `#define max` and `#include "extdll.h"`, respectively):

```
#ifdef max
#error Max defined
#endif
```

If this hits in `extdll.h` then max is being defined, if it hits in `client.cpp` then the definition is making it to that file. If it isn't being hit in `extdll.h` then something is preventing it, and it if isn't being hit in `client.cpp` and is hit in `extdll.h` then something is undefining it elsewhere.

If this is the case, you should pinpoint the cause of this, one way is to move the check up above each include until it hits, then you know which file is doing that.

**Comment by CalmBit** [comment]
It seems to actually be undefined in `extdll.h`, after `#include "stdlib.h"`. The solution was to put the definitions after that include. Thank you for your help!

**Comment by CalmBit** [comment]
Whoops, this actually does seem to conflict with a definition of min in `stl_algobase.h`...
