### ISSUE TITLE
[HL] Add HTML Support in motd window

### ISSUE THREAD

**Issue by tyabus** [ValveSoftware/halflife#1873]
In CS you can use HTML to build colorful and very interesting MOTD windows.
In HL there is not. If you try to put HTML code to motd you just see html markup tags in the MOTD window as just text.

**Comment by tschumann** [comment]
I think it's just a matter of loading the right interface and calling the right methods - https://github.com/SamVanheer/HLEnhanced I think has code to do it (https://github.com/SamVanheer/HLEnhanced/blob/master/source_sdk/public/vgui/IHTML.h is the interface I think but I'm not sure).

**Comment by tyabus** [comment]
And how i can compile, or use it? (sorry for my stupid questions)
