### ISSUE TITLE
The end of open-source GoldSource engine dream(?)

### ISSUE THREAD

**Issue by BlackPhrase** [ValveSoftware/halflife#1874]
In continuation to #1712 

Open sourcing the GoldSrc is a pretty nice idea
But absolutely useless
Everything that community would be able to do with it is to leave a bunch of likes, add to watchlist and fork it without doing anything with that fork
Am I wrong?
I don't think so

**Comment by BlackPhrase** [comment]
**UPD:**
Looks like the game code will also be reimplemented (now for sure)
I'll try to provide something similar to original HL
Still waiting for Alfred's response, but "reimplemented Half-Life Engine != Half-Life Engine" so 99% sure that it wouldn't be possible to interconnect the reimplemented GS with original GS mods without violating the HLSDK EULA

**Comment by BlackPhrase** [comment]
Is anyone planning to write a mod for this engine?
If not, I'll just merge the game and sdk code with the engine repo

**Comment by sballu** [comment]
Can't say I will write a mod for this engine, but at least I'm following your project.

**Comment by BlackPhrase** [comment]
Anyone wanna help porting the game code?
https://github.com/BlackPhrase/ReHL

**Comment by BlackPhrase** [comment]
Only 3 months left...

**Comment by BlackPhrase** [comment]
First breath after almost 2 years overall...
(Or half a year for this specific generation)

> #0  0x6a7f3d30 in FS_Open (pFileName=0x28fb74 "./valve/pak0.pak",
>     pOptions=0x6a829574 "rb")
>     at G:\...\goldsrc\engine\filesystem_internal.cpp:93
> #1  0x6a7cb032 in COM_LoadPackFile (packfile=0x28fb74 "./valve/pak0.pak")
>     at G:\...\goldsrc\engine\common.c:1525
> #2  0x6a7cb328 in COM_AddGameDirectory (dir=0x6a839f00 <string> "./valve")
>     at G:\...\goldsrc\engine\common.c:1600
> #3  0x6a7cb4cb in COM_InitFilesystem ()
>     at G:\...\goldsrc\engine\common.c:1664
> #4  0x6a7ca78f in COM_Init (
>     basedir=0x405120 <VENGINE_HLDS_API_VERSION+136> ".")
>     at G:\...\goldsrc\engine\common.c:1089
> #5  0x6a7cda8f in Host_Init (parms=0x6a83d35c <Sys_InitGame::parms>)
>     at G:\...\goldsrc\engine\host.c:796
> #6  0x6a7f4c88 in Sys_InitGame (
>     lpOrgCmdLine=0x40511b <VENGINE_HLDS_API_VERSION+131> "TODO",
>     pBaseDir=0x405120 <VENGINE_HLDS_API_VERSION+136> ".", pwnd=0x0,
>     bIsDedicated=1)
>     at G:\...\goldsrc\engine\sys_dll2.cpp:96
> #7  0x6a7f4fe7 in CEngine::Load (this=0x6a83d3c0 <gEngine>, dedicated=true,
>     basedir=0x405120 <VENGINE_HLDS_API_VERSION+136> ".",
>     cmdline=0x40511b <VENGINE_HLDS_API_VERSION+131> "TODO")
>     at G:\...\goldsrc\engine\sys_engine.cpp:41
> #8  0x6a7f4dee in CDedicatedServerAPI::Init (
>     this=0x6a83d380 <g_CDedicatedServerAPI_>,
>     basedir=0x405120 <VENGINE_HLDS_API_VERSION+136> ".",
>     cmdline=0x40511b <VENGINE_HLDS_API_VERSION+131> "TODO", launcherFactory=
>     0x401ca4 <CreateInterface(char const*, int*)>, filesystemFactory=
>     0x71101dd8 <CreateInterface(char const*, int*)>)
>     at G:\...\goldsrc\engine\sys_dll2.cpp:246
> #9  0x00401a9c in RunServer ()
>     at G:\...\goldsrc\dedicated\sys_ded.cpp:289
> #10 0x00401c84 in main (argc=1, argv=0x3419b8)
>     at G:\...\goldsrc\dedicated\sys_ded.cpp:320

**Comment by BlackPhrase** [comment]
**Build 0012 "You don't need sigils when you have SIGILLs!":**
* Fixed filesystem code so it now can load wads and lumps;
* Fixed QGL initialization; (Currently fails at video initialization caused by QGL)
* Fixed uninitialized pointer to ICDAudio implementation;

**Comment by BlackPhrase** [comment]
![quakd](https://user-images.githubusercontent.com/10573466/45786911-a6498400-bcad-11e8-806a-c8a28f2c7e91.png)
