### ISSUE TITLE
[Discussion] GoldSrc/CS1.6 is an a*s. We won't be working with him again.

### ISSUE THREAD

**Issue by i486** [ValveSoftware/halflife#1875]
Blizzard recently updated their 16 year old game Warcraft III, adding big improvements like native widescreen support, 24-player mode, map pools updates, tons of balancing and stuff. 

Please... 

Valve

I am not asking you to be like Blizzard. 

I am definitely not asking you to add skins and gloves to CS 1.6. We already have CS:GO.

I am just asking you to have a little bit of decency. LOL. I am serious though.

Can you please do that? Like starting by adding some of those improvements and bugfixes ALREADY made by these guys like Vanheer, REHLDS and such?

The game is a legend. It's sad to see it abandoned like that. 

Sorry about my english. 

Regards

**Comment by djdallmann** [comment]
You should exhibit more professionalism on here if you want to get respect from valve, and yes there's still a lot of people playing CS 1.6 and on the engine, myself included. 

I would also like to see some of the bug fixes people have suggested.

**Comment by kisak-valve** [comment]
Please use the forums for general discussion.
