### ISSUE TITLE
Improve netcode to that of CS 1.3 or below

### ISSUE THREAD

**Issue by dwhy83** [ValveSoftware/halflife#188]
The CS 1.3 netcode was more responsive than later versions of the game.  We saw evidence of this change of behavior as top tournament players lost their ability to effective spray weapons accurately with later releases.

I read a white paper about the netcode by Yahn W. Bernier (yahn@valvesoftware.com), and it seems this change was made in order to mitigate cheating.

Here is a relevant excerpt from the paper (bolded sentences to get the gist):

https://developer.valvesoftware.com/wiki/Latency_Compensating_Methods_in_Client/Server_In-game_Protocol_Design_and_Optimization#Client-Side_Prediction_of_Weapon_Firing
###### Client-Side Prediction of Weapon Firing

> Layering prediction of the firing effects of weapons onto the above system is straightforward. Additional state information is needed for the local player on the client, of course, including which weapons are being held, which one is active, and how much ammo each of these weapons has remaining. With this information, the firing logic can be layered on top of the movement logic because, once again, the state of the firing buttons is included in the user command data structure that is shared between the client and the server. Of course, this can get complicated if the actual weapon logic is different between client and server. In Half-Life, **we chose to avoid this complication by moving the implementation of a weapon's firing logic into "shared code" just like the player movement code.** All of the variables that contribute to determining weapon state (e.g., ammo, when the next firing of the weapon can occur, what weapon animation is playing, etc.), are then **part of the authoritative server state and are replicated to the client** so that they can be used on the client for prediction of weapon state there.

But it goes on to say that this was done in order to mitigate cheating:
###### Umm, This is a Lot of Work

> Replicating the necessary fields to the client and handling all of the intermediate state is a fair amount of work. **At this point, you may be asking, why not eliminate all of the server stuff and just have the client report where s/he is after each movement? In other words, why not ditch the server stuff and just run the movement and weapons purely on the client-side? Then, the client would just send results to the server along the lines of, "I'm now at position x and, by the way, I just shot player 2 in the head." This is fine if you can trust the client. This is how a lot of the military simulation systems work (i.e., they are a closed system and they trust all of the clients). This is how peer-to-peer games generally work. For Half-Life, this mechanism is unworkable because of realistic concerns about cheating.** If we encapsulated absolute state data in this fashion, we'd raise the motivation to hack the client even higher than it already is3. For our games, this risk is too high and we fall back to requiring an authoritative server. 

The problem is that the user experience has suffered, but **people still cheat**.  Since cheaters will invariably cheat, why not optimize the netcode experience for everyone else and allow them to manually police cheaters the way they must already do now in tournaments, competitive leagues, and public servers?

Players want to feel empowered, not restricted.  A more responsive game is more fun and addictive.  Please please please do anything you can to optimize the netcode to what it was in CS 1.3 and earlier versions!  Or even improve it beyond that.

**Comment by cenitr** [comment]
Everything client sided would have been much better. The recoil is a must to be client sided. Counter strike is so much ping based game now that it is not competitive at all. Low pingers have huge, huge advantage to high pingers. Recoil gets totally wrong if you have higher ping than 20ms. If you got 50ms it's not even fun to even play the game. 
CS 1.6 is a LAN game unless you have a really, really good internet connection, period.

Great that this is being highlighted somewhere since it have to change or fps is just not fun to play any more.

**Comment by di57inct** [comment]
Everything client-sided = cheated. Play on servers with low ping. I don't care about players with high ping.

**Comment by cenitr** [comment]
With everything client sided we would always have something real to hit and a working spray pattern and bullets. 
From there we want to develop the net code to render players position as correct as possible.
The server admin would set a maximum ping that would be allowed.
For example a higher ping of 30 would not be allowed by the admin and the player would be banned for x hours.
