### ISSUE TITLE
Can't See My Steam-Only CS 1.6 Server On Internet List

### ISSUE THREAD

**Issue by hashnimmo** [ValveSoftware/halflife#1881]
I have hosted a Counter Strike 1.6 server in Singapore yesterday and it's not showing up in the official internet server list. I'm from Sri Lanka and I have a ping lower than 90 milliseconds every time in my server so it's geographically close to my location. Since many other servers with ping 100 - 150 are showing up in my server list including no-Steam and my server just isn't there no matter how much I reload it.

It's been 24 hours since my server has gone online. Why is this? Just bought this game yesterday and the amount of bugs I'm experiencing is just insane, feels I just paid my money for nothing.

**Comment by BlackShadow306** [comment]
Please be more specific.

Did you hosted this server in your own network?
Did you downloaded files with SteamCMD?
Did you use any P47-48 Patchers?
Tried to add your server in Gametracker? Did it gave any errors?

**Comment by Soyrce** [comment]
sv_region

https://developer.valvesoftware.com/wiki/Sv_region

**Comment by hashnimmo** [comment]
>Did you hosted this server in your own network?
No. Hosted on Vultr, and now moved to New Jersey.

>Did you downloaded files with SteamCMD?
Yes. Files I have is back from May 2017 since I can't download app_id 90 through SteamCMD even after running it for 15 times. And now I'm using ReHLDS.

>Did you use any P47-48 Patchers?
Yes. After 48 hours.

>Tried to add your server in Gametracker? Did it gave any errors?
Yes. Added and tracking without any errors.

>sv_region
This cvar is deprecated, it has been removed from the HLDS and the Steam server browser doesn't have an option to select a region any more.

UPDATE: Now I see some players connecting to the server randomly in my logs. But I'm not sure from where they got my server address since I have advertised it literally everywhere I can. Yesterday I finally asked someone who was playing and he said he saw my server in the Steam list and that's how he came to my server so I think this is resolved. But it's confusing for not been able to see it myself.

**Comment by Maxi605** [comment]
@alfred-valve seems to be solved.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by darkallience3** [comment]
StreetZm.CsBlackDevil.Com [STEAM & NON-STEAM] [CSDM] [RESPAWN]
STREETZM.CSBLACKDEVIL.COM ?
DNS: STREETZM.CSBLACKDEVIL.COM™?
IP: 51.89.9.221:27015

WEAPONS
KNIVES
GLOVES
FREE GRENADES
FREE ARMOR
MM RANKS

FOR INCLUDING STREETZM.CSBLACKDEVIL.COM IN STEAM NAME
GET MONEY: +1500??
GET ARMOR
GET HE/FB
FORUM: https://csblackdevil.com
