### ISSUE TITLE
[TFC Linux] HUD Spew Spam Crash...

### ISSUE THREAD

**Issue by APGRoboCop** [ValveSoftware/halflife#1886]
Well I've been testing the latest 2018 update build for my Linux TFC server. I cannot tell fully on how well its doing because for some odd reason when I play and spawn the bots to see how each of the TFC maps and addons are working, my HUD is flooding with Hazard icons, Armour % icon looking glitchy - then all of a sudden crashed.

I am not sure if the addons are responsible for the crash, but this the stdio and TFC build version im using:-

> 14:14:38 version
> 14:14:38 Protocol version 48
>          Exe version 1.1.2.2/Stdio (tfc)
>          Exe build: 17:23:32 May 24 2018 (7882)

And yes I did use the newer tfc.so not the older tfc_i386.so from HLDSUpdateTool.bin.

**Comment by JoelTroch** [comment]
Can this be reproduced with a clean server installation (aka no addons installed)?

**Comment by APGRoboCop** [comment]
Well I've tried without any addons, followed by FoxBot only and using AdminMod only and AMXX only. And it appears to be some kind of issue with AMXX. I know this isn't AlliedMods forums, but here is the list of AMXX modules and plugins:-

> 19:56:50 amxx modules
> 19:56:50 Currently loaded modules:
>                name                    version     author               status     
>           [ 1] TfcX                    1.8.2       AMX Mod X Dev Team   running    
>           [ 2] GeoIP                   1.8.2       AMX Mod X Dev Team   running    
>           [ 3] FakeMeta                1.8.2       AMX Mod X Dev Team   running    
>           [ 4] Fun                     1.8.2       AMX Mod X Dev Team   running    
>           [ 5] Engine                  1.8.2       AMX Mod X Dev Team   running    
>           [ 6] Ham Sandwich            1.8.2       AMX Mod X Dev Team   running    
>          6 modules, 6 correct

> 19:58:08 amxx plugins
> 19:58:08 Currently loaded plugins:
>                 name                    version     author            file             status   
>           [  1] Admin Base              1.8.2       AMXX Dev Team     admin.amxx       running  
>           [  2] Admin Commands          1.8.2       AMXX Dev Team     admincmd.amxx    running  
>           [  3] Admin Help              1.8.2       AMXX Dev Team     adminhelp.amxx   running  
>           [  4] Slots Reservation       1.8.2       AMXX Dev Team     adminslots.amxx  running  
>           [  5] Multi-Lingual System    1.8.2       AMXX Dev Team     multilingual.am  running  
>           [  6] Menus Front-End         1.8.2       AMXX Dev Team     menufront.amxx   running  
>           [  7] Commands Menu           1.8.2       AMXX Dev Team     cmdmenu.amxx     running  
>           [  8] Players Menu            1.8.2       AMXX Dev Team     plmenu.amxx      running  
>           [  9] Maps Menu               1.8.2       AMXX Dev Team     mapsmenu.amxx    running  
>           [ 10] Admin Chat              1.8.2       AMXX Dev Team     adminchat.amxx   running  
>           [ 11] Anti Flood              1.8.2       AMXX Dev Team     antiflood.amxx   running  
>           [ 12] Info. Messages          1.8.2       AMXX Dev Team     imessage.amxx    running  
>           [ 13] Admin Votes             1.8.2       AMXX Dev Team     adminvote.amxx   running  
>           [ 14] TFC Stats               1.8.2       AMXX Dev Team     stats.amxx       running  
> 19:58:08  [ 15] show motd               1.0         RoboCop           robo_motd.amxx   running  
>           [ 16] Auto Set Langauge       1.5.05      FALUCO/teame06/B  autolang.amxx    running  
>           [ 17] Railgun Blast           2.1         hlstriker         railgunblast.am  running  
>           [ 18] HLstatsX CE Ingame Plu  1.6.19 (HL  psychonic         hlstatsx_comman  running  
>           [ 19] HLSS Blocker            0.1         Ian Cammarata     hlss_blocker.am  running  
>           [ 20] High Ping Kicker        1.2.0       DynAstY           hpk.amxx         running  
>           [ 21] Spray ID                1.12        Cheesy Peteza     sprayid.amxx     running  
>           [ 22] Rates Checker           1.61r3      pizzahut          ratescheck_r3.a  running  
>           [ 23] TFC TP Features         0.3 BETA    Master            tfc_tp_features  running  
>           [ 24] No Spy Crash            1.2         hlstriker,pizzah  nospycrash2.amx  running  
>           [ 25] Simple Team Balancer    2.4.2       pizzahut          stb_beta4.amxx   running  
>           [ 26] Grab + Hook + Rope      1.0         GHW_Chronic       GHW_GHR.amxx     running  
>           [ 27] Bug Fixes TFC           1.0         hlstriker         BugFixesTFC.amx  running  
>          27 plugins, 27 running

If anyone is able to reproduce any HUD Spam crashes, let me know. I'm gonnae test it with AMXX 1.8.3-beta.

**Comment by JoelTroch** [comment]
If the crash happens with AMX Mod X but not without it, you should ask AlliedModders instead.

**Comment by APGRoboCop** [comment]
Yes it appears to run better on AMXX v1.8.3-dev+5154 but not AMXX 1.8.2. It maybe because the latest TFC engine update must of made it dislike 1.8.2...
