### ISSUE TITLE
mouse issue windows 10

### ISSUE THREAD

**Issue by Karaulov** [ValveSoftware/halflife#1887]
Mouse1/Mouse3 buttons works in 80% cases. 

I can't attack in 10% cases, and attack cant disabled when mouse up.

with m_rawinput 1 i can't play in this game. (Play with big additional delay to mouse, and no acceleration)

**Comment by SamVanheer** [comment]
I was looking at the SDL2 source code and found this:
```
/* Win10 "Fall Creators Update" introduced the bug that SetCursorPos() (as used by SDL_WarpMouseInWindow())
   doesn't reliably generate WM_MOUSEMOVE events anymore (see #3931) which breaks relative mouse mode via warping.
   This is used to implement a workaround.. */
```

So the SDL2 library used by the game probably doesn't work properly on Windows 10.

**Comment by Karaulov** [comment]
m_rawinput 1 solve problem with attack but no acceleration mouse as in Window.

**Comment by Karaulov** [comment]
In latest version this comment is changed?

**Comment by BlackShadow306** [comment]
Nope problem still exists, I can't play AWP anymore in Counter-Strike. I can barely rotate my mouse in 2x zoom. Changing zoom cmd making 1x zoom faster and 2x zoom is still slower. It wasn't like this. Happened after the latests updates. Also yeah m_rawinput fixes to issue of pitch and yaw problem.

**Comment by BlackShadow306** [comment]
Nope problem still exists, I can't play AWP anymore in Counter-Strike. I can barely rotate my mouse in 2x zoom. Changing zoom cmd making 1x zoom faster and 2x zoom is still slower. It wasn't like this. Happened after the latest updates. Also yeah m_rawinput fixes to issue of pitch and yaw problem.

**Comment by djdallmann** [comment]
Nice catch Sam! It would be great if they could incorporate latest SDL2 library as it evolves.

**Comment by mikela-valve** [comment]
Closing in favour of #1377.
