### ISSUE TITLE
[LINUX] CS1.6 Kicked :"Fake Player ?!"

### ISSUE THREAD

**Issue by systmrrr** [ValveSoftware/halflife#1890]
**how to fix this issues?
windows can connect but linux not connection :/**

![2018-07-10-000346_1280x1024_scrot](https://user-images.githubusercontent.com/24730797/42476357-5ff7e52e-83d6-11e8-80e9-9c4ef5f1fe86.png)
![2018-07-10-000351_1280x1024_scrot](https://user-images.githubusercontent.com/24730797/42476358-602251b0-83d6-11e8-86c9-d2a3ec33bad6.png)
![2018-07-10-001423_1280x1024_scrot](https://user-images.githubusercontent.com/24730797/42476359-604b4df4-83d6-11e8-84c9-41089cc29de4.png)

**and my system;**
`### Bilgisayar Bilgisi:
    Üretici: Unknown
    Model: Unknown
    Tür: Masaüstü
    Dokunmatik Girdi Algılanmadı

İşlemci Bilgisi:
    CPU Üreticisi: GenuineIntel
    CPU Markası: Pentium(R) Dual-Core  CPU      E6700  @ 3.20GHz
    CPU Ailesi: 0x6
    CPU Modeli: 0x17
    CPU Ölçümü: 0xa
    CPU Türü: 0x0
    Hız: 3203 Mhz
    2 mantıksal işlemci
    2 fiziksel işlemci
    HyperThreading:  Desteklemiyor
    FCMOV:  Destekliyor
    SSE2:  Destekliyor
    SSE3:  Destekliyor
    SSSE3:  Destekliyor
    SSE4a:  Desteklemiyor
    SSE41:  Desteklemiyor
    SSE42:  Desteklemiyor
    AES: Desteklemiyor
    AVX: Desteklemiyor
    CMPXCHG16B: Destekliyor
    LAHF/SAHF: Destekliyor
    PrefetchW: Desteklemiyor

İşletim Sistemi Sürümü:
    Debian GNU/Linux 9.4 (stretch) (64 bit)
    Sistem Adı: Linux
    Sistem Sürümü: 4.9.0-6-amd64
    X Sunucu sağlayıcı: The X.Org Foundation
    X Sunucu Tarihi: 11902000
    X Pencere Yöneticisi: Openbox
    Steam İstemci Sürümü: steam-runtime-beta-release_2017-10-05

Ekran Kartı:
    Sürücü:  X.Org R300 Project Gallium 0.4 on ATI RV515
    Sürücü Sürümü: 2.1 Mesa 13.0.6
    OpenGL Sürümü: 2.1
    Masaüstü Renk Derinliği: 24 bit
    Monitör Yenileme Hızı: 59 Hz
    Üretici Kimliği: 0x1002
    Aygıt Kimliği: 0x7142
    Revizyon Tespit Edilemedi
    Monitör Sayısı:  1
    Mantıksal Ekran Kartı Sayısı:  1
    Birincil Ekran Çözünürlüğü:  1280 x 1024
    Masaüstü Çözünürlüğü: 1280 x 1024
    Birincil Ekran Büyüklüğü: 12.20" x 9.06" (15.20" diag)
 31.0cm x 23.0cm (38.6cm diag)
    Birincil VRAM Belirlenemedi

Ses kartı:
    Ses aygıtı: Realtek ALC662 rev1

Bellek:
    Bellek:  2003 Mb

Çeşitli:
    UI Dili:  Türkçe
    DİL: en_US.UTF-8
    Toplam Kullanılabilir Depolama Alanı: 147190 Mb
    Kullanılabilir Boş Depolama Alanı: 124811 Mb
    VR Başlığı: Hiç algılanmadı

Son Hata Raporları:

`

**Comment by SamVanheer** [comment]
This is not caused by the engine, unless this happens on every server it's some server specific thing.

**Comment by boxvers** [comment]
This is dproto bug (Plugin allows join non-steam players)

**Comment by systmrrr** [comment]
thank you, but windows steam users can connecting server
