### ISSUE TITLE
Goldsrc VAC Bypass method

### ISSUE THREAD

**Issue by BlackShadow306** [ValveSoftware/halflife#1902]
I've found this method few years ago. And i decided to report it. I e-mailed to vacreview@valvesoftware.com about this issue but didn't got any responds. 

So here's the method:

For this method, you'll need Steam ID Changer. It seems VAC verifies from Steam ID first, then checks if the Steam ID is VAC banned or not. However with this ID Changer you can spoof any Steam ID and it grants access to any VAC secured server. However you cannot directly join from "Server Browser". But you can connect by using "connect serverip" on console.

There's some SteamID changers shared to public. Like CT-Shield and Raiz0 Steam Changer.

Hopefully this security issue will be fixed.

**Comment by Splatt581** [comment]
SteamID changers like CT-Shield and others are able to emulate only pirate SteamID's, i.e. with such it will not be possible to connect to the "only Steam" server. So this problem concerns exclusively pirated servers.

**Comment by BlackShadow306** [comment]
I've tested and works okay with Non-steam/Steam servers.

**Comment by SamVanheer** [comment]
VAC doesn't immediately ban you, it's delayed. If you've been using this on your own account, you are putting yourself at risk of getting banned.
While the server-side authentication system may be fooled, the client side cheat detection system will be able to see if the Steam ID being sent differs from the active Steam account ID, so you can still be banned by doing so. I suggest you avoid doing this in the future.

**Comment by BlackShadow306** [comment]
I know VAC collects your data as a hash first then checks collected hash in their database to see if it's matching with any cheat. And also yeah this method will get you VAC if you're not banned. But i was trying this on my VAC banned account. And it was working pretty well.

**Comment by BlackShadow306** [comment]
This method no longer works.
