### ISSUE TITLE
Open-source GoldSource engine (Push It To The Limit Edition)

### ISSUE THREAD

**Issue by BlackPhrase** [ValveSoftware/halflife#1910]
@kisak-valve
@Nephyrin
Please don't close the issue before November 9, if you want to do that, thanks!
You won't open-source the original GoldSource engine, would you? So let at least the community do that

Alright, so for all this time since February I've been working on reimplementing the GoldSrc engine using the original GPL Id Tech 2 Engine (NetQuake/QuakeWorld/Quake2). It's still rough and ugly as hell, but partially works. The codebase is fully clean and consists only of GPL (or other open GPL-compatible licenses) code. SDK code is also partially reimplemented using the original code (some pieces were manually retyped). Can't say for sure, but the game code will probably also end up being reimplemented (but it either will be ported Quake (QC progs) code or reimplemented HL Alpha level functionality). I will release it on November 8 this year

What will be provided in the initial release:
* Authentic C code with a lot of wrappers to C++ - one of the goals was to make the codebase look the same as the original GS, by looking at some trace logs it's possible to extrapolate and say that all original Quake code is still in C, all 1998-2002 era code (game interfaces) are also in C and all wrappers are in C++;
* GameDLL support - support to the point of dlls being playable;
* ClientDLL support - partial support to be usable;
* GameUI support - will support original menu code (= HL Alpha) moved to gameui dll;
* Reimplemented fs module - filesystem code was moved to a filesystem_stdio module (VFileSystem009) and a wrapper for it was added at the engine level;
* GL Render improvements - QGL integration (gl exports are loaded dynamically (the same as GS does), transparent textures support and such;
* Reimplemented interface factory code with virtual destructor removed from the IBaseInterface which make modules ABI-compatible between various compilers (but no compatibility with original GS modules);
* Reimplemented listenserver/dedicated launchers - the code was modified to use IEngineAPI and IDedicatedServerAPI interfaces;
* vguiwrap - custom intermediate level module to optionally support original vgui1 library (compatibility with original client dlls);
* Reimplemented pm_shared module - mostly will contain pmove code moved from the engine without any bunnyhop fixes and/or such;
* User Messages system reimplementation - to add custom game messages;
* Studio models support;
* WAD3, SPRITE_VERSION 2, BSP format 30 support - mostly tweaked constants. It probably will temporarily support 29 format again to load the HL Alpha techdemo map later;
* Partially reimplemented protocol 48 support (excluding resource sending and delta encoding);
* "SOMETHING ELSE, WILL BE ADDED LATER"

I doubt that I will be working on it after that, so it would be nice if someone could provide some help with stuff, it would be sad if this thing ends up nowhere after all the effort put in it
If the community needs an open-source GoldSrc engine this is pretty much the chance to make it real IMO. The only thing I'm sad about is that it won't be in a fully functional state by the time, but at least it will be playable. As guys at Valve said, they might open-source the engine, but not interested in that, and I'm not interested in making them interested

I'll keep my promise and release it on November 8. Don't trust me if you want, I'm not forcing you. But don't forget that I spent 2 years on this and rewrite it from the beginning 4 times during the period and after all that I'm still here. And I want to receive at least one good thing from this shitty year

If you're interested in helping this to come true, let me know by posting here

**P.S. HATERS GONNA HATE**

**Comment by BlackPhrase** [comment]
Also, forgot to mention that reimplemented client dlls will be using the reimplemented vgui2 library
There will be a special interface provided for it specifically to get its interfaces through it
This interface will be sort of specific engine extension that replaces the original "F" export function, it will be optional, so if you don't want to use engine factory interfaces, you just can skip and don't expose the implementation of this interface from your module, the engine will then try to load it through "F" export or on per-export basis (as the original GS does)
There was a discussion about what can be improved in the engine if it's being open-source and one of the ideas was to update engine<->gamedll/clientdll interfaces, so this interface will be a good starting point for that

**Comment by BlackPhrase** [comment]
Well, looks like both engine<->game and engine<->client modules interfaces are now in compliance with the original GS, so I think that it's now possible to provide links to reimplemented sdk and game code repos if someone wanna start working on writing a mod/game or sdk documentation

**Comment by BlackPhrase** [comment]
Looks like we're running out of time...

**The Alpha release will be on the November 8th**
It should contain most of the features from the list above implemented
This is the GS engine release so it will mostly be aimed at engine features support

**The Beta release will be on the November 19th**
It should contain the rest of the unimplemented features and fixes to all of the implemented
This is the HL release so it will feature updated game code closer to HL(:Alpha) functionality
I'll appreciate if someone could help with the game code. I'll update it soon with latest additions from the engine repo but it still needs a lot of things to do. It would be nice if someone could fix worldspawn, player, at least one type of weapon and at least one type of monster code. Here's the repo: https://github.com/headcrab-junkyard/goldsrctest

And, let's say...
**The Final release will be on the December 31th**
...which hopefully will support reimplemented VGUI2, additional implementation of GameUI module using the VGUI2, voice sentences, scripted sequences, delta encoding, save game system, resource loading and fixes to the previous features

I will be working on the engine during the rest of the year and only accepting pull-requests since 2019
<s>Make GS great again!</s>

**Comment by BlackPhrase** [comment]
Trying to get rid of fixed palette...
![ogs-menu-test2](https://user-images.githubusercontent.com/10573466/48062897-bccc8000-e206-11e8-9bbd-4a030a3c46af.png)

**Let me know if someone planning to write a mod using the engine, otherwise I'll merge 3 engine repos (main engine code, sdk, game code) into one**
At least it would be one abandoned repo instead of three in that case...

**Comment by hogsy** [comment]
It's now November the 12th. Can't say I'm surprised to see absolutely nothing come of this. And to be quite honest, I think people should focus on using these boards for real issues - Valve is quite clearly not interested in open-sourcing Half-Life and this doesn't seem like the place to advertise your personal projects.

> P.S. HATERS GONNA HATE

🙄

**Comment by BlackPhrase** [comment]
Patience
![ogs-map-test](https://user-images.githubusercontent.com/10573466/48351806-855e4780-e6ce-11e8-8044-403873f9876b.png)
