### ISSUE TITLE
[HL1] Mouse left click not working sometimes

### ISSUE THREAD

**Issue by tr37ion** [ValveSoftware/halflife#1918]
If playing HL1 my left mouse button is randomly not working for seconds. I change the weapon or just stay in front of an enemy and nothing happens.

---

Processor Information:
    Vendor:  GenuineIntel
    Speed: 2301 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.7.3-1-ARCH
    X Server vendor:  The X.Org Foundation
    X Server release:  11301000

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 9.0.1
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0xdf4
Number of Monitors:  2
Number of Logical Video Cards:  2
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 3286 x 1080
Primary Display Size: 20,91" x 11,77"  (23,98" diag)
                                        53,1cm x 29,9cm  (60,9cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel CougarPoint HDMI

Memory:
    RAM:  7843 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  201822 Mb
    Largest Free Hard Disk Block:  61959 Mb

Installed software:

Recent Failure Reports:

**Comment by WhiteMaterials** [comment]
@gdrewb-valve @vitaliyvalve @kisak-valve @alfred-valve @pd-valve @jeffmvalve @cboyd-valve @austinp-valve @mikela-valve @davidw-valve @EricS-Valve @jeffmvalve @charleslvalve  @jstevens-valve @Nathanael-Valve need more updates for CounterStrike 1.6 

Please ban this my fake for bad pings :)

**Comment by WhiteMaterials** [comment]
@kisak-valve Need fix hitboxes in hlds! See hitbox fixer plugin.

**Comment by shawns-valve** [comment]
Closing this due to age. Please reopen / create a new issue with updated information if it still repros with the 25th anniversary update (December 2023 Steam build).
