### ISSUE TITLE
Half life - Gordon stuck in wall on map transition after tram ride

### ISSUE THREAD

**Issue by salty-horse** [ValveSoftware/halflife#1921]
Start a new game. When exiting the tram, go through the door to the "map transition room" before the black mesa reception area.

Stand in the farthest-right corner. After the map transition, you will be stuck in the wall with no way to move.

**Comment by shawns-valve** [comment]
Some player movement changes were made in the 25th anniversary update (December 2023 Steam build) to improve situations like this where the player can get stuck on level transitions. It's not foolproof, but this should be much less likely to happen now. SDK update forthcoming.
