### ISSUE TITLE
[CS1.6]: in-game UI offset

### ISSUE THREAD

**Issue by ZeXx86** [ValveSoftware/halflife#1931]
Look at the pictures:
![Sn mek obrazovky po zen 2013-02-01 00:14:43](https://f.cloud.github.com/assets/3097353/116528/1d19493e-6bfc-11e2-8948-fdd60782902f.png)
![Sn mek obrazovky po zen 2013-02-01 00:14:50](https://f.cloud.github.com/assets/3097353/116530/244749f4-6bfc-11e2-8b77-b1f4d4aa4d29.png)

No more description is needed I think.

My system info:
http://pastebin.com/E5PJreLG

**Comment by SamVanheer** [comment]
#2240 is a duplicate of this. I described the cause in that issue.

**Comment by shawns-valve** [comment]
This should be fixed (and widescreen modes better supported) as of the December 12, 2023 Counter-Strike update on Steam, corresponding to the Half-Life 25th anniversary updates.
