### ISSUE TITLE
[HL1] No controller/joystick support

### ISSUE THREAD

**Issue by mrbrainsample** [ValveSoftware/halflife#1937]
The cvars and commands are there, but the GoldSrc games (Half-Life and Counter-Strike) don't detect any connected controllers.

Not sure if this is a "bug" or "not implemented feature", but controller supports is perfect in the Windows version, so parity would mean that it works under Linux, too.

**Comment by FindTheBorealis** [comment]
This needs retesting now that Half-Life's input code received a revamp for full Steam Input compatibility in the 25th anniversary update.

**Comment by mrbrainsample** [comment]
Tested with recently updated Half-Life.

As long as SDL_GAMECONTROLLERCONFIG is set correctly, joystick works. I can't bind buttons through the interface, but I can still do it through cfg files, so that works for me.

Closing 10+ year old bug report!

Going to re-play a 25 year old game!
