### ISSUE TITLE
keyboard input randomly dropped or never registering

### ISSUE THREAD

**Issue by jarreboum** [ValveSoftware/halflife#1941]
AS an example I keep the forward key pressed but Gordon will randomly stop, and start again. Sometimes he would never start again, I would have to release the key and press it again. What can also happen is I start pressing the key and the input is never registered, Gordon never moving. This is pretty consistent as the input bug happens in a matter of seconds (I don't think I had a stable input for more than 3 to 4 seconds.)

This happens since the last two patches or so and may be related to how the inputs were changed to accomodate for other layouts.

As far as I know this happen with every key on the keyboard, ctrl alt shift space included.

I'm using the french alternative layout on Ubuntu 12.04. Computer is Asus Eee 901. Possibly related to https://github.com/ValveSoftware/steam-for-linux/issues/1023.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?
