### ISSUE TITLE
[CS] 16bit smoke grenade

### ISSUE THREAD

**Issue by tyftler** [ValveSoftware/halflife#1953]
If the colors are set to 16bit, one can see through smoke grenades way better than somebody using 32bit. It's like an often used cheat in clanwars, because you cannot prove it.

**Comment by SamVanheer** [comment]
The command line options `-16bpp`, `-24bpp` and `-32bpp` are checked but ignored in `CVideoMode_Common::Init`, and no 16 bit option exists in the Video Options tab today.

During startup all supported display modes [are retrieved](https://wiki.libsdl.org/SDL_GetDisplayMode), and are added with 32 bit color depth always, regardless of whether the system is reporting it as that depth or another one.

There is no way to force 16 bit color depth, even using Windows's compatibility mode will not affect bit depth.

Note that the engine sets these OpenGL settings:
* 4 bits for R
* 4 bits for G
* 4 bits for B
* 0 bits for A (this is normal, the color buffer rarely needs an alpha channel unless you're doing render-to-texture followed by overlaying)
* 24 bits for depth buffer

If the engine fails to create a window with these settings it will reduce bit depth:
* 3 bits for R
* 3 bits for G
* 3 bits for B
* 0 bits for A
* 16 bits for depth buffer

So if your system doesn't support a 12 bit color buffer depth it will fall back to a 9 bit color buffer depth.

This is not the same as image quality, images are uploaded as 32 bit RGBA even if the source data is 8 or 16 bit data.

Regardless of color buffer settings it should still render smoke properly, but if it doesn't then something will need to be done to prevent that.

If it is no longer possible to reduce smoke quality then this issue can be closed, so i request a retest to confirm this.

**Comment by kisak-valve** [comment]
Closing pending feedback.
