### ISSUE TITLE
mouse way to sensitive ubuntu 12.04 with half life 1 purchased thru steam

### ISSUE THREAD

**Issue by provervm** [ValveSoftware/halflife#1956]
if i move my mouse even the slightest bit. the character goues into a spin. i have set sensitivity to zero.

**Comment by shawns-valve** [comment]
Closing due to age -- there were some input changes in the 25th anniversary update that could have affected this behavior; please reopen / create a new issue if this still occurs with the December 2023 Steam build. Also try toggling "Raw mouse input" off or on in the Aim options.
