### ISSUE TITLE
NPC voices sound like chipmunks

### ISSUE THREAD

**Issue by FreeBooteR69** [ValveSoftware/halflife#1957]
I use Alsa/kmix and when running Steam with:

SDL_AUDIODRIVER=alsa
AUDIODEV=hw:0,0 

When running Half-Life the NPC voices sound sped up and i can't make out what they are saying.

**Comment by shawns-valve** [comment]
Closing due to age. Please reopen / create a new issue if this still occurs with the 25th anniversary update (December 2023 Steam build) on a current Linux distribution.
