### ISSUE TITLE
[HL1] Have to reload after becoming stuck

### ISSUE THREAD

**Issue by eggman314** [ValveSoftware/halflife#1975]
![2013-02-10_00001](https://f.cloud.github.com/assets/3087751/143061/a1fd9606-7362-11e2-8cce-0fdf26e988da.jpg)

At the start of the Blast Pit level, if you crouch and move all the way over to the wall between the pipes (location of the sights in the screenshot), you will become stuck and need to reload.

**Comment by shawns-valve** [comment]
The 25th anniversary update fixed a few issues where the player could get stuck, especially on level transitions. If this still repros with the December 2023 Steam build, please reopen / post a new issue and attach a savegame at this location.
