### ISSUE TITLE
[HL1] Player stuck (unable to move) after loading 

### ISSUE THREAD

**Issue by jc61990** [ValveSoftware/halflife#1977]
After getting off the train in the very beginning of HL1. When the guard opens the door, i seem to have walked over one of the angled lights on the floor, and while i was walking over it, the game loaded the next area. once the "Loading..."  disappeared,  the Audio seemed to be playing the track like a broken record,  and i was unable to move my player. I am able to move my mouse around and free look, but WASD do nothing, neither does crouching or jumping.  Quitting the game seemed to be the only fix.

![2013-02-10_00004](https://f.cloud.github.com/assets/3512872/143223/86ca077c-7383-11e2-9c93-fccc0331e57e.jpg)
![2013-02-10_00005](https://f.cloud.github.com/assets/3512872/143225/8d0fcdb0-7383-11e2-9df5-5cc25fd707bb.jpg)

this is the floor light DIRECTLY ACROSS from where i am standing.

**Comment by shawns-valve** [comment]
The 25th anniversary update fixed a few issues where the player could get stuck, especially on level transitions. The fix isn't foolproof, but the issue should occur much less frequently. If you can still repro this with the December 2023 Steam build, please reopen / post a new issue and attach a savegame at this location.
