### ISSUE TITLE
[CS1.6] Resolution / Aspect Ratio scaling.

### ISSUE THREAD

**Issue by skylit** [ValveSoftware/halflife#1978]
- Proper Hor+ scaling on widescreen.  This is more of a personal request that while isn't "needed" will help overall perception between 5:4, 4:3, 16:10, and 16:9.. or even 21:9 in future.  This is standard on source and current alternative engines that are horizontally scaled. 

Ex: 
90 fov on 16:9 = 106.26~
90 fov on 16:10 = 100.39~
90 fov on 4:3 = 90
90 fov on 5:4 = 86.3
- Old issue with default_fov command:

Right now default_fov is locked at 90 in the current CS release(s).  This command can be set to any value in HL/TFC

Under normal circumstances, sensitivity doesn't change when properly scaled to the correct FOV (HL/TFC), though since 1.6 is "locked" on screen, the effects of sensitivity when using an alternative "default_fov" value get translated regardless. (Even if the screen is still displaying 90 across multiple aspect ratios)

If not changed in anyway or form, at least find a way to lock this to prevent sensitivity issues.
- I'm not technically asking for FOV to be "unlocked", rather to fix an old bug that got over looked (relating to default_fov).  On the other hand, I am asking for the the same type of scaling found in every other modern shooter as the game is currently more enjoyable at 1440x1080 than native 1920x1080 (Screen gets cut off at top and bottom).  

On Quake live and Call of duty 2 or beyond (Quake 3 roots) I believe alternative 16:9 and 16:10 scaling is locked based on the specific aspect ratio you choose.  QL specifically had an "r_aspectratio" command implemented when porting from Quake 3.
- Examples of Hor+ scaling on source engine.

1280x720 16:9 

http://cloud-2.steampowered.com/ugc/576728807216337194/E3792478D3794E3B4E0B9C56AB769D94F9B5D613/

1280x800 16:10

http://cloud.steampowered.com/ugc/576728807216347955/DBE9E42453D1D891A5F915DD5BD2C18EE1838C40/

1280x960 4:3

http://cloud.steampowered.com/ugc/576728807216348439/9E1EFE3A3F2E4D13889E8124C46DD2528B64A9F3/

1280x1024 5:4

http://cloud-2.steampowered.com/ugc/576728807216348814/2A32402094BF243C85343EA95F91B23A9330684E/

**Comment by shawns-valve** [comment]
The 25th anniversary update (December 2023 Half-Life / Counter-Strike build) improves widescreen support, including an "Allow widescreen Field of View" setting in Video options.
