### ISSUE TITLE
Vending Machines in c2a2d.bsp seem to be linked with eachother

### ISSUE THREAD

**Issue by TheSofox** [ValveSoftware/halflife#1981]
In Half-Life, there's an alcove on map c2a2d.bsp (opposite the barricaded security officer), that has two vending machines. However, when you press the button of one vending machine, soda cans appear in the slot of BOTH machines. No matter which button you press on which machine, cans will simultaneously appear in both machines.

**Comment by shawns-valve** [comment]
This is probably below the bar for us to fix at this point, assuming one considers it a bug.
