### ISSUE TITLE
[CS 1.6] Wall bugs

### ISSUE THREAD

**Issue by dmitrosius** [ValveSoftware/halflife#1983]
In this old game we have many wall viewing bugs
1. de_train - http://s017.radikal.ru/i439/1302/a5/2288fb6913f5.jpg (this place http://s019.radikal.ru/i607/1302/09/e096cb55fa95.jpg)
2. de_dust2 - http://s019.radikal.ru/i628/1302/92/77b769259911.jpg and http://s020.radikal.ru/i706/1302/0b/3ce3b1f4b97b.jpg (http://s60.radikal.ru/i170/1302/cf/f95bb612d075.gif)

**Comment by kisak-valve** [comment]
Closing in favor of #525.
