### ISSUE TITLE
[Half-Life][GoldSource] MessageText gets corrupted (AMXX menu).

### ISSUE THREAD

**Issue by LevShisterov** [ValveSoftware/halflife#2002]
Message is split for lines, but each previous line contains all subsequent ones.
See screenshot: http://cloud-2.steampowered.com/ugc/882974208164079881/7495A953A8F38177CD911BB22E2351D08A6AAB39/
Was ok some time ago.

] version 
Protocol version 48
Exe version 1.1.2.1/Stdio (valve)
Exe build: 15:00:41 Feb 13 2013 (5956)

**Comment by shawns-valve** [comment]
Closing due to age (and the screenshot is no longer available). Please reopen / create a new issue if this still occurs with the 25th anniversary update (December 2023 Steam build).
