### ISSUE TITLE
[CS 1.6] Mic input and output is totally broken 

### ISSUE THREAD

**Issue by revo4ever** [ValveSoftware/halflife#2008]
Hi, i'm just tried to use Mic but is not working, All input and output are broken, so when i go boot to windows it's running fine but On linux never work it with me.

On windows when someone speak with his mic, it's pop-up a small text that's contains the speaker's name
On Linux, never show me the pop-up

Processor Information:
    Vendor:  GenuineIntel
    Speed: 3067 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu Raring Ringtail (development branch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-6-generic
    X Server vendor:  The X.Org Foundation
    X Server release:  11302000

Video Card:
    Driver:  NVIDIA Corporation GeForce G210/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 313.18
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xa60
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1600 x 900
Desktop Resolution: 1600 x 900
Primary Display Size: 17,44" x 9,80"  (20,00" diag)
                                        44,3cm x 24,9cm  (50,8cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 512 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC888

Memory:
    RAM:  3817 Mb

Miscellaneous:
    UI Language:  English
    LANG:  fr_FR.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  147848 Mb
    Largest Free Hard Disk Block:  118190 Mb

Installed software:

Recent Failure Reports:

**Comment by shawns-valve** [comment]
Closing due to age. Please reopen / create a new issue if this still occurs with the 25th anniversary update (December 2023 Steam build) on a current Linux distribution.

**Comment by kisak-valve** [comment]
Hello @shawns-valve, friendly note that when you close an issue report on GitHub, it's authoritative and the reporting user can't re-open. As long as your intent is clear, I'll take care of the matching what you intended.

**Comment by shawns-valve** [comment]
> Hello @shawns-valve, friendly note that when you close an issue report on GitHub, it's authoritative and the reporting user can't re-open. As long as your intent is clear, I'll take care of the matching what you intended.

Thanks, what's the right way to close an issue while allowing the reporter to reopen? We're likely going to be closing a lot of old issues over the next few days.

**Comment by kisak-valve** [comment]
Feel free to use your own judgement. The main detail is that I'm around and will take care of the housekeeping.

Personally, with anything that's not conclusively fixed, I tend to request a retest with an up to date system and add the `Need Retest` label. Anybody interested are free respond before I re-evaluate about a month later. If you choose to use that label, I'll take care of following up later.

**Comment by shawns-valve** [comment]
Sounds good, thanks. I think any very old bug reports that aren't easily testable in a current build (especially Linux issues, issues referencing a beta build, or things likely to be OS/driver-related), we should just close, as it's unlikely that anyone from Valve will get to them and they just clutter up the issue list. We should suggest that people open a new issue if they're having similar problems on post-25th anniversary builds. Old feature requests or core game issues that may still be relevant today are probably good to keep open for future reference.

**Comment by metita** [comment]
@shawns-valve This repository has some milestones which were pretty much abandoned I guess? https://github.com/ValveSoftware/halflife/milestones are these going to be there for the unforeseen future or someone will check them at some time in the near future? @mikela-valve was the guy in charge of this repository a couple of years ago but the support stopped probably due to more important projects, do we have any hope for the milestones to be completed or at least reviewed?
