### ISSUE TITLE
HL/TFC doesn't recognise disabled mouse acceleration on Ubuntu 12.10

### ISSUE THREAD

**Issue by koala02** [ValveSoftware/halflife#2009]
Now this problem might have something to do with Ubuntu 12.10 or my Logitech RX250 mouse itself as well. 

The only way for me to disable mouse acceleration on Ubuntu 12.10 is to enter the following commands into the terminal after startup, because the acceleration slider in the mouse settings on Ubuntu apparently doesn't recognise the most leftward position as "mouse acceleration off"

xinput set-prop 'Logitech USB-PS/2 Optical Mouse' 'Device Accel Profile' -1
xinput set-prop 'Logitech USB-PS/2 Optical Mouse' 'Device Accel Constant Deceleration' 1

This works flawlessly on Ubuntu and even the ingame menus of HL/TFC, but as soon as I am truly ingame with free mouselook, the mouse is accelerated again.

I already diasbled the mouse filter and these commands don't help either: 
-noforcemaccel -noforcemparms -noforcemspd

**Comment by shawns-valve** [comment]
Closing due to age. Please reopen / create a new issue if this still occurs with the 25th anniversary update (December 2023 Steam build) on a current Linux distribution.
