### ISSUE TITLE
[CS 1.6] error 640x480 low graph

### ISSUE THREAD

**Issue by zasjfe** [ValveSoftware/halflife#2011]
http://img401.imageshack.us/img401/3351/detrain0003e.png
http://imageshack.us/photo/my-images/17/detrain0002jk.png/
http://imageshack.us/photo/my-images/401/detrain0003e.png/
 OR 
http://www.girlshare.ro/32206837.3

after 15 minutes my eyes gone crazy

by 1024x768 looks better but i dont like to change resolution 
http://img10.imageshack.us/img10/4901/78720543.jpg
and fps jump 80 to 200
http://img29.imageshack.us/img29/5584/65404990.jpg

my system amd procesor 3600+ 2,01 ghz 1gb ram
monitor crt ,85 hz desktop 120 hz ingame
video card nvidia 8400 gs 512 mb

**Comment by shawns-valve** [comment]
Closing due to age (and the screenshots are no longer available). Please reopen / create a new issue if you're still having problems with the 25th anniversary update (December 2023 Steam build).
