### ISSUE TITLE
[CS 1.6] .wad files download error

### ISSUE THREAD

**Issue by CarlosMestre** [ValveSoftware/halflife#2015]
I'm using correctly the sv_downloadurl and the other cvars, there is a mapname.res file whith mapname required files.
All files are downloaded but .wad files not downloaded, just creates a texturename.wad folder in client diretory. And when a client try to join server, "warning: couldn't open texturename.wad"

**Comment by kisak-valve** [comment]
Closing as a duplicate of #1026 / #1526.
