### ISSUE TITLE
[FeatureRequest] Better widescreen support GoldSrc

### ISSUE THREAD

**Issue by spacelike** [ValveSoftware/halflife#2018]
The only problem with the widescreen support in GoldSrc games is that FOV is not automatically adjusted, or in the case of cs 1.6 is completely blocked from being changed.

I'm not suggesting to allow it to be changed by the user, but I suggest simply to automatically adjust it correctly depending on the current aspect ratio being used. This is done automatically in all Source engine games.

Considering that valve has a higher interest in being able to play your games on a television with most TV's these days being widescreen, and also that 4:3 monitors are becoming less and less common it seems reasonable to me that Valve would want to extend the flawless widescreen support of Source engine games down to GoldSrc as well.

**Comment by shawns-valve** [comment]
The Half-Life 25th anniversary update (December 2023 Steam build) has improved support for widescreen resolutions. Check "Allow widescreen Field of View" in the Video options.
