### ISSUE TITLE
Very low screen responsiveness when "Low Video Quality" enabled.

### ISSUE THREAD

**Issue by demencia** [ValveSoftware/halflife#2021]
When I check that option my screen responds like, every 10 seconds.. though netgraph shows different values (eg: 10fps, 50fps, 30fps) It's like the screen only refresh every 10-15 seconds or so.

I'm on archlinux with integrated graphics Intel HD-3000 core i3, 3gb ram.
Game runs great without that option checked, just wanted to try it.

**Comment by shawns-valve** [comment]
The "Low Video Quality" option is no longer present in the current version of Half-Life (post-25th Anniversary update). Please open a new issue if you're encountering similar issues in a current build.
