### ISSUE TITLE
Some issue with bots in cs:cz

### ISSUE THREAD

**Issue by 1zumik** [ValveSoftware/halflife#2023]
First thank you so much for the bots in CS:CZ
they 're quite smart , and friendly with player ,i really like them ,but they have some problem ,it 's so great if this problem can be fixed
1. the biggest problem is CZbots get stuck in ladder because the navigation mesh which attached to ladder faced in wrong side ,so the bot climbs from the back of ladder ,it can't be fixed by nav tuning 

i 'm so glad if this problem can be fixed by adding command "nav_ladder_flip" like CSS :
http://developer.valvesoftware.com/wiki/Navigation_Meshes#Reversing_ladders

[QUOTE]
 Reversing ladders

Sometimes a ladder will be created facing the wrong way. If a ladder is drawn in red, you are looking at it from the back.
 The ladder is drawn in green if it is facing you. To change the orientation of a ladder, simply point at the ladder and use nav_ladder_flip. 
[/QUOTE]
1. the bot always get stuck in the water athough the navmesh 's created :
   They are the worst swimmers ever. They can sometimes jump out of the water, but they drown most of the time . like in cs_docks
2. it's better if cz bots have some command like 
- Marking areas to avoid 

Using nav_avoid to tell bots to avoid the area unless the normal route has become too dangerous.

+Controlling where bots Can hide

Using nav_no_hide to prevent bots from hiding in that area. This can be used to force the creation of hiding spots during the analysis phase.

+Setting up sniper spots

Mark an area using nav_walk and execute nav_make_sniper_spots. This will break the area into small sub-areas which are used internally by the navigation mesh to encourage sniping. 
1. they have some problem in aiming system , when the enemy hide almost his body in corner and the bots see a little part of his body ,they keep shooting near him ,but none of these bullets go on target 

Thanks in advance

**Comment by kisak-valve** [comment]
Closing as a duplicate of #504.
