### ISSUE TITLE
[HL1-Games] keep playing music when map changes

### ISSUE THREAD

**Issue by TheJJ** [ValveSoftware/halflife#2040]
this is a feature request.

I was just playing Half Life Blue Shift and epic music started playing (at ba yard4a), then I walked into the next map, and typical for hl1, the music stops instantly. I was like aawww why..

please modify the game so the music does not end abruptly!

**Comment by SamVanheer** [comment]
Duplicate of #570

**Comment by TheJJ** [comment]
true
