### ISSUE TITLE
[Half-Life] Freight tram extra speed modes

### ISSUE THREAD

**Issue by kprokin** [ValveSoftware/halflife#2052]
Freight trams that can be encountered during "Power Up", "On A Rail" and "Apprehension" chapters have more speed modes than HUD shows. While there is three forward modes and one reverse mode on HUD, the trains have one extra forward mode and three extra reverse modes, four forward and four backward in total. Using fourth forward speed mode in beginning of chapter "Apprehension" leads train to stuck at half way to the crash trigger.

<pre><code>Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0xf
    CPU Model:  0x68
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  1895 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Windows 7 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0
    
l
Video Card:
    Driver:  ATI Radeon X1200 Series 

    DirectX Driver Name:  atiumdag.dll
    Driver Version:  8.593.100.0
    DirectX Driver Version:  8.14.10.647
    Driver Date: 10 Feb 2010
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 59 Hz
    DirectX Card: ATI Radeon X1200 Series 
    VendorID:  0x1002
    DeviceID:  0x791f
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 20.00" x 12.52"  (23.58" diag)
                                            50.8cm x 31.8cm  (59.9cm diag)
    Primary Bus Type Not Detected
    Primary VRAM: 256 MB
    Supported MSAA Modes:  2x 4x 6x 
    
Sound card:
    Audio device: ???????? (Realtek High Definiti
    
Memory:
    RAM:  3839 Mb
    
Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  305242 Mb
    Largest Free Hard Disk Block:  55177 Mb
    OS Install Date: ??? 01 1970
    Game Controller: None detected
</code></pre>

**Comment by baso88** [comment]
The train always had 4+4 speeds with only 3+1 shown on the HUD. This is true for the initial release (v1.0.0.5) and even for the pre-release OEM demo.
