### ISSUE TITLE
HL1 Rocket Launcher bug

### ISSUE THREAD

**Issue by kprokin** [ValveSoftware/halflife#2054]
After shooting a rocket from RL in guided mode (with laser) the weapon doesn't reloads automatically or manually until laser is turned off.

1) Get RL and ammo for it.
2) Turn laser on.
3) Shoot the rocket.

**Comment by CS-PRO1** [comment]
This issue was fixed long ago @kisak-valve you can close this

**Comment by CS-PRO1** [comment]
I remember having this in WON versions, never experienced this in steam releases. Maybe this has to do with Linux builds but I can't confirm. So this needs to be tested in latest Linux release..

**Comment by agrastiOs** [comment]
Tested in Ubuntu 19.04, the issue has been definitely fixed. @kisak-valve may be closed.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
