### ISSUE TITLE
High CPU LOAD [Counter-Strike 1.6 + OpenGL + Linux]

### ISSUE THREAD

**Issue by klaus1488** [ValveSoftware/halflife#2059]
Using any kernel between 4.18 and 4.19 (with Intel HD Graphics 620 and CPU Intel i5-7200U) CPU LOAD will be very high; --I checked multiple times and load average is up to 4.00 at all times--.
Window manager: i3wm
Is there any possibility or tweak my integrated graphics in the system to lower consumption or something?

I already did my own userconfig.cfg disabling a few graphical options and nothing changed.

The game works great, but the temperatures on my CPU go sky rocket high.
Many blessings and thanks.

**Comment by klaus1488** [comment]
Updated my issue with correct info.

**Comment by Karut** [comment]
Why is it closed? Can you provide a solution?

**Comment by klaus1488** [comment]
I don't think CPU load can be improved. It's always 3.00 up to 4.00. The game runs on a very old engine.
CS: Source on the other hand, runs better on little load and temps are much lower.
That's why I close the ticket.
