### ISSUE TITLE
[CS 1.6] ScrollTextUp does not form cyrillic pfnConsolePrint argument correctly

### ISSUE THREAD

**Issue by 2010kohtep** [ValveSoftware/halflife#2060]
Hi. There's a little problem in the client function **ScrollTextUp**: the Cyrillic text in the chat can't be printed to console.

```
int ScrollTextUp()
{
    // ...

    localize = vgui2::localize();
    (*(*localize + 24))(localize, g_sayTextLine, buf, 512);
    pEnd = &buf[strlen(buf)];
    pBuf2 = buf;
    *pEnd = 10;
    chr = buf[0];
    if ( buf[0] )
    {
      pbuf = buf;
      do
      {
        if ( chr > 5 )
          *pBuf2++ = chr;
        chr = *++pbuf;
      }
      while ( *pbuf );
    }
    *pBuf2 = 0;
    gEngfuncs.pfnConsolePrint(buf);
    
	// ...
}
```

Obviously, this code should delete characters that are responsible for the color of the text in the chat, however, with these characters it also deletes everything above 127, that is the Cyrillic character table. This is due to the fact that the variable **chr** has the type **signed** char. To solve this problem, it is necessary that **chr** has **unsigned** char type.

**Comment by Mistrick** [comment]
Any info about fixing this annoying bug?
We still can't read console messages in native language.

**Comment by 2010kohtep** [comment]
I implemented the patcher in the form of an ASI module, which demonstrates the work of the fix by replacing type **char* with **unsigned char** of **chr** variable.

https://github.com/2010kohtep/ScrollTextUpFix

**Comment by mikela-valve** [comment]
Hi @2010kohtep, this should be fixed in the current CS beta.

**Comment by Mistrick** [comment]
Confirm, fixed

**Comment by 2010kohtep** [comment]
![image](https://user-images.githubusercontent.com/2564175/56457277-d6125480-6380-11e9-8554-e39a012ffa5f.png)

Fixed.

**Comment by shelru** [comment]
@mikela-valve can you post list of current diff's between cs beta and stable cs?
