### ISSUE TITLE
Custom master server not working

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/halflife#2074]
After beta update, my CS 1,6 doesn't recognize master server written in masterserver2.vdf.
It seems that masterserver2.vdf isn't loaded. I used custom masterserver before update, and it worked great.

**Comment by SamVanheer** [comment]
Since the SteamPipe update the engine uses the Steamworks API to query for servers, so Steam itself is responsible for this. The only reason to use a custom master server would be to use an unsupported authentication system (e.g. WON2) so this is intended behavior.
