### ISSUE TITLE
Halflife freezes on startup in i3wm

### ISSUE THREAD

**Issue by lytenyn** [ValveSoftware/halflife#2077]
First of all, thanks for bringing Steam to Linux!

When starting Halflife under i3wm (www.i3wm.org), it shows only the background of the start screen, without the usual text. It then freezes completely, and can only be killed using SIGKILL, SIGTERM is not enough.
It properly switches to fullscreen, so this is not the problem.

This does not happen in another window manager, kwin (from KDE) works fine.

This is on Gentoo, using the latest nvidia driver.

Which kind of additional information can I provide?

**Comment by SamVanheer** [comment]
First go to the Half-Life installation directory and check if there is a `qconsole.log` file, if so clear its contents.

Launch the game with `-condebug -dev +developer 2`, then show us the contents of the `qconsole.log` file. It should at least tell us if startup is succeeding or not.

You can also try running the game under GDB and then generate backtrace to see if it's freezing at a particular point, probably while making an OpenGL or SDL API call.

**Comment by lytenyn** [comment]
Again, sorry for the delay.
Just tested again with the latest software, it works now.
Sorry for the noise
