### ISSUE TITLE
[Opposing Force] Gonome crashes game when NPC enemy dies at specific time

### ISSUE THREAD

**Issue by SamVanheer** [ValveSoftware/halflife#2088]
When the Gonome is charging up for a ranged attack by throwing guts and its current enemy dies, and no other enemies can be found by the AI, the game will crash because the animation event for throwing the guts assumes `m_hEnemy` is a valid pointer.

To fix this, the event should check if it's a valid pointer first. Animation event 4 in class `COFGonome` needs this changed.

The logic should look like this:
```
if( m_hEnemy )
{
    //Original code here
}
else
{
    //Clean up unused projectile entity
    UTIL_Remove( m_pGonomeGuts );
}

m_pGonomeGuts = nullptr;
break;
```

To replicate this, load map `of2a1b`, lower your health to a low amount and prime a grenade. When the Gonome in the first area is about to throw guts, release the grenade to kill yourself.

Note that using `kill` will not work because Opposing Force's `ClientKill` implementation only allows its use when the player is playing the CTF game mode.

The same check should be added to event 3 as well, in case the enemy dies a bit sooner in the animation.

**Comment by mikela-valve** [comment]
This should be fixed in the current OpFor beta.

**Comment by SamVanheer** [comment]
Looks like it's fixed. However i don't see any cleanup done if the enemy is null, unless this is done elsewhere?

**Comment by mikela-valve** [comment]
You're right, I saw that m_pGonomeGuts should not be created before animation event 3 but missed that m_pGonomeGuts is potentially carried over to event 4 and needs to be cleaned up there. 

Surprisingly, it looks like everything should still work even without cleaning up as the guts will either be re-used in a later event 3 or 4 or will be cleaned up when the entity is killed or changes state, but I'll add the cleanup here nonetheless.

**Comment by SamVanheer** [comment]
The problem with not cleaning it up is if the Gonome dies it will leave the guts entity lying around, never to be freed. It can result in `ED_Alloc: no free edicts` if a monstermaker is spawning them.

**Comment by mikela-valve** [comment]
Gotcha, I was thinking COFGonome::Killed would handle it or COFGonome::SetActivity if it transitions to a dying activity before being killed.

**Comment by mikela-valve** [comment]
Fixed, will be included in next beta update.

**Comment by mikela-valve** [comment]
Fixed in beta 'Exe build: 11:12:36 May 21 2019 (8244)',

**Comment by mikela-valve** [comment]
Closing as fixed.
