### ISSUE TITLE
[CS 1.6] Favorites Server List got Deleted [FIXED]

### ISSUE THREAD

**Issue by Maxi605** [ValveSoftware/halflife#2089]
I have a problem, my Favorite server list got deleted, i added all of my servers back and now of all 9 only 7 are shown, sometimes 8 and rarely 9, this issue didn't happened to me before, after the server list got deleted the issue started and i can't seem to fix it, checked the files with the option on steam, reinstalled the game, nothing.

**Comment by djdallmann** [comment]
When this happens I fully close steam and re-open, and they come back.

**Comment by Maxi605** [comment]
So, an update on this, it was a Steam problem, not the game, deleting the files that save the server list on the correct steam directory will fix it.

**Comment by JoelTroch** [comment]
Close the issue instead of changing it's title please.
