### ISSUE TITLE
[Opposing Force] Sniper rifle uses wrong bolt cycling animations

### ISSUE THREAD

**Issue by SamVanheer** [ValveSoftware/halflife#2090]
After firing the sniper rifle the bolt cycling animation used is incorrect. When there is another round in the magazine it plays the magazine empty animation, and when the magazine is empty it plays the next round animation.

The function `EV_FireSniper` treats event parameter `iparam1` as a boolean indicating whether the magazine is empty, when it's actually the magazine's bullet count.

The logic needs to be changed from this:
```
gEngfuncs.pEventAPI->EV_WeaponAnimation(empty ? SNIPER_FIRE_LAST_ROUND : SNIPER_FIRE, 0);
```

To this:
```
gEngfuncs.pEventAPI->EV_WeaponAnimation(empty > 0 ? SNIPER_FIRE : SNIPER_FIRE_LAST_ROUND, 0);
```

It's probably a good idea to rename the variable to `iClip` to match the `CSniperRifle::PrimaryAttack` method.

**Comment by mikela-valve** [comment]
This should be fixed in the current OpFor beta.

**Comment by SamVanheer** [comment]
I can confirm that.
