### ISSUE TITLE
[Opposing Force] Desert Eagle red dot disappears when reloading with full magazine

### ISSUE THREAD

**Issue by SamVanheer** [ValveSoftware/halflife#2091]
When reloading a Desert Eagle that has a full magazine the red dot still disappears. It should only do so when actually performing a reload. To fix this, the result of `DefaultReload` should be checked before turning off the laser.

**Comment by mikela-valve** [comment]
This should be fixed in the current OpFor beta.

**Comment by SamVanheer** [comment]
I can confirm that.
