### ISSUE TITLE
[Opposing Force] Displacer has wrong ammo icon on HUD

### ISSUE THREAD

**Issue by SamVanheer** [ValveSoftware/halflife#2092]
The Displacer has the wrong ammo icon on the HUD. Instead of using the same icon as the Egon and Gauss it uses the icon for the M249.

To fix this just use the `ammo` values from `valve/sprites/weapon_egon.txt` in `gearbox/sprites/weapon_displacer.txt`.

**Comment by mikela-valve** [comment]
Hi @SamVanheer, this should be fixed in the current OpFor beta.

**Comment by SamVanheer** [comment]
I can confirm that.
