### ISSUE TITLE
Counter-Strike: Condition Zero won't start on Linux 

### ISSUE THREAD

**Issue by codedcosmos** [ValveSoftware/halflife#2094]
**Problem:**
When starting Counter Strike: Condition Zero, steam says it is running, and two processes hl_linux and hl.sh start. However they use no CPU, barely any RAM and appear to do nothing.

Note that no screen of any kind appears.

**Error Log:**
When running ./hl_linux this error appears:
```
$ ./hl_linux
Error:libsteam_api.so: cannot open shared object file: No such file or directory
Could not load hw.so.
```

**Attempted Solutions:**
* At first I thought something else in the Half-Life folder might be affecting the game and preventing it from starting, so I deleted the folder and unistalled any games that shared that folder. Installed CS: Zero (Without Deleted scenes) and it didn't change the outcome.\
* I tried launching with `-nofbo` as [this suggested](https://github.com/ValveSoftware/halflife/issues/1257)
* I have tried [reinstalling steam](https://github.com/ValveSoftware/steam-for-linux/issues/2344)
* Updating packages

**Steam Information:**
```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 7 1700 Eight-Core Processor          
    CPU Family:  0x17
    CPU Model:  0x1
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3000 Mhz
    16 logical processors
    8 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.20.4-zen1-1-zen
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12003000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2018-11-28

Video Card:
    Driver:  X.Org Radeon RX 570 Series (POLARIS10, DRM 3.27.0, 4.20.4-zen1-1-zen, LLVM 7.0.0)
    Driver Version:  4.5 (Compatibility Profile) Mesa 18.3.1
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x1002
    DeviceID:  0x67df
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 18.90" x 10.63" (21.65" diag)
                                            48.0cm x 27.0cm (55.0cm diag)
    Primary VRAM: 4096 MB

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  16036 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  223813 Mb
    Largest Free Hard Disk Block:  88196 Mb
    VR Headset: None detected

Recent Failure Reports:
```

**Comment by SamVanheer** [comment]
Do other GoldSource engine games work for you?

**Comment by codedcosmos** [comment]
Running  the export command:

```
$ export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH
$ echo $LD_LIBRARY_PATH
.:
$ ./hl_linux
Error:libopenal.so.1: cannot open shared object file: No such file or directory
Could not load hw.so.
Please try again at a later time.
```

Also Half-Life 1 works as expected. I have the valve complete pack, so I can test more if you want.

**Comment by codedcosmos** [comment]
Also when running this command:

```
$ LD_LIBRARY_PATH="/usr/lib:/usr/lib32:." ./hl_linux
Error:libopenal.so.1: wrong ELF class: ELFCLASS64
Could not load hw.so.
Please try again at a later time.
```

A different error appears

**Comment by SamVanheer** [comment]
It looks like you're running on a 64 bit system. You need to make sure it looks for 32 bit libraries first. I'm not sure if Steam distributes them with its installation though.

**Comment by codedcosmos** [comment]
After installing the following packages:

`sudo pacman -S lib32-gtk2 lib32-openal lib32-libcurl-gnutls lib32-curl lib32-nss lib32-dbus lib32-libpng12 lib32-libgcrypt15 lib32-libpulse`

I was able to start Half-Life 1 with the terminal command:

`LD_LIBRARY_PATH="/usr/lib32:." ./hl_linux`

However Counter-Strike: Condition Zero still fails to launch

**Comment by codedcosmos** [comment]
Deathmatch classic also does not start
But hl1 does

**Comment by calexil** [comment]
referencing this solution to see if related to yours: https://github.com/ValveSoftware/halflife/issues/2100

**Comment by codedcosmos** [comment]
Thanks @calexil. Your issue seems to be the same as mine.

Closing as duplicate of https://github.com/ValveSoftware/halflife/issues/2100
