### ISSUE TITLE
MP5 uses wrong spread values

### ISSUE THREAD

**Issue by SamVanheer** [ValveSoftware/halflife#2095]
The MP5 uses the wrong spread values. Originally spread for singleplayer was 3 degrees, and 6 degrees for multiplayer, but in SDK 2.2 it was accidentally inverted.

This needs changing: https://github.com/ValveSoftware/halflife/blob/5d761709a31ce1e71488f2668321de05f791b405/dlls/mp5.cpp#L160

Compare with the original code from SDK 1.0: https://github.com/SamVanheer/Half-Life-Tools-Backup/blame/462a636f10e65b3b195b74118252a769dd94bc4d/src/dlls/mp5.cpp#L177

**Comment by Enokilis** [comment]
An ancient bug that has left many players frustrated over getting their asses undeservedly kicked by the HECU indeed.

**Comment by ViBE-HU** [comment]
woah. that's pretty cool that someone still care about these games while valve don't give a damn 💓

**Comment by mikela-valve** [comment]
Hi @SamVanheer, this should be fixed in the current HL1 and OpFor betas.

**Comment by SamVanheer** [comment]
I can confirm that. The cone is visibly smaller when firing at walls and observing the bullet decals.
