### ISSUE TITLE
Crowbar always does half damage

### ISSUE THREAD

**Issue by Enokilis** [ValveSoftware/halflife#2096]
The crowbar code checks for the duration since the last swing to decide whether or not it should apply full damage. However, since SDK 2.2, the check executes a function that seemingly always returns 0, even though it should have returned the elapsed time, causing the check to fail.
https://github.com/ValveSoftware/halflife/blob/master/dlls/crowbar.cpp#L235

SDK 1.0 for reference:
https://github.com/SamVanheer/Half-Life-Tools-Backup/blob/462a636f10e65b3b195b74118252a769dd94bc4d/src/dlls/crowbar.cpp#L252

**Comment by kisak-valve** [comment]
Closing in favor of #1600.
