### ISSUE TITLE
mesa glsl cache causes Counter Strike 1.6 to hang on startup

### ISSUE THREAD

**Issue by calexil** [ValveSoftware/halflife#2100]
#### Your system information

* Steam client version (build number or date): feb 2 2019
* Distribution (e.g. Ubuntu): Linux Mint 19.1
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. launch steam
2. try to launch cs 1.6
3. error in console: crypto.cpp (1879) : Assertion Failed: rsaKey.IsValid()

**Comment by TTimo** [comment]
Hello,

Can you post more detailed system information?
In particular, graphics hardware and mesa/driver version?

**Comment by calexil** [comment]
sure thing @TTimo 

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD FX(tm)-8350 Eight-Core Processor           
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux Mint 19.1 Tessa (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.0-45-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  Metacity (Marco)
    Steam Runtime Version:  steam-runtime-beta-release_2019-01-10

Video Card:
    Driver:  X.Org AMD Radeon (TM) R9 380 Series (TONGA, DRM 3.23.0, 4.15.0-45-generic, LLVM 7.0.0)
    Driver Version:  4.5 (Compatibility Profile) Mesa 18.3.3 - padoka PPA
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x6938
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.51" x 11.54" (23.50" diag)
                                            52.1cm x 29.3cm (59.7cm diag)
    Primary VRAM: 4096 MB

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  16011 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  112162 Mb
    Largest Free Hard Disk Block:  80216 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by TTimo** [comment]
Try this workaround:

- Open `~/.steam/steam/steamapps/common/Half-Life/hl.sh`
- Add a line: `unset MESA_GLSL_CACHE_DIR` (after `cd "$GAMEROOT"` for instance)

**Comment by calexil** [comment]
that did the trick, although I had to change the file elsewhere(my game lib is on a backup drive)

thanks for the workaround, I guess now a change in mesa or hl needs to be made

**Comment by TTimo** [comment]
This is a mesa issue, which @kisak-valve traced to disappearing after https://cgit.freedesktop.org/mesa/mesa/commit/?id=c605738113fe91d04f799eae52cec28fafac3f2d

If you backport this into your build of mesa - or update to a newer version that has this change - you will not experience this bug anymore.

Not immediately applicable to you, but we will integrate this fix into the next SteamOS mesa update.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by calexil** [comment]
@kisak-valve @TTimo 

Thanks for all your help, do you know if there is a way to be notified when this commit lands in stable mesa? I can't seem to find it.

**Comment by TTimo** [comment]
@calexil I don't know - I don't follow mesa development very closely
