### ISSUE TITLE
CS:1.6 LAN Party (Fatal Error)

### ISSUE THREAD

**Issue by NERVOC1** [ValveSoftware/halflife#2114]
So then i have a LAN party at my home i made a map in J.A.C.K. when the player join my "map00.bsp" a error shows up.

**Explanation:**

I made a map in J.A.C.K. and also made a "mywad.wad" that contains the textures i want.

When a player join my "map00.bsp" this error shows up:

- Fatal Error : couldn't open "mywad.wad"

I put the "mywad.wad" and my "map00.bsp" on <Half-Life\cstrike_downloads\maps>

_Do i have to script a <path> for the .wad or the .bsp?_

**Comment by NERVOC1** [comment]
> So then i have a LAN party at my home i made a map in J.A.C.K. when the player join my "map00.bsp" a error shows up.
> 
> **Explanation:**
> 
> I made a map in J.A.C.K. and also made a "mywad.wad" that contains the textures i want.
> 
> When a player join my "map00.bsp" this error shows up:
> 
> * Fatal Error : couldn't open "mywad.wad"
> 
> I put the "mywad.wad" and my "map00.bsp" on <Half-Life\cstrike_downloads\maps>
> 
> _Do i have to script a for the .wad or the .bsp?_

**Comment by hashnimmo** [comment]
Please refer this and post back the results;
https://steamcommunity.com/app/10/discussions/0/1848072002761484999/#c1848072002766296575

**Comment by stfkolev** [comment]
Your wad files stay in cstrike folder. As I understood, you placed it into the cstrike_downloads/maps. That might be the problem. Try it out, and tell me what's the outcome

**Comment by NERVOC1** [comment]
> Your wad files stay in cstrike folder. As I understood, you placed it into the cstrike_downloads/maps. That might be the problem. Try it out, and tell me what's the outcome

thanks for the answer but i gonna pass the info in an USB
