### ISSUE TITLE
Visual Studio 2017(Build Only hldll)

### ISSUE THREAD

**Issue by NERVOC1** [ValveSoftware/halflife#2123]
**Build Only hldll:**

### Errors
-----------------------------------------------------------------------------
Code :  
           C2668

Description:
           'abs': ambiguous call to overloaded function	

Project: 
           hldll	

File:
           |bmodels.cpp|func_break.cpp|plats.cpp|player.cpp|roach.cpp|

Line:(respectively with the File)
           |559,595,596,597|599|1129|2075|265|

Suppression State:
                             there's no comments

-----------------------------------------------------------------------------

**Comment by JoelTroch** [comment]
Same thing as #2099

**Comment by NERVOC1** [comment]
Do i have to close this issue?

**Comment by JoelTroch** [comment]
If one of the solution in the issue I linked fixed your problem, yes.
