### ISSUE TITLE
[GoldSource] 'spawn' command may crash the game

### ISSUE THREAD

**Issue by 2010kohtep** [ValveSoftware/halflife#2128]
The engine has a console command 'spawn', the purpose of which is to send to the server some information the client has, namely ```ei.servercount``` and ```ei.mapCRC``` (mapCRC is encrypted using the ```COM_Munge2``` function) values. The command callback name is ```SV_Spawn_f```.

This command sends at the stage of connection in the ```CL_RegisterResources``` function by the engine itself, however, if the client tries to call it using the console, the game will crash due to an incorrect sequence of checks in ```SV_Spawn_f``` function.

![image](https://user-images.githubusercontent.com/2564175/56101271-d0ed7980-5f2a-11e9-8609-9648000117e7.png)

As you can see in the image, the check for execution from the console is present, however, it is performed after a CRC value is written to the ```host_client```, which is NULL on the client, because of what the crash is happening.

Solution is to move the ```cmd_source == 1``` check to the beginning of the ```SV_Spawn_f``` function.

**Comment by mikela-valve** [comment]
Hi @2010kohtep, this should be fixed in the current HL1/OpFor/TFC/CS betas.

**Comment by 2010kohtep** [comment]
I confirm, works fine now. :)
