### ISSUE TITLE
[GoldSource] Host_Kill_f crash server HLDS bug (command kill)

### ISSUE THREAD

**Issue by SkillartzHD** [ValveSoftware/halflife#2129]
hi, the "kill" command is registered in the client/server, but here it is only the server (swds/engine_i486)

How the bug occurs:

1.connect to the server.
2.you expect to be alive
3.slow down the client (HW/SW) whether you do it with cheat engine/fps_max or other software
4.open the console and throw the command retry 
5.close the connect bar (double click on the Steam logo) and then open the console type the "kill" command
Server gets crash

--------------
Because the player remained alive when he gave reconnect/retry (he was not set as disconnected in Host_Reconnect_f that uses SV_New_f)
Then run the gEntityInterface.pfnClientKill player was not found and here occurs crash to the server

![123123-min](https://user-images.githubusercontent.com/8433325/56114222-e7b2c100-5f68-11e9-8730-38e38952376a.gif)
----------------------------------
**Original function without fixed :**
![fasfasfsaf](https://user-images.githubusercontent.com/8433325/56114476-96570180-5f69-11e9-98dc-96fff12654f5.png)
-----------------------------------
**Code fix :**
![dasdsadasd](https://user-images.githubusercontent.com/8433325/56151407-d514a800-5fb9-11e9-8374-80f8be14db35.png)
**void Host_Kill_f(void)
{

	if (cmd_source == src_command){
		Cmd_ForwardToServer();
		return;
	}
	if (sv_player->v.health <= 0.0f){
		SV_ClientPrintf("Can't suicide -- already dead!\n");
		return;
	}
	if (g_pcls.state < ca_connected) {
		SV_ClientPrintf("You can't kill yourself if you're not connected!\n");
		return;
	}
		gGlobalVariables.time = g_psv.time;
		gEntityInterface.pfnClientKill(sv_player);
}**

**Comment by justgo97** [comment]
how are you going to print a message to a non connected player ?

**Comment by SkillartzHD** [comment]
@justgo97 when he connects (ca_connecting)

amxmodx fix : 
[host_kill_f_fixx.txt](https://github.com/ValveSoftware/halflife/files/3081301/host_kill_f_fixx.txt)

**Comment by GiovaniFerraroTrivelli** [comment]
Tested on Linux server but I can't reproduce it.

**Comment by SkillartzHD** [comment]
@GiovaniFerraroTrivelli server should not run dproto, he fixes this bug

**Comment by GiovaniFerraroTrivelli** [comment]
> 
> 
> @GiovaniFerraroTrivelli server should not run dproto, he fixes this bug

Confirmed, you are correct. Tested with reHLDS too but here is fixed.

**Comment by mikela-valve** [comment]
@SkillartzHD This should be fixed in the current CS beta.

**Comment by SkillartzHD** [comment]
@mikela-valve , the check is not good, it is detected even if it is connected
![image](https://user-images.githubusercontent.com/8433325/56452700-f91b1500-633c-11e9-91f2-1e8cc9a40a11.png)
also opengl option is software

**Comment by shelru** [comment]
@mikela-valve wake up. There are OGL problem's and we doesn't need Money value in Tab. Thx.

**Comment by mikela-valve** [comment]
@SkillartzHD I confirmed that as well. When I tested this I did so on a listen server so I didn't notice that the check I was making was checking the server's connected state rather than the state of the player executing the command. The next update should have the proper check in it.

**Comment by mikela-valve** [comment]
Fixed in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by Splatt581** [comment]
This bug works on last beta again.

**Comment by Splatt581** [comment]
Fixed in 8254 build.

**Comment by oaus** [comment]
@mikela-valve close this too

**Comment by afwn90cj93201nixr2e1re** [comment]
wait till skillartz test it.

**Comment by SkillartzHD** [comment]
Fixed in last build.
