### ISSUE TITLE
[GoldSource] [Feature Request] -hijack startup parameter

### ISSUE THREAD

**Issue by 2010kohtep** [ValveSoftware/halflife#2132]
Source Engine games have the ability to run multiple game copies by setting the '-hijack' startup parameter. This is a very useful option for debugging purposes, which allows you to test the engine features on a local server with two game copies launched. If would be nice if ```ValveHalfLifeLauncherMutex``` mutex check in GoldSource game launcher can be skipped if '-hijack' parameter is set.

**Comment by kisak-valve** [comment]
Hello @2010kohtep, this is effectively the same topic as #1680. Feel free to add to that issue report.

Closing in favor of the existing issue report.
