### ISSUE TITLE
[Counter-Strike] SendAudio can crash the game

### ISSUE THREAD

**Issue by 2010kohtep** [ValveSoftware/halflife#2133]
Malformed ```SendAudio``` user message can cause client crash.

![image](https://user-images.githubusercontent.com/2564175/56228229-f6d86280-607f-11e9-8cb8-3635273d75fc.png)

The image shows a section of code in which from the string ```AudioCode``` is copied to ```szSoundName```, but there is no array boundaries validation for ```szSoundName```. The array may be overflowed, causing stack corruption.

**Comment by mikela-valve** [comment]
Hi @2010kohtep, this should be fixed in the current CS beta.

**Comment by 2010kohtep** [comment]
I confirm, fixed.
