### ISSUE TITLE
[GoldSource] SV_FullUpdate_Internal is vulnerable to DoS attacks

### ISSUE THREAD

**Issue by 2010kohtep** [ValveSoftware/halflife#2134]
The ```SV_FullUpdate_Internal``` function, which sends all connected clients information about each other, has an error that allows you to bypass the fullupdate spam filter.

![image](https://user-images.githubusercontent.com/2564175/56252889-c1a13400-60c2-11e9-9d9f-132b5feb8a90.png)

The image shows that fullupdate filtering can be skipped when ```host_client->active``` is 0. Since ```host_client->active``` remains 0 until the client sends the 'spawn' command (it sets to 1 in ```SV_WriteSpawn``` function), an attacker can send a huge amount of fullupdate requests at the connection stage and create server-side lags.

The solution is to leave the function if ```host_client->active``` is 0 without executing ``` SV_ForceFullClientsUpdate```, returning 0.

**Comment by RauliTop** [comment]
@mikela-valve 
It's a potential breach security and seems an easy way to fix.

Community will be more confortable to see on Next release instead of Future release

**Comment by mikela-valve** [comment]
This should be fixed in beta update 8254.

**Comment by 2010kohtep** [comment]
Fix confirmed.
