### ISSUE TITLE
[GoldSource] SV_Spawn_f is vulnerable to DoS attacks

### ISSUE THREAD

**Issue by 2010kohtep** [ValveSoftware/halflife#2137]
The ```SV_WriteSpawn``` function, as well as the ```SV_FullUpdate_Internal``` function, described in #2134, has a predisposition with lag creation on the server side. It sends the fullupdate information, bypassing the fullupdate spam filter.

![image](https://user-images.githubusercontent.com/2564175/56291977-edf29a00-612e-11e9-9ca4-fb6c9325e23c.png)

Creating lags in this way is possible if you continuously send a 'spawn' command in a format identical to the one sent to ```CL_RegisterResources```:

![image](https://user-images.githubusercontent.com/2564175/56292850-9e14d280-6130-11e9-8b1c-00a3e2673bc1.png)

The format must be respected, otherwise the command will be rejected by server.

Under normal conditions, the 'spawn' command is sent by the client one time at the resource processing stage, so sending a multiple 'spawn' commands from the client is undesirable - one time is enough.

The solution is to check the ```host_client->spawned``` parameter in ```SV_Spawn_f```, which is set inside ```SV_WriteSpawn``` to ```true``` as soon as the server receives this command. If this parameter is equal to ```true```, then leave the ```SV_Spawn_f``` function.

**Comment by mikela-valve** [comment]
Fixed, this will be included in the next beta update.

**Comment by mikela-valve** [comment]
Added in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by Splatt581** [comment]
I confirm that server crash is fixed.

**Comment by RauliTop** [comment]
> I confirm that server crash is fixed.

A crash didn't being happened never. Only lag creation on the server side.
Waiting @2010kohtep to confirm the fix

**Comment by Splatt581** [comment]
> A crash didn't being happened never.

It was possible to call `Host_Error` on server, if you send about 100 commands in one packet with valid arguments.

**Comment by 2010kohtep** [comment]
I confirm, problem fixed.
