### ISSUE TITLE
[GoldSource] SV_New_f is vulnerable to DoS attacks

### ISSUE THREAD

**Issue by 2010kohtep** [ValveSoftware/halflife#2138]
The 'new' command has the same problem described in #2134 and #2137 - with it's help attacker can generate lags on the server-side. The problem is identical - ```SV_FullClientUpdate``` called, bypassing the fullupdate spam filter.

The solution is to check whether the value of the ```host_client->hasusrmsgs``` variable is set to ```true```, and if the result is positive, leave the ```SV_New_f``` function. This variable is set to ```true``` if client has already sent a 'new' command, that's why we can validate 'new' command, using this variable.

**Comment by SkillartzHD** [comment]
Same thing with `Host_Reconnect_f` that appeals `sv_new_f`

**Comment by 2010kohtep** [comment]
@SkillartzHD ```Host_Reconnect_f``` just sends the 'new' command, if you are currently on the server.

![image](https://user-images.githubusercontent.com/2564175/56316482-12686980-6163-11e9-88df-8fce4a570784.png)

A similar effect can be achieved by executing 'cmd new' command in the client console. Although using the original client you can't achieve a strong lag effects, instead it's usually used external programs that connect the bot to the server that sends lag commands.

**Comment by Splatt581** [comment]
It seems that in 8254 build, the `new` command only works once during connection. This leads to problem of reconnecting players to server when changing map - instead of reconnecting, nothing happens. When server changing map, it sends `reconnect` command in players console, when executed of which the game client sends `new` command to server.

**Comment by mikela-valve** [comment]
Thanks @Splatt581, it looks like `SV_InactivateClients` doesn’t properly clear `hasusrmsgs` on the clients so they aren’t able to reconnect after a level change (among other things). 

Additionally `SV_ActivateServer` also sends out the registered user messages at the same time it sends out `reconnect` commands to all of them, as well as setting `hasusrmsgs` after sending them, which also prevents `new` from running. I’ve moved sending user messages to occur only for non-multiplayer games, whereas multiplayer clients rely on `reconnect` to get the user messages as normal. 

I’ll update the beta tomorrow with this fix for testing.

**Comment by mikela-valve** [comment]
I updated HL1 earlier today with the fix I referenced in my last post. HL1 beta should be on BuildID 3880668 in the Local File sections of its game info on Steam. This only required a new engine build and not an update to any of the clients so none of the client build ID's should be changed.

**Comment by 2010kohtep** [comment]
I confirm, DoS problem fixed.
