### ISSUE TITLE
[GoldSource] MSG_ReadBitString can create an infinite loop

### ISSUE THREAD

**Issue by 2010kohtep** [ValveSoftware/halflife#2156]
```MSG_ReadBitString``` function is used only in one place - in ```CL_ParseResourceList``` function, when processing the ```svc_resourcerequest``` message. The function contains an error that can lead to an infinite loop and client crash. We can understand the reason if we look at the code:

![image](https://user-images.githubusercontent.com/2564175/56459268-cc491b00-6399-11e9-9383-e11f1ba45cd7.png)

Function stops reading if 0 was returned, however, if ```msg_badread``` equals ```true```, then the ```MSG_ReadBits``` function will always return 1, which can lead to an infinite loop, as ```MSG_ReadBitString``` will never get 0 from ```MSG_ReadBits```.

![image](https://user-images.githubusercontent.com/2564175/56459292-24801d00-639a-11e9-8b3a-28efb71c567c.png)

Solution is to add a ```msg_badread``` check to ```MSG_ReadBitString``` reading loop.

**Comment by mikela-valve** [comment]
Fixed, this will be included in the next beta update.

**Comment by mikela-valve** [comment]
Fixed in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by mikela-valve** [comment]
Closing as fixed.
