### ISSUE TITLE
[Question] CS 1.6 another update

### ISSUE THREAD

**Issue by WhiteFang1319** [ValveSoftware/halflife#2157]
So I noticed few days ago CS 1.6 got another update after that security update which helped against malware
What's the new update about?

**Comment by eat1k** [comment]
https://github.com/ValveSoftware/halflife/issues/2060
https://github.com/ValveSoftware/halflife/issues/2128
https://github.com/ValveSoftware/halflife/issues/2133
https://github.com/ValveSoftware/halflife/issues/2142
https://github.com/ValveSoftware/halflife/issues/2060
https://github.com/ValveSoftware/halflife/issues/702

**Comment by mikela-valve** [comment]
Thanks @eat1k. 
@WhiteFang1319 you can now find the complete list of features for the next release in the [next release milestone](https://github.com/ValveSoftware/halflife/milestone/1). It does contain additional issues in it that are still being worked on for the next release but all issues included in the latest beta are present and at least noted in the comments.

**Comment by WhiteFang1319** [comment]
Thank you.

**Comment by WhiteFang1319** [comment]
Thank you. By the way, @mikela-valve  can we expect performance upgrades on the gold source engine?
