### ISSUE TITLE
mouselag/sensitivity

### ISSUE THREAD

**Issue by men1kmati** [ValveSoftware/halflife#216]
after this update my sensitivity feels competely different and my mouse feels unresponsive. It feels slow and like there is a delay after moving my mouse. before cs felt so perfect and tight. has anyone else experienced this? even keyboard movements feel laggy.

**Comment by shawns-valve** [comment]
Closing due to age. Please create a new issue you're still having issues with the 25th anniversary update (December 2023 Steam build). Also try toggling "Raw mouse input" in the Aim options.
