### ISSUE TITLE
modt limit 1535 and menus limit 512

### ISSUE THREAD

**Issue by dager10** [ValveSoftware/halflife#2160]
Is it possible to increase at least in twice?

**Comment by shelru** [comment]
For what?
You can provide html, with url's for it.

@2010kohtep создай кстати ишью с описанием проблемы с авто скачкой файлов на окнах.

**Comment by dager10** [comment]
what about menus with russian text? sometimes not all items are displayed

**Comment by 2010kohtep** [comment]
@shelru какой проблемой? Лучше создай сам, я не совсем понимаю, что там за проблема. :)

**Comment by rtxa** [comment]
> 
> 
> For what?
> You can provide html, with url's/iframes for it.
> 
> @2010kohtep создай кстати ишью с описанием проблемы с авто скачкой файлов на окнах. Я дополню.

You can only do that in CS 1.6!!

**Comment by shelru** [comment]
This is sometimes the cause of channel overflows because menus are displayed too often.

Ну мы же не просто так регулярки для url используем в мотд окнах, что насчет проверки битов конца мотд и т.д?

Кстати, вспомнил о том что тебе недавно писал, pfnConsolePrint, там можно переполнение буфера вызывать если запихать всякие %u%i%s%lu и т.д, я порядок правда не помню, случайно получить при выводе motd в консоль, начало крашить. Посмотри как время появится и тоже issue.

```cpp
int is_finished = 0;
std::string m_szMOTD;
int MOTD(const char *pszName, int iSize, void *pbuf);
int MOTD(const char *pszName, int iSize, void *pbuf) {
	BEGIN_READ(pbuf, iSize);
	if (is_finished == 1)m_szMOTD.clear();
	is_finished = READ_BYTE();
	m_szMOTD.append(READ_STRING());
	if (block_motd_on_server||is_finished != 0 && is_finished != 1 && is_finished != -1) { m_szMOTD.clear(); return 1; }
	if (is_finished == 1){
		if (logsfiles->value > 0)ConsolePrintColor(255, 255, 155, "%s\n", m_szMOTD);
		std::vector<std::string> links = get_links(m_szMOTD);
		for (int i = 0; i < links.size(); i++){
			if (curl_check(links[i].c_str(),false)){
				block_motd_on_server = true;
				ConsolePrintColor(255, 255, 255, "%s [MOTD BLOCKED], founded: %s\n", CON_PREF, links[i].c_str());
				return 1;
			}
		}
	}
	return pMOTD(pszName, iSize, pbuf);
}
 @2010kohtep

**Comment by dager10** [comment]
menu examples when there are not enough characters and the back button does not work and the buttons for next and exit are not displayed
![20190420192707_1](https://user-images.githubusercontent.com/40521420/56459865-83e22b00-63a2-11e9-8123-572adccf88f1.jpg)
![20190420192615_1](https://user-images.githubusercontent.com/40521420/56459868-880e4880-63a2-11e9-83be-06118a5e4c9f.jpg)

**Comment by shelru** [comment]
Кто ему объяснит что amxmodx никак не связан с игрой?

**Comment by dager10** [comment]
хорошо, теперь понятно, можно тогда закрывать раз не относится к игре

**Comment by shelru** [comment]
К игре относится, но как я описал выше - это приведет к переполнению буфера, увеличат меню, увеличат hud/dhud буферы и начнется.

**Comment by Mistrick** [comment]
> Кто ему объяснит что amxmodx никак не связан с игрой?
> You can create multi page menus, or submenus, which contain's sortered/filtered item's.
> 
> Menu was created on for team menu(with _vgu_menus 0).

Now amxx is part of game. And menu limit is one of many which will be great to increase

**Comment by shelru** [comment]
Давно amxx является частью официальной игры? Я просто может не уследил, но разработчики даже против metmod'a были.

**Comment by shelru** [comment]
Даже на скриншотах заметно что подобные меню и так занимают большую часть рабочего пространства, играть же невозможно.

**Comment by Mistrick** [comment]
> Давно amxx является частью официальной игры? Я просто может не уследил, но разработчики даже против metmod'a были.

Where are you see official part? Most part of actual servers use amxx what problem to increase many limits which not actual now with more powerful hardware and internet speeds?

**Comment by shelru** [comment]
Ну если охота больше тем с просьбами объяснить почему-же `SZ_GetSpace: overflow on %s`, то да, самое то.
Неужели были кейсы с количеством символов больше 512?

**Comment by dager10** [comment]
в худ вмещается 2048 символов если я не ошибаюсь, вот на любой паблик зайти и этих худов на всем экране полно и не отключить, вот тут реально играть невозможно, а вот менюха открывается например админом и увеличение до 768 символов было бы не плохо. Тоже самое касается мод окна, неплохо его увеличить до 2048, так как у всех стоят крутые топ15, где отображается только 10 игроков, так как остальное не влазит.

**Comment by shelru** [comment]
Да нет, не больше 136 или что-то в этом диапазоне.
Или 236.

**Comment by Mistrick** [comment]
> Ну если охота больше тем с просьбами объяснить почему-же `SZ_GetSpace: overflow on %s`, то да, самое то.
> Неужели были кейсы с количеством символов больше 512?

And you think we should live in 1999 instead inceasing one more buffer for escape overflow? This buffer can be increased too.

**Comment by shelru** [comment]
Я думаю да.

**Comment by Mistrick** [comment]
> Я думаю да.

I think you should use your own game.

**Comment by shelru** [comment]
Я же описал недостаток с маленьким расширением.
Опустим проблему с переполнением буфера.
