### ISSUE TITLE
bug when switching camera

### ISSUE THREAD

**Issue by dager10** [ValveSoftware/halflife#2162]
This bug is really annoing when you are playing competitive games 5x5
link for issue: https://github.com/ValveSoftware/halflife/issues/258
link for fix with amx plugin: https://dev-cs.ru/threads/4095/ 

I hope in one day it will be fixed without amx plugin

**Comment by SamVanheer** [comment]
You should've just posted in the issue itself.

**Comment by kisak-valve** [comment]
Closing in favor of the existing issue report.
