### ISSUE TITLE
[TFC] Host_Error: UserMsg: Not Present on Client 59

### ISSUE THREAD

**Issue by se7entfc** [ValveSoftware/halflife#2164]
Since the latest TFC update to fix the double firing bug, some users are getting kicked with this error message.

Happens when the client selects a class.

**Comment by SkillartzHD** [comment]
He added a new svc message called and `svc_exec` (usermsg **59**) through which you can reuse the command  "exec " from the console through a new message transmitted, without svc_stufftext/svc_director

![123123123232](https://user-images.githubusercontent.com/8433325/56464846-7e183400-63fa-11e9-82f9-f63d272ec3d6.png)

-----------------------------------------
problem: your client is not updated (without svc_exec), while the server runs the last **update**

**Comment by se7entfc** [comment]
Updated TFC, problem solved. Thanks
