### ISSUE TITLE
gl_overbright 1 is incompatible with detail textures

### ISSUE THREAD

**Issue by MFKitten** [ValveSoftware/halflife#2166]
Apologies for the lack of "GoldSource" in the title, rest assured that is what I meant.

I am personally attempting to make a mod to "refresh" the game, and custom made detail textures are a part of that. I also want to use GL_Overbright 1, as that's part of how the game was meant to be seen in the origibal release. Unfortunately, this is not compatible with detail textures, and I have to choose one of these, both of which contribute greatly to the visual fidelity of the game.

**Comment by SamVanheer** [comment]
#230 already covers gl_overbright.

**Comment by MFKitten** [comment]
My mistake!
