### ISSUE TITLE
[GoldSource/CS][Inchoerence] AUG & SG zoom

### ISSUE THREAD

**Issue by ArmynC** [ValveSoftware/halflife#2214]
The AUG & SG got an inconsistent zoom. If you use the 'scope' you aren't supossed to see the gun, right? There should be two variants:

1. Scope like in CS:GO
2. Full zoom until we can't see the gun with a different corsshair (ex. dot)

![20190422140202_1](https://user-images.githubusercontent.com/16375271/56497673-3f23d480-6507-11e9-9aef-3b19bbe1da48.jpg)
<p align="right">
<sub>(Preview of SG)</sub>
</p>

**Comment by shelru** [comment]
>If you use the 'scope' you aren't supossed to see the gun, right?
Why?
At awp and scout only.
There are diff fov's.

**Comment by ArmynC** [comment]
Yes, I know that the Field of View differ but the way it render the view... is not really logical...

**Comment by RauliTop** [comment]
It's well like this. They did because they wanted this type of zoom.

It's not good to change the zoom twenty years after

**Comment by mikela-valve** [comment]
Without some kind of example of this being how zoom used to work in earlier versions or something similar I have to think this is intentional and shouldn't be changed.
