### ISSUE TITLE
The command 'motd' allows to read files with any extensions

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#2222]
For example, execute the following string `motdfile config.cfg;motd` - you get the contents of this file. As I understand it, based on the limitations for the `motd_write` command, `motd` command should also be able to work only with `.txt` extensions.

**Comment by shelru** [comment]
Why?

**Comment by shelru** [comment]
Let's try talk 'bout file extension's again. https://github.com/ValveSoftware/halflife/issues/2158 fix too.

**Comment by mikela-valve** [comment]
Fixed, this will be included in the next beta update.

**Comment by mikela-valve** [comment]
Fixed in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by Splatt581** [comment]
I confirm, fixed.
