### ISSUE TITLE
Incorrect display of the map overview on widescreen high resolutions

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#2223]
Example in the screenshot below, 1600x900 resolution used

[https://i.imgur.com/oMoph79.jpg](https://i.imgur.com/oMoph79.jpg)

**Comment by djdallmann** [comment]
Can confirm, not sure what resolution this starts at or if it's only widescreen. I play 1920x1080 wide and it's there.

**Comment by basuritashka** [comment]
That happens because the overview file itself has a pre-defined resolution when it gets created, we need a new method to generate a friendly overview file and making it work on every native resolution.

**Comment by oaus** [comment]
Duplicate of https://github.com/ValveSoftware/halflife/issues/226

**Comment by kisak-valve** [comment]
Closing as a duplicate of #226.
