### ISSUE TITLE
The 'slist' command does not work correctly

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#2226]
This command is responsible for finding servers on the local network in console mode. The code sends a broadcast datagram with an _A2S_INFO_ message inside. The problem is that an old request type (`infostring` string) is sent, which has not been supported by servers for a long time instead of a new one (`TSource Engine Query` string), so nothing comes from the servers and the search fails.

**Comment by mikela-valve** [comment]
Fixed, in two parts. I added back support to the server and client for processing infostring messages so slist should work again with updated servers in the old way. I also added a new `slist_s` command that queries servers through Source Engine queries. This will be included in the next beta update.

**Comment by Splatt581** [comment]
Perhaps it is better not to reopen old query protocol, but simply to make `slist` command working with new query format. The old protocol is disabled more than 10 years ago, and now it is not used anywhere. Also, old format is less compact than new format (strings instead of bytes are used). And attackers, in absence of confirmation of requests through request id, can redirect traffic to victim's server through spoofing of sender's address, as described here #2407

**Comment by mikela-valve** [comment]
Good suggestion, I'll pull the `infostring` support and just turn `slist` into a `TSource Engine Query` command. Initially it looked like there were some fields missing from the new query that were present in `infostring` that made `infostring` desirable to re-enable but I should be able to get `slist` working similarly with the new query type.

**Comment by mikela-valve** [comment]
Fixed in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by Splatt581** [comment]
Now this command works fine. But, in older clients, this command also displayed such fields as server type (listen, dedicated or hltv proxy), server operating system, password availability and VAC. All this information is also transmitted in a new format - https://developer.valvesoftware.com/wiki/Server_queries#Response_Format

![slist](https://user-images.githubusercontent.com/31417200/58155360-c5594500-7c84-11e9-9c8a-9e670d2c0b60.jpg)


Is it possible to add a display of these fields too?

**Comment by mikela-valve** [comment]
Hi @Splatt581, I added those fields in as requested in beta  'Exe build: 16:32:50 May 22 2019 (8245)'.

**Comment by Splatt581** [comment]
Thanks! Everything works great.
