### ISSUE TITLE
[CS][Bug] UMP45 secondary attack bug

### ISSUE THREAD

**Issue by voed** [ValveSoftware/halflife#2228]
UMP45 is not marked as weapon without secondary attack for some reason, so clicking on right mouse button stops primary attack

![image](https://user-images.githubusercontent.com/10352360/56516552-65676580-6543-11e9-8070-e8d782324e72.png)

**Comment by GiovaniFerraroTrivelli** [comment]
Is this really a bug? So many years and I always think this was intentionally lol

**Comment by mikela-valve** [comment]
Fixed, will be in next beta update.

**Comment by mikela-valve** [comment]
Fixed in 'Exe build: 11:12:36 May 21 2019 (8244)'.
