### ISSUE TITLE
MOTD resolution bugged on 1440x900

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2240]
Title. (Probably on more resolutions, not tested)

1440x900 main MOTD:
![Image 1](https://i.gyazo.com/9ad8b9dc0f80b0858d5925333c837266.jpg)

1440x900 Chooseteam VGUI
![Image 2](https://i.gyazo.com/c09e46826069360379aef3cd00d57a89.jpg)

I would like more testing on more resolutions so we can provide a more complete feedback.

**Comment by Maxi605** [comment]
720x480, 1280x800, 1600x1024, 1680x1050 also have this similar issue.

**Comment by shelru** [comment]
![image](https://user-images.githubusercontent.com/9306996/56638427-3c4bef80-667f-11e9-899d-99f1aa7a79a0.png)
![image](https://user-images.githubusercontent.com/9306996/56638437-41a93a00-667f-11e9-9530-da55af11bad0.png)
1920x1080,

![image](https://user-images.githubusercontent.com/9306996/56638509-6bfaf780-667f-11e9-8539-6ea75ef72af6.png)
![image](https://user-images.githubusercontent.com/9306996/56638519-72896f00-667f-11e9-8cc1-10c7d6e85f3d.png)
1600x900

**Comment by JoelTroch** [comment]
When you made the tests, did you changed the resolutions or did you made game restarts in-between?

**Comment by shelru** [comment]
Just changed resolution's.

**Comment by shelru** [comment]
![image](https://user-images.githubusercontent.com/9306996/56640489-33115180-6684-11e9-9825-5035214596c6.png)
![image](https://user-images.githubusercontent.com/9306996/56640503-3a385f80-6684-11e9-9886-1d5b458cc53d.png)
After restart's also work's.

**Comment by SamVanheer** [comment]
I checked this with 1680x1050, both windowed and fullscreen:
https://i.imgur.com/VcYmKil.png

**Comment by sjain882** [comment]
Happens on all 16:10 aspect ratio resolutions for me

**Comment by kisak-valve** [comment]
Closing in favor of #1931.
