### ISSUE TITLE
Add a function to detect when a player closes a MOTD.

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2242]
Title.

With this, we can make great additions or make some gameplay changes on custom servers. (mod oriented)

**Comment by shelru** [comment]
That' can be spoofed. There no reasons for add this feature.

**Comment by JoelTroch** [comment]
Agree with @shelru , this can be abused by servers operators for malicious purposes like having ads every 30 seconds, run a heavy web page to lag the client and such

**Comment by basuritashka** [comment]
Agreed. No need to add.

**Comment by oaus** [comment]
> Agree with @shelru , this can be abused by servers operators for malicious purposes like having ads every 30 seconds, run a heavy web page to lag the client and such

This is still possible with AMXX, doing a task and opening the motd every second or more.

**Comment by shelru** [comment]
But there no event's for hooking motd close event.

**Comment by oaus** [comment]
> Pero no hay evento para enganchar a Motd ahora.

with AMXX: show_motd(...)

**Comment by shelru** [comment]
????
