### ISSUE TITLE
Re-enable "r_shadows" as an optional cvar.

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2252]
Title.

It got deleted a few years ago for some reason but it should be a optional cvar if someone wants to use it, or maybe it's a game-changing feature?

![Ir_shadows enabled](https://scontent.fcor2-2.fna.fbcdn.net/v/t1.0-9/10645013_935446746470329_2382432122928592369_n.png?_nc_cat=104&_nc_ht=scontent.fcor2-2.fna&oh=a80a7723551d4f92e5fddf14f5210c3d&oe=5D343607)

**Comment by kisak-valve** [comment]
Duplicate of #451.
