### ISSUE TITLE
Make the actual crosshair more customizable (CSGO like)

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2255]
Title.

Nothing else to add, on higher resolutions the Crosshair becomes really thin and a lot harder to see and more even on maps with a lot of brightness.

Example:
`cl_crosshairstyle`
`cl_crosshairdot`
`cl_crosshairthickness`
`cl_crosshair_drawoutline`
`cl_crosshair_outlinethickness`

**Comment by kisak-valve** [comment]
Duplicate of #265 / #2105.
