### ISSUE TITLE
[Feature Request?] Make FastDL case-sensitive

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2275]
Not sure if this is intended or not but when you got a file with "MyFileIsThis.mdl" FastDL will just ignore it and just download it without using FastDL

**Comment by kisak-valve** [comment]
Hello @basuritashka, this issue is already being tracked at #1490. Closing as a duplicate.

**Comment by basuritashka** [comment]
I thought they were talking about .wads specifically, my bad then. hehe

**Comment by LucesEnBabel** [comment]
It's the FastDL host the one that's case sensitive. Making the game try to download every possible combination of the file is not feasible, you should fix either your precache list or your host.
