### ISSUE TITLE
[Opposing Force] Able to reload glock when magazine is full

### ISSUE THREAD

**Issue by IntriguingTiles** [ValveSoftware/halflife#2285]
This happens on both the public branch and the beta branch. I did some quick RE and figured out the cause.

From `CGlock::Reload`:
```
if (m_iClip == 0)
	iResult = DefaultReload( 17, GLOCK_RELOAD, 1.5 );
else
	iResult = DefaultReload( 18, GLOCK_RELOAD_NOT_EMPTY, 1.5 );
```
Changing 18 to 17 should fix this issue.

**Comment by agrastiOs** [comment]
Isn't this on original HL too?

**Comment by SamVanheer** [comment]
Duplicate of #1076

**Comment by mikela-valve** [comment]
Fixed, will be included in next beta update.

**Comment by mikela-valve** [comment]
Fixed in beta 'Exe build: 11:12:36 May 21 2019 (8244)',

**Comment by IntriguingTiles** [comment]
Confirmed fixed.
