### ISSUE TITLE
"Bots" on Internet tab seems to be throwing incorrect values.

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2295]
![imagen](https://user-images.githubusercontent.com/33007491/56748619-2c4f1100-674e-11e9-9a06-9062b9291bea.png)

As you can see, there are certain values getting displayed but on the server there are 0 players/bots

**Comment by kisak-valve** [comment]
Players and bots are intentionally not combined. This is not a bug. https://github.com/ValveSoftware/steam-for-linux/issues/1506#issuecomment-13341161 https://github.com/ValveSoftware/halflife/issues/539

**Comment by basuritashka** [comment]
There are servers with 0/32 (real players and bots), when you are on it, you are the only one playing but the "Bots" value still show a high value, is that really intended? Doesn't seems like alfred was refering to that.

**Comment by basuritashka** [comment]
You are right, sorry :)
