### ISSUE TITLE
Crowbar uses incorrect time base for nextthink value

### ISSUE THREAD

**Issue by SamVanheer** [ValveSoftware/halflife#2296]
When the Crowbar is swung and something is hit a delayed response is created using a think function. Unfortunately the code was incorrectly updated when weapon prediction was implemented:
https://github.com/ValveSoftware/halflife/blob/5d761709a31ce1e71488f2668321de05f791b405/dlls/crowbar.cpp#L310

This should be using `gpGlobals->time`.

**Comment by Sockman1** [comment]
Just wondering, what's the consequences of this in-game? Would this fix the rapid crowbar bug?

**Comment by SamVanheer** [comment]
No this doesn't affect that, #617 tracks that bug.

The consequences of this are that the next think time is in the past and so will run more quickly than intended. For correctness the time should be at some point >= current time. It may also be responsible for occasional longer delays between hits, i'm not sure about that.

**Comment by mikela-valve** [comment]
Fixed, will be included in next beta update.

**Comment by mikela-valve** [comment]
Fixed in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by mikela-valve** [comment]
Closing as fixed.
