### ISSUE TITLE
Crosshair appearance is out of place when "Auto-size" or "Large" is set

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2305]
Title.

Multiplayer:
![imagen](https://user-images.githubusercontent.com/33007491/56775272-51667280-6794-11e9-8793-84153ca2b64f.png)

Video:
![imagen](https://user-images.githubusercontent.com/33007491/56775280-5aefda80-6794-11e9-99a5-daa40d66d5a4.png)

**Comment by kisak-valve** [comment]
Looks like there's an issue with the screenshot, but this is a duplicate of #416. Closing in favor of the existing issue report.
