### ISSUE TITLE
"gl_picmip" with value higher than 3 crashes the game and "gl_picmip 3" on cs_italy crashes the game.

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2306]
Title.

On actual Counter-strike 1.6 version:
If you set `gl_picmip` with a value higher than 3 and you join a server, your client will crash.

also when playing `cs_italy` and going to Terrorist base your game will crash with `gl_picmip 3`

This does not happen on beta branch.

Reference to `gl_picmip` higher than 3 via Youtube:
https://www.youtube.com/watch?v=pC3uk0tpO7I

Reference to `cs_italy` via Youtube:
https://www.youtube.com/watch?v=-RvDKCOirUE

**Comment by SamVanheer** [comment]
`gl_picmip` is used to divide the width and height of a texture by 2 the specified number of times to reduce GPU memory usage.

The function `ComputeScaledSize` does this by bit shifting:
```
int maxSize = ...;
int divideNTimes = (int)gl_picmip.value;

if ( wscale )
{
  int newWidth = width >> divideNTimes;
  if ( newWidth > maxSize )
    newWidth = maxSize;
  *wscale = newWidth;
}

if ( hscale )
{
  int newHeight = height >> divideNTimes;
  if ( newHeight > maxSize )
    newHeight = maxSize;
  *hscale = newHeight;
}
```

This invokes undefined behavior if `gl_picmip` is greater than 31 or a negative value (which is not checked for): https://en.cppreference.com/w/cpp/language/operator_arithmetic
> In any case, if the value of the right operand is negative or is greater or equal to the number of bits in the promoted left operand, the behavior is undefined. 


`gl_round_down` is also affected in the same way in the same function.

**Comment by mikela-valve** [comment]
Fixed for gl_picmip and gl_rounddown, will be included in the next beta update.

**Comment by mikela-valve** [comment]
Fixed in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by mikela-valve** [comment]
Closing as fixed.
