### ISSUE TITLE
"Enable voice in this game" has no effect in game

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2317]
We were testing it on latest beta branch and latest game version and it doesn't seems to work.

It should block all player microphones but has no effect apparently. We tried it on online servers.

It set `voice_modenable 0/1` depending on what player set but has no effect apparently.

![imagen](https://user-images.githubusercontent.com/33007491/56842195-0fefc900-6861-11e9-819b-ebb2228b9a83.png)

**Comment by eat1k** [comment]
If I remember correctly it disables your microphone.

**Comment by basuritashka** [comment]
> 
> 
> If I remember correctly it disables your microphone.

We were testing it and other players were able to hear me regardless, would like more confirmation on this if possible.

**Comment by SamVanheer** [comment]
This checkbox sets the `voice_modenable` cvar, which is registered by game code:
https://github.com/ValveSoftware/halflife/blob/5d761709a31ce1e71488f2668321de05f791b405/cl_dll/voice_status.cpp#L189

The value is sent to the server. If the server supports it it will use the setting to determine whether a player wants to receive voice from other players:
https://github.com/ValveSoftware/halflife/blob/5d761709a31ce1e71488f2668321de05f791b405/game_shared/voice_gamemgr.cpp#L236-L273

You can use `voice_clientdebug` to display some of the state changes as they occur.

If this isn't working then it should definitely be fixed.

**Comment by basuritashka** [comment]
Will do, expect an update soon here.
