### ISSUE TITLE
[GoldSource] Client-side mapcycle processing can fail

### ISSUE THREAD

**Issue by 2010kohtep** [ValveSoftware/halflife#2318]
When a client connects to the server, the server sends mapcycle to the client, which is written in the ```SV_SendServerinfo``` function. The problem is that the server can send a very large mapcycle list, length of which can be more or equal to 8192, what is the maximum size of returned buffer in ```MSG_ReadString```, which is called in ```CL_ParseServerInfo```. Unread bytes will cause the client to crash.

![image](https://user-images.githubusercontent.com/2564175/56841920-3cbfd280-6899-11e9-92d1-e595c929cb88.png)

![image](https://user-images.githubusercontent.com/2564175/56841950-6ed13480-6899-11e9-93a5-6cc2748d4b68.png)

One of the solutions that I see in the client-side: since one of the images shows that mapcycle is not used by the client, we can simply skip this data. Let's say we can write function like this and replace ```MSG_ReadString``` call with it:

![image](https://user-images.githubusercontent.com/2564175/56842076-a42a5200-689a-11e9-8ce5-37054bfb6014.png)

As a result, a mapcycle of any length will be successfully processed.

There is also a solution for server-side: after receiving the mapcycle with the ```COM_LoadFileForMe``` function, we cut it in position 8190 by setting zero byte so that the client can handle the mapcycle if its size is too large.

I believe that it is desirable to implement both of the proposed solutions.

**Comment by mikela-valve** [comment]
Fixed in client and server, will be included in next beta.

**Comment by mikela-valve** [comment]
Fixed in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by mikela-valve** [comment]
Closing as fixed.
