### ISSUE TITLE
[GoldSource] MSG_WriteBitString can write incorrect characters

### ISSUE THREAD

**Issue by 2010kohtep** [ValveSoftware/halflife#2323]
If you try to write a string with ```MSG_WriteBitString``` that contatins characters whose code is >= 0x80 (f.e. Cyrillic), then 0xFF will be written instead of a needed characters. More on this described here: dreamstalker/rehlds/issues/150

![image](https://user-images.githubusercontent.com/2564175/56849172-dcad4880-68f9-11e9-8df8-ea2eff28fa2d.png)

The image shows the original ```MSG_WriteBitString``` function. We can see the type of the variable ```const char```, which is the cause of the problem.

The solution is to use ```unsigned char *pch``` instead of ```char *pch```.

**Comment by mikela-valve** [comment]
Fixed, will be included in the next beta.

**Comment by mikela-valve** [comment]
Fixed in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by mikela-valve** [comment]
Closing as fixed.
