### ISSUE TITLE
[GoldSource] Some MSG_Read functions can return incorrect values

### ISSUE THREAD

**Issue by 2010kohtep** [ValveSoftware/halflife#2324]
The ```MSG_ReadAngle``` and ```MSG_ReadHiresAngle``` functions do not handle situations in which nested read functions had "bad read", which can lead to incorrect result.

![image](https://user-images.githubusercontent.com/2564175/56849328-a5d83200-68fb-11e9-8797-8cbeec231196.png)

![image](https://user-images.githubusercontent.com/2564175/56849307-79241a80-68fb-11e9-966e-a68e1ae1b998.png)

The solution is to check the results of ```MSG_ReadChar``` and ```MSG_ReadShort```: if they returned -1, then leave the function with the result 0.

**Comment by 2010kohtep** [comment]
In addition. The ```MSG_ReadCoord``` function has the same problem. The fix is identical. I would also recommend removing the unused ```sizebuf_t *sb``` argument.

![image](https://user-images.githubusercontent.com/2564175/56849426-b9d06380-68fc-11e9-9449-a377fb4e1a32.png)

**Comment by mikela-valve** [comment]
Fixed, will be included in the next beta.

**Comment by mikela-valve** [comment]
Fixed in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by mikela-valve** [comment]
Closing as fixed.
