### ISSUE TITLE
[GoldSource] MSG_ReadString and MSG_ReadStringLine functions can be interrupted by 0xFF char

### ISSUE THREAD

**Issue by 2010kohtep** [ValveSoftware/halflife#2325]
If the read string contains the character 0xFF, then reading will be interrupted due to the check shown in the image:

![image](https://user-images.githubusercontent.com/2564175/56849489-c0aba600-68fd-11e9-8436-b8acef77e042.png)

The solution is to replace the check ```if (c == -1) break;``` with ```if (msg_badread) break;``` one.

**Comment by SamVanheer** [comment]
I made the same mistake when i first saw code like that.

`MSG_ReadChar` returns int, not char. `-1` is `0xFFFFFFFF`, not `0xFF` so this isn't possible.

**Comment by 2010kohtep** [comment]
Yes, you're right, I'm inattentive. :) Thanks for noticing.
