### ISSUE TITLE
Make server side opensource

### ISSUE THREAD

**Issue by voed** [ValveSoftware/halflife#2329]
Maybe i am too optimistic but why not? A lot of people can create pull requests instead of just creating an issue, so less work for you. Anyways it already fully reversed and there's nothing to hide🤔

**Comment by kisak-valve** [comment]
Duplicate of #2125.

**Comment by SamVanheer** [comment]
Given how tangled up the engine is open sourcing only part of it is probably harder than just open sourcing everything anyway.
