### ISSUE TITLE
[Netcode Bug] Default rate values of GoldSrc games are bad and make games unplayable in Online servers and LAN

### ISSUE THREAD

**Issue by erdemtekin** [ValveSoftware/halflife#2344]
I reported this issue 2-3 years ago and it still didn't fixed..

Default client and server rates (rate, cl_cmdrate, cl_updaterate, cl_dlmax, sv_maxupdaterate, sv_minupdaterate... etc.) of Goldsrc games are too bad. They are too low for today's technology. 

When I connect to online servers with default rates, lag appears.

Also, lag appears on LAN (Dedicated Server) too. 

Valve updated only "cl_cmdrate" and "cl_updaterate" to "60" and "rate" to "100000" in 2013 and i guess "60" is low value. Also, valve didn't update server rate values.

Here is my net_graph comparisions between default rate values and my rate values:
http://prnt.sc/det725

As you can see, when I use default values, red dots appear. This means the default rates are bad. 

Please fix this issue. This makes GoldSrc games unplayable. (Especially Counter Strike and Counter Strike Condition Zero) 

GAMEPLAY COMPARISION VIDEOS: (Please watch at Fullscreen and max quality) 

Here is my gameplay on LAN (With Default Rate Values):
https://www.youtube.com/watch?v=3z3Cy4Ciexo

Here is my gameplay video on LAN (With My Rate Values) 
https://www.youtube.com/watch?v=XEMZZ0u8YY0

**Comment by erdemtekin** [comment]
also, please don't close this thread.

**Comment by SamVanheer** [comment]
You could've just updated the original issue.

**Comment by striyker98** [comment]
i have same problem they need to be changed
