### ISSUE TITLE
[HL] Tau Cannon right-click seems to be using "hotglow.spr" more than one time on release.

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2345]
Right-clicking into a wall using Tau Cannon seems to be using "hotglow.spr" more than one time, not sure if this is intended or not but seems really weird, it should be just using one instance of "hotglow.spr"

You can see the overheating on wall:
![imagen](https://user-images.githubusercontent.com/33007491/56866864-77665f80-69ac-11e9-9b26-b5db3583bbad.png)

Should be more like this:
![imagen](https://user-images.githubusercontent.com/33007491/56866885-bb596480-69ac-11e9-85af-0eea7f53a442.png)

**Comment by SamVanheer** [comment]
This is intentional. The way the effect works each additional sprite is less bright and lives for a shorter time so the glow fades out over time.

**Comment by basuritashka** [comment]
Closing this then, as this seems to be intentional.
