### ISSUE TITLE
[Counter-Strike, HL?...] [bug] Enhance pointer precision

### ISSUE THREAD

**Issue by 10th** [ValveSoftware/halflife#2372]
Enhance pointer precision is automatically set when start the game without launch options: -noforcemspd or -noforcemparms. Mouse acceleration starts working in Windows and in the game menu, even with m_rawinput 1.

![1](https://user-images.githubusercontent.com/11433503/57054086-09b37f80-6c9b-11e9-9490-cd472c0cd3b0.jpg)

**Comment by kisak-valve** [comment]
Hello @10th, this issue is already being tracked at #66 / #1989. Closing as a duplicate.

**Comment by s0zum** [comment]
this helps a lot, i would always open the game and have to disable it manually
