### ISSUE TITLE
[CS 1.6] commandmenu.txt does not load from the cstrike_addon folder

### ISSUE THREAD

**Issue by 10th** [ValveSoftware/halflife#2379]
When i create custom menu, i have to replace the cstrike/commandmenu.txt because file it is not loaded from the cstrike_addon folder.

**Comment by tschumann** [comment]
I think this is probably because the cstrike_addon folder is not mounted by client.dll which is what loads and processes commandmenu.txt

**Comment by 10th** [comment]
Validating Steam files permanently deletes my commandmenu.txt located in the cstrike folder, replacing the standard one. This is wrong behavior.

Therefore, please add the ability to load information from a file located in the folder cstrike_addon.

**Comment by SamVanheer** [comment]
Did you enable the addon directory in  `Options->Video->Allow custom addon content`?

**Comment by 10th** [comment]
Yes, the option is of course enabled.
But I'm very sorry, because today I checked - the file is loaded (it is strange, before this I have worked for many years, it may have been fixed recently?).
