### ISSUE TITLE
Half - Life master server

### ISSUE THREAD

**Issue by bogdaniel** [ValveSoftware/halflife#2380]
Hello, I'm playing a little with the valve server query api and i'm trying to get a list of servers from master server but each time i get operation timed out. does hl2master.steampowered.com:27011 and hl1master.steampowered.com:27011 still work or they changed it ? Sorry if this isn't the place to post.

**Comment by SamVanheer** [comment]
Master server queries are routed through the Steamworks API. I don't think there's a public access point to directly query this information from. You should check the Steamworks documentation to be sure.

**Comment by bogdaniel** [comment]
Ok thank you very much for your answer now i have a route to check. :-)
