### ISSUE TITLE
[TFC] Entity Error

### ISSUE THREAD

**Issue by DarthMan** [ValveSoftware/halflife#2381]
Hello. Basically with new TFC there's an issue with plug-ins that use Hamsandwich and Orpheu especially for virtual functions. Hooking CBasePlayer::Kiled, when a player is killed I get this: FATAL ERROR (shutting down): Bad entity in IndexOfEdict() and the server crashes . This doesn't happen on other HL1 engine-based games, just TFC. Hooking the DeathMsg event works fine and doesn't make the server crash, but it's not a reliable method to detect when a player is killed. There are cases when a player can be killed by an entity and the event would not be sent to the client.

**Comment by SamVanheer** [comment]
Sounds like you may be using an out of date offset list, ask for help on the AMX Mod X forums. This issue is beyond the purview of this issue tracker.

**Comment by DarthMan** [comment]
Offsets should be fine. I checked andI have the latest hamdata, and Killed sometimes works just fine.

**Comment by PM32** [comment]
Are you using Orpheu or other 3rd party addons that hooks gamedll functions? This is actually not related to the main valve's purpose on "fixing" things, because it's not broken. I agree with @SamVanheer , you should check your addons

**Comment by DarthMan** [comment]
People from Allied Modders no longer care about a thing. They didn't care to update gamedata offsets for Fortress Forever. All they care about is Counter-Strike games, that's all. For a game like TFC I'm pretty sure nobody, not even Arkshine would look and make sure all offsets are right. No CS = No support !

**Comment by LucesEnBabel** [comment]
Sadly if there's no one to create an updated `hamdata.ini` file for TFC you can't really force them, but the thing about Open Source projects like AMXX is that people can volunteer and create pull requests containing the updated indexes.

**Comment by DarthMan** [comment]
But the hamdata I believe is right, some linux difference offsets for pdata changed from 4 to 5 and I guess that's it.

**Comment by Arkshine** [comment]
The virtual table seems to be unchanged unless i'm wrong.

Talking about Hamsandwich.
Does it crash if you're hooking Killed alone and does the param values seems correct?
If no crash, please identify first what is the cause from your code and report back.

**Comment by DarthMan** [comment]
> 
> 
> The virtual table seems to be unchanged unless i'm wrong.
> 
> Talking about Hamsandwich.
> Does it crash if you're hooking Killed alone and does the param values seems correct?
> If no crash, please identify first what is the cause from your code and report back.

It no longer seems to crash. Either my tfc.dll was buggy or idk. Updated to beta and now everything seems fine. By the way Arkshine, are u able to compile Observer_SetMode for me? I need Rage ahndler and function to be able to call it in a plug-in that I'm working on. I have already made the signature, but I can't seem to be able to make the stuff right because when the plug-in is loaded it simply crashes.

**Comment by PM32** [comment]
> > The virtual table seems to be unchanged unless i'm wrong.
> > Talking about Hamsandwich.
> > Does it crash if you're hooking Killed alone and does the param values seems correct?
> > If no crash, please identify first what is the cause from your code and report back.
> 
> It no longer seems to crash. Either my tfc.dll was buggy or idk. Updated to beta and now everything seems fine. By the way Arkshine, are u able to compile Observer_SetMode for me? I need Rage ahndler and function to be able to call it in a plug-in that I'm working on. I have already made the signature, but I can't seem to be able to make the stuff right because when the plug-in is loaded it simply crashes.
> 
> About pdata offsets, a few were changed. For example ammo_shells on Windows is 53 but now the linux difference is 5. Previously it was 4 and on the old 2012 linux .so it was 3. A friend tested on his server and it didn't work with 4, but did with 5.
> 
> I posted on AM about CBasePlayer::StartObserver . Would be cool if you can share it there so other can see it too. https://forums.alliedmods.net/showthread.php?t=179706&page=21

Are you aware that this is not the right section to ask that? Here we are debating engine's enhancement, please leave your modding doubt on Alliedmodders on it respective section
