### ISSUE TITLE
[CS 1.6 - Bug] Russian text from chat in console

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/halflife#239]
- Send a message in chat with cyrillic symbols (абвгдеёжзий)
- Open the console and wait when it appears here
- You'll see your nickname, but not cyrillic text

The same problem, if a message is sent by translated AMXX plugin.

**Comment by Mistrick** [comment]
can be closed as fixed in #2060

**Comment by kisak-valve** [comment]
Closing per the last comment.
