### ISSUE TITLE
__GL_THREADED_OPTIMIZATIONS=1 prevents launch

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/halflife#2394]
This is been going on for about half a year, and has occured before in the past. No GoldSrc games will launch on my system, even with the runtime enabled. This is on a fully up too date Arch Linux system.

https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341

**Comment by JoelTroch** [comment]
Gonna need more info than your system specs.

Try launching Steam from the terminal and then the game to see if there is any useful logging we could use.

Did you looked at Arch's wiki as well? https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Game_crashes_immediately

**Comment by shoober420** [comment]
Heres more system specs from my Steam profile.

https://steamcommunity.com/id/sHooBer42o

When I click Play, the game will say "Running", but the game window doesnt ever pop up, and I remain at the desktop staring at Steam.

Heres some output from console.

ActivateActionSet.GameAction [AppID 10, ActionID 3] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 10, ActionID 3] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 10, ActionID 3] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 10, ActionID 3] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 10, ActionID 3] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 10 "", ProcID 21869, IP 0.0.0.0:0
Starting app 10
>>> Adding process 21869 for game ID 10
GameAction [AppID 10, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 10, ActionID 3] : LaunchApp changed task to Completed with ""
pid 21871 != 21870, skipping destruction (fork without exec?)
>>> Adding process 21870 for game ID 10
>>> Adding process 21872 for game ID 10
>>> Adding process 21873 for game ID 10

**Comment by Sockman1** [comment]
If you haven't, try forcing proton enabled and launch the windows version. I don't have Linux myself so I can't test, but it might be a good temporary solution.

**Comment by glitchbunny** [comment]
I had a similar problem (well, similar symptoms, anyway, it could be a different problem!) and found the solution was to set the launch options as follows;

`env -u MESA_GLSL_CACHE_DIR %command%`

I have no idea why - I found this by comparing the env of the Steam launched Half-Life with the env of Half-Life launched manually from the CLI (which was working) and then some trail/error with the extra environment variables set by Steam.

The MESA_GLSL_CACHE_DIR environment variable had to be unset.  I initially noticed that it was set to point at an NFS filesystem and assuming that might be the problem, I tried setting it to point at somewhere on the local disk.  Although it did work in the sense that a Mesa cache directory was created there when I ran Half-Life, it didn't work in the sense that the no-display bug remained.  Only unsetting the variable resulted in a successful launch.

**Comment by shoober420** [comment]
This does not work for me. I know I did it correctly, because according to htop, Steam is launched with the exact command in the path.

**Comment by glitchbunny** [comment]
It could be that you are experiencing a different problem with similar symptoms, of course, but possibly worth picking up on one thing in your reply (assuming it isn't simply a typo) - you say that Steam has the command string in the path, but it is Half-Life that needs to be launched with that option, not Steam.  i.e;

- Start Steam.
- Right-click on Half-Life, select "Properties".
- Click on the "SET LAUNCH OPTIONS..." button.
- Enter the string in the resulting dialog, click "OK".

If you do this, you will find that it is hl.sh rather than the actual game itself (hl_linux) that shows up in htop (or ps/top/whatever) with the commandline prepended.  If you want to check the variable is actually unset, one way would be to get the PID of hl_linux from htop, then use it in place of {PID} in the command below;

`grep --null-data MESA /proc/{PID}/environ`

This should NOT match anything, because the variable is unset if everything is correctly done.

**Comment by shoober420** [comment]
I've found the time to debug this further, with no luck, but maybe getting closer to the root of the issue.

So when starting HL with that launch option, I dont encounter the same scenario as you. Instead of there simply being the hl.sh script running when using that launch option string, I have TWO seperate hl_linux processing running, along with the hl.sh process, so THREE in total. All 3 of these processes have their own PID number. When entering the grep command, it returns nothing, like you said, but still the game doesnt launch. 

What I do notice, on my four CPU cores, the game will max out each core one at a time, to 100%. So each core will go to 100% every minute or so, and switch around. The other three will sporadically go between 0.0-3.0%, with one of the random fourth core maxed to 100%.

When I launch HL without Steam, so with "./hl_linux" or "./hl.sh", the same behavior occurs with the cores maxing to 100% one at a time. This happens when running Steam with or without the runtime. This sucks pretty bad, the game doesnt even launch when I use the runtime. Thats ridiculous.

**Comment by shoober420** [comment]
Completely uninstalling Steam and reinstalling Steam and HL didn’t fix this either...

**Comment by glitchbunny** [comment]
I also have three processes (although two shell and one hl_linux, this is just the result of the way it is launched and not an issue).  However, if you have two hl_linux processes it may be that something is going wrong there that will need some investigation.

Also, you say that HL does not successfully launch if you attempt to launch it from the CLI, whereas that did work in my case, and it was what led me to experiment with and discover that it was an environment variable set by Steam that was causing the issue (or possibly the environment variable happens to be a workaround for whatever the real issue is).  

Given this, I think that we can safely say that whatever is causing your issue, it is a different problem than in my case.  Sorry I couldn't help and good luck in fixing it!

**Comment by shoober420** [comment]
I came across this issue (https://github.com/ValveSoftware/halflife/issues/2094), and it seems to have brought me closer to finding out whats going on. Although I followed the steps in this issue thread, starting the game via "./hl_linux" will stay running in the background with the game not actually starting.

That issue brought me to the suggested solution by glitchbunny (https://github.com/ValveSoftware/halflife/issues/2100), so I'm going to try that solution again and see if it works.

**Comment by shoober420** [comment]
I added "unset MESA_GLSL_CACHE_DIR" to the hl.sh file like suggested in issue (#2100), and I get an error after executing "./hl.sh" that says "./hl.sh: line 37: cd: too many arguments". I also added that argument string to my CS1.6 launch options and it doesnt make a difference. I literally have no idea what to do. 

@SamVanheer could you please help?

**Comment by shoober420** [comment]
So Im going to do each process step by step for reference on my part, and for someone who may know whats going on.

Simply running "./hl_linux" will result with this error.

Error:libsteam_api.so: cannot open shared object file: No such file or directory
Could not load hw.so.
Please try again at a later time.%

When doing "LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./hl_linux", the process starts, but the game never boots up, like I've been experiencing this whole time.

I then tried "export unset MESA_GLSL_CACHE_DIR" and "./hl_linux", that also didnt work.

Then I tried "env -u MESA_GLSL_CACHE_DIR ./hl_linux", that didnt work.

Previously, I tried adding "unset MESA_GLSL_CACHE_DIR" to line 37 in the hl.sh, and it gives me an error, but it still runs.

./hl.sh: line 37: cd: too many arguments

I then moved the "unset MESA_GLSL_CACHE_DIR" command string below line 37. I got no error, but the game still did not start.

@SamVanheer, could you please help?

**Comment by shoober420** [comment]
After going as far as to install the git master of mesa, I finally figured out what it was.

**export __GL_THREADED_OPTIMIZATIONS=1**

I have this in my .zshrc script, and have had it in there for over half a decade. GoldSrc games havent been launching for me for almost a whole YEEEEEEEEEEEEEAR.  I would of never thought a NVIDIA driver update would brake GoldSrc because of this FREAKING COMMAND. :LJKDHFJIUDK:FJHKJHSDFKGJHSLFDJGHKLKSDGJHFKJGHSKJGDFHKJGHSDFKJGHSFDLKJHblAZDKJFHLKJZDFGKJDAZFGKHJKDSAFGJHKJHGR

So Im going to make a post on the NVIDIA Linux forums about it, and see if its a thing.

Now I can finally Counter-Strike l:LFJCK VKEDJNLFGLKBJN:D:LFJNKlkdczfbjngkjbazdflkbjgkjhzdbFkjbDXKJHFCVbgJKHSDFBCVkjhDBFkjhBDFGJKHzDFBNJHKGVkjbnzfkjbnvzkjbvdck,bjhl.zk,djhbl.vk,l.jhzbdf,ilzvbuerdiku78blze48lik7vbzelk8b7iuvzxerk8b7lvzxelk8b7ivzxelbu7ivzxeibuyvzleibuyzvibduhivbuhfibuhvfibjhzxvdf

**Comment by shoober420** [comment]
I thought about it, and decided that just Incase this is an issue with GoldSrc, I’ll leave it open. If it’s an bug on NVIDIAs end, please feel free to close it.

**Comment by SamVanheer** [comment]
Launch the game with `-condebug -dev +developer 2` and then post the contents of `Half-Life/qconsole.log` . Make sure to clear the file's contents first to remove any unrelated info.

The contents should help pinpoint when the game fails to continue launching, if it manages to launch at all.

**Comment by thaewrapt** [comment]
Is it still a case for anybody else? Quick testing showed it's not a thing for me anymore on Arch.

**Comment by kisak-valve** [comment]
Closing per the last comment.
