### ISSUE TITLE
[Latest Betas] gl_texturemode resets to GL_NEAREST for every single mod - only with latest betas

### ISSUE THREAD

**Issue by sjain882** [ValveSoftware/halflife#2395]
Happens every game launch, tried setting it to default (GL_LINEAR_MIPMAP_LINEAR) but it doesn't stick.

There are no gl_texturemode entries in any of my cfg files anywhere in my HL directory (valve, cstrike, etc) and I have never changed this option.

I don't even have "low video quality" checked either.

What could this be? Really don't want to have to resort to a clean install of HL.

# Solved

I simply opted out of the latest betas for Half Life and Counter Strike.

Here are my launch options:

-w 640 -h 480 -insecure +sv_lan 1 -noforcemaccel -noforcemparms -noforcemspd -nomsaa

**NOTE - I also tried NOT using any of these options, and using different resolutions too while opted into beta. didnt fix it!**

My PC specs - https://uk.pcpartpicker.com/list/vDxFmq

latest GPU drivers installed, i also tried a clean install with DDU to fix it but only opting out of beta fixed it!

**Comment by SamVanheer** [comment]
The default setting was changed to be closer to the original version of the game, but after feedback the decision was made to revert it: https://github.com/ValveSoftware/halflife/issues/1650#issuecomment-485557341

**Comment by sjain882** [comment]
Wow, thanks so much for informing, I missed that. That is very very interesting. Honestly, I love playing classic HL like that but after while it just starts to look awful for me. Thanks again, very interesting

**Comment by SamVanheer** [comment]
If this answers your question then you can close the issue.
