### ISSUE TITLE
'writecfg' created (null).cfg if argument is not specified

### ISSUE THREAD

**Issue by 2010kohtep** [ValveSoftware/halflife#2397]
```Host_WriteCustomConfig``` gets the name of the configuration file to write using ```Cmd_Args```, however, there is no check if the ```Cmd_Args``` function returns ```NULL```.

**Comment by 2010kohtep** [comment]
@mikela-valve, is it possible to make a fix for this problem in the next release? Handling a NULL situation should not take a lot of time.

**Comment by mikela-valve** [comment]
Fixed, this will be included in the next beta update.

**Comment by mikela-valve** [comment]
Added in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by mikela-valve** [comment]
Closing this as fixed.
