### ISSUE TITLE
Change game client renderer using '_setrenderer' command ignores windowed mode

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#2400]
If we try to change the renderer in the game client that is running in windowed mode using the GUI (`Options -> Video tab`), then everything will work correctly and the game will restart in windowed mode. But if we try to do the same thing using console by executing `_setrenderer software; _restart`, the game will start in full screen mode, ignoring the previously specified windowed mode.

**Comment by SamVanheer** [comment]
That's because the command takes two parameters, not one. While it does still work when using just one you're supposed to pass the windowed setting as the second parameter.

The second parameter has as arguments either `windowed` or `fullscreen`.

**Comment by Splatt581** [comment]
@SamVanheer, thanks, I didn't know, it really works. In this case, I close the issue.
