### ISSUE TITLE
Repeating lines when trying to add a game server to favorites

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#2401]
If we try to add a new server to the favorites tab in the game client (`Find Servers -> Add a Server button`) and ping multiple times, then a new line will appear for each response from the server, rather than updating the old one. The example in the screenshot:
![3](https://user-images.githubusercontent.com/31417200/57547930-bd3e0300-7370-11e9-8244-cba1e6b6e42e.jpg)

**Comment by kisak-valve** [comment]
Hello @Splatt581, this issue is already being tracked at #18. Closing as a duplicate.
