### ISSUE TITLE
Crashes on Linux Xubuntu v16

### ISSUE THREAD

**Issue by sabian-heatwave** [ValveSoftware/halflife#2417]
I have tried windowed mode, there is no option for software mode. How can I fix this?

**Comment by kisak-valve** [comment]
Hello @DiseCoding-or-DiseGames, what game are you trying to run? Are there any hints in `/tmp/dumps/<username>_stdout.txt` or `~/.steam/error.log`?

**Comment by DiseCoding-or-DiseGames** [comment]
> Hello @DiseCoding-or-DiseGames, what game are you trying to run? Are there any hints in /tmp/dumps/<username>_stdout.txt or ~/.steam/error.log?

I am trying to run **Half-Life.** I won't be able to provide my error log for a few hours.
