### ISSUE TITLE
Ricochet FGD

### ISSUE THREAD

**Issue by SethTooQuick** [ValveSoftware/halflife#2422]
You wouldn't happen to have one lying around would ya?

**Comment by SamVanheer** [comment]
Is this what you're looking for: https://developer.valvesoftware.com/wiki/Ricochet.fgd

**Comment by SethTooQuick** [comment]
Yeah, thanks. I guess I should've looked it up to see if it existed. I just thought it wasn't included in the Half-Life SDK's "FGD" file. Do you have access to edit that too?

**Comment by SamVanheer** [comment]
@mikela-valve can probably update the SDK to include it.

**Comment by mikela-valve** [comment]
Thanks @SamVanheer, I'd be happy to add that. The reason it's not there already is that we only have FGD's for DOD and CS in our repository, otherwise it probably would have been added in an earlier commit.

**Comment by mikela-valve** [comment]
Added both DMC and Ricochet FGD's in bb5a8b9a9f5551ace8a5847afd868b0749765544.

**Comment by SamVanheer** [comment]
I was actually referring to the Half-Life SDK on Steam since that includes Hammer along with some of the fgds. Could they be added there as well?

**Comment by mikela-valve** [comment]
Got it, I’ll have to look at what the SDK is built from to see how it’s updated but I can probably get update it with the FGD’s. I’ll reopen this.

**Comment by SethTooQuick** [comment]
Awesome to see this getting updated! Only noticing these changes now as I never have a reason to view GitHub. Thanks!

**Comment by mikela-valve** [comment]
This has been updated in the SDK as well.
