### ISSUE TITLE
[CS] return roll angle

### ISSUE THREAD

**Issue by hackovh** [ValveSoftware/halflife#2424]
for magic

**Comment by Lifeisstrange74** [comment]
CS didn't have viewroll since the betas, so it was removed on purpose.
However,this would be a great feature readdition for Half Life games since it was removed there, when both pre 1.1.0.8 versions of HL1 and OF and Blue Shift had view roll originally

**Comment by Solokiller** [comment]
As stated above roll was removed from CS on purpose. For other games #1544 already tracks this request, so this issue is a duplicate.

**Comment by kisak-valve** [comment]
Closing as a duplicate.
