### ISSUE TITLE
[CS] A collection of fixes for default weapons

### ISSUE THREAD

**Issue by GBCS-PRO** [ValveSoftware/halflife#2427]
Try to officially implement as many as possible from these
https://gamebanana.com/wips/46720

**Comment by kisak-valve** [comment]
Hello @GBCS-PRO, the individual issues mentioned in the link should have separate issue reports, one issue per issue report for proper tracking. I'm going to consider a request like this an untrackable mess.

**Comment by GBCS-PRO** [comment]
I just wanted to make it all-in-one so it'd be easier. Anyway i'll report these individually
