### ISSUE TITLE
[cs] Scrambled text when using -nofbo

### ISSUE THREAD

**Issue by disabledgamer** [ValveSoftware/halflife#243]
Example:http://i.imgur.com/v7K4sII.jpg
Without -nofbo 4:3 is stretched out to fit monitor so I can't use it.

Vendor:  AuthenticAMD
    Speed: 2094 Mhz
    2 logical processors
    1 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Windows XP (32 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  ATI Mobility Radeon HD 4200

```
DirectX Driver Name:  ati2dvag.dll
Driver Version:  6.14.10.7028
DirectX Driver Version:  6.14.10.7028
Driver Date: 10 Dec 2009
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
DirectX Card: ATI Mobility Radeon HD 4200
VendorID:  0x1002
DeviceID:  0x9712
Number of Monitors:  1
Number of Logical Video Cards:  1
No SLI or Crossfire Detected
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.27" x 7.48"  (15.20" diag)
                                        33.7cm x 19.0cm  (38.6cm diag)
Primary Bus Type Not Detected
Primary VRAM: 700 MB
Supported MSAA Modes:  2x 4x 
```

Sound card:
    Audio device: Conexant HD Audio output

Memory:
    RAM:  2812 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  2060344 Mb
    Largest Free Hard Disk Block:  1627025 Mb
    OS Install Date: Sep 01 2012
    Game Controller: None detected

Installed software:
    Adobe Flash Player 11 Plugin
    ALPS Touch Pad Driver
    AnyDVD
    Atheros Client Utility
    ATI Catalyst Install Manager
    ATI Display Driver
    Catalyst Control Center Core Implementation
    Catalyst Control Center Graphics Full Existing
    Catalyst Control Center Graphics Full New
    Catalyst Control Center Graphics Light
    Catalyst Control Center Graphics Previews Common
    Catalyst Control Center InstallProxy
    Catalyst Control Center Localization All
    CCC Help Chinese Standard
    CCC Help Chinese Traditional
    CCC Help Czech
    CCC Help Danish
    CCC Help Dutch
    CCC Help English
    CCC Help Finnish
    CCC Help French
    CCC Help German
    CCC Help Greek
    CCC Help Hungarian
    CCC Help Italian
    CCC Help Japanese
    CCC Help Korean
    CCC Help Norwegian
    CCC Help Polish
    CCC Help Portuguese
    CCC Help Russian
    CCC Help Spanish
    CCC Help Swedish
    CCC Help Thai
    CCC Help Turkish
    ccc-core-preinstall
    ccc-core-static
    ccc-utility
    CCleaner
    Combined Community Codec Pack 2012-12-30
    Conexant HD Audio
    Counter-Strike
    CPUID CPU-Z 1.62.0
    DVD Shrink 3.2
    eReg
    foobar2000 v1.1.14a
    Fraps (remove only)
    GCFScape 1.8.4
    Hotfix for Microsoft .NET Framework 3.5 SP1 (KB953595)
    Hotfix for Windows XP (KB2443685)
    Hotfix for Windows XP (KB954550-v5)
    IrfanView (remove only)
    Jed's Half-Life Model Viewer 1.3.6
    Karen's Directory Printer
    Microsoft .NET Framework 1.1
    Microsoft .NET Framework 2.0 Service Pack 2
    Microsoft .NET Framework 3.0 Service Pack 2
    Microsoft .NET Framework 3.5 SP1
    Microsoft .NET Framework 4 Client Profile
    Microsoft Kernel-Mode Driver Framework Feature Pack 1.9
    Microsoft User-Mode Driver Framework Feature Pack 1.0
    Microsoft Visual C++ 2005 Redistributable
    Microsoft Visual C++ 2008 Redistributable - x86 9.0.21022
    Microsoft Visual C++ 2008 Redistributable - x86 9.0.30411
    Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17
    Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.4148
    Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219
    Microsoft Visual C++ 2012 Redistributable (x86) - 11.0.51106
    Microsoft Visual C++ 2012 x86 Additional Runtime - 11.0.51106
    Microsoft Visual C++ 2012 x86 Minimum Runtime - 11.0.51106
    Mozilla Firefox 18.0.2 (x86 en-US)
    Mozilla Maintenance Service
    MPC-HC 1.6.5.6366
    qBittorrent 3.0.8
    Realtek USB 2.0 Card Reader
    Skins
    Steam
    Unlocker 1.8.5
    VLC media player 2.0.4
    WebFldrs XP
    Windows Media Format 11 runtime
    Windows Media Player 11
    WinRAR 4.00 (32-bit)

**Comment by shawns-valve** [comment]
Closing due to age. Please create a new issue if this still occurs with the 25th anniversary update (December 2023 Steam build). Newer builds also have improved support for widescreen resolutions.
