### ISSUE TITLE
[CS] Pushable velocity bug

### ISSUE THREAD

**Issue by voed** [ValveSoftware/halflife#2448]
Player is pushed along with func_pushable when using it
Example here https://www.youtube.com/watch?v=idAsaXfBRfI
Or chair near the door on cs_estate https://www.youtube.com/watch?v=AwbuBFdYoYw
Solution here https://github.com/s1lentq/ReGameDLL_CS/pull/352/files
This bug does not affect half-life because in half-life player slows down while pressing E

**Comment by SamVanheer** [comment]
Duplicate of #2188

**Comment by kisak-valve** [comment]
Closing per the last comment.
