### ISSUE TITLE
[CS 1.6, Feature Request] new crosshair cvars

### ISSUE THREAD

**Issue by 10th** [ValveSoftware/halflife#2468]
cl_crosshairsize 1/2/3 --> 1-100...
cl_crosshairgap
cl_crosshairthickness
cl_crosshair_translucent 0/1 --> cl_crosshair_alpha 0-255

cl_crosshair_draw_outline
cl_crosshair_outline_thickness
cl_crosshair_outline_gap
cl_crosshair_outline_color "0 50 0"
cl_crosshair_outline_alpha "60"

translucent micro crosshair inside the main crosshair (including point)
cl_crosshair_mini_size
cl_crosshair_mini_gap
cl_crosshair_mini_alpha "22"

cl_crosshair_sniper_width
cl_crosshair_sniper_gap
Adding cvars sniper, sprite sniper_scope.spr need to leave only points.
Otherwise, with zoom x2, the crosshair sprite shakes and it looks bad (most often when running).

**Comment by kisak-valve** [comment]
Hello @10th, there's a couple feature requests already open for crosshair customization at #265, #2105. Closing in favor of the existing issue reports.
