### ISSUE TITLE
[CS] [CZ] [8245] Bug view Sprite

### ISSUE THREAD

**Issue by Shalun22** [ValveSoftware/halflife#2470]
Hey.

Today I tested the Beta client on my server and found an unpleasant bug. More in the video: https://www.youtube.com/watch?v=LWMqSgHR-g8

When distanced from the sprite, it is distorted. Used sprite "Alpha Test"

P.S. Google translate.

**Comment by CS-PRO1** [comment]
@mikela-valve This is worth looking..

**Comment by Shalun22** [comment]
Hi. Are you planning to fix this problem or is there no hope anymore?

**Comment by RauliTop** [comment]
When does it start to happen? Only after that beta version?

**Comment by Shalun22** [comment]
@RauliTop

Yes...
