### ISSUE TITLE
The 'save' command can write files with arbitrary extensions

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#2479]
For example:

```
] save asd.exe
Saving game to SAVE\asd.exe...
```

It is probably necessary to force the addition of the native `.sav` extension to the end of the path, as is done for the `writecfg` command:

```
] writecfg asd.exe
asd.exe.cfg successfully created!
```

**Comment by mikela-valve** [comment]
Fixed, this will be included in the next beta update.

**Comment by Splatt581** [comment]
I confirm, fixed in 8254 build.
