### ISSUE TITLE
[Half-Life] No label icon is assigned.

### ISSUE THREAD

**Issue by drogga** [ValveSoftware/halflife#2489]
After installing Half-Life, it is proposed to create a shortcut on the desktop. We agree and we end up with:

![hldd](https://user-images.githubusercontent.com/43634578/58556662-0ebd0d80-820c-11e9-95c6-347f3fc65dd3.PNG)

And when trying to change manually:

---------------------------
Error working with shortcut
---------------------------
This web label cannot be modified.
---------------------------
OK
---------------------------

**Comment by SamVanheer** [comment]
When i create a desktop shortcut through Steam it uses the icon from the game as expected. Are you installing the Steam version or some older version?

**Comment by drogga** [comment]
Official Steam version of Half-Life Beta [Buld 8245]. I already guess that the problem may be specific to different versions of operating systems, and also depend on the version of Steam used.

**Comment by drogga** [comment]
I am canceling this issue because Steam on Windows XP is no longer being updated.

**Comment by rtxa** [comment]
> 
> 
> I am canceling this issue because Steam on Windows XP is no longer being updated.

I don't think that, this issue happens to me in Windows 10.
