### ISSUE TITLE
Mouseacc

### ISSUE THREAD

**Issue by trollollol123** [ValveSoftware/halflife#25]
I seen about 15 players complaining about new mouseacc since the update. Also other issues with the mouse/sens have been reported in forums. I have no idea how to describe the issues here.

**Comment by djdallmann** [comment]
''without'' SHIM_RENDERING_MODE_ENABLE my mouse sensitivity is very inconsistent. Anyone with NVIDIA should enable this regardless if you have optimus or not.

Download nvidia inspector then find "Half Life" from the drop down menu, and then scroll down to "enable application optimus option" and set it to "SHIM_RENDERING_MODE_ENABLE" and click apply settings.
