### ISSUE TITLE
[Half-Life] Maps don't load through level triggers (recent beta)

### ISSUE THREAD

**Issue by Sockman1** [ValveSoftware/halflife#2500]
On the recent beta, I and at least one other person have been having this issue. The maps load fine from the console, but as soon as a level change trigger is hit in-game, the game is stuck loading. The issue is fixed if the beta is reverted. Verifying the game files doesn't fix it.

Strangely enough, I can go into the menu and look at the console, the game doesn't actually freeze or crash. This is the output after touching a level trigger (from c1a1 to c1a0c):

> CHANGE LEVEL: c1a0c c1a0catoc1a1
> Spawn Server c1a0c: [c1a0catoc1a1]
> Clearing memory
> loading maps/c1a0c.bsp
> Texture load:   70.2ms
> WARNING: failed to locate sequence file c1a0c
> Loading game from SAVE\c1a0c.HL1...
> ERROR: couldn't open.
> 
> GAME SKILL LEVEL:1
> loading sprites/hotglow.spr
> loading sprites/smoke.spr
> loading sprites/laserdot.spr
> loading sprites/streak.spr
> loading sprites/xbeam1.spr
> loading sprites/XSpark1.spr
> loading sprites/muz1.spr
> loading sprites/laserbeam.spr
> loading sprites/zerogxplode.spr
> loading sprites/WXplo1.spr
> loading sprites/steam1.spr
> loading sprites/bubble.spr
> loading sprites/bloodspray.spr
> loading sprites/blood.spr
> loading sprites/explode1.spr
> 
> *Graph Loaded!
> Chapter title: C1A1TITLE
> loading sprites/flare1.spr
> loading sprites/glow04.spr
> loading sprites/Fexplo1.spr
> loading sprites/XFlare1.spr
> loading models/w_medkit.mdl
> 0 entities inhibited
> Loading game from SAVE\c1a1.HL1...
> Transferring player (1)
> **Graph Pointers Set!
> Transferring env_spark (477)
> Transferring env_spark (478)
> Loading game from SAVE\c1a0e.HL1...
> ERROR: couldn't open.
> Game started
> loading sprites/640hud1.spr
> loading sprites/640hud4.spr
> loading sprites/crosshairs.spr
> loading sprites/640hud7.spr
> loading sprites/640hud2.spr
> loading sprites/640hud5.spr
> loading sprites/640hud3.spr
> loading sprites/640hud6.spr

Another note: me and the one other person both have integrated intel gpus, I doubt that it's the cause but if someone could test with a dedicated gpu just to make sure that'd be great.

**Comment by RauliTop** [comment]
Related to: https://github.com/ValveSoftware/halflife/issues/2496

please, verify you have HL1 beta BuildID 3884097

**Comment by mikela-valve** [comment]
Thanks @RauliTop, unfortunately I tested this with 3884097 and found that it was easily reproducible.

Apparently there are just too many different ways that games are initialized that presume user messages are either already registered or have not been registered, so I'm going to update HL1 again with a change that reverts what I've done already for #2138 and instead just tracks whether `new` has been executed and blocks that from occurring again, rather than blocking user messages from registering multiple times.

**Comment by mikela-valve** [comment]
This should be fixed in BuildID 3886304, along with #2496 and #2138.

**Comment by Sockman1** [comment]
Thanks, I'll test if it's fixed when I have the chance, then I'll close this.
