### ISSUE TITLE
Developer text is not displayed in the HLDS console

### ISSUE THREAD

**Issue by 2010kohtep** [ValveSoftware/halflife#2503]
The text that should be displayed by the ```Con_DPrintf``` (developer 1) function is not displayed in the HLDS console. This is due to the fact that the ```Con_DPrintf``` function does not call the ```Launcher_ConsolePrintf``` (which in ```Sys_Printf```) function, unlike the ```Con_Printf```. The problem is solved by calling ```Sys_Printf``` inside the ```Con_DPrintf``` function.

@mikela-valve , this is a pretty annoying problem and its existence makes it difficult to debug and test the HLDS functionality. Since the fix is simple, I would like to ask to implement a fix for this problem ASAP.

**Comment by mikela-valve** [comment]
Fixed, this will be included in the next beta update.

**Comment by mikela-valve** [comment]
This should be fixed in beta update '15:46:27 Jun 11 2019 (8265)'.

**Comment by mikela-valve** [comment]
Closing as fixed.
