### ISSUE TITLE
[Feature Request] sv_cheats 1 without "restart"

### ISSUE THREAD

**Issue by BlackShadow306** [ValveSoftware/halflife#2511]
It's a small simple request yet still semi-useful. As the title says, it would be good if we can enable sv_cheats  (1) without restarting the game. Just like in Source .

**Comment by mikela-valve** [comment]
Hi @BlackShadow306, I actually added this in the last beta when making changes for #2339. Try starting up a game in HL1 with `sv_cheats 0` then switch to `sv_cheats 1` and try `impulse 101`.

**Comment by BlackShadow306** [comment]
Thank you! Cheers!
