### ISSUE TITLE
Higher FOV for Widescreen resolutions

### ISSUE THREAD

**Issue by CS-PRO1** [ValveSoftware/halflife#2512]
Currently the FOV used for widescreen is too narrow and makes gameplay a bit annoying. I feel that  FOV being set to 110 for widescreen resolutions would greatly improve gameplay on those resolutions. You can compare that by yourself here:
![59167d6febb06](https://user-images.githubusercontent.com/50755959/59059544-e4242200-88a7-11e9-9829-6d7f9ad10de4.jpg)

**Comment by kisak-valve** [comment]
Hello @CS-PRO1, there's some issue reports already open on this topic (#748 / #1978 / #2018 ). Closing in favor of the existing issue reports.
