### ISSUE TITLE
[CS 1.6] sv_restartround should be changed

### ISSUE THREAD

**Issue by Maxi605** [ValveSoftware/halflife#2518]
Currently sv_restart and sv_restartround behave the same, they both reset completely the game, removing rounds won, frags, deaths, money, etc.
sv_restartround should restart the current round keeping all the previous progress saved, i don't know if this is a functionality on CS:GO or not but it is on CS:GO tournaments, it would be a good addition to the game that i guess everyone can agree on.

**Comment by basuritashka** [comment]
AFAIK sv_restart reset timeleft and sv_restartround doesn't.

**Comment by kisak-valve** [comment]
Hello @Maxi605, there's already a feature request to change sv_restartround at #558. Closing in favor of the existing issue report.
