### ISSUE TITLE
[Half-Life - 8260] sv_cheats console spam

### ISSUE THREAD

**Issue by BlackShadow306** [ValveSoftware/halflife#2525]
Changing sv_cheats from "1" to "0 " creates infinite console spam while in game.

```
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 10:20:22 Jun  6 2019 (8260)
```

**Comment by mikela-valve** [comment]
Thanks @BlackShadow306, I'll have a fix for this included in the next beta.

**Comment by mikela-valve** [comment]
This should be fixed in beta update '15:46:27 Jun 11 2019 (8265)'.

**Comment by BlackShadow306** [comment]
Working like charm now.
