### ISSUE TITLE
[Half-Life] Breaking Crossfire with Satchels

### ISSUE THREAD

**Issue by BlackShadow306** [ValveSoftware/halflife#2529]
This issue been there for years. The problem is players breaking Crossfire with Satchels. Satchels can block func_door. 

Here's a small footage:

https://streamable.com/qtmgt

I also tried to Tower block trick but i failed since i forgot how to do it.

But i was able to found a video about it:

https://youtu.be/wi_DLqLr0a0?t=35

With this trick nobody can enter the bunker from towers except the player who throw the satchel. Because satchel is non-solid to player who throwed it. As in the video i dropped the satchel to unreachable spot. This will make block the bunker still even the player left the server. And only way is to remove satchels is either restart map or pickup capsules which is impossible. Servers without admin moderation is always facing with this issue.

**Comment by kisak-valve** [comment]
Hello @BlackShadow306, this issue is already being tracked at #787. Closing as a duplicate.
