### ISSUE TITLE
Уничтожение Steam клиента CS 1.6

### ISSUE THREAD

**Issue by DaiwaSport** [ValveSoftware/halflife#2530]
Доброго времени суток, я к Вам с таким вопросом. Вы же наверно знаете что есть эмулятор Counter-Strike 1.6, т.е пиратская версия игры и что есть мониторинги по раскрутке пиратских серверов кс 1.6, теперь они запрещают администраторам серверов выдавать бонусы за оффициальный клиент игры, т.е полностью блокировкой лицензионного клиента игры. Более подробно можете почитать вот тут: https://c-s.net.ua/forum/topic90167s480.html#entry1091668

Я бы полностью запретил распространение пиратского клиента в РФ. Вот полный список сайтов которые распространяют новый билд с блокировкой официального:^ https://yandex.ru/search/?text=%D1%81%D0%BA%D0%B0%D1%87%D0%B0%D1%82%D1%8C%20%D0%BA%D1%81%201.6&clid=2270455&banerid=6301000000%3A5cca780ad6aec2004b8175d5&win=383&lr=13

Поддержка сказала продублировать сюда обращение.

**Comment by DaiwaSport** [comment]
И хочу отметить, нас много таких соберётся для подобных сообщений в поддержку, может после многочисленного обращения Valve услышит нас.

**Comment by basuritashka** [comment]
English please.

**Comment by CrazyHackGUT** [comment]
No-Steam = No official support

**Comment by Rawr1337** [comment]
> English please.

You probably know that there is an emulator fot CS 1.6, pirated client and there are monitorings for promotion of no-steam cs 1.6 clients. Now they forbid server administrators to give out bonuses for Steam clients or even fully blocking legitimate Steam clients from accessing servers. More compete information here: https://c-s.net.ua/forum/topic90167s480.html#entry1091668

I wish redistribution of No-Steam clients would forbidden all over across Russia/CIS . Here is the full list of websites wich redistribute the latest build with blocking the official one:  https://yandex.ru/search/?text=%D1%81%D0%BA%D0%B0%D1%87%D0%B0%D1%82%D1%8C%20%D0%BA%D1%81%201.6&clid=2270455&banerid=6301000000%3A5cca780ad6aec2004b8175d5&win=383&lr=13

Steam support have asked to duplicate the message here

**Comment by BlackShadow306** [comment]
This guy is still requesting for non-steam. If emulators can join servers because they allow it. @kisak-valve  please close it.

**Comment by Mistrick** [comment]
> This guy is still requesting for non-steam. If emulators can join servers because they allow it. @kisak-valve please close it.

Guy request close unofficial monitorings for cs which spread non-steam clients for boost online.
Now we have 60% fake servers in official monitoring and tons of unofficial monitorings.

> requesting for non-steam

What do you mean by this?

**Comment by BlackShadow306** [comment]
From what've understand this guy was complaining about Steam emulated CS 1.6 entering the server he's played and taking advantage of rewards given to Steam players. If those steam emulated can enter their server they probaly allow it with D-Proto and stuff. Which means non-steam.

Non-steam = No support in here.

**Comment by Mistrick** [comment]
You misunderstood TS. Owners of unofficial monitorings want to block steam clients on servers which they boost. 
Guy request to close this monitorings.

**Comment by Mistrick** [comment]
We still have a big problem with official monitoring.
Players can't find normal server in thousands of fake servers which want redirect client to another server.
Server owners can't get online because normal server disappear in thousands of fake servers.
Who will solve this problems?

**Comment by SamVanheer** [comment]
I don't think Valve can do anything about what no-Steam servers do, but Mike or somebody else can probably say for sure.

**Comment by Mistrick** [comment]
Anyway we need clean official monitoring.
Current server owner see crap in official and go to unofficial for online.

**Comment by BlackShadow306** [comment]
I'm not sure if this can be done but, if Server Browser has specific check for actual HLDS then Server Browser will only scan actual servers.

**Comment by fe7ch** [comment]
>I don't think Valve can do anything about what no-Steam servers do

For example Valve can prevent fake/malicious servers from registering on official master servers and therefore protect users of official game client from a risk of being infected and/or redirected somewhere.

**Comment by SamVanheer** [comment]
> 
> 
> > I don't think Valve can do anything about what no-Steam servers do
> 
> For example Valve can prevent fake/malicious servers from registering on official master servers and therefore protect users of official game client from a risk of being infected and/or redirected somewhere.

They'd have to block ReHLDS has well in that case since there is no way to be sure if the code that's using Steamworks was loaded by hl.exe or some custom engine build. Since a lot of servers use ReHLDS it'd be very difficult to do this effectively.

**Comment by fe7ch** [comment]
> > > I don't think Valve can do anything about what no-Steam servers do
> > 
> > 
> > For example Valve can prevent fake/malicious servers from registering on official master servers and therefore protect users of official game client from a risk of being infected and/or redirected somewhere.
> 
> They'd have to block ReHLDS has well in that case since there is no way to be sure if the code that's using Steamworks was loaded by hl.exe or some custom engine build. Since a lot of servers use ReHLDS it'd be very difficult to do this effectively.

I don't see any troubles with it. Since Valve started rolling out fixes for CS 1.6 it isn't necessary to run ReHLDS instead of the official HLDS any more. 
Also Valve could easily monitor which servers allow clients with 47th protocol and ban them from the official MS.

**Comment by BlackShadow306** [comment]
Actually it's important because %75 of the community servers are using reHLDS. Also what you saying is easy on paper but not really on technical side.

**Comment by fe7ch** [comment]
> Actually it's important because %75 of the community servers are using reHLDS. Also what you saying is easy on paper but not really on technical side.

What excatly is so hard to do from your point of view?

**Comment by BlackShadow306** [comment]
It will be hard decision to make because:

reHLDS will be broken, community won't be pleased about this.
HLDS needs to be re-worked. Which isn't easy.
Also we're not sure if this can be fixed fully.

**Comment by DaiwaSport** [comment]
Решение не трудное, просто valve стоит проработать все это. Мониторинги уйдут с своими пиратками, останется только лицензия и люди так же будут её покупать и играть.

**Comment by BlackShadow306** [comment]
@DaiwaSport We speak English only.

**Comment by DaiwaSport** [comment]
okay

**Comment by DaiwaSport** [comment]
The decision is not difficult, just the valve is worth all this work. The monitoring will leave with their pirates, only the license will remain and people will also buy and play it.

P.s Translated with the help of a translator

**Comment by fe7ch** [comment]
>HLDS needs to be re-worked. Which isn't easy.

What is wrong with HLDS (except for security issues that are present in ReHLDS as well) ?

**Comment by Mistrick** [comment]
> > HLDS needs to be re-worked. Which isn't easy.
> 
> What is wrong with HLDS (except for security issues that are present in ReHLDS as well) ?

ReHLDS has own API which allow much more than hlds. With hlds you need tons of signatures for memhacks, etc.

**Comment by Dosyk** [comment]
TS is unhappy that non-steam monitorings don't want to let servers create benefits for steam players so he wants boost sites to be closed, so that steam will become more popular after that (it doesn't make sense, but it's his logic, lol). I think what's more important is for steam to disallow steam players to enter servers with dproto. If valve finds a way to block this non-steam supported servers, it may have an actual impact on server owners so they will disallow non-steam support and therefore players will have to buy licensed game and that will bring more steam players into the game.

**Comment by Dosyk** [comment]
Other than that, there isn't much to do, valve cant force people to stop downloading non-steam by a snap of fingers. But removing servers with dproto from Steam master server seems like a possibility.
