### ISSUE TITLE
Certain Latin letters not showing properly in the chat !

### ISSUE THREAD

**Issue by Seko1337** [ValveSoftware/halflife#2533]
I tried these letters "ɛ ṛ ṭ ḍ ɣ ḥ ǧ ř ʷ č "and all of them show in the name except for "ɣ" and "č"
![image](https://user-images.githubusercontent.com/16926182/59601325-90ada180-90fb-11e9-802a-cd219fde8faf.png)
but when I try to type them in the chat most of them don't show up, I hope you guys fix it...
![image](https://user-images.githubusercontent.com/16926182/59601257-6bb92e80-90fb-11e9-8cd7-9f909dd50a52.png)
thanks in advance...
Edit: it turns out it actually works on certain servers...but not on lan

**Comment by xerus6** [comment]
Lmao XD you guys better fix that shit!
