### ISSUE TITLE
[CS] [REQUEST] Cs steam and no steam

### ISSUE THREAD

**Issue by ptrBR** [ValveSoftware/halflife#2538]
So there will be something to block non-steam players to play with steam players, because this betas and updates, not affect them so, is unfair to play with them...

sorry for bad english btw

**Comment by LucesEnBabel** [comment]
By default non-steam clients can't join legit servers.

**Comment by CS-PRO1** [comment]
Yea, unless you set the server to let non steam clients in it's disabled by default.
@kisak-valve I'd consider this closed

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
