### ISSUE TITLE
[CS 1.6][REQ] Music in MOTD

### ISSUE THREAD

**Issue by vjatseslav** [ValveSoftware/halflife#254]
Another anti-annoying-music request. Thank you for adding _speak_enable_ cvar, it works perfectly, but there's an another way to play high volume music on 1.6 server.

With [this code](http://pastebin.com/Uhq2tvQm) in MOTD all players will listen for music if they have **volume 0**, **MP3Volume 0** and even after they leave your server. Song will play until it ends or till you quit cs.

Windows 7 x86, build 5958.

**Comment by SamVanheer** [comment]
@mikela-valve I was unable to play an mp3 file using this. If plugins are disabled then this issue and #342 can probably both be closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
