### ISSUE TITLE
what's trusted sources？

### ISSUE THREAD

**Issue by OneJc1** [ValveSoftware/halflife#2541]
hi
The lastest update released have a larger change:
Larger changes:
Added privilege checking to command execution. Commands originating outside of the client are now only able to execute commands that are considered to be safe. Commands such as 'connect', 'bind', 'quit' and certain cvars such as 'cl_filterstuffcmd' are now only executable by trusted sources.
Setting 'cl_filterstuffcmd' to a value greater than zero (e.g. 'cl_filterstuffcmd 1') will set a number of commands that are potentially abusable, such as 'say', 'fps_max', and 'setinfo', to also be only executable by privileged sources.

i cant understand trusted sources and privileged sources。
please exlpain it. thx.
sorry for my bad english.

love cs.

**Comment by afwn90cj93201nixr2e1re** [comment]
gamedll, client console, local etc.

**Comment by OneJc1** [comment]
thank you.
😀

**Comment by RauliTop** [comment]
@kisak-valve closed??
