### ISSUE TITLE
100% CPU usage when attempting to run Half Life 1 (Steam Version)

### ISSUE THREAD

**Issue by TacticalBooger** [ValveSoftware/halflife#2543]
I've noticed 2 stuff wrong with Half Life 1 lately.

Firstly, upon booting up your PC and launching the game for the first time, the game refuses to open. The process hl.exe and rundll32.exe are still running in the background.

Secondly, if you decide to close hl.exe and try booting it up again, the game opens but CPU usage is at 100%. Judging by what I've seen through Resource Monitor, rundll32.exe takes all the CPU resources.

The fix: https://www.gog.com/forum/general/old_games_not_launching_and_eating_100_of_the_cpu_on_windows_7/post1

**Comment by kisak-valve** [comment]
Hello @TacticalBooger, please verify the game's files. Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

The symptoms you've described sounds similar to #2526.

**Comment by TacticalBooger** [comment]
> Hello @TacticalBooger, please verify the game's files. Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.
> 
> The symptoms you've described sounds similar to #2526.

Here is the gist you asked for: <script src="https://gist.github.com/TacticalBooger/84f4ce61f9e278d607abc04c5cb262ed.js"></script>

I should mention, I tried validating but the same issue happens. However I noticed that after opening the game I can close rundll32.exe through task manager and the game performs fine and CPU usage is normal.

Could there perhaps be a workaround by completely blocking rundll32.exe? Closing it through task manager everytime I boot up a Goldsrc might become annoying pretty quick.

**Comment by SamVanheer** [comment]
rundll32 is used to host dlls, it shouldn't be blocked. That said, it probably shouldn't be launched by the game.

Take a look at this article and see if you can figure out which dll it's hosting: https://www.howtogeek.com/howto/windows-vista/what-is-rundll32exe-and-why-is-it-running/

**Comment by TacticalBooger** [comment]
Ironically Sven Coop seems to run fine without any CPU usage issues. I'll try cleaning up every Half Life related file and do a clean, fresh reinstall and I will update on the issue.

I don't wanna believe it but are multiplayer servers capable of downloading malicious files?

**Comment by SamVanheer** [comment]
It's possible yes. The only way to be sure is to check if a malicious file is being loaded.

**Comment by TacticalBooger** [comment]
Reinstalling the game didn't help.

I also noticed that the game doesn't boot if rundll32 isn't already running. When thats the case, hl.exe only takes around 1400k memory only.

**Comment by SamVanheer** [comment]
It would help to know which dll it's loading through rundll32. Can you try the guide i linked earlier?

**Comment by TacticalBooger** [comment]
Sure, I'll post the results asap.

**Comment by TacticalBooger** [comment]
C:\Windows\system32\rundll32.exe C:\Windows\system32\gameux.dll,GameUXShim {e01d8bbe-5c81-4ee8-85bb-ac75b922cedc};G:\Steam\steamapps\common\Half-Life\hl.exe;5016

This was taken from the command line tab just like it said in the guide.

**Comment by SamVanheer** [comment]
`gameux.dll` is apparently part of Windows, specifically it deals with launching games.

See these articles:
https://answers.microsoft.com/en-us/windows/forum/windows_other-gaming/windows-7-game-explorer-interfering-with-game/efd39c74-cfab-4c2c-b6c5-834b8849a1b3
https://superuser.com/questions/376691/i-am-running-windows-7-and-want-to-remove-games-explorer

Try it and see if the problem continues to occur.

Perhaps Valve can figure out how to configure the game so the game explorer doesn't try to launch it anymore.

**Comment by BlackShadow306** [comment]
Hi, i'm not sure what your issue could be but i have few suggestions.


• Do all Windows Updates. Make sure you're up-to-date.
• Do a virus scan with external virus scanners. (Such as Norton or Kaspersky)
• Open up cmd and type /sfc scannow
• Upgrade to Windows 10 (Optional)
• Maybe something is up with your Xeon CPU. Even though it supports AVX and SSE 4.1, 4.2 Half-Life could have issues with Xeon but still this is out of the case.

Side note: Clicking "delete" from libary doesn't fully delete game. Make sure the game is deleted fully checking by Steamapps/common/Half-Life. If your Half-Life folder is still there click on it and press Shift+Delete let us know if your issue still persists.

**Comment by TacticalBooger** [comment]
> `gameux.dll` is apparently part of Windows, specifically it deals with launching games.
> 
> See these articles:
> https://answers.microsoft.com/en-us/windows/forum/windows_other-gaming/windows-7-game-explorer-interfering-with-game/efd39c74-cfab-4c2c-b6c5-834b8849a1b3
> https://superuser.com/questions/376691/i-am-running-windows-7-and-want-to-remove-games-explorer
> 
> Try it and see if the problem continues to occur.
> 
> Perhaps Valve can figure out how to configure the game so the game explorer doesn't try to launch it anymore.

I already tried something very similar to this. I booted the game once, stopped hl.exe, booted it again and then closed rundll32. The game played fine and this can be used as a workaround.

I'm thinking that the main issue is with my Windows 7 despite me trying to keep it as updated as I can. I've also seen some post around the community hub of Half Life in Steam with the exact issue as mine, so I don't think this problem is happening only to me. It might have been some recent update of Half Life which might have broken a few stuff.

**Comment by SamVanheer** [comment]
@mikela-valve According to the developer documentation Game Explorer requires some kind of file embedded into the binary: https://docs.microsoft.com/en-us/windows/desktop/dxtecharts/windows-game-explorer-integration

Perhaps this was accidentally added by the build system?

**Comment by Maxi605** [comment]
This happen to me, reported it here: https://github.com/ValveSoftware/halflife/issues/2526

I fixed it by re-installing the game.

**Comment by TacticalBooger** [comment]
I came across this post:
https://www.gog.com/forum/general/old_games_not_launching_and_eating_100_of_the_cpu_on_windows_7/post1

This fella did an amazing job at explaining the bug and also providing a very easy solution on how to fix it. I applied the fix to my registry manually and everything is working normally again!

**Comment by CS-PRO1** [comment]
The fix mentioned above is confirmed. I experienced this recently as well and it's working like a charm now. I'd consider this as closed :D
