### ISSUE TITLE
[BUG] Holding down fire button causes some guns to do a "Double shot"

### ISSUE THREAD

**Issue by McBean56545** [ValveSoftware/halflife#2544]
I can confirm this is a bug with the latest release of Half-Life using GoldSource. To replicate this bug, activate cheats, start a built in server, find a map with a large flat wall, give yourself everything until there is no room in your inventory using the impulse 101 command, equip shotgun (MOST NOTICEABLE), stand a considerable distance (7 or so steps) from the wall, hold the primary attack button while strafing adjacent to the wall, when Gordon goes to reload the shotgun, count the holes left from the pellets of the shotgun (normal amount is 4 holes per shot in multiplayer) If one of your shots has 8 holes, and you know you didn't use the secondary fire button, you have seen the bug in action. This also happens with the 375 magnum. It may take more than one try to get it to work, but It does.

**Comment by kisak-valve** [comment]
Hello @McBean56545, this reads like the issue being tracked at #1621. Closing as a duplicate.
