### ISSUE TITLE
[Beta 8265] Game crashes and rundll32.exe consumes CPU power

### ISSUE THREAD

**Issue by CS-PRO1** [ValveSoftware/halflife#2547]
Today out of nowhere this started to happen. once launching the game there are 2 things happening:

1. The game wouldn't launch and only using 1000KB of RAM, while rundll32.exe consumes 40-50% of CPU power and nothing else happens
2. The game launches (after several tries) and has very poor performance. CSCZ:DS missions aren't even starting.

Tested on CS/CZ/CZDS all giving same results
related to https://github.com/ValveSoftware/halflife/issues/2543

**Comment by kisak-valve** [comment]
Hello @CS-PRO1, same as https://github.com/ValveSoftware/halflife/issues/2543#issuecomment-504545792, it would help if we knew what rundll32.exe is running.

**Comment by CS-PRO1** [comment]
@kisak-valve it's the same .dll the guy reported there. I'll try the fix he referenced in  the latest comment.

**Comment by CS-PRO1** [comment]
The fix worked. The game launches again and performance improved. But it seems CZDS issue is different
I'll close this and open another for CZDS
