### ISSUE TITLE
[CS 1.6] Steam CMD - fix hlds cs 1.6 download

### ISSUE THREAD

**Issue by wilianmaique** [ValveSoftware/halflife#2551]
Not from now on, but when you try to download the hlds direct through steamcmd we are having some problems, one of them is that you have to keep running "app_update 90 validate" several times to work correctly. Both windows and linux.

Thank you.

**Comment by kisak-valve** [comment]
Hello @wilianmaique, this issue is already being tracked in various issue reports (#928 / #1541 / #1583). Closing as a duplicate.
