### ISSUE TITLE
Save .dem files in cstrike_download

### ISSUE THREAD

**Issue by eat1k** [ValveSoftware/halflife#2561]
Title. Save .dem files in cstrike_download instead of cstrike folder.

**Comment by voed** [comment]
how about to add new folder `demos`? 🤔

**Comment by di57inct** [comment]
Disagree. They should be saved in cstrike but have a folder just like @voed said.

**Comment by eat1k** [comment]
> how about to add new folder `demos`? 🤔

Yeah, it's also a good idea. The point is that demos shouldn't be in the main folder.

**Comment by 10th** [comment]
You forgot about screenshots. ;-)

**Comment by CS-PRO1** [comment]
Duplication of https://github.com/ValveSoftware/halflife/issues/409
also it's added to future release..

**Comment by kisak-valve** [comment]
Closing as a duplicate.
