### ISSUE TITLE
[Linux] Bad hl.sh?

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/halflife#2564]
Upon trying to remedy GoldSrc games not launching for me for quite some time (https://github.com/ValveSoftware/halflife/issues/2394), I came across a potential scripting error.

While trying to debug this issue, I tried launching HL manually with "./hl_linux", "./hl.sh", and "sh hl.sh". Methods "./hl_linux" and "./hl.sh" produced the same behavior as launching from Steam (game says "Running", but the game never launches).

But when I used "sh hl.sh", I got two errors.

hl.sh: line 9: cd: hl.sh: Not a directory
hl.sh: line 41: /hl_linux: No such file or directory

I was able to fix the two errors by changing line 9 code like so:

> GAMEROOT=$(cd `"${0%/*}"` && echo $PWD)
> GAMEROOT=$(cd `"${*}"` && echo $PWD)

Im not entirely sure if this is just a minor script error or what. Changing line 9 didnt solve my issue, but it may prevent an issue in the future since the script doesnt run if launched with "sh hl.sh".

By the way, please look into my issue, I really want to play 1.6! Thank you!

**Comment by kisak-valve** [comment]
Hello @shoober420, forcing a bash script to run with sh is expected to fail. Sh is not the same shell https://stackoverflow.com/questions/5725296/difference-between-sh-and-bash.

**Comment by shoober420** [comment]
Whoops, thanks for that information.
