### ISSUE TITLE
Client updated today and CS crashes on startup

### ISSUE THREAD

**Issue by 10th** [ValveSoftware/halflife#2567]
Hello!
No error messages.
The client closes after the background image is displayed.

Win7x64
What other information should I provide?

**Comment by SamVanheer** [comment]
Are you running the beta?

**Comment by 10th** [comment]
Yes.

**Comment by SamVanheer** [comment]
Run with `-condebug +developer 2 -dev`, then check and post the contents of `Half-Life/qconsole.log` after running the game.

**Comment by 10th** [comment]
Console initialized.
Base networking initialized.
"sv_cheats" changed to "1"
Initializing deltas
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 12:17:35 Jul  3 2019 (8279)
128.0 Mb heap
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce GTX 570/PCIe/SSE2
GL_VERSION: 4.5.0 NVIDIA 376.09
GL_SIZES:  r:8 g:8 b:8 a:0 depth:24
ARB Multitexture extensions found.
4 texture units.  Detail texture supported.
Sound Initialization
Set primary sound buffer format: yes
Using secondary sound buffer
   2 channel(s)
   16 bits/sample
   11025 bytes/sec
DirectSound initialized
Loaded library demoplayer.dll.
Loaded library core.dll.
Creating fake network channel.
Server module initialized.
Loaded library core.dll.
World module initialized.
DemoPlayer module initialized.

**Comment by 10th** [comment]
Half-Life [beta] starts without closing
CS [beta] closes at startup

**Comment by SamVanheer** [comment]
It's definitely crashing since there's no shutdown logging going on.

The beta is loading for me so try verifying files, if that doesn't do it try reinstalling CS, if that doesn't work reinstall Half-Life as well.

If it still doesn't work after that you should post more detailed system specs.

**Comment by CS-PRO1** [comment]
Nope, works fine for me
Probably something went wrong through updating process. Verify the game files and if it didn't work delete the game and have a fresh re-install

**Comment by 10th** [comment]
Validating Steam files yielded no results.
I deleted HL and CS, turned off beta (otherwise, only CS folders are downloaded), 
downloaded the game, switched to beta version and updated.
Аfter that, the launch returned to normal.
Thank you for your help!

**Comment by 10th** [comment]
Empirically found out that the reason was in my files:
Half-Life\cstrike_addon\sound\player\
- pl_shell1.wav
- pl_shell2.wav
- pl_shell3.wav

In the current beta version only 1 file:
- pl_shell1.wav

**Comment by 10th** [comment]
Also, the client is painted when creating a map:
Half-Life\cstrike_addon\sound\common\wpn_hudon.wav

**Comment by mikela-valve** [comment]
@10th Could you upload some of those sound files so I could give them a try? The last beta update included some fixes to sound file loading reported through another channel so it would be good to see if those are just addon sounds that have legitimate issues or if they're being erroneously caught by the new checks.

**Comment by 10th** [comment]
These are empty audio files that I replaced with the standard null.wav
[test.zip](https://github.com/ValveSoftware/halflife/files/3374468/test.zip)

**Comment by mikela-valve** [comment]
Thanks. Some of the changes were using the length of sample data in the file and were presuming that the sound file was not empty. I've fixed those to skip the checks for empty audio files.

**Comment by mikela-valve** [comment]
This is fixed in the current beta. It did not require a full build so the build number is still 8279.
