### ISSUE TITLE
The 'gg' command can crash game client

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#2570]
Just try to play any demo with this command. The command will do its job - game client will create a file `fps.txt` with the results in the mod folder, but after playback it will definitely crash.

**Comment by CS-PRO1** [comment]
I always wondered what does 'gg' do exactly?

**Comment by Splatt581** [comment]
> I always wondered what does 'gg' do exactly?

As far as I know, this command is used to evaluate performance using example of playing a demo. The demo starts playing without delays between frames, as a result, the number of frames that were processed per second, as well as maximum and minimum results are writed in `fps.txt` file.

**Comment by Splatt581** [comment]
I was mistaken, in fact, the game client at the end of playing the demo executes the command `quit`. To prevent this from happening, player need to add the start option `-noquit`. Its in `CL_FinishGameGauge` function:

```
if ( !COM_CheckParm("-noquit") )
    Cbuf_AddText("quit\n");
```
