### ISSUE TITLE
[CS/MP titles] Add option to force off custom server GUI/HUD elements

### ISSUE THREAD

**Issue by CS-PRO1** [ValveSoftware/halflife#2574]
It's quite awful to join a server and see your fps drop from ~90 to 20-10 due to so many HUD/GUI stuff being shown on your screen. hud_draw 0 fixes the fps drop but now you have to play without a crosshair and default HUD stuff (ammo/health etc..).
Can we please have an option to force off the custom elements? Or at least a cvar to keep the crosshair visible?

**Comment by Mistrick** [comment]
I think we need hud optimizations, just text can't drop fps too low.
Сurrent hud/dhud/chat realization in client render leaves much to be desired.

**Comment by CS-PRO1** [comment]
Well glowing text based on tsay and csay commands of amxx are getting me significant drops even on lowest graphical settings..

**Comment by i486** [comment]
Possible duplicate of https://github.com/ValveSoftware/halflife/issues/1259 https://github.com/ValveSoftware/halflife/issues/1522

**Comment by shoober420** [comment]
Yes, I made a issue thread long ago about not only AMXX messages, but sounds as well. I play on 640x480, so AMXX are huge and blocking my view of the game. I hope they make an option to disable them.

**Comment by CS-PRO1** [comment]
Closed in favor of older discussion in https://github.com/ValveSoftware/halflife/issues/23
