### ISSUE TITLE
[CS] Server spams weapon animations in some cases

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#2575]
Server starts sending a large number of animations in each packet if player is holding a bomb or one of shotguns (xm1014 or m3). It's easy to check, just start server, take one of these objects and see incoming data via `cl_showmessages 1;net_showpackets 2`. Example:

```
c <-- sz=50 seq=708 ack=5612 rel=1 tm=511.663971
Msg: svc_weaponanim
Msg: svc_weaponanim
Msg: svc_weaponanim
Msg: svc_weaponanim
Msg: svc_weaponanim
Msg: svc_weaponanim
Msg: svc_weaponanim
Msg: svc_time
Msg: svc_clientdata
Msg: svc_deltapacketentities
```

In the case of shotguns, the animation 'idle' is sent:
![1](https://user-images.githubusercontent.com/31417200/60995431-8f227280-a363-11e9-9f55-5b34e99dde78.JPG)

and in the case of a bomb - 'idle1' and 'draw':
![2](https://user-images.githubusercontent.com/31417200/60995443-934e9000-a363-11e9-9d9d-01aa7bf288e7.JPG)

**Comment by mikela-valve** [comment]
@Splatt581 I know why this is happening, but I can't seem to reproduce it in either public or beta, I just see `svc_time`, `svc_clientdata` and `svc_deltapacketentities` and the occasional usermsg. Can anyone else reproduce this?

Either way I'll add a fix for this to the next update. The M3, XM1014 and bomb all have `WeaponIdle` timeouts that aren't reset once they trigger, leading to the idle animations constantly playing, so I'll change that to properly reset the timeout.

**Comment by mikela-valve** [comment]
Got it, forgot that I had to disable weapon prediction. Let me know if you see this with any other weapons.

**Comment by mikela-valve** [comment]
@Splatt581 This should now be fixed in beta along with the empty click being played repeatedly for the M3 and XM1014 when `+attack` is held when you have no ammo remaining which I noticed while testing this.

**Comment by Splatt581** [comment]
> @Splatt581 I know why this is happening, but I can't seem to reproduce it in either public or beta, I just see `svc_time`, `svc_clientdata` and `svc_deltapacketentities` and the occasional usermsg. Can anyone else reproduce this?

It seems that problem exists only with `cl_lw 0` on game client. I confirm, problem was fixed in the last beta and I did not find other weapons with which there is such a problem.
