### ISSUE TITLE
[GoldSrc] libSteamValidateUserIDTickets_amd64.so => not found

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/halflife#2578]
* Steam client version (build number or date): July 8 2019
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

System Information: https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341

Upon trying to figure out why my GoldSrc games dont launch (https://github.com/ValveSoftware/halflife/issues/2394), I was running the "ldd" command on every .so file in the Half-Life directory. When running "ldd engine_amd64.so", I recieved this string.

linux-vdso.so.1 (0x00007ffed85e2000)
libSteamValidateUserIDTickets_amd64.so => not found
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f296c852000)
libstdc++.so.5 => /usr/lib/libstdc++.so.5 (0x00007f296c771000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007f296c62b000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f296c611000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f296c44e000)
/usr/lib64/ld-linux-x86-64.so.2 (0x00007f296d051000)

This file is missing from my Half-Life folder. In an effort to remedy this issue, I've completely reinstalled Steam, therefore, reinstalling HL and CS1.6. This didnt fix the issue, and that file is still missing. I validated my files, and it said they validated successfully, and it didnt download that file. I opted into the Beta, and still dont have this file. I see this occured before (https://github.com/ValveSoftware/halflife/issues/1301), but it seems that when he opted into the beta, it downloaded that file. Reinstalling CS and HL will not download this file, nor validating the files. I have a good feeling this is why my game hangs on desktop and says "Running", but the game never actually launches.

**Comment by kisak-valve** [comment]
There's a good chance engine_amd64.so and filesystem_stdio_amd64.so has never been used with goldsrc / linux and are stray 64 bit libraries that slipped into these 32 bit games.

**Comment by shoober420** [comment]
I should still have a libSteamValidateUserIDTickets_amd64.so though right? Or are you saying all the files that end in “amd64” are not needed on Linux?

**Comment by shoober420** [comment]
This file isnt needed for GoldSrc to run, very odd it shows as a dependency. Closing.
