### ISSUE TITLE
[Request] Creating a list of cvars that are prohibited from sending values to Query Client CVar

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#2581]
I propose to create a list of cvars that will not send values ​​to server requests `svc_sendcvarvalue` and `svc_sendcvarvalue2` - in response, game client can send a `Bad CVAR request` string.

Such a list may include, for example, cvars `rcon_address`, `rcon_port` and `rcon_password`. They must be private, because the remote control mechanism of the game server by the game client implies that the player does not have to be on the controlled server - using the cvars `rcon_address` and `rcon_port`, player can specify the data where rcon commands will be sent. An attacker can take advantage of this and, having lured the victim-admin to his server, obtain the values ​​of the cvars `rcon_address`, `rcon_port` and `rcon_password` via `svc_sendcvarvalue` or `svc_sendcvarvalue2`.

**Comment by SamVanheer** [comment]
I've already reported this on HackerOne with those cvars listed.

@mikela-valve you should add this issue to the private one.

**Comment by afwn90cj93201nixr2e1re** [comment]
@mikela-valve can you also make setinfo buffer lil more than now? Or make some cmd for auto clearing?
For reset to default, coz some server's making some stupid records, then we get info  buffer exceeded blah blah blah, then we must close hame, clear config and start game again.

**Comment by SamVanheer** [comment]
Changing the info buffer size will break this API:
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/common/com_model.h#L315-L349

Same for physics info buffers.

**Comment by GiovaniFerraroTrivelli** [comment]
> 
> 
> @mikela-valve can you also make setinfo buffer lil more than now? Or make some cmd for auto clearing?
> For reset to default, coz some server's making some stupid records, then we get info buffer exceeded blah blah blah, then we must close hame, clear config and start game again.

A command for reset to default userinfo values is a good idea 👍

**Comment by 10th** [comment]
exec clear_si.cfg ;-)

**Comment by afwn90cj93201nixr2e1re** [comment]
and? This do nothing. Coz this doesn't rewrite any setinfo's. It's can just replace some of keys.

**Comment by 2010kohtep** [comment]
Setinfo restorer from one of my project. It would be nice to have something like this officially, I think.

![image](https://user-images.githubusercontent.com/2564175/61183888-8d043080-a64f-11e9-9be5-ecf51c08ccb8.png)

**Comment by mikela-valve** [comment]
@2010kohtep Could you post that as a separate issue for tracking? I'm going to implement something like that but it might take a bit more discussion to finish.

**Comment by 2010kohtep** [comment]
@mikela-valve Sure thing: #2589

**Comment by mikela-valve** [comment]
This should be fixed now in the current beta.

**Comment by Splatt581** [comment]
Fixed, I confirm. Now, in response to requests for these cvars, game client sends string `CVAR is privileged`. Also, the server cannot change values of these cvars via `svc_stufftext` in order to send password to the changed address.

I think that client command `rcon` should also be added to the list of privileged ones, so that the attacker could not control the victim’s server through the victim’s client using `svc_stufftext`.

**Comment by mikela-valve** [comment]
I agree, I'll make `rcon` privileged as well.

**Comment by Splatt581** [comment]
Fixed.
