### ISSUE TITLE
[Suggestion] CS 1.6 Radar

### ISSUE THREAD

**Issue by WhiteFang1319** [ValveSoftware/halflife#2583]
My request is probably the same as #385. Can the radar be modified so that it can be seen clearer like in CS GO and seeing your teammates as well? 
One more suggestion I have is, add the radar in spectator mode too ( player dead ) so that it will help admins to spectate the player from the player's pov

**Comment by SamVanheer** [comment]
#308 already covers improvements to the radar and is still open.

**Comment by kisak-valve** [comment]
Closing in favor of the existing feature request.

**Comment by afwn90cj93201nixr2e1re** [comment]
@kisak-valve maybe we should close old topic's instead new?
