### ISSUE TITLE
[CS] There are no avatars have players

### ISSUE THREAD

**Issue by 10th** [ValveSoftware/halflife#2584]
Quite often I have and other players case:
- 1 player doesn't have an avatar in my scoreboard.
- In my scoreboard, many players do not have their avatars.
- In my scoreboard there is my avatar, but the other player doesn't have my avatar on his scoreboard.
- I don't see my avatar on my scoreboard.

Restarting the client normalizes the display of avatars.

**Comment by CS-PRO1** [comment]
Maybe those are non-steam clients? They usually don't have avatars..

**Comment by SamVanheer** [comment]
Are you playing the beta or the public release?

Also @kisak-valve and @mikela-valve maybe update the [Reporting Issues](https://github.com/ValveSoftware/halflife#reporting-issues) section in the readme to include which branch of the game issues are occurring in to make this easier.

**Comment by 10th** [comment]
It's only about steam clients.
This problem was noticed a few years ago in public releases.
But also occurs today in beta.

**Comment by afwn90cj93201nixr2e1re** [comment]
Check your steam status. It's must be online. Play only on legal server's without multi-protocol modules.

There no problem in CS, maybe some problem's with cdn server's or with steam api.
