### ISSUE TITLE
1280x768 does not show Friend Icon anymore. [Latest beta update]

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2597]
AFAIK this is happening with several resolutions but it was tested on **1280x768**

C a r i t t a ^~^ is on my friend list and his friend icon doesn't appear on Scoreboard tab.

![image](https://user-images.githubusercontent.com/33007491/61506022-c968c100-a9ae-11e9-87dc-77a95269d997.png)

![image](https://user-images.githubusercontent.com/33007491/61505939-8a3a7000-a9ae-11e9-8381-556eccd18ca1.png)

![image](https://user-images.githubusercontent.com/33007491/61505977-a3dbb780-a9ae-11e9-9f11-ac98cf399725.png)

**Comment by oaus** [comment]
The same happens in 1280x768.

**Comment by oaus** [comment]
It occurs in all resolutions.
I tested in: 640x480, 1024x768, 1280x768, 1280x960, 1280x1024.

**Comment by mikela-valve** [comment]
Thanks for the report. I was testing different ways to increase the size of the avatar at lower resolutions without changing the other column sizes and I didn't realize that space was used to show the friend icon. I'll add that space back in.

**Comment by mikela-valve** [comment]
This should be fixed now, let me know if anything else doesn't look correct. Thanks!

**Comment by basuritashka** [comment]
Can confirm this is now fixed, thanks.

**Comment by basuritashka** [comment]
Friend icon is now working but Steam Avatar are not being displayed correctly. (Looks like avatars are being cut up a bit)

640x480
![image](https://user-images.githubusercontent.com/33007491/61508984-6c730800-a9ba-11e9-92f1-92b0e1ceaa10.png)

**Comment by mikela-valve** [comment]
That’s expected currently at 640x480. The issue is that the space available in the row is rectangular but Steam avatars are square and there isn’t enough vertical space in the line at 640x480 to show the entire avatar at a good size, so the options are cutting off part of the avatar like that but having it fill the space well or showing the entire avatar but having it look smaller on-screen. See #2155 for more details.

**Comment by basuritashka** [comment]
Thanks, I will close this then.

**Comment by mikela-valve** [comment]
Thanks, definitely feel free to make a comment on #2155 if you think of ways it could look better.
