### ISSUE TITLE
[Feature request] cl_filetransfercompression

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2607]
Probably everyone here know that when `sv_filetransfercompression` is set to "1", HLDS will create a `.ztmp` file when FastDL is not being used to allow faster loading times and lower file size, but this is only when server has their command set to 1.

There should be a new client command to define if we allow the usage `sv_filetransfercompression` on our client when downloading files.

If `cl_filetransfercompression` is set to 1 and `sv_filetransfercompression` is set to 1, `.ztmp` files will be created when needed, but if `cl_filetransfercompression` is set to 0 and `sv_filetransfercompression` is set to 1 that will get ignored and server will just download all resources needed in their pure state without depending on .ztmp files to being compressed.

`cl_filetransfercompression` default value should be 1.

**Comment by afwn90cj93201nixr2e1re** [comment]
Don't get it at all. One client with 1 gonna connect to the server and ztmp file will be created. So, why we need it?

**Comment by basuritashka** [comment]
> 
> 
> Don't get it at all. One client with 1 gonna connect to the server and ztmp file will be created. So, why we need it?

`sv_filetransfercompression 1` will force you to use/download .ztmp files if FastDL is not enabled, at the moment there is no way to disable that unless server operator set that command to 0.

There is people like me who does not like .ztmp files and there is no client-way to disable that, if we manage to implement `cl_filetransfercompression`, we can allow the usage of `sv_filetransfercompression`

**Comment by afwn90cj93201nixr2e1re** [comment]
Don't get it again.

You don't wanna download packed files from server or what?

**Comment by basuritashka** [comment]
I don't wanna being forced by the server to download `.ztmp` files when they have `sv_filetransfercompression` set to 1, instead, if server operator have that command set to 1 check if user have `cl_filetransfercompression 1` to allow the free usage of `sv_filetransfercompression`, otherwise just download the file in their pure state.

OFFTOPIC: I am sure I am being totally clear on what I am trying to request here, I don't wanna sound rude but if you don't understand English at all you can just PM me and I will try to explain it but you are just causing confusion on several threads because you are not understanding at all what we are trying to post here.

**Comment by basuritashka** [comment]
I will close this for now as I am testing some benchmarks with this.
