### ISSUE TITLE
"Game" label from "Servers" should be improved to fight against fake servers.

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2620]
This is a heavily known hot issue and should be `fixed/improved`, a lot of fake servers are using `Game` label to make players think that there are players on their servers.

Credits to @Rainnegan on this workaround:
`Game`, `Players` and `Map` should be **centered**.

![image](https://user-images.githubusercontent.com/33007491/61744722-fc6fd380-ad65-11e9-967c-e35c9680104b.png)

Reference: #2302

**Comment by SamVanheer** [comment]
I think an argument can be made that mod names should be trimmed so no more than one whitespace character in a row can occur in them.

That would cut down on this a bit but they'd respond by using longer names to pad it out, so perhaps adding an empty fixed size column in-between the `Game` and `Players` column should solve this most effectively. It'll reveal manipulative game names like this.

**Comment by RauliTop** [comment]
Well, if you have a look you see something strange at players number.

But yes, it should be improved/solved that "trick" at client side

**Comment by fe7ch** [comment]
Actually, the all of the listed on the screenshot servers were created by Trojan.Belonard. I don't understand why Valve still let those servers be listed on their master server when it's several months since the research has been posted.

**Comment by hackovh** [comment]
give me banhammer))

**Comment by mikela-valve** [comment]
@basuritashka @SamVanheer I decided to address this by reordering the columns rather than changing the justification or adding empty columns. I moved the Players column to instead be the first column to the left of Servers and left the justification the same. I also unhid the bots column by default (#2481).

**Comment by basuritashka** [comment]
Nice, that is a cool idea!

**Comment by basuritashka** [comment]
@mikela-valve Should be possible to add a Milestone for this one? or is not needed?

**Comment by mikela-valve** [comment]
Thanks, added to the issues missing it.

**Comment by mikela-valve** [comment]
This should now work as I noted above in build 8308.

**Comment by basuritashka** [comment]
@mikela-valve As I said in #2481 this is not working.

**Comment by mikela-valve** [comment]
I just updated 8308 a few moments ago to fix this and #2481 working on macOS/Linux but not on Windows so you may not have the updated build yet. It will be BuildID 4042650 in the Local Files tab of the game info in Steam.

**Comment by basuritashka** [comment]
Makes sense, I will let you know then.

**Comment by Maxi605** [comment]
> I just updated 8308 a few moments ago to fix this and #2481 working on macOS/Linux but not on Windows so you may not have the updated build yet. It will be BuildID 4042650 in the Local Files tab of the game info in Steam.

When i open the 'History' tab it lags out quite a bit, takes time to load the servers (wich aren't much) and doesn't let me leave the History tab untill the servers are loaded

**Comment by basuritashka** [comment]
This is working correctly on latest beta build.

![image](https://user-images.githubusercontent.com/33007491/61847352-5365cd80-ae78-11e9-87e0-0de9fd795186.png)

**Comment by mikela-valve** [comment]
@Maxi605 Can you check that against the current public build to see if it happens there as well?

**Comment by Maxi605** [comment]
> @Maxi605 Can you check that against the current public build to see if it happens there as well?

Happens in both

**Comment by CS-PRO1** [comment]
Sometimes, both History and Favorites tabs are cleared out with no reason. Can you look at that as well please? @mikela-valve

**Comment by SamVanheer** [comment]
@mikela-valve note that this also occurs in the Steam server browser. The default column width for the game name seems to be smaller so the number is cut off and shows as `...` instead to indicate that the name is longer, but it should probably be tracked on whichever issue tracker exists for that Steam feature, in case it isn't already known.

**Comment by Maxi605** [comment]
> @Maxi605 Can you check that against the current public build to see if it happens there as well?

I empty the history tab, still lags out every time it needs to load the servers.

**Comment by basuritashka** [comment]
I can confirm that sometimes Internet tab seems to freeze for no reason when refreshing all servers, you need to scroll down to unfreeze it.

**Comment by mikela-valve** [comment]
@SamVanheer Noted, I'll take a look at the Steam server browser when I have a moment and see if there's anything reasonable to do about it. Closing this as fixed.

@basuritashka @Maxi605 @CS-PRO1 We should open another issue if there isn't one already to see about addressing the server browser clearing or reloading incorrectly.

**Comment by di57inct** [comment]
can we have this after the map name at least instead of in front of the server name? it's really bad right now imo.

**Comment by di57inct** [comment]
@kisak-valve can we have this after the map name at least instead of in front of the server name? it's really bad right now imo. thanks.

**Comment by SamVanheer** [comment]
That'll just make them move the misinformation to map names by calling this:
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/steam/isteamgameserver.h#L94-L97

**Comment by di57inct** [comment]
then after the ping please. anywhere but in the front because it honestly sucks.

**Comment by eat1k** [comment]
I think it's fine as it is.
