### ISSUE TITLE
[CS 1.6] History Tab isn't using UTF-8

### ISSUE THREAD

**Issue by Maxi605** [ValveSoftware/halflife#2625]
On the history tab UTF-8 isn't working. This is in Spanish, my guess i that other languages have this issue too.
![20190725015314_1](https://user-images.githubusercontent.com/40327830/61846898-37195f00-ae7f-11e9-862d-039295dbd38d.jpg)

**Comment by basuritashka** [comment]
This was already reported.

**Comment by eat1k** [comment]
Yeah, in Russian the same issue.

**Comment by kisak-valve** [comment]
Hello @Maxi605, this issue is already being tracked at #2290. Closing as a duplicate.

As a side note, #2290 was unreasonably difficult to find in a search due to the heavy use of screenshots instead of text.

**Comment by RauliTop** [comment]
> As a side note, #2290 was unreasonably difficult to find in a search due to the heavy use of screenshots without also describing the issue with text for Github to parse into keywords.

So, it will be better to close 2290 instead of 2625. No?

**Comment by kisak-valve** [comment]
For clarity, my general preference is to go with the older issue report unless there is a substantially better feedback on duplicate or a Valve dev has shown interest in the duplicate. I could also copy this over to a comment in #2290, but it doesn't really add any insight that would help the issue be resolved.
