### ISSUE TITLE
Two identical names in the same server.

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2630]
This was "already" posted here #2629 but lacks information, so I just decided to create a separate issue.

We managed to repro this in latest beta branch, thanks to @oaus and @FEDERICOMB, this is probably related to `SV_CheckForDuplicateNames`.

Output from Notepad++ (ANSI):
![image](https://user-images.githubusercontent.com/33007491/61970099-139f0300-afaa-11e9-97b7-790cc0c53ec2.png)

1. Connect to a server, change your name to `Github lol`.
2. Open Console and write name `Github lol` (WITHOUT USING NORMAL SPACE BUT ALT + 255)
3. Voila, it should replicate that name easily.

![image](https://user-images.githubusercontent.com/33007491/61970254-65e02400-afaa-11e9-87be-20fb59b333ea.png)

![image](https://user-images.githubusercontent.com/33007491/61970276-7395a980-afaa-11e9-9e8e-facdb58e3a82.png)

**Comment by kisak-valve** [comment]
Hello @basuritashka, there's no value in fragmenting the discussion across more than one issue report, so I've transferred this issue report to https://github.com/ValveSoftware/halflife/issues/2629#issuecomment-515543639.
