### ISSUE TITLE
[CS1.6] Problem with letters (Ő and Ű)

### ISSUE THREAD

**Issue by norbee16** [ValveSoftware/halflife#2637]
I've realized that if either Ő or Ű is written on a HUD, their position will be lower than the other letters, they are working totally fine in chat

![20190727003307_1](https://user-images.githubusercontent.com/40767816/61994935-0c4b2880-b082-11e9-9748-c990229236f5.jpg)

**Comment by Mistrick** [comment]
Same to #2152
And chat not fine, you can see letter is cut from right side. #1315

**Comment by kisak-valve** [comment]
Thanks @Mistrick, closing in favor of the existing issue reports.
