### ISSUE TITLE
[Feature Request] Adding Hungarian language

### ISSUE THREAD

**Issue by norbee16** [ValveSoftware/halflife#2643]
I would like if Hungarian language/translation was added to Counter-Strike 1.6. I guess developer's can not solve this by themselves, so I thought it would be a good idea to import community's translation. I'd take part in it gladly, and I've found other people who would be willing to do so. If the sounds needed to be changed, we can solve those too.

**Comment by kisak-valve** [comment]
Hello @norbee16, I'm going to close this issue report because it's not actionable as it is now. If at some point there are usable suggestions to be used to get a translation started, let me know and I can re-open this issue report.

**Comment by SamVanheer** [comment]
Related to #2311
