### ISSUE TITLE
Minimization Issue.

### ISSUE THREAD

**Issue by Talondronia** [ValveSoftware/halflife#2644]
So, I've just re-installed my copy of Blue-Shift, after getting the sudden urge to play it, it went through the installation process fine, and I can launch the game just fine, keep in mind I'm still using the old retail version, not from steam, although I have to use a CD-key from the internet because I lost mine (somehow).

I can get into the main menu and edit the settings and all of that, but I can't seem to create a new game, or even load a save, if I could even get into the game that is, every time I try to start a new game, the game itself minimizes, and no matter how many times I try to ALT-TAB back into the game it minimizes again, I've been working on getting this game to work for a month now and nothing happens, even my retail version of half-life 1 does this.

I'm confused, what's the problem here?

Is it a W10 thing or just BS+HL1 acting stupid?

(**Apologies if this was already answered**)

**Comment by CS-PRO1** [comment]
Does this happen in latest steam version?

**Comment by Talondronia** [comment]
I don't own it on steam, I use the retail CD versions.

**Comment by CS-PRO1** [comment]
We need to confirm if this happens in latest steam version. Send a list of your PC spec and OS as well

**Comment by SamVanheer** [comment]
Run the game with `-condebug +dev + developer 2` and post the contents of `Half-Life\qconsole.log`.

**Comment by BlackShadow** [comment]
I believe you're using Software mode in Windows 10. Try to change it to OpenGL with 1024x768 resolution at least in video options.

**Comment by Talondronia** [comment]
> I believe you're using Software mode in Windows 10. Try to change it to OpenGL with 1024x768 resolution at least in video options.

after doing that the game won't even launch anymore.

**Comment by Talondronia** [comment]
> We need to confirm if this happens in latest steam version. Send a list of your PC spec and OS as well
> If it was a retail WON version only bug then we have no power over it..

here you go, although I'm not sure how this helps:

Computer Information:
    Manufacturer:  Hewlett-Packard
    Model:  700-406
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD A10-7700K Radeon R7, 10 Compute Cores 4C+6G
    CPU Family:  0x15
    CPU Model:  0x30
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3394 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Windows 10 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  NVIDIA GeForce GTX 660 Ti
    DirectX Driver Name:  nvldumd.dll
    Driver Version:  26.21.14.3086
    DirectX Driver Version:  26.21.14.3086
    Driver Date: 5 22 2019
    OpenGL Version: 4.6
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    DirectX Card: NVIDIA GeForce GTX 660 Ti
    VendorID:  0x10de
    DeviceID:  0x1183
    Revision:  0xa1
    Number of Monitors:  2
    Number of Logical Video Cards:  2
    No SLI or Crossfire Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3360 x 1080
    Primary Display Size: 18.78" x 10.55" (21.54" diag)
                                            47.7cm x 26.8cm (54.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2047 MB
    Supported MSAA Modes:  2x 4x 8x 

Sound card:
    Audio device: Communication Headphones (IDT H

Memory:
    RAM:  12212 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  3902416 Mb
    Largest Free Hard Disk Block:  1151276 Mb
    OS Install Date: Dec 31 1969 (Incorrect)
    Game Controller: None detected
    VR Headset: None detected

**Comment by BlackShadow** [comment]
Are you using latest patch? 1.1.1.0? If you not sure try to apply it. If you still can't enter the game after the patch click Properties and type on Target box after the hl.exe"

-gl -w 800 -h 600

or if it's still doesn't work try:

-d3d -w 800 -h 600

should be like this

"C:\Sierra\Half-Life\hl.exe" -gl -w 800 -h 600

**Comment by Talondronia** [comment]
I think I've just found the patch, although I'm not entirely sure, I'll try
and see if that works.

**Comment by Talondronia** [comment]
> Are you using latest patch? 1.1.1.0? If you not sure try to apply it. If you still can't enter the game after the patch click Properties and type on Target box after the hl.exe"
> 
> -gl -w 800 -h 600
> 
> or if it's still doesn't work try:
> 
> -d3d -w 800 -h 600
> 
> should be like this
> 
> "C:\Sierra\Half-Life\hl.exe" -gl -w 800 -h 600

Figures it just needed patched, thanks!
