### ISSUE TITLE
[CS 1.6/CZ] Game Crashing When Creating a Server "Couldn't Get DLL API From `]" (Linux)

### ISSUE THREAD

**Issue by ArmagdoGaming** [ValveSoftware/halflife#2646]
Using Linux Fedora 30.
As the title says, this problem occurs to me with CS 1.6 and CZ.
CZ: Whenever I try to load a map or play Condition Zero, I get this error.
"LoadLibrary failed on Host Error: Couldn't get DLL API from `]".

CS 1.6: When I try to load a map after installing a mod to add bots to the game, it crashes with no error in console. It worked PERFECTLY with Windows, though.
![20190728225554_1](https://user-images.githubusercontent.com/52860974/62012976-02fab280-b18d-11e9-9311-f33db30378b3.jpg)

**Comment by SamVanheer** [comment]
What mod did you install?

**Comment by ArmagdoGaming** [comment]
> What mod did you install?

For CS 1.6:
All in One 3.2a from Bots United.
"All In One Installer with podbot mm V3B22c, AMX MOD X 1.8.2 (with ChickenMod OE 0.6.5, CSDM 2.1.3c, ATAC 3.0.1b) metamod 1.20 in one zip file! Linux and windows supported!"
http://filebase.bots-united.com/?act=view&id=222

For CZ: Nothing. It's just the base game.

**Comment by SamVanheer** [comment]
Metamod 1.20 is really old, you should be using Metamod-P: http://metamod-p.sourceforge.net/

You should ask them to update their package to include the latest version of everything to avoid compatibility issues.

**Comment by ArmagdoGaming** [comment]
> Metamod 1.20 is really old, you should be using Metamod-P: http://metamod-p.sourceforge.net/
> 
> You should ask them to update their package to include the latest version of everything to avoid compatibility issues.
> 
> For CZ: try verifying files to see if that fixes it.

Thanks! Both of them work perfectly now. CS: CZ seems to be connected to CS 1.6 in someway, since when I tried to verify it's files, it verified files for 1.6, too. Downloaded the files, installed Metamod-P and everything works find now. Thanks.

**Comment by SamVanheer** [comment]
Yes, CZ uses CS 1.6's files as a base.
