### ISSUE TITLE
[CS 1.6] History Tab cause game temporal freeze

### ISSUE THREAD

**Issue by Maxi605** [ValveSoftware/halflife#2649]
After the last beta (and public) the History Tab is causing the game to freeze for 1 to 3 seconds when reloading information, even if there's no servers to show, when it needs to load the information the game freezes.

**Comment by RauliTop** [comment]
When you said public do you mean stable version?

Edit the issue to post the version where the issue is presented.

**Comment by Maxi605** [comment]
> When you said public do you mean stable version?
> 
> Edit the issue to post the version where the issue is presented.

Yes, i mean Stable, the issue is on Stable and Beta since the changes were applied to the stable

**Comment by SamVanheer** [comment]
I can't reproduce this on either branch, try verifying game files and see if that fixes it.

**Comment by CS-PRO1** [comment]
It's not the entire game that freezes. It's just the server browser and it's kinda normal cuz it's loading servers

**Comment by Maxi605** [comment]
> It's not the entire game that freezes. It's just the server browser and it's kinda normal cuz it's loading servers

In my case the game completly freezes, this only started happening after the update

**Comment by SamVanheer** [comment]
Go to `Steam\userdata\<account id>\7\remote` and back up and remove `serverbrowser_hist.vdf`, then see if it still happens. If not, the history/favorites list file is causing it, probably because it's slow to load from disk and/or parse.

Make sure to restore it when you're done so you don't lose your favorites and history.

**Comment by Maxi605** [comment]
> Go to `Steam\userdata\<account id>\7\remote` and back up and remove `serverbrowser_hist.vdf`, then see if it still happens. If not, the history/favorites list file is causing it, probably because it's slow to load from disk and/or parse.
> 
> Make sure to restore it when you're done so you don't lose your favorites and history.

Removing the file seems to fix the issue, i'll re-add all the servers on the new generated file and check on the next upcoming days to see if the issue starts again, thanks.
