### ISSUE TITLE
[CS1.6] What do you think about adding these improvements?

### ISSUE THREAD

**Issue by 666JuL** [ValveSoftware/halflife#2652]
**What do you think about adding these improvements?**

1) add that the player can not place the bomb if it is on top of another player.
2) add the sound Counter Terrorist Win !, after the sound the bomb has been defused!
3) add that while the player is deactivating the bomb it can not jump.
4) add If the bomb has been defused, the model of w_c4.mdl does not disappear, it remains there and at the beginning of the next round it disappears.
5) add that players can not jump and crouch during the freezing period.
6) add that the bomb can not be deactivated through walls or boxes
7) add that players can not place the bomb in boxes, only on the ground, or at a certain distance from the ground so they can not place the bomb in boxes

**Comment by Maxi605** [comment]
2 and 3 already have an issue if i remember correctly.

5 i don't agree, during freezetime the player can jump to drop a weapon to a teammate, i get why you want it changed, but i think it's a gameplay change that isn't necessary.

I agree with the 6, but as it's a gameplay change it may not be accepted.

**Comment by CS-PRO1** [comment]
1. Already reported here: https://github.com/ValveSoftware/halflife/issues/301
2. Already reported here: https://github.com/ValveSoftware/halflife/issues/279
3&5. Unnecessary gameplay changes aren't taken.
4. Not really worth un update for this..
6. Already reported here: https://github.com/ValveSoftware/halflife/issues/147
7. Same as 1

**Comment by perforatorRU** [comment]
> 5\. add that players can not jump and crouch during the freezing period.

On map de_dust2 player can set fps_max 2 and do DoubleDuck for abuse his place and timing.
This is bug and need be fixed!
Video: https://www.youtube.com/watch?v=L0bLuOdzXV8

**Comment by CS-PRO1** [comment]
@perforatorRU Report that as a separate issue. It'll get more chance of being fixed.

**Comment by wilianmaique** [comment]
There is really still this bug., Suppose you are inside the server, there you go and add any plugin that contains models / resources, you upload on the server and fastdownload. When you change the map to update the download of new files are slow, to fix I have to quit the game and enter the server again so the download will get faster.

sorry for my bad english

**Comment by CS-PRO1** [comment]
I see we discussed it enough to be closed. Everything is duplicated/won't change stuff @kisak-valve

**Comment by kisak-valve** [comment]
Hello @666JuL, in general, multi-issue issue reports is bad for any issue tracker. If you have an issue that isn't already being tracked in their own issue report, please open a new issue report that only focuses on that one topic so that it can be discussed separately. 

Closing in favor of the existing issue reports.
