### ISSUE TITLE
MOTD Memory

### ISSUE THREAD

**Issue by JohanCorn** [ValveSoftware/halflife#2675]
The problem is...

If you create a page on your own website for ex. example.com and you set the contet like "A".
Than you open this link in a MOTD it displays "A"
You close the MOTD and set the contet to "B".
Than you reopen the MOTD with the same link it displays "A" instead of "B"

If the client want to see the true data from webserver he should right click and press reload.
It can fix the problem but it is not a great way to do.

Is it a bug or what can I do to remove the stored content from MOTD to display the correct one?

**Comment by SamVanheer** [comment]
That's how browsers work. Until you refresh the page it will just show what the browser has loaded. The VGUI2 MOTD is using CEF1, which is the earlier version of the Chromium framework that Chrome and Edge use.

**Comment by JohanCorn** [comment]
I didn't check this but probably this can solve my problem.

So...
After exaple.com loaded I send an ajax (jquery) request to example.com/post and in the response I overwrite the body of example.com with the returned content.

What do you think @SamVanheer ?

**Comment by SamVanheer** [comment]
That might work, it looks like it supports JavaScript execution but it might be limited in some ways since CEF1 is fairly old, so it likely won't support newer JS.

**Comment by JohanCorn** [comment]
Unfortunetely the JS doesn't work, BUT header tags can fix the problem. So if anyone else want to "remove" the cache memory, just use this tags: (I set them in php)

header("Cache-Control: no-cache, must-revalidate");
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");

I'm closing this one. Thank you @SamVanheer again.
