### ISSUE TITLE
Hearing pain sound when not receiving damage.

### ISSUE THREAD

**Issue by 4D1G06** [ValveSoftware/halflife#2678]
I've found a glitch (**well supposedly**) in Counter-Strike, it happens when jumping off a ledge. It's so rare, as if it's frame-perfect. 
PS: This happens only in multiplayer, I never noticed this on a local game. At least as of now.

**Comment by kisak-valve** [comment]
Hello @4D1G06, this reads like this issue being tracked at #2201. Closing in favor of the existing issue report.
