### ISSUE TITLE
[СS 1.6] Mоuse lоcked aftеr аlt + tаb

### ISSUE THREAD

**Issue by karaul0v** [ValveSoftware/halflife#2685]
https://github.com/ValveSoftware/halflife/issues/2116#issuecomment-476413890

problem is not solved but issue closed :(

**Comment by CS-PRO1** [comment]
This has already been discussed at https://github.com/ValveSoftware/halflife/issues/2635 https://github.com/ValveSoftware/halflife/issues/20
Duplicating issues is not allowed.

**Comment by kisak-valve** [comment]
Closing as a duplicate.

As a side note, the issue report in question is not closed as indicated at the top left of the issue report.
