### ISSUE TITLE
[CS] ammo buying spawns visible ammo box/magazines

### ISSUE THREAD

**Issue by CS-PRO1** [ValveSoftware/halflife#2691]
Simply load up CS 1.6 and buy an M3 or XM1014 and start buying ammo for them, you'll be able to see a visible shotgun ammo box spawning at your position. It's better visible when looking down. This only happens in 1.6 as I tested it in CZ and found nothing..
[Video proof](https://youtu.be/SJn-d8zbEYI)
Update: In current public build most weapons show this behavior.

**Comment by SamVanheer** [comment]
That's how buying ammo works. It spawns an ammo entity that is made to touch you automatically to give it to you. You'll see this in Half-Life as well when using impulse 101.

Both use `GiveNamedItem`:
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/dlls/player.cpp#L3322-L3339

It should be easy to fix by setting `pent->v.effects |= EF_NODRAW;` after calling `DispatchSpawn`.

**Comment by CS-PRO1** [comment]
I know that, but in the beta something happened that made the ammo box go fully visible..

**Comment by afwn90cj93201nixr2e1re** [comment]
> It should be easy to fix by setting pent->v.effects |= EF_NODRAW; after calling DispatchSpawn.

**Comment by sjain882** [comment]
Note that the shotgun ammo was always visible.

**Comment by CS-PRO1** [comment]
No it wasn't, I tried several builds from 2013 and 2011 as well as CS 1.4 and none had a visible ammo box spawning..

**Comment by tschumann** [comment]
I think it needs to be visible to that manually placed ammo entities show up (like in the training room for example, where the ammo entities are definitely visible).

**Comment by CS-PRO1** [comment]
That's a completely different thing. Buying one shouldn't make it visible as older versions handled it correctly

**Comment by CS-PRO1** [comment]
@mikela-valve I just realized, this also happens to all weapons now in current public build for some reason. Can you look into it please?

**Comment by mikela-valve** [comment]
Hi @CS-PRO1, this should be fixed in the current beta version 8308.

**Comment by CS-PRO1** [comment]
@mikela-valve Thanks a lot, I can confirm the fix. Closing the issue.. ^^
