### ISSUE TITLE
[HL] Fatal Error

### ISSUE THREAD

**Issue by Matthaiks** [ValveSoftware/halflife#270]
Create server, disconnect, load saved game and Half-Life will crash with message: Entity is not a player.

Specs:
Exe version 1.1.2.2/Stdio (valve)
Exe build: 14:30:42 Feb 15 2013 (5958)

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3214 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Windows 7 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  ATI Radeon HD 5700 Series

```
DirectX Driver Name:  aticfx32.dll
Driver Version:  9.12.0.0
DirectX Driver Version:  8.17.10.1172
Driver Date: 19 Dec 2012
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
DirectX Card: ATI Radeon HD 5700 Series
VendorID:  0x1002
DeviceID:  0x68b8
Number of Monitors:  1
Number of Logical Video Cards:  1
No SLI or Crossfire Detected
Primary Display Resolution:  1920 x 1200
Desktop Resolution: 1920 x 1200
Primary Display Size: 26.65" x 16.65"  (31.42" diag)
                                        67.7cm x 42.3cm  (79.8cm diag)
Primary Bus Type Not Detected
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 
```

Sound card:
    Audio device: Glosniki (ASUS Xonar DS Audio D

Memory:
    RAM:  8191 Mb

**Comment by FrenchMan** [comment]
While this issue is supposed to be fixed for Half-Life itself, it is still pretty valid for third-party mods.

**Comment by RiverHornet3209** [comment]
This issue still affects third-party mods in 2026. 
The issue seems to be caused by the engine not setting `maxplayers` to 1 on save load in third-party mods.
The workaround for this issue is entering `maxplayers 1` in the console before loading a saved game.
