### ISSUE TITLE
[CS 1.6] High refresh rate breaks recoil

### ISSUE THREAD

**Issue by djdallmann** [ValveSoftware/halflife#2700]
Why does having high refresh rate make the recoil less predictable, with below 100hz you can tap shoot, spray and the bullets stay consistent any really high refresh rate makes spraying less consistent and the same for tapping bullets.

**Comment by kisak-valve** [comment]
Hello @djdallmann, physics being influenced by framerate in counter-strike is already being tracked at #403. Closing in favor of the existing issue report.

**Comment by djdallmann** [comment]
No problem sorry for duplicate
