### ISSUE TITLE
remove 640x480 800x600 resolution

### ISSUE THREAD

**Issue by hackovh** [ValveSoftware/halflife#2701]
you spoil people's eyes

**Comment by TezH1337** [comment]
absolutely right

**Comment by afwn90cj93201nixr2e1re** [comment]
Не, ну реально, кто играет на этих разрешениях? Там фов x y вообще не в попад нифига.
На 640x480 это меньше заметно чем на 640x860, но все же есть.

**Comment by tschumann** [comment]
Leave it. I use it for development in a Linux VM.

**Comment by CS-PRO1** [comment]
I really don't see a point in dropping them

**Comment by BlackShadow** [comment]
It's a matter of choice and shouldn't be touched.

**Comment by SamVanheer** [comment]
The engine lists all resolutions supported by your primary display, there is no built-in list to modify.
