### ISSUE TITLE
CSCZ Deleted Scenes banner

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/halflife#2704]
Can you add banner in new library for CSCZ deleted scenes?
CSCZ has both banner and logo, but not CSCZ DS

**Comment by Koterminus** [comment]
@kisak-valve An anonymous hero at Valve just added a new library banner and logo to CSCZ:DS (as seen [here](https://steamdb.info/app/100/history/?changeid=6899564) so this issue can now be closed.

**Comment by Koterminus** [comment]
@kisak-valve An anonymous hero at Valve just added a new library banner and logo to CSCZ:DS (as seen [here](https://steamdb.info/app/100/history/?changeid=6899564)) so this issue can now be closed.

**Comment by kisak-valve** [comment]
Thanks @Koterminus, closing.
