### ISSUE TITLE
[GoldSrc] Implement Sound Resampler Option

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/halflife#2709]
Similar to Quakespasm (sndspeed and snd_mixspeed), please add those options to GoldSrc to keep the kHz true to the original audio files (22kHz), if ones sound card doesn't support true 22Khz playback.

My sound card (ASUS Xonar Essence STX) only supports 32-192kHz, meaning GoldSrc 22kHz sound files playback too fast if one has ALSA resampling disabled on their system.

Please allow the user to select the desired resample rate if the sound card they have doesn't support 22kHz, but also allowing true 22Khz playback, which is what is currently done, if their sound card supports 22kHz.

https://github.com/ValveSoftware/halflife/issues/1505
https://github.com/ValveSoftware/steam-for-linux/issues/3335
https://github.com/ValveSoftware/halflife/issues/1917

Commit that brought about this issue thread, that I've been meaning to post.

https://github.com/kcat/openal-soft/issues/346

My current "asound.conf" file in the "/etc/" directory to disable ALSA resampling system wide.

pcm.STX {
type hw
card "STX"
}

ctl.!default {
type hw
card "STX"
}

pcm.!default {
type plug
slave {
pcm "STX"
rate "unchanged"
}
}

**Comment by kisak-valve** [comment]
Hello @shoober420, this is the same issue you reported in #1917. Feel free to add your recent findings to the existing issue report.

Closing as a duplicate.
