### ISSUE TITLE
Client max speed (cl_forwardspeed/backspd/sidespd) should be handled server sidedly and be removed from the client.

### ISSUE THREAD

**Issue by hellmoss** [ValveSoftware/halflife#2710]
[CS 1.6]

My amxx mod allows higher speeds than 400 and in certain cases needs to manipulate how fast the player can go in order to reach the desired outcome. Is there any good reason for this to be client controlled? (sv_maxspeed becomes relevant after 400)

**Comment by kisak-valve** [comment]
Hello @hellmoss, this feature request is already being tracked at #412. Closing in favor of the existing issue report.
