### ISSUE TITLE
Cs 1.6 Old models are  broken!. 

### ISSUE THREAD

**Issue by dimi456** [ValveSoftware/halflife#2716]
Mostly Leet model and GIGN . Watch this video :) 
https://youtu.be/6ZlCPgxUw_4

**Comment by Maxi605** [comment]
Probably related to #2154

**Comment by afwn90cj93201nixr2e1re** [comment]
that's totally duplicate :/ @kisak-valve

**Comment by CS-PRO1** [comment]
Most certainly a dup.

**Comment by kisak-valve** [comment]
Closing in favor of #2154.
