### ISSUE TITLE
[TFC] Connecting to passworded servers

### ISSUE THREAD

**Issue by pizzahut2** [ValveSoftware/halflife#2718]
Didn't have an issue myself, maybe because I've opted into the beta.

-X-:
	I think there might be some [...] issues after the tfc oct 8 update
	servers with a pw are no longer accessible it seems
-X-:
	i have digged into this, it gives an error
	"Info string length exceeded"
	the solution is to type in console : setinfo model ""

Mr. Loyd:
	ya it looks like it does not work =
	had to do that setinfo model

pizzahut:
	which server did you try?

Mr. Loyd:
	420
	wasn't letting me connect
	when i was doing it
	putting the password*

**Comment by mikela-valve** [comment]
Both beta and public should be the same at the moment, so possibly their client userinfo is significantly longer for some reason? It might be useful for them to dump their infostring with `setinfo` to see if there are any fields that look weirdly long or different.

**Comment by Maxi605** [comment]
"Info String Length Exceeded" is send when the client can't store any more info, when you connect to a passworded server i'll try to set the info "password" with the value you set, if it can't, i'll throw the error you encounter, clear your info of any useless stuff or try with a clean install and try again.

**Comment by basuritashka** [comment]
Probably we should extend that limit.

#2361

**Comment by Maxi605** [comment]
> Probably we should extend that limit.
> 
> #2361

With the recent and probably future additions of more info strings, seems like a wise choice.

**Comment by SamVanheer** [comment]
Changing the limit will break mods:
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/common/com_model.h#L315
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/pm_shared/pm_info.h#L22

**Comment by pizzahut2** [comment]
@mikela-valve This is from -X- , mind that since he blanked the model info once, the issue didn't re-appear. https://paste.esclan.net/raw/uyisehuvif

**Comment by pizzahut2** [comment]
Closing this, looks like it's a one time issue which only happened to very few people, plus there's #2361 open.
