### ISSUE TITLE
[Counter-Strike] Hitbox Issue

### ISSUE THREAD

**Issue by BlackShadow** [ValveSoftware/halflife#2721]
Hi,

There's a hitbox problem with Counter-Strike player models.

The problem is hitbox on the Neck is too big it covers the head and bullets register to back instead head.

Here's an example:

![ezgif-4-d30463773f9c](https://user-images.githubusercontent.com/30868395/66458774-3c4c7a00-ea7c-11e9-9826-efe03b1f2ad1.gif)

As it seems in the picture back hitbox is bigger than head hitbox, resulting blocking the half of the head hitbox.

![cats](https://user-images.githubusercontent.com/30868395/66460456-a31f6280-ea7f-11e9-8f87-2723a1629bdd.jpg)

This issue can be fixed by lowering the Neck hitbox and expanding Head hitbox to the neck. Just like 
in CSGO. (They actually added head hitbox to the neck, but i don't think that's how it works in GoldSRC)

https://blog.counter-strike.net/index.php/2018/05/20414/

I'd like to post this with fix proposed but sadly, i don't have too much knowledge about hitboxes.

**Comment by BlackShadow** [comment]
Closing as duplicate

**Comment by 2020karaulov2020** [comment]
@BlackShadow duplicate?
