### ISSUE TITLE
[HL/OPFOR/BSHIFT] There's no option to disconnect from Singleplayer

### ISSUE THREAD

**Issue by BlackShadow** [ValveSoftware/halflife#2722]
When player enters the singleplayer mode, there's no option to disconnect from it. Player either can quit to desktop or create a new singleplayer game. Only way to disconnect from singleplayer without quitting the game is typing "disconnect" to the console.

This may be confusing for new players.

Disconnect option can be easily added editing this string on GameMenu.res

{
		"label" "#GameUI_GameMenu_Disconnect"
		"command" "Disconnect"
		"OnlyInGame" "1"
		"notsingle" "0"
}

![20191009105000_1](https://user-images.githubusercontent.com/30868395/66461882-9c461f00-ea82-11e9-970b-86e91c97e960.jpg)

**Comment by CS-PRO1** [comment]
For SP I'd rename it to something else as disconnect fits MP servers better..

**Comment by BlackShadow** [comment]
> For SP I'd rename it to something else as disconnect fits MP servers better..

It's a little bit hastle to do that, you need to add new row to menu, sort menu for new label. I'd say save the hastle and go with disconnect.

**Comment by hashnimmo** [comment]
What's the reason to have a disconnect option from single player? Add Find/Create Server options to immediately go online instead if possible.

**Comment by BlackShadow** [comment]
> What's the reason to have a disconnect option from single player? Add Find/Create Server options to immediately go online instead if possible.

Simplistic and consistency with other titles. Like in CZ:DS

![image](https://user-images.githubusercontent.com/30868395/66639980-a6058900-ec20-11e9-8ad9-b5b07df205d6.png)

**Comment by BlackShadow** [comment]
The method you're suggesting may broke mods that not using custom GameMenu.res and without Multiplayer support.

**Comment by BlackShadow** [comment]
The method you're suggesting may broke the mods. Not every mod has custom GameMenu.res and most of them doesn't even have Multiplayer. It will be odd to see LAN options on a mod without Multiplayer. Infact i don't see a reason to stress about this issue any further because literally both methods does the same thing but my method is much better when you put the odds.

**Comment by mikela-valve** [comment]
Sorry, missed updating this issue before. This is in the current release.
