### ISSUE TITLE
[CS 1.6] Matchmaking system.

### ISSUE THREAD

**Issue by Morritz** [ValveSoftware/halflife#2723]
![pobrany plik (1)](https://user-images.githubusercontent.com/12800230/66493791-ef39c980-eab6-11e9-8a22-703995708a3e.png)
Many people suggested this feature already, but I am down to create this kind of system on my own, because it seems that Valve employees are not very focused on old CS. I just need help in integrating vgui panels with game coordinator backend (It might not be possible without source code or SDK.) Thanks in advance.

**Comment by kisak-valve** [comment]
Hello @Morritz, this feature request is already being tracked at #691. Closing as a duplicate.
