### ISSUE TITLE
[Half-Life/OpFor/BShift] Adding a new CVar for Software mode style liquid in OpenGL

### ISSUE THREAD

**Issue by TwelveEyes** [ValveSoftware/halflife#2724]
I've always preferred the Software mode style liquid effect to the hardware accelerated D3D/OpenGl texture warping liquid effect. I think it would be nice to have a CVar to toggle the default OpenGL liquid effect with the Software mode one. Something like: "gl_software_liquid" as the toggle, for example.

Example of the Software liquid effect: [https://www.youtube.com/watch?v=DHgtWODyUUo](url)

**Comment by LucesEnBabel** [comment]
Duplicate of https://github.com/ValveSoftware/halflife/issues/2165

**Comment by kisak-valve** [comment]
Closing as a duplicate of #2165.
