### ISSUE TITLE
Game crash when viewing demo files

### ISSUE THREAD

**Issue by 2010kohtep** [ValveSoftware/halflife#2734]
The game can crash when you try to play dem files using the ```playdemo``` and ```viewdemo``` commands. A crash occurs when the scoreboard is displayed on the screen. Apparently, a crash occurs only when viewing dems that were recorded on game servers with an outdated build.

Having analyzed the problem, I found that when viewing dems recorded on newest game build, the function ```CCSClientScoreBoardDialog::InitScoreboardSections``` is called, while for older versions, the function execution does not occur. For this reason, such variables as ```CCSClientScoreBoardDialog::m_pShortHeaders``` are not initialized, which leads to crash.

The crash itself was found in the ```CCSClientScoreBoardDialog::UpdateHeaders``` function when trying to get the value of the ```CCSClientScoreBoardDialog::m_pShortHeaders``` variable at the beginning of the function. Since this variable is not initialized, we get a pointer to 0 instead of correct ```cvar_t``` pointer.

Apparently, the crash occurs due to the fact that the problematic dem files do not contain UserMsg call - ```InitHUD```, which performs the necessary initializations when starting the dem view. Demos that do not crash contain this call.

I believe that this problem has existed for a very long time, but due to recent innovations, it began to manifest itself in the form of a game crash. Earlier, I often noticed that the opening scoreboard when viewing old demos looked distorted - it lacked a list of players and any other data:

![image](https://user-images.githubusercontent.com/2564175/66701222-9494ad80-ed02-11e9-9bb2-165d89fff296.png)

I think that HUD initialization, bypassing UserMsg, is appropriate if we playing the dem file. This would fix two problems at once - scoreboard distortion and crash of the game when viewing old dem files.

**Comment by afwn90cj93201nixr2e1re** [comment]
without demo: https://github.com/ValveSoftware/halflife/issues/2686#issuecomment-526933951

sometimes SVC_NEWMSG not trigger properly, so...


https://github.com/ValveSoftware/halflife/issues/2725#issuecomment-540222689

**Comment by RauliTop** [comment]
@mikela-valve priority bugfix.

Finally, we will see the scoreboard well at demos.

**Comment by Maxi605** [comment]
If you connect to a server and watch the demo it'll work correctly.

**Comment by uniarch** [comment]
@mikela-valve 

https://volafile.org/r/11w8xdgt8 - corrupted demo example

Please review this asap

**Comment by talnaim2323** [comment]
Yes I noticed that too

"There has been a problem since the last update

when i try watch demo viewdemo/playdemo

after few sec game crash
this happens in most of the files I try to see

i check if the problem with file , i try download counter strike non steam
and its work fine excluding few things like voice player , scoreboard..

so its problem with new update"

i hope valve fix that with update or publish file fix that.

**Comment by satnatantas** [comment]
For anybody in a hurry, here are previous executables for Windows:
https://filebin.net/ljw29q0o01q78k65
Always check the signatures before using.

**Comment by talnaim2323** [comment]
> For anybody in a hurry, here are previous executables for Windows:
> https://filebin.net/ljw29q0o01q78k65
> Always check the signatures before using executable files from unknown source.

im dont understand what i need to do with files....

**Comment by kisak-valve** [comment]
Hello @satnatantas, the link you posted is legally problematic and has been removed.

**Comment by Maxi605** [comment]
> For anybody in a hurry, here are previous executables for Windows:
> `<Link removed by moderator>`
> Always check the signatures before using executable files from unknown source.

You can just  connect to a server and then watch the demo, no need to modify any files untill is fixed.

**Comment by satnatantas** [comment]
@Maxi605 oh, I see it now. The files I posted are from previous update when no such bug existed.

**Comment by RauliTop** [comment]
> @Maxi605 oh, I see it now. The files I posted are from previous update when no such bug existed.

The bug was always there.
Difference is that now is causing a crash.

**Comment by mikela-valve** [comment]
Hi all, this should be fixed now in the current beta. Based on the suggestion from @2010kohtep I added an `InitHUD` message that is artificially sent when starting a demo through `viewdemo` or `playdemo`.

**Comment by talnaim2323** [comment]
> Hi all, this should be fixed now in the current beta. Based on the suggestion from @2010kohtep I added an `InitHUD` message that is artificially sent when starting a demo through `viewdemo` or `playdemo`.

so only on beta version its ok ?
when u fix that on normal ?

its matter ? if im use beta or not ?

**Comment by mikela-valve** [comment]
@talnaim2323 I'll be updating the public version soon with this and other fixes from https://github.com/ValveSoftware/halflife/milestone/37. I'm just waiting for some additional information on another issue to determine if there are any other changes going into it.

**Comment by talnaim2323** [comment]
> @talnaim2323 I'll be updating the public version soon with this and other fixes from https://github.com/ValveSoftware/halflife/milestone/37. I'm just waiting for some additional information on another issue to determine if there are any other changes going into it.

oh ok i understand u , so when u take all probelm and fix them
u update in public version

nice and ty for fast answer xD

if i found problems i post here

i hope u fix rates / shooting
i remmber before update of 2017
The shooting was better and more accurate

**Comment by mikela-valve** [comment]
Closing as fixed.

**Comment by WestBoy15** [comment]
Hi. The viewdemo still not work in Condition Zero.

**Comment by afwn90cj93201nixr2e1re** [comment]
Just call mikela thru @
