### ISSUE TITLE
[CS 1.6] Gameplay changes

### ISSUE THREAD

**Issue by ptrBR** [ValveSoftware/halflife#2736]
I have noticed some changes in the game's gamplay in recent years. For example, it is now possible to shoot while walking, or even in some cases jumping too. The movement is very strange, did anyone notice that too?

**Comment by basuritashka** [comment]
Since ever you were able to shoot while walking or jumping, not sure what are u really trying to explain but those mechanics have been in the game since years.

**Comment by BlackShadow** [comment]
Valve doesn't change gameplay for older games. What you've been saying was always possible.

**Comment by Maxi605** [comment]
> Valve doesn't change gameplay for older games. What you've been saying was always possible.

Well, when they fix the hitboxes it would be a gameplay change technically

**Comment by BlackShadow** [comment]
> > Valve doesn't change gameplay for older games. What you've been saying was always possible.
> 
> Well, when they fix the hitboxes it would be a gameplay change technically

Hitbox is not really a gameplay thing. Like changing fire rate of a weapon or a weapon's recoil, etc... is  more like gameplay.

**Comment by CS-PRO1** [comment]
It's always been able to shoot while walking or jumping since the invention of the first person genre wtf r u talking about xd
@kisak-valve safe to close..
