### ISSUE TITLE
half life 1 fails to load: libpgp-error

### ISSUE THREAD

**Issue by Gibbz** [ValveSoftware/halflife#2740]
#### Your system information

* Steam client version:
dec 9 2016
* Distribution (e.g. Ubuntu): 
ubuntu 16.04
* Opted into Steam client beta?: [Yes/No] 
no
* Have you checked for system updates?: [Yes/No]
no

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1.  Install half life 1
2. load steam
3. the error in the commandline:
Error:libgpg-error.so.0: cannot open shared object file: No such file or directory

**Comment by kisak-valve** [comment]
Hello @Gibbz, Steam's handling of the Steam runtime changed to prefer host libraries over the Steam runtime variants, which may have resolved your original issue. Are you still experiencing this issue on an up to date system?

As for the missing library, that should be provided by the Steam runtime, which wasn't in use when you tried to run the game from a terminal. You should be able to try to run the game with a similar environment as Steam by calling run.sh with the game's launcher script, something like `<steam install>/ubuntu12_32/steam-runtime/run.sh ./hl.sh -steam`

**Comment by kisak-valve** [comment]
Closing pending feedback.
