### ISSUE TITLE
+showscore causing the game to crash when playing demos?

### ISSUE THREAD

**Issue by rawe1337** [ValveSoftware/halflife#2745]
Hello, recently with the last update we found an issue that it's a problem for the KZ community, the game crashes when someone on the demo presses +showscore, making the demo unplayable.

However, if you play a demo before that and let it finish, when you play the "bugged" demo, it works. I don't really know what's causing that problem, but it has something to do with showscores.

**Comment by kisak-valve** [comment]
Hello @rawe1337, this reads like #2734 which was recently resolved. Please clarify what game you're seeing this issue with and the client version used.

**Comment by rawe1337** [comment]
I was talking about 1.6, my bad, seems it was indeed fixed with the latest update you guys posted, and not because I played a demo earlier, thank you very much!

**Comment by kisak-valve** [comment]
Closing as a duplicate.

**Comment by rawe1337** [comment]
How can I get in contact with you? @kisak-valve
