### ISSUE TITLE
CS 1.6 Installation Help Needed

### ISSUE THREAD

**Issue by OnePointSixIzLiFE** [ValveSoftware/halflife#2746]
System info : Win 10 Home 64-bit, Gpu: nvidia 970m , Drivers are all updated

Problem : Steam does not install the latest client instead install an older version

Solution tried: Steam reinstall twice, game redownload/reinstall , tried different pc, cleared download cache, download region, validate game cache files 

Current game version: 24 June 2019
Latest release : 8 Oct 2019 (confirmed for my region)

The problem persists for both PUBLIC AND BETA branch of 1.6. 

You can replicate the problem by reinstalling CS 1.6 but PLEASE take BACKUP FIRST ( FOR EVERY STEAM FOLDER ) !!!!!!

Any Help would be appreciated

I did post it over at steam hub as well , ( in case any1 wanna help :) )
https://steamcommunity.com/app/10/discussions/0/1694969361083978913/

![1](https://user-images.githubusercontent.com/57029233/67615404-e1579a00-f780-11e9-91ea-69934219ef2f.PNG)

**Comment by basuritashka** [comment]
That is the latest release, just because the `Exe Build` date from a few months ago does not mean that it is not the actual one.

**Comment by OnePointSixIzLiFE** [comment]
I am a bit confused , since my brother plays the same game and has different build date after his game updated and the way game looks is also different. 

Also the latest add mp_infinite_ammo and other cvars are not availabe , hence i speculated that the game is not updated.

Please help me understand this.

**Comment by RauliTop** [comment]
> Also the latest add mp_infinite_ammo and other cvars are not availabe , hence i speculated that the game is not updated.

Where are not available??

That is your client version, don't confuse to server version.

**Comment by OnePointSixIzLiFE** [comment]
Ty 4 explaining 

It was a mistake on my part 
apparently  those cvars are only accessible after joining the server as well as the cvarlist 

And the problem for beta branch is resolved as well since both public and beta branch are at same build version.

@RauliTop @basuritashka @kisak-valve Thank You for helping immediately :)
The issue is resolved :)
