### ISSUE TITLE
cl_autowepswitch not working in Half-Life 1

### ISSUE THREAD

**Issue by TheStormN** [ValveSoftware/halflife#2749]
The Half-Life 1 update from 08.10.2019 added the long awaited client command "cl_autowepswitch" which for example CS had for... lets say forever. Anyway it is buggy, randomly stops working, especially after you are killed and respawn. The new update from this Friday does not fix it... Could you please fix it?

**Comment by afwn90cj93201nixr2e1re** [comment]
@mikela-valve can you also fix something?
Add check is there IN_Attack flag - then skip switching, that's really anoying when i walking with knife and c4 dropped out at ground.

**Comment by TheStormN** [comment]
@mikela-valve Anything new on this? I can confirm that after a respawn the command does not have any effect.

**Comment by mikela-valve** [comment]
Hi @TheStormN, this should be fixed in the current beta version 8308.

**Comment by afwn90cj93201nixr2e1re** [comment]
lol

**Comment by afwn90cj93201nixr2e1re** [comment]
Did you add in_attack condition?
Coz it's really sometimes became useless to picking up some weapons when you shooting.

**Comment by TheStormN** [comment]
@mikela-valve Thank you, it is fixed!

Just a note - I would've prefer to be spawn holding the pistol, instead of the crowbar. :)

**Comment by mikela-valve** [comment]
@TheStormN That's a good point, I noticed that just now as well when I was checking something. I'll change the spawn behaviour specifically to ignore cl_autowepswitch for the initial weapon loadout.

@afwn90cj93201nixr2e1re That sounds fine to me, I'll add another cvar `cl_autowepswitchinattack` to toggle that.

**Comment by afwn90cj93201nixr2e1re** [comment]
Damn, thanks for response.

**Comment by afwn90cj93201nixr2e1re** [comment]
You know what?? Possible it's gonna be better if you keep using same cavr, but extend values, 1.0 - always, 2.p - if not in attack something like that.

**Comment by mikela-valve** [comment]
I thought about that but didn't want to make that cvar confusing. 2 is actually already in use in DMC to mean auto-swap if the weapon is better (DMC also has 1 to signify always auto-swap).

**Comment by afwn90cj93201nixr2e1re** [comment]
Oh, ok, that's your choice. Also acceptable. Thanks.

**Comment by mikela-valve** [comment]
Actually, `cl_autowepswitch` is part of userinfo and anything else setting up player state also needs to be, so it's probably better to go with extending `cl_autowepswitch`. Since DMC has its own special logic already I'm not planning to change it so everything else will just treat `2` as switch if not attacking.

**Comment by afwn90cj93201nixr2e1re** [comment]
x D, i forgot about that.

**Comment by mikela-valve** [comment]
The beta branch is updated for HL1/HLDS and CS for the above changes.

**Comment by TheStormN** [comment]
@mikela-valve Once again, it does not work after respawn...

**Comment by mikela-valve** [comment]
@TheStormN Could you try uninstalling/reinstalling and double-checking that? I just ran through a few tests locally in HL1 with `cl_autowepswitch` 0 and 1 and each time it was still respected after respawn. Just to be sure I switched back to the crowbar for each test to ensure other weapons would have higher weight and each time it either switched or didn't switch as appropriate.

**Comment by TheStormN** [comment]
@mikela-valve Ok, I've used `verify integrity of game files` and now it is working as expected. Sorry for the false positive and thank you for the good work! :)

**Comment by mikela-valve** [comment]
Thanks @TheStormN! Closing as fixed.
