### ISSUE TITLE
[CS 1.6] Server Domain Address Lookup

### ISSUE THREAD

**Issue by hashnimmo** [ValveSoftware/halflife#2750]
Is it possible to lookup for the newest IP attached to a server with domain address each time the server browser is refreshed? It only lookup for the first time and keep that IP forever until the domain address is re-added manually to the server browser. I think the issue is that once a domain address is added to the server browser, it saves as an IP address in the servers file.

Perhaps this is an entire game engine issue.

**Comment by kisak-valve** [comment]
Hello @hashnimmo, this request is already being tracked at #193 / #823. Closing as a duplicate.
