### ISSUE TITLE
[CS 1.6] You can't type while crouching anymore

### ISSUE THREAD

**Issue by Maxi605** [ValveSoftware/halflife#2754]
In older versions of the game you were able to write on chat while crouched, now, if you try, you can't.
This is pretty a pretty useful option for people who don't have microphone and need to give information to the team via say_team while they're holding a position (crouching) and for a few other circumstances.

**Comment by kisak-valve** [comment]
Hello @Maxi605, if this is a regression, than this report contradicts #1065. Please clarify what the last known good client version was.

**Comment by Maxi605** [comment]
> Hello @Maxi605, if this is a regression, than this report contradicts #1065. Please clarify what the last known good client version was.

Hello, i tried it on this client,
Exe build: 10:56:59 Oct  3 2005 (3266)

**Comment by kisak-valve** [comment]
Thanks for clarifying, closing in favor of the existing feature request.
