### ISSUE TITLE
[CS] Redirect suggestion 

### ISSUE THREAD

**Issue by kraasimir** [ValveSoftware/halflife#2756]
I've been thinking about this idea for a long time. I think it's great that you have blocked the connect, bind ... commands, but I come to propose a suggestion. That a new option is implemented that can only be redirected in terms of the port, that is, if I connect to xx.xxx.xx.xxx:27015 when using “redirect 27040” the player is sent to xx.xxx.xx.xxx : 27040. This is a solution for the communities.

**Comment by kisak-valve** [comment]
Hello @kraasimir, the logical next part of this is that the bad actor runs a proxy server on port 27040 to go to any other ip address and that re-opens the long standing issue which was there before, but with more latency to the player.
