### ISSUE TITLE
[CS 1.6] Can't see players Steam Picture on unprotected servers

### ISSUE THREAD

**Issue by Maxi605** [ValveSoftware/halflife#2759]
If the server is unprotected and not using the latest version you can't see other players steam picture except yours and your friends on the server. If the server is protected and not using the lastest version you can see everyones steam picture.
![1](https://user-images.githubusercontent.com/40327830/68176374-5423fa80-ff63-11e9-8738-a459731edd26.jpg)
![2](https://user-images.githubusercontent.com/40327830/68176375-5423fa80-ff63-11e9-8f49-db388ad8f407.jpg)

**Comment by hashnimmo** [comment]
By the word "protected" you must be meaning about VAC? Besides I think using the latest version is a must.

**Comment by kisak-valve** [comment]
Possible duplicate of #2584.

**Comment by afwn90cj93201nixr2e1re** [comment]
Not duplicate, but i provide the answer in comments(https://github.com/ValveSoftware/halflife/issues/2584#issuecomment-511780135), yes.

There's no connection with Steam servers(steam api), that's why you can't see player avatars.

@kisak-valve should be closed as expected.

**Comment by Maxi605** [comment]
> Not duplicate, but i provide the answer in comments([#2584 (comment)](https://github.com/ValveSoftware/halflife/issues/2584#issuecomment-511780135)), yes.
> 
> There's no connection with Steam servers(steam api), that's why you can't see player avatars.
> 
> @kisak-valve should be closed as expected.

i can see avatars, only mine and friends.

> By the word "protected" you must be meaning about VAC? Besides I think using the latest version is a must.

I wanted to updated the server but im having issues with my hosting provider atm

**Comment by afwn90cj93201nixr2e1re** [comment]
> i can see avatars, only mine and friends.

and? What is wrong in my answer? You see it coz it's ur friends, and it's handled by your Steam.exe, not by server, server just handle other player's avatar's.

> I wanted to updated the server but im having issues with my hosting provider atm

The only one thing you should to do is just change version in steam.inf and disable double protocol module, it's can cause this bugs.

**Comment by Maxi605** [comment]
> > i can see avatars, only mine and friends.
> 
> and? What is wrong in my answer? You see it coz it's ur friends, and it's handled by your Steam.exe, not by server, server just handle other player's avatar's.
> 
> > I wanted to updated the server but im having issues with my hosting provider atm
> 
> The only one thing you should to do is just change version in steam.inf and disable double protocol module, it's can cause this bugs.

Not really, tested it with Doble Protocol and without with the latest version and both ways worked, is just the outdated version that causes the problem.
