### ISSUE TITLE
Screenshots and Demos should be in a separate folder

### ISSUE THREAD

**Issue by Rafflesian** [ValveSoftware/halflife#2760]
Title. 
Searching them it's annoying in a lot of different files like .wad, .cfg, .tga, etc...
A example of those new folders could be "[mod name]_screenshots" and "[mod name]_demos"
or "screenshots" and "demos" inside the mod folder

**Comment by hashnimmo** [comment]
Also the sounds and resources folders are named as just `sound` and `resource` when the rest of it's neighboring folders are named in plural form. Weird? Yes.

**Comment by kisak-valve** [comment]
Hello @Rafflesian, this request is already being tracked at #1441. Closing as a duplicate.
