### ISSUE TITLE
[CS1.6] Texture overflow (v8308)

### ISSUE THREAD

**Issue by raiz0x** [ValveSoftware/halflife#2763]
] version 
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 15:17:55 Jul 24 2019 (8308)

I get crash with 'Texture overflow: GL_idk..' for some servers...

**Comment by kisak-valve** [comment]
Hello @raiz0x, this reads like the issue being tracked at #2234. Closing in favor of the existing issue report.
