### ISSUE TITLE
[CS/CZ] Limit cl_*speed values to avoid Walk-Speed abuse

### ISSUE THREAD

**Issue by Rainnegan** [ValveSoftware/halflife#2779]
Walking at 150 u/s or less, you can't make any step sound.
Normally a player walk at 130 u/s with SHIFT key, but by using:

cl_fowardspeed "150"
cl_backspeed "150"
cl_sidespeed "150"

You can walk more faster than others players, will be nice if those cvars can be forced to "400" (default value) or avoid go less than 200.

**Comment by kisak-valve** [comment]
Hello @Rainnegan, this issue is already being tracked at #2371. Closing as a duplicate.
