### ISSUE TITLE
[GoldSrc] SZ_GetSpace:  Tried to write to an uninitialized sizebuf_t

### ISSUE THREAD

**Issue by s1lentq** [ValveSoftware/halflife#2785]
How to reproduce it?

1. You must have at least one fakeclient (zbot or something else) in your listenserver.
2. Open console and type sv_cheats 1
3. Got error `Tried to write to an uninitialized sizebuf_t`

This bug affect commits since when @mikela-valve made sv_cheats works in realtime.

For solution this issue we must to ignore packet svc_sendextrainfo for fakeclient in sv_cheats_hook_callback function.

![image](https://user-images.githubusercontent.com/5860435/68611903-ceb5c280-04ed-11ea-814f-79e3a5da20aa.png)

**Comment by deprale** [comment]
can confirm i get this crash as well.
One side effect: Your server browser history will be completely wiped.

**Comment by afwn90cj93201nixr2e1re** [comment]
> Your server browser history will be completely wiped

How it's related to this issue? Serverbrowser history and other stuff saved in your STEAM account and it's returned thru steamclient.dll interfaces(a.k.a. SteamApi).

**Comment by Veticus** [comment]
Can somebody recommend a workaround or hotfix?
I imagine pushing a fix for this to steam, is of rather low priority.

**Comment by afwn90cj93201nixr2e1re** [comment]
If you r using metamod or something like than, then yes.

**Comment by Veticus** [comment]
> 
> 
> If you r using metamod or something like than, then yes. But im not sure where this function placed and when called, if on serverside without listen game server (separate start from hlds.exe) then we need something like metamod, if it's can be reproduce only on client with listen game server then we can write some patcher.

In my case it's also happening with the Steam published (vanilla) client.
It happens both for CS1.6 and CSCZ. Both for "listen" servers and dedicated servers.

I mostly need a workaround for the CSCZ client.

**Comment by mikela-valve** [comment]
Hi @s1lentq, this should be fixed in the current beta version 8308.

**Comment by s1lentq** [comment]
@mikela-valve, The fix works, but I'm not sure that check for network buffer validity using `SZ_IsValid` was the correct way in terms of GoldSrc style, because fakeclients never network buffer. All code of GoldSrc uses check `client_t::fakeclient` before sending any network message. I don't see any other reason not to do it the same way, unless you plan to replace all checks fakeclient to SZ_IsValid in the future.

**Comment by mikela-valve** [comment]
Thanks @s1lentq, closing as fixed.
