### ISSUE TITLE
Counter-Strike crashing, but worked fine before??

### ISSUE THREAD

**Issue by jmanof08** [ValveSoftware/halflife#2787]
I tried to play Counter-Strike after installing it onto my Steam account through the Half-Life GOTY disc, and it worked fine when I installed it two days ago...but yesterday morning when I tried to play, it just force closed and Steam still shows it as running and I can't stop it or uninstall it. Restarting the computer closes it, but trying to play it only gives the same result...I've uninstalled, reinstalled, checked file integrity and still nothing. What should I do????

**Comment by Solokiller-GH** [comment]
You need to install CS through Steam itself. The WON versions (disc based versions) are not supported.

**Comment by SamVanheer** [comment]
You need to install CS through Steam itself. The WON versions (disc based versions) are not supported.

**Comment by jmanof08** [comment]
But all the others work just fine, I played Team Fortress Classic, Day of Defeat and Deathmatch without any problems...is it just Counter Strike?

**Comment by SamVanheer** [comment]
If the WON version of a game works under Steam then that's by chance, there is no guarantee it will work. The engine has special logic for specific games so that's probably the cause here.

I'm guessing it's the VGUI2 code, since the WON version doesn't have those interfaces it's just crashing when it tries to use them.

**Comment by BlackShadow** [comment]
> I tried to play Counter-Strike after installing it onto my Steam account through the Half-Life GOTY disc, and it worked fine when I installed it two days ago...but yesterday morning when I tried to play, it just force closed and Steam still shows it as running and I can't stop it or uninstall it. Restarting the computer closes it, but trying to play it only gives the same result...I've uninstalled, reinstalled, checked file integrity and still nothing. What should I do????

Why don't you enter your GOTY Disc CD-Key to Steam and get Steam version of these games if you don't have it on your Steam library. I'm not sure this thing still continues though.

**Comment by BlackShadow** [comment]
Edit: You still can use your WON Half-Life CD Key in Steam and get the games. I've tried with my Half-Life Generation Disc with GOTY CD Key on it and it seems ok.

![image](https://user-images.githubusercontent.com/30868395/68946411-fc3b8e00-07c3-11ea-82d9-3eca4a93ef4e.png)

**Comment by jmanof08** [comment]
> Why don't you enter your GOTY Disc CD-Key to Steam and get Steam version of these games if you don't have it on your Steam library. I'm not sure if this thing still continues though.

That's what I did to get it in my library. I caved and bought the CS: Condition Zero bundle and after I uninstalled and reinstalled CS, it works just fine now... thank you the help, guys
