### ISSUE TITLE
[CS/CS:CZ] Viewdemo is still bugged and causes crash after last update

### ISSUE THREAD

**Issue by WestBoy15** [ValveSoftware/halflife#2788]
Viewdemo is still bugged, and viewdemo is too important for the Brazilian Condition Zero community to discover cheaters.
Example:
https://youtu.be/lzEXmZHnT58

**Comment by afwn90cj93201nixr2e1re** [comment]
Can you write version in console and show an output?

Also append demo file.

**Comment by WestBoy15** [comment]
> Can you write version in console and show an output?
> 
> Also append demo file.

Version:
![20191115203202_1](https://user-images.githubusercontent.com/19874910/68982835-42eeaf80-07e7-11ea-9628-ec4ef9219fd2.jpg)

Demo file:
[mega.zip](https://github.com/ValveSoftware/halflife/files/3853543/mega.zip)

**Comment by RauliTop** [comment]
Probably not updated correctly at Condition Zero

**Comment by CS-PRO1** [comment]
@mikela-valve Can you check if CZ was updated with the demo fix?

**Comment by WestBoy15** [comment]
Hello, I'm still waiting for an answer @kisak-valve @mikela-valve

**Comment by SmileyAG** [comment]
Until Valve fixes this issue, you can fix it yourself: 
1) Download old version of GoldSrc binaries by using the Steam depots (you need only **hw.dll**): https://steamdb.info/depot/2/history/?changeid=M:7511900663473023951

2) Replace it in the /Half-Life/ folder 

3) Done.
