### ISSUE TITLE
Very slow moving while crouch on edge.

### ISSUE THREAD

**Issue by Erikk26** [ValveSoftware/halflife#2793]
Game makes your movement very slow for no reason at non dangerous map parts too if you're on an edge and moving forward while crouching. Make this a server/client side optional function even if you guys don't remove it. Idk anyone already reported it or not, sorry if someone did before!

**Comment by kisak-valve** [comment]
Hello @Erikk26, please clarify which game you're seeing this issue with.

**Comment by Erikk26** [comment]
sorry, its Counter-Strike 1.6

**Comment by perforatorRU** [comment]
> Game makes your movement very slow for no reason at non dangerous map parts too if you're on an edge and moving forward while crouching. Make this a server/client side optional function even if you guys don't remove it. Idk anyone already reported it or not, sorry if someone did before!

Google -> edgefriction cs 1.6 (Kreedz \ HNS \ etc... )

**Comment by Erikk26** [comment]
> > Game makes your movement very slow for no reason at non dangerous map parts too if you're on an edge and moving forward while crouching. Make this a server/client side optional function even if you guys don't remove it. Idk anyone already reported it or not, sorry if someone did before!
> 
> Google -> edgefriction cs 1.6 (Kreedz \ HNS \ etc... )

What should i do with that? What i said its an annoying thing in a Zombie Escape server where you need to crouch to complete section of the map and this thing slows you down. The only solution is spamming jump and strafe while you're in a e. g. ventilation passage.

**Comment by Rainnegan** [comment]
> > > Game makes your movement very slow for no reason at non dangerous map parts too if you're on an edge and moving forward while crouching. Make this a server/client side optional function even if you guys don't remove it. Idk anyone already reported it or not, sorry if someone did before!
> > 
> > 
> > Google -> edgefriction cs 1.6 (Kreedz \ HNS \ etc... )
> 
> What should i do with that? What I was talking about really is an annoying thing for example in a Zombie Escape server where you need to crouch to complete section of the map and this thing slows you down. The only solution is spamming jump and do strafe while you're in a e. g. ventilation passage.

Thats is normal, because the server slow down your speed while you are a zombie, also slow down your speed when you receive a shoot, and so on ...

**Comment by Erikk26** [comment]
actually, server speed up zombie's movement. This is a game engine thing i say again. Test it yourself if you don't believe me.

**Comment by Erikk26** [comment]
> > > > Game makes your movement very slow for no reason at non dangerous map parts too if you're on an edge and moving forward while crouching. Make this a server/client side optional function even if you guys don't remove it. Idk anyone already reported it or not, sorry if someone did before!
> > > 
> > > 
> > > Google -> edgefriction cs 1.6 (Kreedz \ HNS \ etc... )
> > 
> > 
> > What should i do with that? What I was talking about really is an annoying thing for example in a Zombie Escape server where you need to crouch to complete section of the map and this thing slows you down. The only solution is spamming jump and do strafe while you're in a e. g. ventilation passage.
> 
> Thats is normal, because the server slow down your speed while you are a zombie, also slow down your speed when you receive a shot, and so on ...

actually, server speed up zombie's movement. This is a game engine thing i say again. Test it yourself if you don't believe me.

**Comment by afwn90cj93201nixr2e1re** [comment]
It's actualy map problem, not related to cs.
Can you post video? And map name.

**Comment by Erikk26** [comment]
> It's actualy map problem, not related to cs.
> Can you post video? And map name.

Try to start a New Game on menu for example with as_oilrig and try it. My internet is slow for video recording.

**Comment by afwn90cj93201nixr2e1re** [comment]
Where i should walk on as_oilrig?

**Comment by Erikk26** [comment]
try in front of the helicopter outside... and crouch walk.

**Comment by GameChaos** [comment]
you can disable this by setting the"edgefriction" command to 0.
