### ISSUE TITLE
Fps drops to 20-40 when playing online

### ISSUE THREAD

**Issue by Samir-dharar** [ValveSoftware/halflife#2795]
Hi Guys,

Can anyone help with fixing this extreme FPS drop issue? I am currently able to get -
1. 300+ FPS on main screen of 1.6
2. 100-150 FPS when playing with bots (offline)

But when I am playing online on community servers, fps drops down to 20-40 in game. When I hit escape or open console fps goes back to 200-300 but when I am back in game it goes back to 20-40. 

I have tried the following after doing some research online - 

1) -nofbo in screen.
2) gl_textermode to GL_NEAREST_MINMAP_NEAREST

Any suggestion would highly be appreciated.

**Comment by afwn90cj93201nixr2e1re** [comment]
not sure, but expected, seems like cpu / gpu(too much polygons) problems.

Same issue since 2017.

**Comment by BlackShadow** [comment]
System specs?

**Comment by hackovh** [comment]
buy new computer

**Comment by Maxi605** [comment]
What server are you playing on?

**Comment by TheScaryGuy** [comment]
Try these suggestions: [Got Lag?](https://tekservers.net/forums/viewtopic.php?f=11&t=31)
