### ISSUE TITLE
Нitbох nоt fiхеd

### ISSUE THREAD

**Issue by zoruamonster** [ValveSoftware/halflife#2801]
Рlеаsе fiх HIТBОХ РRОВLЕМ 
https://github.com/ValveSoftware/halflife/issues/2154
**SkillartzHD opened this issue on 20 Apr** but nоt fiхеd!

**Comment by kisak-valve** [comment]
Hello @zoruamonster, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #2154.

**Comment by zoruamonster** [comment]
@kisak-valve but this not fixed, please fix hitbox, or it impossible ?!
