### ISSUE TITLE
Particleman is out of memory, too many particles

### ISSUE THREAD

**Issue by TheScaryGuy** [ValveSoftware/halflife#2850]
While playing Day of Defeat on Linux Mint 19.3, the game crashes to the desktop. Using _developer 3_ and _condebug_ in console to look in qconsole.log to see the error. Any suggestions on how to fix this problem?

**Comment by kisak-valve** [comment]
Hello @TheScaryGuy, this issue is already being tracked at #1447. Closing in favor of the existing issue report.
