### ISSUE TITLE
I have bug when I play though change level it happens bad movement.

### ISSUE THREAD

**Issue by SourceSkyBoxer** [ValveSoftware/halflife#2858]
Hello everyone

NOTE: I NO LONGER PLAY ON STEAM NOW. 

Thanks for everyone! I am sorry for that. I close it.

**Comment by afwn90cj93201nixr2e1re** [comment]
So, there no changelevel or what? if yes, that's mean there is bug in command restrictiion, seems it's still doesnt recognize local game server and other stuff.

**Comment by SourceSkyBoxer** [comment]
@afwn90cj93201nixr2e1re Look video currently! It is change level since loading map than it looks like lagging. But my computer's ram is enough highly. 16 GB Ram. It is very stably. I don't know why does Half-Life happens since changing level ( change map ) if you use trigger_changelevel in single player.
