### ISSUE TITLE
[GoldSrc] [Linux] Underscores don't display in console

### ISSUE THREAD

**Issue by Yetoo1** [ValveSoftware/halflife#2860]
Underscores don't display in console on Linux (tested with Fedora 31) for all GoldSrc games. This is annoying to work with. 

Notice the lack of underscores in the console specifically between cl and messages in cl_messages:
![20200213160914_1](https://user-images.githubusercontent.com/12403440/74490348-22cd9b80-4e7d-11ea-9e17-2afc8eb854e1.jpg)

System info here:
https://web.archive.org/web/20200212215631/https://pastebin.com/3JgmQcsf

**Comment by kisak-valve** [comment]
Hello @Yetoo1, this issue is already being tracked at #104. Closing as a duplicate.
