### ISSUE TITLE
HUD x Resolution

### ISSUE THREAD

**Issue by lamukraine** [ValveSoftware/halflife#2863]
It will be great to add hud scaling, because on resolitions higher than 720 its hard to see hud info like health & money. Low resolution having bigger hud scale than high resolution having smaller hud scalin.
Here's the comparison:
FULL HD HUD
![image fullhd](https://i.imgur.com/kXGdxTI.png)
LOW RESOLUTION HUD SCALE
![image 640](https://i.imgur.com/NNu5pBQ.png)

**Comment by Koterminus** [comment]
I agree, but this issue is already being tracked at #1982 and #2210.

**Comment by kisak-valve** [comment]
Closing in favor of the existing issue report.
