### ISSUE TITLE
[CS 1.6]HUD color change

### ISSUE THREAD

**Issue by SanAntonio2** [ValveSoftware/halflife#2866]
So far, the only way to change the color of the HUD is to change some values in the``` client.dll``` file, but this is not very safe since many user anti-cheats instantly issue a lock when a file changes, it does not match the original file.

 It’s possible as a solution to add a new line to the file ```ClientScheme.res```, which would be responsible for the color of the HUD.

**Comment by kisak-valve** [comment]
Hello @SanAntonio2, this feature request is already being tracked at #2107. Closing as a duplicate.
