### ISSUE TITLE
[REQUEST] Add support for vs2017 & vs2019

### ISSUE THREAD

**Issue by sabian-heatwave** [ValveSoftware/halflife#2868]
@Solokiller 's repo https://github.com/solokiller/halflife-updated has support for Visual Studio 2017 and Visual Studio 2019 and builds natively in the programs. I think it would be nice if this was implemented into this repo.

**Comment by kisak-valve** [comment]
Hello @sabian-heatwave, this is an alternative suggestion to #2246, and not worth tracking separately, so I've transferred this issue report to https://github.com/ValveSoftware/halflife/issues/2246#issuecomment-589800478.
