### ISSUE TITLE
Drop outdated HLDS builds from master server

### ISSUE THREAD

**Issue by tyabus** [ValveSoftware/halflife#2878]

**Comment by hashnimmo** [comment]
You mean from the in-game server list? Not a bad idea. I don't see the real reason why someone would not update their server to the latest version. But things won't change if they somehow find a way to fake the version output.

**Comment by tyabus** [comment]
> You mean from the in-game server list? Not a bad idea. I don't see the real reason why someone would not update their server to the latest version. But things won't change if they somehow find a way to fake the version output.

But players can still view build when they are joining to server, right? But i think that it can be faked too, like console cleaning, but there is command-line parameter that allows to log everything in qconsole.log, about reason, well... On latest HLDS build (at current moment) the metamod plugin callled 'dproto' ( i'm not using it ) dosen't work, and that's the reason why some people stays on previous builds. Another reason can be like 'working? - don't touch.'

**Comment by hashnimmo** [comment]
I don't think the players even care about the server version. They just want to join and play. It's just that they are too late when they find out their game files were slow hacked by joining bad servers. About the Metamod plugin, there is a new one called ReUnion.

**Comment by tyabus** [comment]
> I don't think the players even care about the server version. They just want to join and play. It's just that they are too late when they find out their game files were slow hacked by joining bad servers. About the Metamod plugin, there is a new one called ReUnion.

I know, but this is for ReHLDS platform, not for HLDS.

**Comment by hashnimmo** [comment]
ReHLDS or HLDS, both acts the same from the outside and the master list doesn't see a difference when they get listed. Except ReHLDS claim to do everything better than HLDS. Regardless of their names, slow hacking is a problem. At least dropping older builds from the master list will minimize slow hacking servers, but there's no guarantee they won't slow hack again in newer builds.

**Comment by tyabus** [comment]
> ReHLDS or HLDS, both acts the same from the outside and the master list doesn't see a difference when they get listed. Except ReHLDS claim to do everything better than HLDS. Regardless of their names, slow hacking is a problem. At least dropping older builds from the master list will minimize slow hacking servers, but there's no guarantee they won't slow hack again in newer builds.

Maybe implement 'black list' for master server? Or implement server check before accessing the master server

**Comment by hashnimmo** [comment]
> Maybe implement 'black list' for master server? Or implement server check before accessing the master server
This is the solution. Every server should be attached to a paid Steam player account.

**Comment by kisak-valve** [comment]
Hello @tyabus, @hashnimmo, this discussion is effectively a repeat of #2064. Feel free to add your experience to the existing issue report.

Closing in favor of the existing issue report.
