### ISSUE TITLE
how to make people download models

### ISSUE THREAD

**Issue by OriamK** [ValveSoftware/halflife#2886]
Hi i have run a dedicaded server for Half Life in a Linux machine. Now i want people that join to my server can download new models, but i don't know how to do it. 
I have already the models that people should download, i have placed the models inside the models directory but  when people load the match, they doesn't download anything.

Where i should put these models? 

Thanks

**Comment by LucesEnBabel** [comment]
For content to be transferred it needs to be precached, you can achieve this using a server-side mod like AMXX.

I suggest you to close this issue because this is out of the scope of this issue tracker.

**Comment by OriamK** [comment]
Thanks I got it!!
