### ISSUE TITLE
[cstrike] Game crashes while ducking after being killed.

### ISSUE THREAD

**Issue by greymood09** [ValveSoftware/halflife#2888]
Referencing #1576.

It's a bug that crashes the game (freezes it, no way to recover).
Triggers inconsistently (did not crash when I tried to do it on purpose), to reproduce you must be spamming +duck before and during death animation/killcam to trigger it.

OS: Linux (**not** OS dependent, happened with windows too)

Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 15:17:26 Jul 24 2019 (8308)

**Comment by kisak-valve** [comment]
Hello @greymood09, there's no value in splitting the discussion of this issue into multiple issue reports. Closing as a duplicate.

**Comment by greymood09** [comment]
> Hello @greymood09, there's no value in splitting the discussion of this issue into multiple issue reports. Closing as a duplicate.

Understandable, I wasn't too sure how you're managing the issues, didn't see any assignees/tags.
