### ISSUE TITLE
[CS 1.6] Disallow the use of some console commands

### ISSUE THREAD

**Issue by SanAntonio2** [ValveSoftware/halflife#2889]
Please add the commands: "`stopsound`, `force_centerview`" to the list of those that are attached to `sv_cheats`, that is, if `sv_cheats 0` - these commands will not work, they (commands) can be considered as cheats.

**Comment by kisak-valve** [comment]
Hello @SanAntonio2, this is already being tracked at #2206, #2208. Closing as a duplicate.
