### ISSUE TITLE
[Ricochet] Homing Discs glitch

### ISSUE THREAD

**Issue by APGRoboCop** [ValveSoftware/halflife#2901]
Hello, I've noticed that those discs from Ricochet tend to follow and home in on enemy targets - which occasionally happens, from where I've spotted when airborne or even being respawned. Now I find it weird and how players tend to be accused of cheating by making their discs home in.

Those discs are supposed to shoot in a straight line until they hit those neon bumpers to make them bounce in a straight line also, but never curve in.

Please can we fix those discs from curving in and homing in onto enemy targets!

**Comment by JillCrungus** [comment]
If you're talking about freeze discs, this seems to be intended behavior, not a bug:

https://github.com/ValveSoftware/halflife/blob/5d761709a31ce1e71488f2668321de05f791b405/ricochet/dlls/wpn_shared/disc_weapon_disc.cpp#L332
