### ISSUE TITLE
[cstrike]64Bit Update For MacOS Catalina Users

### ISSUE THREAD

**Issue by berkay97** [ValveSoftware/halflife#2905]
Hello,

Im using MacOS Catalina 10.15.4 and cant run 1.6 from Steam. I've almost got 4k hours and i want to keep playing. I don't want to downgrade to mojave or virtual machine or install windows with bootcamp. Are dev's going to update game from 32 bit to 64 bit? Thanks..

**Comment by kisak-valve** [comment]
Hello @berkay97, this issue is already being tracked at #2231. Closing in favor of the existing issue report.
