### ISSUE TITLE
Is the SDK able to use C++ GUI library like DeadImGUI?

### ISSUE THREAD

**Issue by kalenclark** [ValveSoftware/halflife#2916]
Just wanna make new UI with new GUI library...

**Comment by barney-heatwave** [comment]
Yes, it is. https://github.com/suXinjke/HalfPayne uses a modern C++ GUI library in its SDK.

**Comment by kalenclark** [comment]
> Yes, it is. https://github.com/suXinjke/HalfPayne uses a modern C++ GUI library in its SDK.

OK, thanks for the reply, I'll try it~

**Comment by kalenclark** [comment]
> Yes, it is. https://github.com/suXinjke/HalfPayne uses a modern C++ GUI library in its SDK.

Can you tell me what's the name of the GUI lib?

**Comment by tmp64** [comment]
> Can you tell me what's the name of the GUI lib?
Dear ImGui

**Comment by kalenclark** [comment]
> > Can you tell me what's the name of the GUI lib?
> 
> Dear ImGui

OK, thank you very much~
