### ISSUE TITLE
[cstrike] Lost connection after first connect to server.

### ISSUE THREAD

**Issue by 2020karaulov2020** [ValveSoftware/halflife#2917]
At first launch CS 1.6 and connect to any server, I got lost connection at 5-10 play seconds.

WIFI, connection power 80-100%, ping to router (192.168.100.1) 1-5ms.

If I connect to same server two times, I can play without lost connection.

**Comment by kisak-valve** [comment]
Hello karaulov, you've repeatedly abused this issue tracker over a sustained period of time and created account after account to bypass the ban. You are not welcome here.
