### ISSUE TITLE
How to draw third-party GUI over Half Life (and VGUI)?

### ISSUE THREAD

**Issue by kalenclark** [ValveSoftware/halflife#2918]
I'm currently using Noesis GUI, don't know how to draw my Noesis GUI over Half Life and VGUI.
Half-Payne integrated Dear ImGUI by
taking a detour from certain engine's function into HL_ImGUI_Draw function,
but it seems doesn't work for me.

**Comment by tmp64** [comment]
You could try drawing GUI during HUD_Draw. Internally, engine calls OpenGL functions to draw sprites and text textures so, if Noesis GUI supports OpenGL, it should just work.

**Comment by SNMetamorph** [comment]
I embedded ImGui in my mod without using an engine detour, but this causes to one limitation - ImGui can't be used in main menu.
I think it also can be used with Noesis in same way.

**Comment by kalenclark** [comment]
Thank you guys, I planed to use original GUI library, because in my opinion, the SDK's limited in some aspects without the source code.
