### ISSUE TITLE
Incomplete download of windows dedicated server due to depot 5 missing from sub 17906, 0

### ISSUE THREAD

**Issue by molerone** [ValveSoftware/halflife#2919]
I tried to download Counter-Strike 1.6 Dedicated Server with steamcmd many times, but it is not fully downloaded.

**Comment by kisak-valve** [comment]
Hello @molerone, this issue is already being tracked in various issue reports (#928 / #1541 / #1583). Closing as a duplicate.

**Comment by molerone** [comment]
@kisak-valve hello, but its new problem, i know about this old issues, it's not that, so, please reopen this

**Comment by kisak-valve** [comment]
Are you able to clarify exactly how your experience differs from the long standing issues? Simply claiming that its broken without logs or details doesn't justify fragmenting the discussion over yet another issue report.

**Comment by molerone** [comment]
@kisak-valve 
i used command app_update 90 validate many times and answer is - Success! app "90" fully installed, but in game folder i have only 2 folders and 6 dlls, without hlds.exe, without hltv,exe etc. [See](https://imgur.com/vrDcBXP) Not only I have this problem
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Steam>login anonymous

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK

Steam>**app_update 90 validate**
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x1) running, progress: 0.00 (0 / 409689568)
 Update state (0x61) downloading, progress: 0.02 (180200 / 771884554)
 Update state (0x61) downloading, progress: 1.42 (10937444 / 771884554)
 Update state (0x61) downloading, progress: 3.51 (27072559 / 771884554)
 Update state (0x61) downloading, progress: 4.71 (36350110 / 771884554)
 Update state (0x61) downloading, progress: 7.67 (59195705 / 771884554)
 Update state (0x61) downloading, progress: 9.90 (76386668 / 771884554)
 Update state (0x61) downloading, progress: 13.60 (104954091 / 771884554)
 Update state (0x61) downloading, progress: 17.35 (133888444 / 771884554)
 Update state (0x61) downloading, progress: 21.01 (162186254 / 771884554)
 Update state (0x61) downloading, progress: 23.93 (184701676 / 771884554)
 Update state (0x61) downloading, progress: 26.95 (208014645 / 771884554)
 Update state (0x61) downloading, progress: 28.47 (219740001 / 771884554)
 Update state (0x61) downloading, progress: 29.96 (231223749 / 771884554)
 Update state (0x61) downloading, progress: 30.53 (235625796 / 771884554)
 Update state (0x61) downloading, progress: 30.76 (237427905 / 771884554)
 Update state (0x61) downloading, progress: 30.76 (237427905 / 771884554)
 Update state (0x61) downloading, progress: 30.76 (237427905 / 771884554)
 Update state (0x61) downloading, progress: 37.87 (292322309 / 771884554)
 Update state (0x61) downloading, progress: 38.44 (296742090 / 771884554)
 Update state (0x61) downloading, progress: 40.16 (310018411 / 771884554)
 Update state (0x61) downloading, progress: 43.36 (334667838 / 771884554)
 Update state (0x61) downloading, progress: 47.44 (366155535 / 771884554)
 Update state (0x61) downloading, progress: 52.34 (403996247 / 771884554)
 Update state (0x61) downloading, progress: 57.37 (442806183 / 771884554)
 Update state (0x61) downloading, progress: 62.49 (482388793 / 771884554)
 Update state (0x61) downloading, progress: 67.14 (518220643 / 771884554)
 Update state (0x61) downloading, progress: 70.63 (545219062 / 771884554)
 Update state (0x61) downloading, progress: 73.84 (569986843 / 771884554)
 Update state (0x61) downloading, progress: 75.71 (584392403 / 771884554)
 Update state (0x61) downloading, progress: 79.00 (609763272 / 771884554)
 Update state (0x61) downloading, progress: 82.45 (636383045 / 771884554)
 Update state (0x61) downloading, progress: 84.23 (650163314 / 771884554)
 Update state (0x61) downloading, progress: 84.83 (654822992 / 771884554)
 Update state (0x61) downloading, progress: 86.26 (665793747 / 771884554)
 Update state (0x61) downloading, progress: 88.15 (680453559 / 771884554)
 Update state (0x61) downloading, progress: 89.83 (693404214 / 771884554)
 Update state (0x61) downloading, progress: 90.32 (697198241 / 771884554)
 Update state (0x61) downloading, progress: 91.54 (706550676 / 771884554)
 Update state (0x61) downloading, progress: 93.04 (718158986 / 771884554)
 Update state (0x61) downloading, progress: 93.55 (722104748 / 771884554)
 Update state (0x61) downloading, progress: 93.96 (725230812 / 771884554)
 Update state (0x61) downloading, progress: 96.79 (747109546 / 771884554)
 Update state (0x61) downloading, progress: 100.00 (409689568 / 409689568)
 Update state (0x101) committing, progress: 91.95 (269060938 / 292611285)
 Update state (0x101) committing, progress: 39.66 (292611285 / 737743914)
 Update state (0x101) committing, progress: 71.40 (526713653 / 737743914)
 Update state (0x101) committing, progress: 88.70 (654357342 / 737743914)
 Update state (0x101) committing, progress: 90.34 (666471862 / 737743914)
 Update state (0x101) committing, progress: 93.77 (691751495 / 737743914)
 Update state (0x101) committing, progress: 95.79 (706707730 / 737743914)
 Update state (0x101) committing, progress: 100.00 (409689568 / 409689568)
**Success! App '90' fully installed.**

**Steam>app_update 90 validate**
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) verifying install, progress: 2.73 (7974353 / 292611285)
 Update state (0x5) verifying install, progress: 31.18 (91247113 / 292611285)
 Update state (0x5) verifying install, progress: 47.86 (140030037 / 292611285)
 Update state (0x5) verifying install, progress: 69.97 (204726855 / 292611285)
 Update state (0x5) verifying install, progress: 80.39 (235230627 / 292611285)
 Update state (0x5) verifying install, progress: 88.60 (259259725 / 292611285)
 Update state (0x5) verifying install, progress: 92.23 (269864893 / 292611285)
 Update state (0x5) verifying install, progress: 94.30 (275935833 / 292611285)
 Update state (0x5) verifying install, progress: 95.84 (280432337 / 292611285)
 Update state (0x5) verifying install, progress: 42.20 (311331384 / 737743914)
 Update state (0x5) verifying install, progress: 45.78 (337710185 / 737743914)
 Update state (0x5) verifying install, progress: 53.28 (393059337 / 737743914)
 Update state (0x5) verifying install, progress: 69.23 (510743345 / 737743914)
 Update state (0x5) verifying install, progress: 76.14 (561693187 / 737743914)
 Update state (0x5) verifying install, progress: 84.56 (623863817 / 737743914)
 Update state (0x5) verifying install, progress: 86.06 (634898873 / 737743914)
 Update state (0x5) verifying install, progress: 86.67 (639393281 / 737743914)
 Update state (0x5) verifying install, progress: 90.11 (664786032 / 737743914)
 Update state (0x5) verifying install, progress: 92.03 (678916330 / 737743914)
 Update state (0x5) verifying install, progress: 94.87 (699892925 / 737743914)
 Update state (0x5) verifying install, progress: 97.39 (718501704 / 737743914)
 Update state (0x5) verifying install, progress: 99.94 (771399402 / 771884554)
**Success! App '90' fully installed.**

**Steam>app_update 90 validate**
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) verifying install, progress: 28.12 (82276685 / 292611285)
 Update state (0x5) verifying install, progress: 35.66 (104343007 / 292611285)
 Update state (0x5) verifying install, progress: 67.03 (196126979 / 292611285)
 Update state (0x5) verifying install, progress: 78.07 (228446215 / 292611285)
 Update state (0x5) verifying install, progress: 88.46 (258841801 / 292611285)
 Update state (0x5) verifying install, progress: 92.51 (270688013 / 292611285)
 Update state (0x5) verifying install, progress: 94.72 (277172441 / 292611285)
 Update state (0x5) verifying install, progress: 41.89 (309008042 / 737743914)
 Update state (0x5) verifying install, progress: 44.71 (329815956 / 737743914)
 Update state (0x5) verifying install, progress: 52.42 (386711885 / 737743914)
 Update state (0x5) verifying install, progress: 68.99 (508942545 / 737743914)
 Update state (0x5) verifying install, progress: 76.41 (563735679 / 737743914)
 Update state (0x5) verifying install, progress: 84.96 (626797321 / 737743914)
 Update state (0x5) verifying install, progress: 86.37 (637199601 / 737743914)
 Update state (0x5) verifying install, progress: 89.84 (662806749 / 737743914)
 Update state (0x5) verifying install, progress: 91.54 (675301843 / 737743914)
 Update state (0x5) verifying install, progress: 94.07 (694011024 / 737743914)
 Update state (0x5) verifying install, progress: 97.51 (719391534 / 737743914)
**Success! App '90' fully installed.**

**Comment by molerone** [comment]
@kisak-valve https://forums.alliedmods.net/showthread.php?p=2702005

**Comment by kisak-valve** [comment]
Thanks @molerone, looking at this a bit more and I think I see a Steam database configuration issue, but as a moderator, I don't have access to make adjustments. We'll need to hear from an interested Valve dev who is working on Steam or goldsrc if/when this is looked into further.

**Comment by kisak-valve** [comment]
Hello @molerone, please retest this issue.

**Comment by molerone** [comment]
@kisak-valve now its working, thanks

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
