### ISSUE TITLE
Increase number of slots in default.cfg

### ISSUE THREAD

**Issue by artkirienko** [ValveSoftware/halflife#2921]
By default in the latest steam Half-Life client (`build 8308`), only 5 slots are defined, previous builds had same configs.

The problem is that you can't vote for map extending in AMXX. I created an Issue there too: https://github.com/alliedmodders/amxmodx/issues/866

![image](https://user-images.githubusercontent.com/2473081/83674871-cb486c80-a5e0-11ea-8507-03e83dc0080c.png)

# Proposal

## Before

default.cfg
```
// ...
bind 1 slot1
bind 2 slot2
bind 3 slot3
bind 4 slot4
bind 5 slot5
// ...
```

## After

default.cfg
```
// ...
bind 0 slot10
bind 1 slot1
bind 2 slot2
bind 3 slot3
bind 4 slot4
bind 5 slot5
bind 6 slot6
bind 7 slot7
bind 8 slot8
bind 9 slot9
// ...
```

**Comment by kisak-valve** [comment]
Hello @artkirienko, this issue is already being tracked at #2903. Closing as a duplicate.
