### ISSUE TITLE
Cstrike -> Movement bug

### ISSUE THREAD

**Issue by deprale** [ValveSoftware/halflife#2929]
IF you look up with an usp and shoot really fast with it while holding w or s you're gonna go opposite direction. +forward will become +back and vice-versa.

**Comment by basuritashka** [comment]
Already reported by me a few months ago

**Comment by JoelTroch** [comment]
This issue is a duplicate of #2248

**Comment by metita** [comment]
@kisak-valve This is a duplicate as @JoelTroch stated.
