### ISSUE TITLE
if i load my maps in cs 1.6 its wont load but it plays the map but all is black screen

### ISSUE THREAD

**Issue by Ashehaw** [ValveSoftware/halflife#2931]
Sorry bad english i need help video is here https://youtu.be/EsqutdfhrJo

**Comment by Ashehaw** [comment]
can someone help plz :(

**Comment by wopox1337** [comment]
You have a customized client. Try to buy official on Steam

**Comment by PRinceBhai** [comment]
They don't support pirated or heavily modified games.
