### ISSUE TITLE
Gauss Gun beam effect is incorectly reading colors and brightness values

### ISSUE THREAD

**Issue by vasiavasiavasia95** [ValveSoftware/halflife#2933]
After client prediction was introduced, gauss effect handling was moved to the client resulting in gauss's beam effect being broken.
Primary attack beam's color became yellow instead of orange and secondary attack beam is always shown at full brightness instead of relying on the charge time.
I did some research and found out this happens becasue beam effect requires it's color and brightness values divided by 255. This requriement was overlooked resulting in the broken behavior we got.

To fix this, this function:
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/cl_dll/ev_hldm.cpp#L922-L963

Should be modifed to look like this:
```

if (fFirstBeam)
		{
			if ( EV_IsLocal( idx ) )
			{
				// Add muzzle flash to current weapon model
				EV_MuzzleFlash();
			}
			fFirstBeam = 0;

			gEngfuncs.pEfxAPI->R_BeamEntPoint( 
				idx | 0x1000,
				tr.endpos,
				m_iBeam,
				0.1,
				m_fPrimaryFire ? 1.0 : 2.5,
				0.0,
				(m_fPrimaryFire ? 128.0 : flDamage) / 255.0,
				0,
				0,
				0,
				(m_fPrimaryFire ? 255 : 255) / 255.0,
				(m_fPrimaryFire ? 128 : 255) / 255.0,
				(m_fPrimaryFire ? 0 : 255) / 255.0
			);
		}
		else
		{
			gEngfuncs.pEfxAPI->R_BeamPoints( vecSrc,
				tr.endpos,
				m_iBeam,
				0.1,
				m_fPrimaryFire ? 1.0 : 2.5,
				0.0,
				(m_fPrimaryFire ? 128.0 : flDamage) / 255.0,
				0,
				0,
				0,
				(m_fPrimaryFire ? 255 : 255) / 255.0,
				(m_fPrimaryFire ? 128 : 255) / 255.0,
				(m_fPrimaryFire ? 0 : 255) / 255.0
			);
		}
```

**Comment by kisak-valve** [comment]
Hello @vasiavasiavasia95, this issue was already reported at #2865 and there's no value in fragmenting the discussion, so I've transferred this issue report to https://github.com/ValveSoftware/halflife/issues/2865#issuecomment-665079425.

**Comment by vasiavasiavasia95** [comment]
> 
> 
> Hello @vasiavasiavasia95, this issue was already reported at #2865 and there's no value in fragmenting the discussion, so I've transferred this issue report to [#2865 (comment)](https://github.com/ValveSoftware/halflife/issues/2865#issuecomment-665079425).

Ok. Thanks
