### ISSUE TITLE
Latest Beta Update broke entity sounds from maps like cs_italy

### ISSUE THREAD

**Issue by metita** [ValveSoftware/halflife#2938]
![image](https://user-images.githubusercontent.com/33007491/89245676-54772200-d5d7-11ea-80f2-51e70c544e66.png)

Tested on latest update from today, I was playing on de_westwood_big and just noticed that the Jukebox from the map started playing a horrible sound like a bip on loop.

We also tested locally on cs_italy and the same thing happened.

How to reproduce:

Open the game and launch a local server with map cs_italy, you will spawn on TT side, keep walking from the left side of the map and you will start hearing a horrible sound that won't stop, also the Jukebox is not playing any audio at all or random sounds on loop.

Preview #01: www.youtube.com/watch?v=c1dLgspWQzI
Preview #02: www.youtube.com/watch?v=k5mUGN2Dv7s

**Comment by mikela-valve** [comment]
Thanks @metita, that was part of a fix to a sound crash that was improperly detecting sound files that required resampling (like the opera track on cs_italy). I've fixed that in the latest beta and fixed the track not being silenced properly if it's legitimately bad.

**Comment by CS-PRO1** [comment]
Good fetch. Just on a side note, I had my client updated today but the version still refer to the build at July 24 2019, 
![image](https://user-images.githubusercontent.com/50755959/89290855-2ab70d00-d662-11ea-9819-62f6df07fb2b.png)

**Comment by Splatt581** [comment]
> Good fetch. Just on a side note, I had my client updated today but the version still refer to the build at July 24 2019,

Just try exiting beta and join again. I also failed to download all the files the first time.

**Comment by metita** [comment]
Can confirm it is fixed, thanks!
