### ISSUE TITLE
HLDS with CS 1.6 crash at start in beta

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#2939]
A clean server crashes on startup with the latest beta binaries. Error:

`FATAL ERROR (shutting down): Mod_LoadModel: Bad model name length: models/shield/v_shield_fiveseven.mdl`

It looks like the client's listen server doesnt crash due to the lack of this check in client engine.

**Comment by mikela-valve** [comment]
Thanks @Splatt581, the model loader used by the dedicated server was using the wrong size when converting filenames to resource names and failing on certain longer files like that one. This is fixed now in beta.

**Comment by Splatt581** [comment]
Fixed, I confirm, the server starts normally.
