### ISSUE TITLE
[Half-Life: Opposing Force] cl_autowepswitch 0 not working after respawn

### ISSUE THREAD

**Issue by andrewgillich** [ValveSoftware/halflife#2958]
Title. It works fine in original Half-Life though.

**Comment by Solokiller** [comment]
Which gamemode was this in?

**Comment by andrewgillich** [comment]
Deathmatch. Seems like it works if you create your own server but doesn't if you connect to others.

**Comment by Solokiller** [comment]
Are you sure the server is running the latest version of the game? It might not have the changes that implement this feature.

**Comment by andrewgillich** [comment]
I'm not sure. I thought server shouldn't affect client side variables?

**Comment by Solokiller** [comment]
This feature requires server side support because automatic weapon switching is server side logic.

**Comment by andrewgillich** [comment]
Well, good to know. Thanks.
