### ISSUE TITLE
Raise the default "default_fov" to 106.

### ISSUE THREAD

**Issue by Pi0h1** [ValveSoftware/halflife#2962]
Leaving the FOV at 90 in an era where most people have 16:9 monitors makes no sense. I've seen cases where players have gotten motion sick from how small the FOV is in GoldSRC games by default and not everyone, specially players playing through these games for the first time, have the technical knowledge to know that they have to open the console and set default_fov to that.

There are threads that propose GoldSRC games should be able to determine the best FOV based on your monitor's aspect ratio like how Source does, and while that would be an ideal solution, this is a much faster one to implement that would better the experience across all screens, even for those who still use 4:3 monitors.

**Comment by kisak-valve** [comment]
Hello @Pi0h1, there's some issue reports already open on this topic (#748 / #1978 / #2018 ). Closing in favor of the existing issue reports.
