### ISSUE TITLE
[COUNTER STRIKE 1.6] opengl smoke performance issue

### ISSUE THREAD

**Issue by 2e45846a9cfe** [ValveSoftware/halflife#2966]
My graphic card overclocked GEFORCE 520GT i got drop fps from 140HZ to 30-15 when someone uses smoke grenade.
Why game 20 year old can load 100% gpu at smoke scene?)) I contacted with nvidia and got response what smoke scene in these game is not optimized. Please optimize smoke grenades, please!
Or please add 'frame skip' option if frame rate smaller than in setting, because I can't use weapon in smoke.

**Comment by 2e45846a9cfe** [comment]
Or add 'low particles smoke' option for 10 year old PC

I tried any tweaks and other nvidia settings, but any way got drop fps from 140 Hz to 10-40 in smoke scenes.

**Comment by kisak-valve** [comment]
Hello karaulov, you've repeatedly abused this issue tracker over a sustained period of time and created account after account to bypass the ban. You are not welcome here.
