### ISSUE TITLE
[Counter Strike 1.6] Shoot and reload animation issue!

### ISSUE THREAD

**Issue by 2e45846a9cfe** [ValveSoftware/halflife#2967]
First fire - not animated.
Some weapon reload - not animated.
I can't add more info, but I playing at servers with many online (32/32) non steam (but I play with Steam Counter Strike 1.6 beta)

**Comment by kisak-valve** [comment]
Hello karaulov, you've repeatedly abused this issue tracker over a sustained period of time and created account after account to bypass the ban. You are not welcome here.
