### ISSUE TITLE
[Counter Strike 1.6] attack and any other actions dropped if seeing a smoke grenade

### ISSUE THREAD

**Issue by 2e45846a9cfe** [ValveSoftware/halflife#2968]
Weapon (attack, reload) and mouse (+attack,-attack) and other events not works if seeing through smoke in 10-20% cases, if more than one smoke, in 20-50%. (Dropped frames?)

Please fix these issue!

**Comment by kisak-valve** [comment]
Hello karaulov, you've repeatedly abused this issue tracker over a sustained period of time and created account after account to bypass the ban. You are not welcome here.
