### ISSUE TITLE
[HLDS] No damage source in vehicle ! Please do it!

### ISSUE THREAD

**Issue by 2e45846a9cfe** [ValveSoftware/halflife#2970]
Please use latest 'vehicle driver' as 'damage source' in vehicle code, it will be cool and easy to realizing! (Just add/edit 1-5 lines of code)

**User 'Player' kill a hostage with vehicle
User 'Player' kill a enemy with vehicle
User 'Player' kill a allies with vehicle**

**Comment by kisak-valve** [comment]
Hello karaulov, you've repeatedly abused this issue tracker over a sustained period of time and created account after account to bypass the ban. You are not welcome here.
