### ISSUE TITLE
[HLDS: Counter Strike 1.6] need to be update recoil parameters to bypass any existing AIM with 'no recoil' and 'no spread' features

### ISSUE THREAD

**Issue by 2e45846a9cfe** [ValveSoftware/halflife#2971]
Need to be update recoil parameters to bypass any existing AIMBOT with 'no recoil' and 'no spread' features.
It can be realized?

**Comment by kisak-valve** [comment]
Hello karaulov, you've repeatedly abused this issue tracker over a sustained period of time and created account after account to bypass the ban. You are not welcome here.
