### ISSUE TITLE
[CS 1.6] Windows 10 'Software Mode' cause crash in fullscreen

### ISSUE THREAD

**Issue by aiktju** [ValveSoftware/halflife#2973]
Switching 'opengl' mode to 'software' cause crash... and then switch back to 'opengl'!

**Comment by BlackShadow** [comment]
Try Windows XP SP3 compability

**Comment by aiktju** [comment]
@BlackShadow I no has these settings in Counter-Strike.lnk

**Comment by BlackShadow** [comment]
go to Steam/Steamapps/common/Half-Life

Right click to hl.exe choose Properties go to Compability tab

Select XP SP3 in OS compability.

**Comment by aiktju** [comment]
> go to Steam/Steamapps/common/Half-Life
> 
> Right click to hl.exe choose Properties go to Compability tab
> 
> Select XP SP3 in OS compability.

@BlackShadow with Win XP SP3 compatibility it work;' yes
you can add Win10 compability in"Software mode" ?

**Comment by MuhammadZeeshan1** [comment]
The new counter strike version is quite amazing, I have learned a lot about it. There was a post about it on the site where I learned about [logistic software types](https://andersenlab.com/blueprint/logistics-software-development-types-features). I am very excited to try it out for myself.

**Comment by shawns-valve** [comment]
Software renderer Win10 compatibility was addressed in the 25rh anniversary update. Please open a new issue if you're still having problems with the latest Steam build.
