### ISSUE TITLE
[cs 1.6] Add csgo style crosshair option to cs 1.6.

### ISSUE THREAD

**Issue by Automatics** [ValveSoftware/halflife#2975]
Recently it came to my attention not only was this possible it has already been done, please implement in official version of the game.

https://www.youtube.com/watch?v=q-nsio1Jj_E

**Comment by kisak-valve** [comment]
Hello @Automatics, this feature request is already being tracked at #2105. Closing as a duplicate.

**Comment by ashtonhogan** [comment]
Go play csgo, don't bring that junk here
