### ISSUE TITLE
[Half-Life SDK][Linux native & Proton] Mouse movement is broken.

### ISSUE THREAD

**Issue by Fujinn981** [ValveSoftware/halflife#2979]
I'm having a very odd issue that I haven't seen anyone else having so I'm hoping some one here will be able to help because I'm out of ideas.

I've tried the unofficial Half-Life updated SDK, and the original Half-Life SDK, what happens is, if I put use my newly compiled client.so (Nothing modified) in any mod, it breaks mouse movement, I can't turn a full 360 degrees, it locks up at a point forcing me to turn the other direction, which also locks up at a point. I'm beyond confused and can use whatever help I can get. This also happens if I use Valve's own client.so file, oddly doesn't happen in the original game. Any help is greatly appreciated.

Tested on Proton and it happens on Proton as well.

Update: Worked around by using Xash3d, leaving this open in hopes that some one will come around and give an idea as to how this can be properly fixed.

**Comment by kisak-valve** [comment]
Hello @Fujinn981, this reads like #1546. Maybe give #1900 a try?

**Comment by Fujinn981** [comment]
> Hello @Fujinn981, this reads like #1546. Maybe give #1900 a try?

Same issue. I find it strange because I tried even the client.so file from Half-Life (Not from the SDK.) and still had the same issue.

**Comment by Idiot64** [comment]
maybe it your window manager i dunno

**Comment by shawns-valve** [comment]
There were some mouse input issues fixed in the HL 25th anniversary update. Please open a new issue if this is still happening in the current Steam build.
