### ISSUE TITLE
[CS 1.6] External Demo Viewer

### ISSUE THREAD

**Issue by dhiganthrao** [ValveSoftware/halflife#2990]
Hi! I'm a student based in India who plays a lot of CS 1.6. The CS community in India is still thriving; unfortunately that also means a lot of hackers. Recording of demos are done but many people do not view these demo due to the fact that these demos can only be viewed if you use CS. There's no option for easy viewing of demos out of CS. Added to this, there is no functionality of trimming certain parts of the demo (examples of players hacking, for instance), and there's no functionality to export this demo outside to display to other people as well. People have to resort to recording the entire demo using software like FRAPS, and then trimming parts as they wish. My suggestion is, can there be an application that lets you view demos outside of CS? Also, converting .dem files into .mp4 or any other video formats? (That is, if there aren't any applications doing this already; even though I've searched literally everywhere for this.) The information I read on .dem files is that it tells your copy of CS how the demo is going to be; as in, it tells CS that the demo was played in a particular map, the players were positioned here and here, and so on. Is there a way to convert this information into video? I would definitely like to work on an application like this if I know where to start. Thank you for reading this long issue and hopefully you would know what to do with respect to this.

**Comment by kisak-valve** [comment]
Hello @dhiganthrao, realistically, major unvetted feature requests aren't going to happen for goldsrc, but it doesn't hurt to ask.

**Comment by dhiganthrao** [comment]
Understandable, but if I were to create this application independently without any affiliation to Valve or anything, where would you suggest a good start?

**Comment by Maxi605** [comment]
This would be outstandingly good.

**Comment by BlackShadow** [comment]
Valve isn't going to do stuff like this, but community may do it with help of Xash. But it's not going to be a plenty idea. A 3rd party demo viewer will still need files of the game so it'll be pretty much same thing as installing CS. In other hand UI will be better than viewmode in CS. But yeah, nobody will bother do something like this.

**Comment by BlackShadow** [comment]
Valve isn't going to do stuff like this, but community may do it with help of Xash. But it's not going to be a plenty idea. A 3rd party demo viewer will still need files of the game so it'll be pretty much same thing as installing CS. In other hand UI and demo playback controls will be better than viewdemo in CS. But yeah, nobody will bother do something like this.

**Comment by djdallmann** [comment]
https://github.com/skyrim/hlviewer.js

**Comment by dhiganthrao** [comment]
@djdallmann wow, tysm for this! Looks like a good solution for this issue, hence closing.
