### ISSUE TITLE
sight modification for CounterStrike 1.6

### ISSUE THREAD

**Issue by chicho88** [ValveSoftware/halflife#2993]
CounterStrike 1.6 STEAM: Modify the look to suit each one without having to install the GSclient..

![asddd](https://user-images.githubusercontent.com/72889275/96039405-f8cedd80-0e3e-11eb-8ada-42b772a4d3a0.jpg)

**Comment by kisak-valve** [comment]
Hello @chicho88, this feature request is already being tracked at #265 / #2105. Closing as a duplicate

**Comment by SooDD** [comment]
> CounterStrike 1.6 STEAM：修改外观以适合每个人，而无需安装 GSclient..
> 
> ![自闭症 （ASDDD）](https:user-images.githubusercontent.com/72889275/96039405-f8cedd80-0e3e-11eb-8ada-42b772a4d3a0.jpg)

2023 is coming to an end. Have you found a solution to this problem?

**Comment by ZakiyyullohDev** [comment]
What is this mod called?
