### ISSUE TITLE
gldraw.c in utils.sln failed

### ISSUE THREAD

**Issue by mintchoco0122** [ValveSoftware/halflife#2995]
#include <GL/glaux.h> -> glaux.h is depreacted. Any solutions?

**Comment by mintchoco0122** [comment]
Oh, I didn't read README. Sorry

**Comment by sabianroberts** [comment]
> Oh, I didn't read README. Sorry

Just some friendly advice, for every repo you visit you should always read the README because they contain important info for building, licensing etc.
