### ISSUE TITLE
Steam support sent me here because we couldn't fix the problem

### ISSUE THREAD

**Issue by PatTheMad** [ValveSoftware/halflife#2997]
Hallo my name is Patrick,
I'm from germany and I'm a huge fan from Half Life.
The german version of Half Life is still censored although it had already been removed from
the "black list"/ index since 2018. 

Here in germany we all just can play a light uncensored version. It is just half-uncensored. 
For example: Robots (only in german version) replaced with soldiers, deathanimation (censored) shows a head shaking victim who slowly disappears - replaced with the original death animation ,but the rest of the game is still the vannilla version with dissapearing bodys and no blood or gore effects. Organs and guts are still replaced with springs and gears like they would be some kind of robots. The Addons "Blue shift" and "Opposing force" are a complete different type of problem, especially "Opposing force" is very very hard to get working without any stupid cencorship. 
I tried last year but I gave up after a couple of days,

I would like to play the uncensored version with german language and contacted steam support.
They sent me instructions to fix the problem (seen in the attachment) but unfortunately it did not work. 
I hope there will be a permanent solution for the entire german community from the start on without any fixing and trying.

![11](https://user-images.githubusercontent.com/74302131/98810583-be496800-241f-11eb-8eda-82fbc042a36b.JPG)
![22](https://user-images.githubusercontent.com/74302131/98810598-c1dcef00-241f-11eb-90a0-0fc2a9812891.JPG)
![33](https://user-images.githubusercontent.com/74302131/98810606-c4d7df80-241f-11eb-86d9-71e0193c9669.JPG)

**Comment by kisak-valve** [comment]
Hello @PatTheMad, this issue is already being tracked at #2362. Closing as a duplicate.
