### ISSUE TITLE
[CS 1.6] forces Windows 10 to go into 4:3 640 X 480 

### ISSUE THREAD

**Issue by Broch2003** [ValveSoftware/halflife#2999]
I own the Steam version of CS 1.6 and for some reason when I start the game up it forces my internal resolution to 4:3 640 X 480 while the in game setting say it in a completely different resolution. This also happens with other GoldSrc games. I am aware of -autoconfig and all that stuff that I have tried already. One other small issue is that HLDS will not open for me.

**Comment by sabianroberts** [comment]
Did you check your launch options on Steam?
If you’re opening the game from a shortcut, check the compatibility settings and make sure that “Run this program in 640 x 480” is unchecked

**Comment by BlackShadow** [comment]
> I own the Steam version of CS 1.6 and for some reason when I start the game up it forces my internal resolution to 4:3 640 X 480 while the in game setting say it in a completely different resolution. This also happens with other GoldSrc games. I am aware of -autoconfig and all that stuff that I have tried already. One other small issue is that HLDS will not open for me.

Try to reinstall the game and make sure there's no launch commands in launch options. Make sure delete files in Steamapps/common/Half-Life because Steam doesn't fully remove the games. If that didn't help list your specs so we might find a clue there.

Also HLDS GUI won't work anymore. You need to run it in console mode. To do this, create a shortcut to desktop and type -console -game cstrike +map mapname to the Target box.

**Comment by Broch2003** [comment]
- Windows 10 Pro
- 4th gen Intel i7-4770 @ 3.40 GHz 
- Samsung 32 GB of GDDR3 Ram @ 1600 MHz  
- MSI AMD 290x Lightning

**Comment by Broch2003** [comment]
> > I own the Steam version of CS 1.6 and for some reason when I start the game up it forces my internal resolution to 4:3 640 X 480 while the in game setting say it in a completely different resolution. This also happens with other GoldSrc games. I am aware of -autoconfig and all that stuff that I have tried already. One other small issue is that HLDS will not open for me.
> 
> Try to reinstall the game and make sure there's no launch commands in launch options. Make sure delete files in Steamapps/common/Half-Life because Steam doesn't fully remove the games. If that didn't help list your specs so we might find a clue there.
> 
> Also HLDS GUI won't work anymore. You need to run it in console mode. To do this, create a shortcut to desktop and type -console -game cstrike +map mapname to the Target box.

- Windows 10 Pro
- 4th gen Intel i7-4770 @ 3.40 GHz
- Samsung 32 GB of GDDR3 Ram @ 1600 MHz
- MSI AMD R9 290x Lightning
- ASUS Z87-B mobo

I did what you said and deleted the cstrike folder in C:\Program Files (x86)\Steam\steamapps\common\Half-Life\cstrike this didn't fix the issue. Do I need to delete the whole Half-Life folder?

**Comment by sjain882** [comment]
Just curious, you've checked that your compatibility settings for hl.exe haven't enabled this?

![image](https://user-images.githubusercontent.com/43217178/102489309-37625d80-4065-11eb-8065-5a991c8fe5d7.png)

**Comment by Broch2003** [comment]
> Just curious, you've checked that your compatibility settings for hl.exe haven't enabled this?
> 
> ![image](https://user-images.githubusercontent.com/43217178/102489309-37625d80-4065-11eb-8065-5a991c8fe5d7.png)

**Comment by Broch2003** [comment]
> > Just curious, you've checked that your compatibility settings for hl.exe haven't enabled this?
> > ![image](https://user-images.githubusercontent.com/43217178/102489309-37625d80-4065-11eb-8065-5a991c8fe5d7.png)

I just got a new computer and it's working the way I want it to now but I will keep that in mind if ever encounter it again thank you so much.

**Comment by shawns-valve** [comment]
Sounds like this was resolved.
