### ISSUE TITLE
[TFC] List of Bugs and Glitches

### ISSUE THREAD

**Issue by Samekh55** [ValveSoftware/halflife#3000]
-After you reload the Soldier's Rocket Launcher, the player's hand disappears from holding the weapon and only reappears after firing or switching to another weapon;

-The Pyro's Incendiary Cannon doesn't show if you are either in the red or blue team in the player's arms, instead showing a yellow-colored arms just like in regular Half-Life;

-Also the Incendiary Cannon plays its animation of the player checking the weapon's visor all the time, and if you check the "Enable HD Models if Available" in the Video section of the Options Menu, it uses the HD Pack model of the RPG from Half-Life, even though the Soldier's Rocket Launcher doesn't use it;

-When firing the Sniper Rifle in automatic mode, the firing animation sometimes keeps looping even when you stop pressing the fire key;

-In the map rock2, if you take the key to the gas chamber, the player who activates the switch dies to the nerve gas, while in the WON version of the game, they are protected from the gas because it's locked in the room while the gas is still in effect;

-In the map push, you can press the use in any of the signs spread throughout the map to turn on or off the lamps, even though their purpose is to show where the ball is;

-In the Multiplayer section of the Options menu, there's a "Crosshair appearance" option, which is a reminiscent from CS 1.6 and Condition Zero but it's completely not functional in Team Fortress Classic;

-In the Mouse section of the Options menu, there's an Auto-Aim toggle, which is also totally useless in a multiplayer-only mod like TFC and only works in single player games such as Half-Life itself.

**Comment by kisak-valve** [comment]
Hello @Samekh55, in general, multi-issue issue reports are bad for any issue tracker. Each of these should be tracked separately if they do not already have an issue report.

The TFC crosshair issue is already being tracked at #2762.
