### ISSUE TITLE
[GoldSrc] R_DrawTorus gNoise buffer overrun

### ISSUE THREAD

**Issue by s1lentq** [ValveSoftware/halflife#3004]
Discovered using AddressSanitizer
This bug doesn't affect the appearance of weird visual artifacts or the game until linker put another data below buffer.
This may lead to undefined behavior, so would be nice to fix it.

![image](https://user-images.githubusercontent.com/5860435/100797038-1807e580-3454-11eb-98ca-7ff16f4fb99f.png)

![image](https://user-images.githubusercontent.com/5860435/100793980-84ccb100-344f-11eb-984e-42c35bb9a9e4.png)

Fix proposed:
`int index = noiseIndex >> 16;`
->
`int index = (noiseIndex >> 16) % NOISE_DIVISIONS;`

**Comment by RauliTop** [comment]
@kisak-valve fix proposed?
