### ISSUE TITLE
SetLocale('en_US.UTF-8') failed.

### ISSUE THREAD

**Issue by FreeSlave** [ValveSoftware/halflife#3006]
On Linux I use my own version of hl.sh when I launch mods. The only difference is that I've manually added all Steam paths to LD_LIBRARY_PATH. Like this:

```export LD_LIBRARY_PATH="/home/freeslave/.local/share/Steam/steamapps/common/Half-Life:/home/freeslave/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/freeslave/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib32:/usr/lib32:/libx32:/usr/libx32:/lib:/usr/lib:/usr/lib/i386-linux-gnu/sse2:/usr/lib/i386-linux-gnu/i686:/usr/lib/i386-linux-gnu/i686/sse2:/home/freeslave/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/freeslave/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/freeslave/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/freeslave/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/freeslave/.local/share/Steam/ubuntu12_32/steam-runtime/lib:/home/freeslave/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib"```

The paths are taken by checking the environment of the Half-Life process launched via Steam.
This allows me to launch mods without going through steam interface and it's much easier for me to set command line options that way. However since the last engine update I started gettings warning messages (in a form of a message box, does not happen when I launch from Steam) on the startup saying:

`SetLocale('en_US.UTF-8') failed. Using 'C'. You may have limited glyph support. Please install 'en_US.UTF-8' locale.`

This makes me to press OK every time I launch the game which is very annoying. How can I fix this issue? I already have LC_CTYPE and other LC_ variables set to en_US.UTF-8. Do I miss some additional configuration done by Steam?

**Comment by kisak-valve** [comment]
Hello @FreeSlave, you can check what system-wide locale you have installed with `locale -a`. If `en_US.utf8` isn't in the list, then edit `/etc/locale.gen` and remove the leading `#` from the line with `#en_US.UTF-8 UTF-8` or add `en_US.UTF-8 UTF-8` on a new line. Then regenerate your locales with something like `sudo locale-gen`.

**Comment by FreeSlave** [comment]
@kisak-valve hello. This is my `locale -a` output:
```
C
C.UTF-8
en_US.utf8
POSIX
pt_PT.utf8
ru_RU.utf8
```

The way I extracted the `LD_LIBRARY_PATH` from Half-Life launched via Steam:
```
grep -z "^LD_LIBRARY_PATH" /proc/`pidof hl_linux`/environ
```

**Comment by kisak-valve** [comment]
Running from outside the Steam client is generally not supported, however, I made an attempt at reproducing this issue and was successful. I then gathered all the env variables in the environment Half-Life usually gets launched with by setting the game's launch options to `env > ~/game_env #%command%` and discovered that `SteamEnv=1 ./hl.sh` has an effect outside of the normal Steam launch of the game.

**Comment by FreeSlave** [comment]
Thank you. Adding SteamEnv=1 fixed the issue. Closing.
