### ISSUE TITLE
Non-complete Russian localization, which is also not added to the txt file.

### ISSUE THREAD

**Issue by DrHesperusModoVestnic** [ValveSoftware/halflife#3014]
![1](https://user-images.githubusercontent.com/37004902/102718962-f12f2780-430c-11eb-954e-c2c447b03333.png)
![2](https://user-images.githubusercontent.com/37004902/102718968-f55b4500-430c-11eb-8544-9f2115b9d976.png)
Everything, that shown is not translated as well as don't is it added to the txt file.

**Comment by kisak-valve** [comment]
Hello @DrHesperusModoVestnic, this issue is already being tracked at #2311. Closing as a duplicate.
