### ISSUE TITLE
SOLID_VPHYSICS (Counter-Strike 1.6)

### ISSUE THREAD

**Issue by teddiboy** [ValveSoftware/halflife#3015]
Hi, can it be done in Counter-Strike 1.6 SOLID_VPHYSICS? I know i can do to in CS: GO and it works great. I also know $ flags 512 per model but I would like to code. Possible update? Greetings.

**Comment by Solokiller** [comment]
VPhysics is part of Source, it doesn't exist in GoldSource.

**Comment by kisak-valve** [comment]
Thanks @Solokiller, closing per the last comment.
