### ISSUE TITLE
[ HL1, CS 1.6 ] CPU - not using enough resources to meet performance request

### ISSUE THREAD

**Issue by adversaru** [ValveSoftware/halflife#3032]
This issue im having is about what the title says - the game isn't using enough resources to meet maxim performance.
Specs PC ( saw on youtube ) - https://www.youtube.com/watch?v=bSSrh380kBs&ab_channel=zWORMzGaming

Intel i7-4770
Nvidia GTX 1060 - 6GB
RAM 12GB DDR3 1600MHz Dual Channel
This person is recording the game playing CS 1.6 using the specs specified earlier and reach even 1000 FPS +.

My LAPTOP specs
Intel i7-10750H
Nvidia RTX 2060 - 6GB
RAM 16GB DDR4 - 3200 MHz Dual Channel
With these specs, my game reach in turbo boost mode ( touching even 5.0 ghz on single core ) just 400-500 FPS.

As i know, the engine of HL1 - CS 1.6 is absolutely single core and the idea of it is simple:
Even if the game is single core, the problem is that the game isn't using enough resources from the single core he want to use.
What do i mean? i'm sure my processor can reach 1000 FPS on single core, as it is faster than the old i7-4770 that appear reaching 1000 FPS in the video attached above. The thing is the game is somehow on adaptive mode, using enough resources as it wants to use. I can see in the task manager that the process hl is using ONLY 1.5 % out of processor and i think that's the problem.
If i run the game on dedicated card or integrated one, its the same result. The game doesnt benefit not a little fps from using the graphics card. Of course, i'm using OpenGL renderer.

The question is: how i can force it to use more power from the CPU so it tries harder to meet my request on FPS_MAX ? because the engine obviously dont do that.
-

**Comment by djdallmann** [comment]
The video mentioned a Xeon processor which is intended for use in servers, it is different but similar to the Core i7-4770, the Xeon doesn't have a graphics processor and has a few other features.
https://ark.intel.com/content/www/us/en/ark/products/80910/intel-xeon-processor-e3-1231-v3-8m-cache-3-40-ghz.html
https://ark.intel.com/content/www/us/en/ark/products/75122/intel-core-i7-4770-processor-8m-cache-up-to-3-90-ghz.html

The video also shows stable drops to 500-700, fps will be dependent on settings ingame and graphics control panel, what's on screen or part of the map.

**Comment by adversaru** [comment]
> The video mentioned a Xeon processor which is intended for use in servers, it is different but similar to the Core i7-4770, the Xeon doesn't have a graphics processor and has a few other features.
> https://ark.intel.com/content/www/us/en/ark/products/80910/intel-xeon-processor-e3-1231-v3-8m-cache-3-40-ghz.html
> https://ark.intel.com/content/www/us/en/ark/products/75122/intel-core-i7-4770-processor-8m-cache-up-to-3-90-ghz.html
> 
> The video also shows stable drops to 500-700, fps will be dependent on settings ingame and graphics control panel, what's on screen or part of the map.

Ok, i understand this now but.. in the end, the conclusion is: nothing can be done to force the game to use more resources so he can reach my request? the engine is old and bad, i know, but mnah, im asking, maybe someone out there knows a trick. 
Thanks mate.

**Comment by djdallmann** [comment]
Your hl.exe should be using much more CPU than 1.5%, it's a cpu dependent game. Are you checking when alt-tabbed or using another method to capture cpu usage while it's in the foreground/on-screen?

**Comment by adversaru** [comment]
> Your hl.exe should be using much more CPU than 1.5%, it's a cpu dependent game. Are you checking when alt-tabbed or using another method to capture cpu usage while it's in the foreground/on-screen?

Yes, im checking alt-tabbed.
But anyway, i dont think the actual usage of CPU really matter because im sure it cant be 100% using my CPU. The only thing that matters ( at least for me ) is how to force it to use more power from the CPU.

**Comment by sketchycrypt** [comment]
The game is locked to 1 cpu core, I don't think there is a way to make it multi threaded, The only thing i can think of is making the game High/Realtime priority in the task manager.

**Comment by adversaru** [comment]
> The game is locked to 1 cpu core, I don't think there is a way to make it multi threaded, The only thing i can think of is making the game High/Realtime priority in the task manager.

Thanks for ur reply.
No, you can make it multi-threaded, for that, the rendering engine should be rewrited.
The Priority set in Taskmgr doesn't help.
