### ISSUE TITLE
[Opposing Force] Game crash on loading after quicksaving during shock attack

### ISSUE THREAD

**Issue by Aynekko** [ValveSoftware/halflife#3060]
How to reproduce: make a shot using shock roach. While the projectile is still flying through the air - quicksave. Then load the game and it will crash.

Same applies if you quicksave during shock trooper's attack (while the projectile is still flying).

**Comment by kisak-valve** [comment]
Hello @Aynekko, this issue is already being tracked at #2363. Closing as a duplicate.
