### ISSUE TITLE
[Counter-Strike] Steam Join Game Feature Not Working

### ISSUE THREAD

**Issue by hashnimmo** [ValveSoftware/halflife#3068]
Steam profiles show a **Join Game** button whenever someone is playing Counter-Strike. Nothing happens when I click on it, the button contains a `steam://` link and there's no server address in it.

![cs-join-game-button-not-working](https://user-images.githubusercontent.com/24617729/109413588-3a1def00-79d4-11eb-97ba-1a3582749a28.png)

**Comment by kisak-valve** [comment]
Hello @hashnimmo, this reads like a general Steam Community web server issue. Please report it to [Steam Support](https://help.steampowered.com/).

**Comment by hashnimmo** [comment]
**Update**: I have checked another player's profile and it was working, maybe it wasn't working before because that player I have mentioned in this issue was probably in the main menu of the game and not actually in a server.

This issue is solved, posting this as additional information for future reference.
