### ISSUE TITLE
[Counter-Strike] Bots & VAC Icons Aren't Centered

### ISSUE THREAD

**Issue by hashnimmo** [ValveSoftware/halflife#3072]
Bots and VAC column icons in the server browser aren't centered like the Password column icon. Also, the VAC icons in each row aren't aligned with the VAC column icon. [#2481](https://github.com/ValveSoftware/halflife/issues/2481#issuecomment-516488403)

![62012569-b9ac6200-b190-11e9-8cce-209b5a8604c5](https://user-images.githubusercontent.com/24617729/110432675-6f61c580-80d5-11eb-934e-c0a0d02246d2.png)

**Comment by kisak-valve** [comment]
Hello @hashnimmo, this issue is already being tracked at #2624. Closing as a duplicate.
