### ISSUE TITLE
[CS 1.6]  doesnt exit properly on Fedora Linux

### ISSUE THREAD

**Issue by nakobejo** [ValveSoftware/halflife#3093]
when exit game just stuck on this screen
![Screenshot_20210409_044856](https://user-images.githubusercontent.com/49896401/114155354-99fca380-994b-11eb-82bd-04f8b0add5e7.png)
only happen at Fedora 33, other distro work just fine
already tried steam linux runtime, still have this problem

**Comment by kisak-valve** [comment]
Hello @nakobejo, this issue is already being tracked at #2703. Closing as a duplicate.
