### ISSUE TITLE
[1.6] Strange bullet spread behavior on some online servers (loss of precision)

### ISSUE THREAD

**Issue by exegg** [ValveSoftware/halflife#3098]
Hi, I have suffered this issue for as long as I can remember with my ISP. So I come here for help if maybe you can find a better solution for me.

To keep it short, my bullet precision is messed up on a lot of the online servers I like to play. For the sake of comparison, this is how it is supposed to go. Even with the added latency of playing online, the bullet spread should be very similar.

https://user-images.githubusercontent.com/19347211/114974051-ab641500-9e4f-11eb-93c2-3b7b3b1711bb.mp4

And this is how it goes

https://user-images.githubusercontent.com/19347211/114974127-cc2c6a80-9e4f-11eb-8a93-c4c75969ce7e.mp4

The only solution that brings it back to normal when I play online is using a VPN. Or another ISP. My conection is from a TV provider so I use a cable modem attached to a router, wired or wireless does the same thing.

Is there any settings that might be causing this disbalance with my ISP that makes my game play like this online? It is very annoying as basically shooting is ruined. I have compensated a lot of it in the years I've been playing but it has been bugging me out the whole time and I remembered this place existed and maybe a solution could be found. Playing behind a VPN is suboptimal because a lot of reasons, more latency and having to pay for one in order to get a stable service.

**Comment by Maxi605** [comment]
600ms is quite a lot of ping. depends on the servers rates and fps too

**Comment by exegg** [comment]
> 600ms is quite a lot of ping. depends on the servers rates and fps too

Hi when you see the demos with viewdemo the ping through net graph is all over the place. My actual ping was around 70. Is not a ping issue since with VPN I get about 120 and the bullets fire like in the first clip.

**Comment by Automatics** [comment]
can you label and upload some demos of correct and incorrect gameplay in a zip or rar?
