### ISSUE TITLE
hw.dll failed to load

### ISSUE THREAD

**Issue by Drek282** [ValveSoftware/halflife#3107]
I'm getting this error using Proton on Steam on Linux to launch mods for which there are only good working Windows versions.  Half-Life won't launch this way, neither will Firearms 3.0 or Natural Selection 3.2.  I've tried the latest three versions of Proton, including experimental.  I've tried renaming hw.dll and verifying the cache.

I've run both Firearms and Natural Selection successfully this way for about a year.  I don't know when exactly the hw.dll error started, but my guess is a recent Half-Life or Steam update is causing the problem, and there has been at least one recent Steam update.

I'm running Debian Bullseye (testing).

**Comment by kisak-valve** [comment]
Hello @Drek282, issues with games run with Proton are not tracked in this issue tracker. Running Half-Life and mods of it with Proton is not officially supported.

That said, unofficially, it looks like there isn't a compatibility report for Half-Life (1), so feel free to open a new [compatibility report](https://github.com/ValveSoftware/Proton/issues/new?assignees=&labels=&template=compatibility-report.md) for the Proton devs to ponder the issue you're seeing.
