### ISSUE TITLE
HLDS Crashing

### ISSUE THREAD

**Issue by J1327** [ValveSoftware/halflife#3117]
-insecure

> Faulting application name: hlds.exe, version: 4.1.1.1, time stamp: 0x5f28cdba
> Faulting module name: crashhandler.dll, version: 6.64.77.14, time stamp: 0x60df60e7
> Exception code: 0xc0000409
> Fault offset: 0x0002bbf1
> Faulting process id: 0x21c8
> Faulting application start time: 0x01d772b728e76f88
> Faulting application path: G:\STEAM\steamapps\common\Half-Life\hlds.exe
> Faulting module path: G:\STEAM\crashhandler.dll
> Report Id: 90af15ea-7c6b-4077-a565-066f9cbe85bd
> Faulting package full name: N/A
> Faulting package-relative application ID:  N/A

> Faulting application name: hlds.exe, version: 4.1.1.1, time stamp: 0x5f28cdba
> Faulting module name: mp.dll, version: 0.0.0.0, time stamp: 0x5f28cdd1
> Exception code: 0xc0000005
> Fault offset: 0x0009c209
> Faulting process id: 0x21c8
> Faulting application start time: 0x01d772b728e76f88
> Faulting application path: G:\STEAM\steamapps\common\Half-Life\hlds.exe
> Faulting module path: G:\STEAM\steamapps\common\Half-Life\cstrike\dlls\mp.dll
> Report Id: e6edc60f-d3b9-4c77-be16-9d64161b2656
> Faulting package full name: N/A
> Faulting package-relative application ID: N/A

> Fault bucket , type 0
> Event Name: APPCRASH
> Response: Not available
> Cab Id: 0
> Problem signature:
> P1: hlds.exe
> P2: 4.1.1.1
> P3: 5f28cdba
> P4: mp.dll
> P5: 0.0.0.0
> P6: 5f28cdd1
> P7: c0000005
> P8: 0009c209
> P9: N/A
> P10: N/A

> Fault bucket 1759231262340868248, type 5
> Event Name: BEX
> Response: Not available
> Cab Id: 0
> Problem signature:
> P1: hlds.exe
> P2: 4.1.1.1
> P3: 5f28cdba
> P4: crashhandler.dll
> P5: 6.64.77.14
> P6: 60df60e7
> P7: 0002bbf1
> P8: c0000409
> P9: 00000007
> P10:  N/A

it no matter if i use steam HLDS or github reHLDS it crashes anyway , self , randomly ;

**Comment by xLeviNx** [comment]
steam HLDS is outdated. Use Steamcmd.
