### ISSUE TITLE
Counter-Strike Hitbox Issue

### ISSUE THREAD

**Issue by Tortuna** [ValveSoftware/halflife#3118]
Hi,
My name is Tuna. I have been playing CS 1.6 for a long time. I really like this game and I have given many years into this game. Thanks to Valve for this beautiful game.

Today, the problem I want to share with you is about hitboxes.
I am really troubled with this problem to the point that I don't really enjoy playing.

When I fire, my bullets don't get to the target even though they do. This is because hitboxes are problematic as seen on the video.

https://www.youtube.com/watch?v=umEO6BDsEwM&t=92s

I would really like to get any kind of information or document to help me solve this problem.

Thanks.
Tuna

**Comment by kisak-valve** [comment]
Hello @Tortuna, this issue is already being tracked at #2154. Closing as a duplicate.

**Comment by Tortuna** [comment]
Hi again.
As a CS player, I know that this problem has been going on for years.
Please solve this problem now or we, CS players, will quit now and find another game.
I would like you to solve this problem. I can not enjoy playing. That a rooted firm like Valve cannot solve this problem is absurd.
Please do what is necessary and solve this problem.
Or the respect and belief in you will be shaken completely and I will have to quit this platform even if I really do not want to.
