### ISSUE TITLE
[Condition Zero] Missing sound files for de_fastline_cz map

### ISSUE THREAD

**Issue by Vladislav4KZ** [ValveSoftware/halflife#3120]
When you launch the de_fastline_cz map you may notice that the console writes warnings about missing sound files

Like that:
```
BUILD 8684 SERVER (0 CRC)
Server # 1
Warning:  Unable to open sound/ambience/fastline/misc_vendmachine_loop.wav for transfer
Warning:  Unable to open sound/ambience/fastline/fastline_station3.wav for transfer
Warning:  Unable to open sound/ambience/fastline/fastline_turnreject.wav for transfer
Warning:  Unable to open sound/ambience/fastline/fastline_station2.wav for transfer
Warning:  Unable to open sound/ambience/fastline/fastline_station4.wav for transfer
Error: server failed to transmit file 'sound/ambience/fastline/misc_vendmachine_loop.wav'
Error: server failed to transmit file 'sound/ambience/fastline/fastline_station3.wav'
Error: server failed to transmit file 'sound/ambience/fastline/fastline_turnreject.wav'
Error: server failed to transmit file 'sound/ambience/fastline/fastline_station2.wav'
Error: server failed to transmit file 'sound/ambience/fastline/fastline_station4.wav'
```

I found these sounds in the "Counter-Strike Condition Zero: Deleted Scenes" in the czeror\sound\ambience folder

And I took these sounds and copied them to the right folder. After that, I noticed that sounds appeared on this map, and the warnings in the console disappeared

**Comment by Vladislav4KZ** [comment]
Created an archive with all the missing sounds for this map
[fastline.zip](https://github.com/ValveSoftware/halflife/files/6796829/fastline.zip)
It needs to be unzipped into the "Half-Life/czero/sound/ambience" folder

**Comment by kisak-valve** [comment]
Hello @Vladislav4KZ, this issue is already being tracked at #1465. Feel free to add a note there.

Closing as a duplicate.
