### ISSUE TITLE
[Condition Zero] Buy presets bug

### ISSUE THREAD

**Issue by Vladislav4KZ** [ValveSoftware/halflife#3121]
The menu for selecting how many ammo clips to buy hides into the background
![Снимок экрана (26) (1).png](https://user-images.githubusercontent.com/22411953/125960220-5ad0e360-b726-4faf-be2e-29ce4a5de98c.png)
Because of this, no menu item can be selected.

Also, when pressed, the text covers the yellow rectangle.
![Снимок экрана (26) (2).png](https://user-images.githubusercontent.com/22411953/125960770-71725d0b-b13a-4a22-bd29-f177c932612d.png)
Because of this, it is not visible which menu item is selected.

**Comment by kisak-valve** [comment]
Hello @Vladislav4KZ, this issue is already being tracked at #2034. Closing as a duplicate
