### ISSUE TITLE
Half-Life's main menu does not play music until alt-tab'd

### ISSUE THREAD

**Issue by BlackShadow** [ValveSoftware/halflife#3124]
Game still have issues with MP3.

• First one is, if Half-Life has gamestartup.mp3 added by user, it plays in every other game if gamestartup is not present in those games.

• If user creates a LAN game or joins a internet game, when playing singleplayer while music playing at the same time, music still goes on in multiplayer.

• For some reason Half-Life doesn't play any music in Main Menu until game is ALT + TAB'ed.

• (Half-Life Only) Main Menu music still plays when in-game. 

• Expansions and mods still facing music cutting issue.

• Although i'm not sure if this is intentional but leaving a server and returning to main menu, music doesn't play anymore.

**Comment by kisak-valve** [comment]
Hello @BlackShadow, the majority of these are already being discussed at #570. It looks like the third bullet point is not mentioned there, so let's use this issue report to focus specifically on that issue.

**Comment by BlackShadow** [comment]
Needs retesting closing it for now.
