### ISSUE TITLE
[CS 1.6] New Freeze issue

### ISSUE THREAD

**Issue by Maxi605** [ValveSoftware/halflife#3151]
Can't give much info about it, with the new issues that started happening (crashes, steam pictures not showing, etc.) seems to introduce another bug where the game randomly freezes for everyone (Everyone that uses Steam, that is). Can't say what causes it, i got no info about it.

**Comment by motelbible** [comment]
How often does it happen on a daily basis? Is it on every server you join? How exactly is the "freeze"?

**Comment by Maxi605** [comment]
Can't tell, it looks quite random, is on any server and it affects every steam client in it. It's a normal game freeze, like the game stops responding for a few seconds

**Comment by motelbible** [comment]
I thought you meant as in a screen freeze, but it's actually a game freeze (you can look around but cant move, right?)

**Comment by fox3562** [comment]
the fact that the problem is in your PC, have you ever had a thought? xD

**Comment by fox3562** [comment]
miracle or miraculous coincidence  xD

**Comment by Maxi605** [comment]
> miracle or miraculous coincidence xD

Doubtful, with the issues that started happening lately. My PC runs the game perfectly fine, always had, this freeze issue started with the other issues (People having the game crashing, steam pictures not showing, weird frequent game updates that don't update anything)

**Comment by fox3562** [comment]
Why don't I have freeze? 
The game does not crash and there are no other problems. xD
You have problem with your PC or connect to server or server.
Bu the way, the game has not been updated for more than a year...

**Comment by Maxi605** [comment]
> Why don't I have freeze?

I don't know, this happened twice in different servers and multiple people confirmed that it happened to them at the same time.

> The game does not crash and there are no other problems.

For you it might not crash, other people do get the crash, as seen here https://github.com/ValveSoftware/halflife/issues/3147

> You have problem with your PC or connect to server or server.

The issue is not on my end or on the server end, otherwise i would report said issue.

> Bu the way, the game has not been updated for more than a year...

I'm aware of this, like i said, this is another issue that got shipped with the other ones where the game updates (not for everyone) for some reason but nothing changes.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.

**Comment by Maxi605** [comment]
This continues to happen, more frequent than before and the freezes are getting longer.

**Comment by Maxi605** [comment]
Can't reproduce this issue anymore. Could've been a hdd issue.
