### ISSUE TITLE
Common ammo pool for mp5 smg and terrorist glock pistol

### ISSUE THREAD

**Issue by pingumaharaj** [ValveSoftware/halflife#3153]
Hi,
counter-Strike 1.6 : Buying ammo for the glock pistol in terrorists also buys ammo for the mp5 smg. Spending the mp5 ammo also reduces the glock reserve ammo count, even if you are not firing the glock.

As far as i know this is not supposed to happen. they seem to have a common pool of extra ammo or something.

Example : say i have 20 / 100 bullets of glock , i will get 100 of mp5 too.
after firing the glock and reloading , i get 20/80 after reload , and 30/80 of the mp5 too despite not having used the mp5 . the mp5 counter shouldnt be deducted unless you are spending mp5 bullets and reloading.

Can this be resolved?

**Comment by pingumaharaj** [comment]
Yes , but if i am firing the mp5 , and not using the glock at all , why
does it reduce the counter for the glock which has not been used at all ?
This is was not so before as far as I can tell.
Attaching relevant screenshots :

**Comment by SamVanheer** [comment]
That's intentional behavior, and has been for all of Counter-Strike's existence. Half-Life also does this.

**Comment by pingumaharaj** [comment]
Awesome, thanks!
