### ISSUE TITLE
Counter-strike launches slowly

### ISSUE THREAD

**Issue by Catishere** [ValveSoftware/halflife#3155]
I've been having this issue for years on my old build and I have it now. Please do something.

Title -
Counter-strike launches slowly

Environment -

Windows 10 Pro, Build 19043.1288
Intel i5-11600K
NVidia GTX 1060 6GB, Driver version 496.13
16GB RAM 3200MHZ
Keyboard layouts: US International, BG, JP
Launch options: -freg 144

Steps to reproduce -
1. Launch the game in steam

Expected Result
The game launches instantly

Actual Result
The game launches after 20-30 seconds.

Severity/Priority
Moderate

**Comment by molecula451** [comment]
Ideal would be if you paste a short clip of your issue to see how slow it launches

**Comment by Catishere** [comment]
> Ideal would be if you paste a short clip of your issue to see how slow it launches

It seems like its a problem with windows. I'm gonna close this issue and investigate further
