### ISSUE TITLE
hl1 engine games crash on Arch linux, glibc error?

### ISSUE THREAD

**Issue by kellerman** [ValveSoftware/halflife#3161]
#### Your system information

- Steam client version (current)
- Distribution: Arch Linux (latest)
- Opted into Steam client beta?: [No]
- Have you checked for system updates?: [Yes]
- System specs: i5-6600K, Nvidia GTX1660, Asus Z170-A, 24GB DDR4 memory

#### Please describe your issue in as much detail as possible:

When trying to launch any HL1 engine game, the game throws out this error and doesnt launch. Tried both Steam native and runtime versions. Cant find much information, just one guy with similar system and same problem
https://forum.manjaro.org/t/counter-strike-1-6-run-problem/70974
```
hl_linux: **malloc.c:2539: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed**.
/mnt/dati/Steam/steamapps/common/Half-Life/hl.sh: line 43:  5251 Aborted                 (core dumped) ${DEBUGGER} "${GAMEROOT}"/${GAMEEXE} $@
Game process removed: AppID 10 "/home/km/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=10 -- '/mnt/dati/Steam/steamapps/common/Half-Life/hl.sh' -steam -game cstrike", ProcID 5247 
```

#### Steps for reproducing this issue:

1. Start steam using terminal
2. Launch any Half Life engine based game ( Half Life, Counter Strike, Day of Defeat Classic, Ricochet etc...)
3. Check terminal output of the error

**Comment by kisak-valve** [comment]
Hello @kellerman, this issue is already being tracked at #3158. Closing as a duplicate.
