### ISSUE TITLE
[CS 1.6]Microfreezes every few seconds

### ISSUE THREAD

**Issue by SanAntonio2** [ValveSoftware/halflife#3164]
When playing on servers, I catch the screen freezing every few seconds. If you enable net_graph, then during friezes the green bar bounces and immediately falls as in the screenshot below:
![ApplicationFrameHost_YftZiDhrrw](https://user-images.githubusercontent.com/47498583/141810829-47bf61ef-6037-4647-a294-dc438f1ede0a.png)

For the solution I tried:
- Reinstall cs (did not help)
- Reinstall OS (Windows 7 was installed, installed 10, did not help)
 
A little information:
* Steam and CS are installed on the hard drive, Windows are on ssd.
* Freezes occur only in CS 1.6, in other games there are no problems with this, of course there may be a problem on other goldsrc games, I have not tested it here.
* CPU: AMD Phenom II x4 965; GPU: Nvidia GeForce GTX 560; HDD: PATA 120Gb; RAM: DDR2 8Gb(4+4);
* rate 100k; updaterate 102; cmdrate 102; ex_interp 0.02; cmdbackup 2;

I sin on the hard drive where the CS is, although in different programs for monitoring the health of the disks, it says that everything is fine. I read somewhere that the friezes can be due to the smart behavior of the hard drive (after 5-6 seconds of inactivity, it parks the head unit, and when trying to read something, unparks them, while the entire system freezes for a short time). So far there is no way to check if the issue is in the disk and something tells me that even if the disk is replaced, friezes may remain. Please try to help find the issue elsewhere. In any case, I planned to buy the disc, but most likely this will happen at the end of the month, if the issue was in the disc, I will unsubscribe here.

**Comment by metita** [comment]
Can confirm the game freezes randomly since a few months already, cannot reproduce.

**Comment by Maxi605** [comment]
Probably related to https://github.com/ValveSoftware/halflife/issues/3151, in my case, this happened to everyone on the server (Except no-steam users)

**Comment by Automatics** [comment]
when i use opengl games on my secondary drive my game stutters constantly, when it's on the windows drive it works normally.

move your stuff to your c drive and try

**Comment by fox3562** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/72519728/143912236-0f0505f3-4a26-4362-80c4-bde6a2c15283.jpg)
the green graph shows the quality of the connection, and in this case, the reason may be a network lag. try to run CS locally (preferably with bots), if there is no problem, then most likely the problem is in the connection. 
For diagnostics, make a trace and look at the drawdown by ping (as a variant of ping with the -t flag), if there are drawdowns in time, then this will be the reason for your "freezes".
(also try ex_interp to put 0.1. If the "friezes" disappear, then this will also indicate a problem with the connection)
P.s. sorry for my English, I use a translator.

**Comment by SanAntonio2** [comment]
> For diagnostics, make a trace and look at the drawdown by ping (as a variant of ping with the -t flag), if there are drawdowns in time, then this will be the reason for your "freezes".

send / received - 193
lost - 0%
max ping 41
average ping 25-30

A new hard drive will arrive very soon. I will immediately make a report after testing if there will be any changes. Also, the reason may be in crooked drivers, I will deal with latencymon if the reason is not in the disk.

**Comment by SanAntonio2** [comment]
Report: Microfreezes disappeared on ssd, therefore, the problem was in my old IDE / PATA hard drive.
