### ISSUE TITLE
Would it be possible to compile this to JavaScript with emscripten?

### ISSUE THREAD

**Issue by nuggetofwisdom** [ValveSoftware/halflife#3180]
I've been messing around with emscripten (A compiler to compile things to the web) and I was wondering if it was possible to compile this to JavaScript with emscripten. If you could help, that would be SO AMAZING!!

Thanks!

**Comment by ChaoticPumpkin** [comment]
Someone [did that exact thing](https://icrazyblaze.github.io/Xash3D-Emscripten/xash-intro.html) with Xash3D, so I could totally see it being possible with the original engine, good luck!
