### ISSUE TITLE
Add support for LTR languages please

### ISSUE THREAD

**Issue by prozinsky** [ValveSoftware/halflife#3218]
I know it's an old game, but many are still playing it and I think it would be an easy fix for the developers
The issue is that LTR languages, such as Hebrew, are displayed in reverse in the chat, so you have to type everything opposite to display it correctly.

For example if it was in English, I'd need to type "esaelp siht xiF" so that it will be displayed as "Fix this please"
Or, an example in Hebrew in-game: [https://imgur.com/a/Ix9quJN](https://imgur.com/a/Ix9quJN)
Thanks

**Comment by kisak-valve** [comment]
Hello @prozinsky, I'm guessing you meant to write right to left languages in this context, and this issue is already being tracked at #2507. Closing as a duplicate.
