### ISSUE TITLE
directblit / nodirectblit usage question

### ISSUE THREAD

**Issue by SanAntonio2** [ValveSoftware/halflife#3219]
For what and in what cases the launch parameters **"nodirectblit"** and "**directblit"** are used? Obviously, the game works fine for me without these parameters, I just would like to know, from the technical side, what will change in the game.

**Comment by SmileyAG** [comment]
# Definition:

Slightly makes a game textures look different.

# Techincal side:

`-directblit` passes **GL_EXT_framebuffer_multisample_blit_scaled** extension to OpenGL.

And, `-nodirectblit` forces to disable that extension.
