### ISSUE TITLE
[HL1][PC] Could not load hw.dll

### ISSUE THREAD

**Issue by Bukethead** [ValveSoftware/halflife#323]
I've updated Half Life and verified the game cache, I still receive this error message immediately after launching. 

![fatalerror](https://f.cloud.github.com/assets/3620872/165557/d7a1ae80-7954-11e2-8aa0-e6b38bc3165f.jpg)

<code>Processor Information:
    Vendor:  GenuineIntel
    Speed: 2937 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Windows XP (32 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  LogMeIn Mirror Driver

```
DirectX Driver Name:  ati2dvag.dll
Driver Version:  2.50.596
DirectX Driver Version:  6.14.10.7261
Driver Date: 17 Sept 2010
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 75 Hz
DirectX Card: ATI Radeon HD 4600 Series
VendorID:  0x1002
DeviceID:  0x9490
Number of Monitors:  1
Number of Logical Video Cards:  1
No SLI or Crossfire Detected
Primary Display Resolution:  1280 x 1024
Desktop Resolution: 1280 x 1024
Primary Display Size: 14.76" x 11.81"  (18.90" diag)
                                        37.5cm x 30.0cm  (48.0cm diag)
Primary Bus Type Not Detected
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 
```

Sound card:
    Audio device: Realtek HD Audio output

Memory:
    RAM:  3071 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  1240017 Mb
    Largest Free Hard Disk Block:  753778 Mb
    OS Install Date: Feb 05 2010
    Game Controller: None detected

Installed software:
    µTorrent
    3.4.0.9271.1
    32 Bit HP CIO Components Installer
    Adobe Flash Player 11 ActiveX
    Adobe Flash Player 11 Plugin
    Adobe Reader X (10.1.4)
    AIO_Scan
    AMD Catalyst Install Manager
    ARMA 2 Army of The Czech Republic - Data cache removal
    ARMA 2: British Armed Forces
    ARMA 2: British Armed Forces - Data cache removal
    ARMA 2: Operation Arrowhead
    Arma 2: Operation Arrowhead Beta
    ARMA 2: Private Military Company
    ARMA 2: Private Military Company - Data cache removal
    ATI AVIVO Codecs
    ATI Catalyst Control Center
    ATI Parental Control & Encoder
    ATI Problem Report Wizard
    Audacity 1.3.13 (Unicode)
    Audiosurf
    Auslogics Duplicate File Finder
    AutoCAD 2012 - English
    AutoCAD 2012 Language Pack - English
    Autodesk Content Service
    Autodesk Inventor 2013 Quick Uninstaller
    Autodesk Inventor Professional 2013
    Autodesk Inventor Professional 2013 English
    Autodesk Inventor Professional 2013 English Language Pack
    Autodesk Material Library 2012
    Autodesk Material Library 2013
    Autodesk Material Library Base Resolution Image Library 2012
    Autodesk Material Library Base Resolution Image Library 2013
    Autodesk Material Library Low Resolution Image Library 2013
    Autodesk Sync
    Avira Free Antivirus
    Bandicam
    Bandisoft MPEG-1 Decoder
    BattlEye for OA Uninstall
    BufferChm
    CamStudio version 2.7
    Catalyst Control Center
    Catalyst Control Center - Branding
    Catalyst Control Center Core Implementation
    Catalyst Control Center Graphics Full Existing
    Catalyst Control Center Graphics Full New
    Catalyst Control Center Graphics Light
    Catalyst Control Center Graphics Previews Common
    Catalyst Control Center HydraVision Full
    Catalyst Control Center InstallProxy
    Catalyst Control Center Localization All
    CCC Help Chinese Standard
    CCC Help Chinese Traditional
    CCC Help Czech
    CCC Help Danish
    CCC Help Dutch
    CCC Help English
    CCC Help Finnish
    CCC Help French
    CCC Help German
    CCC Help Greek
    CCC Help Hungarian
    CCC Help Italian
    CCC Help Japanese
    CCC Help Korean
    CCC Help Norwegian
    CCC Help Polish
    CCC Help Portuguese
    CCC Help Russian
    CCC Help Spanish
    CCC Help Swedish
    CCC Help Thai
    CCC Help Turkish
    ccc-core-preinstall
    ccc-core-static
    ccc-utility
    CCleaner
    Color Cop 5.4.3
    Company of Heroes
    Copy
    Core Temp version 0.99.7
    CPUID CPU-Z 1.60.1
    CPUID HWMonitor 1.19
    CwGet V2.26
    DayZ Commander
    dBpoweramp Music Converter
    dBpoweramp Windows Media Audio 10 Codec
    Destination Component
    DeviceDiscovery
    DeviceManagementQFolder
    DivX Setup
    DocProc
    DocProcQFolder
    Dota 2
    Dwarfs F2P
    DWG TrueView 2013
    Dxtory version 2.0.114
    EaseUS Todo Backup Free 5.5
    Fallout Mod Manager 0.12.6
    FARO LS 1.1.406.58
    ffdshow v1.1.3507 [2010-07-07]
    FL Studio 10
    Folder Size for Windows
    Fraps (remove only)
    Freemake Video Converter version 3.2.1
    GameSpy Arcade
    Garry's Mod
    GCFScape 1.8.2
    GIMP 2.8.0
    GoldWave v5.20
    Google Earth
    Google Talk Plugin
    Google Update Helper
    Guitar Pro 5.2
    Half-Life
    Half-Life: Blue Shift
    Half-Life: Opposing Force
    High Definition Audio Driver Package - KB888111
    Hotfix for Microsoft .NET Framework 3.5 SP1 (KB953595)
    Hotfix for Microsoft .NET Framework 3.5 SP1 (KB958484)
    Hotfix for Windows Media Format 11 SDK (KB929399)
    Hotfix for Windows Media Player 11 (KB939683)
    Hotfix for Windows XP (KB2443685)
    Hotfix for Windows XP (KB2633952)
    Hotfix for Windows XP (KB938759)
    Hotfix for Windows XP (KB942288-v3)
    Hotfix for Windows XP (KB952287)
    Hotfix for Windows XP (KB954550-v5)
    Hotfix for Windows XP (KB961118)
    Hotfix for Windows XP (KB976098-v2)
    Hotfix for Windows XP (KB979306)
    Hotfix for Windows XP (KB981793)
    HP Imaging Device Functions 9.0
    HP OCR Software 9.0
    HP Photosmart All-In-One Software 9.0
    HydraVision
    IL Download Manager
    IrfanView (remove only)
    J2SE Runtime Environment 5.0 Update 21
    Java 7 Update 13
    Java Auto Updater
    Java(TM) 6 Update 29
    JDownloader 0.9
    LAME v3.99.3 (for Windows)
    Left 4 Dead 2
    Livestream Procaster
    LogMeIn Hamachi
    Malwarebytes Anti-Malware version 1.70.0.1100
    ManyCam 2.6.55 (remove only)
    MediaInfo 0.7.47
    Microsoft .NET Framework 2.0 Service Pack 2
    Microsoft .NET Framework 3.0 Service Pack 2
    Microsoft .NET Framework 3.5 SP1
    Microsoft .NET Framework 4 Client Profile
    Microsoft .NET Framework 4 Extended
    Microsoft Application Error Reporting
    Microsoft Chart Controls for Microsoft .NET Framework 3.5 (KB2500170)
    Microsoft Choice Guard
    Microsoft Compression Client Pack 1.0 for Windows XP
    Microsoft Games for Windows - LIVE Redistributable
    Microsoft Games for Windows Marketplace
    Microsoft Internationalized Domain Names Mitigation APIs
    Microsoft Kernel-Mode Driver Framework Feature Pack 1.5
    Microsoft MPEG-4 VKI Video Codec V1/V2/V3
    Microsoft National Language Support Downlevel APIs
    Microsoft Silverlight
    Microsoft User-Mode Driver Framework Feature Pack 1.0
    Microsoft Visual C++ 2005 Redistributable
    Microsoft Visual C++ 2008 Redistributable - x86 9.0.21022
    Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729
    Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17
    Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.4148
    Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.6161
    Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219
    Microsoft Visual Studio 2005 Tools for Applications - ENU
    Microsoft WSE 3.0 Runtime
    Microsoft XNA Framework Redistributable 3.1
    Microsoft XNA Framework Redistributable 4.0
    Mozilla Firefox 18.0.2 (x86 en-US)
    Mozilla Maintenance Service
    Mozilla Thunderbird 17.0.2 (x86 en-US)
    Mp3tag v2.49b
    MSI Afterburner 2.3.1
    MSVCRT
    MSVCRT Redists
    MSXML 4.0 SP2 (KB954430)
    MSXML 4.0 SP2 (KB973688)
    MSXML4 Parser
    NETGEAR WG111v3 wireless USB 2.0 adapter
    Network Stumbler 0.4.0 (remove only)
    Notepad++
    NVIDIA PhysX
    OpenAL
    OpenOffice.org 3.2
    Orbit Downloader
    Origin
    PeerBlock 1.1 (r518)
    Pocket Tanks Deluxe 1.3
    proDAD Mercalli 2.0
    Project64 1.6
    PS_AIO_Software
    PS_AIO_Software_min
    PunkBuster Services
    QuickTime Alternative 3.2.2
    Realtek High Definition Audio Driver
    Recuva
    S.T.A.L.K.E.R.: Shadow of Chernobyl
    Saints Row: The Third
    Saints Row: The Third - Initiation Station
    Sanctum
    Scan
    Security Update for Microsoft .NET Framework 3.5 SP1 (KB2604111)
    Security Update for Microsoft .NET Framework 3.5 SP1 (KB2657424)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2518870)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2539636)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2572078)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2604121)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2656351)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2656368)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2656405)
    Security Update for Microsoft .NET Framework 4 Extended (KB2487367)
    Security Update for Microsoft .NET Framework 4 Extended (KB2656351)
    Security Update for Microsoft Windows (KB2564958)
    Security Update for Windows Internet Explorer 7 (KB2544521)
    Security Update for Windows Internet Explorer 7 (KB2559049)
    Security Update for Windows Internet Explorer 7 (KB2618444)
    Security Update for Windows Internet Explorer 7 (KB2675157)
    Security Update for Windows Internet Explorer 7 (KB938127-v2)
    Security Update for Windows Internet Explorer 7 (KB982381)
    Security Update for Windows Media Player (KB2378111)
    Security Update for Windows Media Player (KB952069)
    Security Update for Windows Media Player (KB954155)
    Security Update for Windows Media Player (KB968816)
    Security Update for Windows Media Player (KB973540)
    Security Update for Windows Media Player (KB975558)
    Security Update for Windows Media Player (KB978695)
    Security Update for Windows Media Player 11 (KB954154)
    Security Update for Windows XP (KB2079403)
    Security Update for Windows XP (KB2115168)
    Security Update for Windows XP (KB2229593)
    Security Update for Windows XP (KB2296011)
    Security Update for Windows XP (KB2347290)
    Security Update for Windows XP (KB2360937)
    Security Update for Windows XP (KB2387149)
    Security Update for Windows XP (KB2393802)
    Security Update for Windows XP (KB2412687)
    Security Update for Windows XP (KB2419632)
    Security Update for Windows XP (KB2423089)
    Security Update for Windows XP (KB2440591)
    Security Update for Windows XP (KB2443105)
    Security Update for Windows XP (KB2476490)
    Security Update for Windows XP (KB2478960)
    Security Update for Windows XP (KB2478971)
    Security Update for Windows XP (KB2479943)
    Security Update for Windows XP (KB2481109)
    Security Update for Windows XP (KB2483185)
    Security Update for Windows XP (KB2485663)
    Security Update for Windows XP (KB2503665)
    Security Update for Windows XP (KB2506212)
    Security Update for Windows XP (KB2507618)
    Security Update for Windows XP (KB2507938)
    Security Update for Windows XP (KB2508272)
    Security Update for Windows XP (KB2508429)
    Security Update for Windows XP (KB2509553)
    Security Update for Windows XP (KB2510581)
    Security Update for Windows XP (KB2524375)
    Security Update for Windows XP (KB2535512)
    Security Update for Windows XP (KB2536276-v2)
    Security Update for Windows XP (KB2544893)
    Security Update for Windows XP (KB2544893-v2)
    Security Update for Windows XP (KB2555917)
    Security Update for Windows XP (KB2562937)
    Security Update for Windows XP (KB2566454)
    Security Update for Windows XP (KB2567680)
    Security Update for Windows XP (KB2570222)
    Security Update for Windows XP (KB2570947)
    Security Update for Windows XP (KB2584146)
    Security Update for Windows XP (KB2585542)
    Security Update for Windows XP (KB2592799)
    Security Update for Windows XP (KB2598479)
    Security Update for Windows XP (KB2603381)
    Security Update for Windows XP (KB2618451)
    Security Update for Windows XP (KB2619339)
    Security Update for Windows XP (KB2620712)
    Security Update for Windows XP (KB2621440)
    Security Update for Windows XP (KB2624667)
    Security Update for Windows XP (KB2631813)
    Security Update for Windows XP (KB2633171)
    Security Update for Windows XP (KB2639417)
    Security Update for Windows XP (KB2646524)
    Security Update for Windows XP (KB2653956)
    Security Update for Windows XP (KB2659262)
    Security Update for Windows XP (KB2661637)
    Security Update for Windows XP (KB2676562)
    Security Update for Windows XP (KB2686509)
    Security Update for Windows XP (KB2695962)
    Security Update for Windows XP (KB923561)
    Security Update for Windows XP (KB923789)
    Security Update for Windows XP (KB941569)
    Security Update for Windows XP (KB946648)
    Security Update for Windows XP (KB950762)
    Security Update for Windows XP (KB950974)
    Security Update for Windows XP (KB951066)
    Security Update for Windows XP (KB951376-v2)
    Security Update for Windows XP (KB951748)
    Security Update for Windows XP (KB952004)
    Security Update for Windows XP (KB952954)
    Security Update for Windows XP (KB954459)
    Security Update for Windows XP (KB955069)
    Security Update for Windows XP (KB956572)
    Security Update for Windows XP (KB956744)
    Security Update for Windows XP (KB956802)
    Security Update for Windows XP (KB956803)
    Security Update for Windows XP (KB956844)
    Security Update for Windows XP (KB957097)
    Security Update for Windows XP (KB958644)
    Security Update for Windows XP (KB958687)
    Security Update for Windows XP (KB958869)
    Security Update for Windows XP (KB959426)
    Security Update for Windows XP (KB960225)
    Security Update for Windows XP (KB960803)
    Security Update for Windows XP (KB960859)
    Security Update for Windows XP (KB961501)
    Security Update for Windows XP (KB969059)
    Security Update for Windows XP (KB969947)
    Security Update for Windows XP (KB970238)
    Security Update for Windows XP (KB970430)
    Security Update for Windows XP (KB971468)
    Security Update for Windows XP (KB971486)
    Security Update for Windows XP (KB971557)
    Security Update for Windows XP (KB971633)
    Security Update for Windows XP (KB971657)
    Security Update for Windows XP (KB971961)
    Security Update for Windows XP (KB972270)
    Security Update for Windows XP (KB973354)
    Security Update for Windows XP (KB973507)
    Security Update for Windows XP (KB973525)
    Security Update for Windows XP (KB973869)
    Security Update for Windows XP (KB973904)
    Security Update for Windows XP (KB974112)
    Security Update for Windows XP (KB974318)
    Security Update for Windows XP (KB974392)
    Security Update for Windows XP (KB974571)
    Security Update for Windows XP (KB975025)
    Security Update for Windows XP (KB975467)
    Security Update for Windows XP (KB975560)
    Security Update for Windows XP (KB975561)
    Security Update for Windows XP (KB975562)
    Security Update for Windows XP (KB975713)
    Security Update for Windows XP (KB977165)
    Security Update for Windows XP (KB977816)
    Security Update for Windows XP (KB977914)
    Security Update for Windows XP (KB978037)
    Security Update for Windows XP (KB978251)
    Security Update for Windows XP (KB978262)
    Security Update for Windows XP (KB978338)
    Security Update for Windows XP (KB978542)
    Security Update for Windows XP (KB978601)
    Security Update for Windows XP (KB978706)
    Security Update for Windows XP (KB979309)
    Security Update for Windows XP (KB979482)
    Security Update for Windows XP (KB979559)
    Security Update for Windows XP (KB979683)
    Security Update for Windows XP (KB979687)
    Security Update for Windows XP (KB980195)
    Security Update for Windows XP (KB980218)
    Security Update for Windows XP (KB980232)
    Security Update for Windows XP (KB980436)
    Security Update for Windows XP (KB981322)
    Security Update for Windows XP (KB981349)
    Security Update for Windows XP (KB981997)
    Security Update for Windows XP (KB982132)
    Security Update for Windows XP (KB982665)
    Segoe UI
    Six Updater
    Skype™ 6.1
    Smart Defrag 2
    Sothink SWF Quicker
    Spybot - Search & Destroy
    Stalker Complete 2009
    Status
    Steam
    StreamTransport version: 1.0.2.2171
    swMSM
    System Requirements Lab
    Team Fortress 2
    Terraria
    Toolbox
    TortoiseSVN 1.7.6.22632 (32 bit)
    TrayApp
    Trillian
    Tseries BIOS Update
    Tunatic
    UnloadSupport
    Update for Microsoft .NET Framework 3.5 SP1 (KB963707)
    Update for Microsoft .NET Framework 4 Client Profile (KB2468871)
    Update for Microsoft .NET Framework 4 Extended (KB2468871)
    Update for Windows XP (KB2345886)
    Update for Windows XP (KB2541763)
    Update for Windows XP (KB2641690)
    Update for Windows XP (KB2718704)
    Update for Windows XP (KB951978)
    Update for Windows XP (KB955759)
    Update for Windows XP (KB961503)
    Update for Windows XP (KB967715)
    Update for Windows XP (KB968389)
    Update for Windows XP (KB971029)
    Update for Windows XP (KB971737)
    Update for Windows XP (KB973687)
    Update for Windows XP (KB973815)
    Update for Windows XP (KB978207)
    VBA (2627.01)
    VC80CRTRedist - 8.0.50727.4053
    Vegas Pro 10.0
    Ventrilo Client
    Visual C++ 2008 x86 Runtime - (v9.0.30729)
    Visual C++ 2008 x86 Runtime - v9.0.30729.01
    VLC media player 2.0.4
    VST Bridge 1.1
    VTFEdit 1.2.5
    War Thunder Launcher 1.0.1.143
    Warframe
    WebFldrs XP
    WebReg
    Winamp
    Windows Feature Pack for Storage (32-bit) - IMAPI update for Blu-Ray
    Windows Genuine Advantage Notifications (KB905474)
    Windows Genuine Advantage Validation Tool (KB892130)
    Windows Internet Explorer 7
    Windows Live Call
    Windows Live Communications Platform
    Windows Live Essentials
    Windows Live ID Sign-in Assistant
    Windows Live Messenger
    Windows Media Format 11 runtime
    Windows Media Player 11
    Windows XP Service Pack 3
    WinPcap 4.1.2
    WinRAR archiver
    World of Tanks
    XviD MPEG-4 Video Codec
    Yontoo 1.12.02

</code>

**Comment by kingkriss** [comment]
The issues with non loading etc, but it really does load if you look in your task manager you can see HL.exe and Rundll32.exe with it too. It's to do with running a 32bit game on a 64bit system, todo with syswow32. Now what i do for a quick fix is to, open task manager, right click on HL.exe and restart it, it reloads straight away. I use process explorer instead of the windows version, it's quicker and dont use no cpu.
