### ISSUE TITLE
m_rawinput changes take no effect if a new map has started and less time has passed than on any previous map or if weapon prediction is disabled

### ISSUE THREAD

**Issue by SamVanheer** [ValveSoftware/halflife#3255]
Changing the `m_rawinput` cvar doesn't change the raw input behavior if a new map has started and less time has passed than on any previous map where more time has passed, or if weapon prediction is disabled.

This code checks if the cvar has changed:
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/cl_dll/inputw32.cpp#L366-L370

`s_flRawInputUpdateTime` is updated once a second. When a new map starts the time value starts at `1`, so until the map has been running for `s_flRawInputUpdateTime + 1` seconds this code will not update the cached value of the raw input cvar.

The time value is also read from a variable that isn't updated unless `cl_lw` is enabled:
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/cl_dll/hl/hl_weapons.cpp#L680-L681

Rather than resetting the time variable it would be better to change how the input code checks for raw input settings to match Source, which checks the cvar directly:
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/client/in_mouse.cpp#L345

Remove these lines:
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/cl_dll/inputw32.cpp#L58
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/cl_dll/inputw32.cpp#L61
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/cl_dll/inputw32.cpp#L366-L370

Change this:
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/cl_dll/inputw32.cpp#L59

To this:
```cpp
static cvar_t* m_rawinput = nullptr;

static bool IN_UseRawInput()
{
	return m_rawinput->value != 0;
}
```

Change this:
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/cl_dll/inputw32.cpp#L1093

```cpp
m_rawinput = gEngfuncs.pfnGetCvarPointer("m_rawinput");
```

Replace all occurrences of `m_bRawInput` with `IN_UseRawInput()`.

The input code will now check the value of the cvar directly, so changing the raw input cvar will immediately change input behavior instead of taking up to a second to change. It will also change even if the amount of time that has passed is less than on a previous map.

This fix renders #3254 obsolete.

**Comment by shawns-valve** [comment]
The suggested fix was applied as part of the Half-Life 25th Anniversary update (November / December 2023 Steam build).
