### ISSUE TITLE
Mouse issue [Counter-Strike]

### ISSUE THREAD

**Issue by eskiq** [ValveSoftware/halflife#3271]
![L](https://user-images.githubusercontent.com/17961697/169651567-c0aa0995-3b11-4e42-be66-363624c4699c.gif)

I'm moving mouse up. down, right, left but while moving left crosshair is staying in the same place. You can see on a gif that its shaking. Can move pixel by pixel any other directions except left, upper left and down left. Problem is very apparent when using second zoom. My sensitivity was 0.3 and 1800dpi. Tried different mouse with 400dpi, m_rawinput 0, default config and nothing helps. To move crosshair left I need to move it left enough fast or it will stay in the same place. Anybody having the same problem as me? My OS is win7 ultimate.

**Comment by kisak-valve** [comment]
Hello @eskiq, this issue is already being tracked at #154 / #356. Closing as a duplicate.
