### ISSUE TITLE
Locale issues in cs1.6

### ISSUE THREAD

**Issue by TAforever** [ValveSoftware/halflife#3278]
Contacted Steam support and was redirected here.
Case number HT-3746-2CKD-2GR7.
When starting the game, an error message appears in setting the en_US.UTF-8 locale. My system language is Russian, but the en_US.UTF-8 locale is also on the system. When running in the terminal, there is such a line "ILocalize::AddFile() failed to load file "resource/cstrike_russian.txt."" I am also attaching screenshots.
![cstrike](https://user-images.githubusercontent.com/52626363/170819806-5f81ee33-b374-49f0-8082-ec8949904ef5.png)
![cs_bug](https://user-images.githubusercontent.com/52626363/170819831-c51f4412-588c-43ce-8f8a-a60504bf963a.png)

**Comment by kisak-valve** [comment]
Hello @TAforever, can you check the output of `locale -a` for a line that reads `en_US.utf8`?

**Comment by TAforever** [comment]
Yes, I wrote that the locale exists. Here is the output of the locale -a command: C
en_US.utf8
POSIX
ru_RU.utf8

**Comment by kisak-valve** [comment]
Maybe try setting the game's launch options to `SteamEnv=1 %command%` (from https://github.com/ValveSoftware/halflife/issues/3006#issuecomment-739517922) and see if that works around your issue.

**Comment by TAforever** [comment]
Yes, I already saw this solution when I searched on Google, but it doesn't work for me.

**Comment by TAforever** [comment]
I tried now to install the Windows version of the game and run it through Proton and this problem does not exist here, the problem is in the Linux version of the game.

**Comment by TAforever** [comment]
I tried to install Steam-native-runtime, the problem disappeared, but I don’t want to drag 93 32-bit libraries into the system.

**Comment by TAforever** [comment]
> Maybe try setting the game's launch options to `SteamEnv=1 %command%` (from [#3006 (comment)](https://github.com/ValveSoftware/halflife/issues/3006#issuecomment-739517922)) and see if that works around your issue.

The problem lies with the Steam-runtime client

**Comment by chinese-soup** [comment]
This started happening to me as well about a month ago (maybe after a packages upgrade, unsure). Locale is available and correctly set. SteamEnv=1 does not affect it just like the original reporter mentions.

**Comment by redve-dev** [comment]
@chinese-soup i have fixed similar error with half life 1 on my machine.
I added
SteamEnv=1 %command% to launch options
and then i set compatibility tool to proton 7.0.3

**Comment by TAforever** [comment]
Today, after updating the openal and lib32-openal packages, the problem was solved.

**Comment by chinese-soup** [comment]
> Today, after updating the openal and lib32-openal packages, the problem was solved.

Agreed, same for me.
