### ISSUE TITLE
Can you please upload Half-Life: Uplink to Steam after porting it from the WON Edition to the GoldSrc engine?

### ISSUE THREAD

**Issue by Cuthalion45** [ValveSoftware/halflife#3292]
https://archive.org/download/hlfurtherdatav1/FURTHER_DATA.iso01.iso

**Comment by Cuthalion45** [comment]
It could be added as an update for Half-Life (so that you don't have to port it from the ground up): [valve.zip](https://github.com/ValveSoftware/halflife/files/9224113/valve.zip)

**Comment by sabianroberts** [comment]
I really don't think this is going to happen. Uplink was only a short, non-canon demo made on the engine by Valve to showcase Half-Life's gameplay. There are, however, fan-made mods such as Uplink Extended on ModDB.
