### ISSUE TITLE
DoD crashing randomly on Linux Mint

### ISSUE THREAD

**Issue by TheScaryGuy** [ValveSoftware/halflife#3295]
Day of Defeat crashes randomly during game play. Also happens in spectate mode too. Have tried full screen and windowed game play. I have not been able to isolate what the cause is. Any suggestions?

    Steam client version (build number or date): 1658644613
      Jul 26 2022, at 18:54:18
    Steam API: v020
    Distribution (e.g. Ubuntu): Mint 
      Linux version 5.4.0-122-generic (buildd@lcy02-amd64-095) (gcc version 9.4.0  
      (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022
    Opted into Steam client beta?: [Yes/No] No
    Have you checked for system updates?: [Yes/No] Yes

[crash-Inxi.LinuxMintInfo.Packages.zip](https://github.com/ValveSoftware/halflife/files/9285484/crash-Inxi.LinuxMintInfo.Packages.zip)

**Comment by TheScaryGuy** [comment]
CoreDump (92.3MB compressed) was too large, but here are the other files from the crash:
[LinuxMintInfo.zip](https://github.com/ValveSoftware/halflife/files/9934198/LinuxMintInfo.zip)
[Packages.zip](https://github.com/ValveSoftware/halflife/files/9934201/Packages.zip)
[Inxi.zip](https://github.com/ValveSoftware/halflife/files/9934202/Inxi.zip)

Any suggestions on how to track down the problem?

**Comment by TheScaryGuy** [comment]
In console, I entered developer 2 and after the crash, opened the file "qconsole.log" in the Half-Life folder. The last line entered after the crash is:
Particleman is out of memory, too many particles

**Comment by kisak-valve** [comment]
Hello @TheScaryGuy, that makes this the same issue as #1447. Closing in favor of the older issue report.
