### ISSUE TITLE
[Counter-Strike] The scoreboard ImagePanel is shown only within the scoreboard

### ISSUE THREAD

**Issue by SanAntonio2** [ValveSoftware/halflife#3302]
I decided to return the old orangebox banner to the scoreboard, but it doesn't draw outside the scoreboard.
Scoreboard.res code:
`"ct-banner1"

	{
		"ControlName"		"ImagePanel"
		"fieldName"			"ct-banner1"
		"xpos"				"145"
		"ypos"				"-25"
		"wide"				"234"
		"tall"				"50"
		"autoResize"		"1"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"textAlignment"		"west"
		"image"				"gfx/vgui/cs_banner"
		"scaleImage"		"1"
                "linespacing"		"13"
        }`
How it looks in game:
![cs_bunker0000](https://user-images.githubusercontent.com/47498583/190377360-70494c9b-d396-483a-8740-7d0447ad108c.jpg)

One more question, so as not to create a new topic: in which file can be changed the position of the colon, near the timer?

**Comment by kevinkarlssonbr** [comment]
Do you know how I add in this format?

![image](https://github.com/ValveSoftware/halflife/assets/51301526/bd675fb1-faee-4323-b21c-666c874a3905)

**Comment by SanAntonio2** [comment]
> Do you know how I add in this format?
> 
> ![image](https://user-images.githubusercontent.com/51301526/248487481-bd675fb1-faee-4323-b21c-666c874a3905.png)

Sorry for the late reply, yes I found a solution to my problem. Solution:
Open "ScoreBoard.res" file (found in Half-Life\cstrike\resource\UI), for "ClientScoreBoard" change "autoResize" from "1" to "0".

**Comment by kevinkarlssonbr** [comment]
![image](https://github.com/ValveSoftware/halflife/assets/51301526/42c77f2d-7f1b-479f-840e-f12676881082)

Even editing "autoResize", it remains cut.

**Comment by franco1050** [comment]
I know im late , i couldn't make the banner fit outside the scoreboard but i managed to fit it like this, i just had to move the "player list" and "server name". I also added the banner on the spectator screen. It look ugly but is the best i can do haha.
![mrMRZwX](https://github.com/ValveSoftware/halflife/assets/147289256/5922ea1a-8e76-40e9-85d1-96a4ebf1c4d6)
![zPGboiE](https://github.com/ValveSoftware/halflife/assets/147289256/9f303d64-176f-4264-a18a-b8d8c1b9294e)

**Comment by franco1050** [comment]
> ![image](https://user-images.githubusercontent.com/51301526/273077961-42c77f2d-7f1b-479f-840e-f12676881082.png)
> 
> Even editing "autoResize", it remains cut.

I know im late , i couldn't make the banner fit outside the scoreboard but i managed to fit it like this, i just had to move the "player list" and "server name". I also added the banner on the spectator screen. It looks ugly but is the best i can do haha.
![mrMRZwX](https://github.com/ValveSoftware/halflife/assets/147289256/2e3371a5-596c-4ef4-a3c7-2fbd71df4478)
![zPGboiE](https://github.com/ValveSoftware/halflife/assets/147289256/300f50fd-523f-4697-b028-67ccd44acdd6)

**Comment by franco1050** [comment]
Here's the link for it if you wanna try it :

https://gamebanana.com/mods/472766

**Comment by SanAntonio2** [comment]
> > Replying to [#3302 (comment)](https://github.com/ValveSoftware/halflife/issues/3302#issuecomment-1749854596)
Pretty much the same as yours.
![0000](https://github.com/ValveSoftware/halflife/assets/47498583/73c31647-3fae-46c3-96eb-7404952cdaa0)
[GUI_Orange_Box.zip](https://github.com/ValveSoftware/halflife/files/12845882/GUI_Orange_Box.zip)

**Comment by shawns-valve** [comment]
It sounds like this was figured out.
