### ISSUE TITLE
Unable to build on Windows

### ISSUE THREAD

**Issue by f1am3d** [ValveSoftware/halflife#3320]
Repo already contains `vcxproj` files which are meant to be used for buliding different parts of the project, right?
So why does building process has errors? 

Example:
```
\common\mathlib.h(20,15): error C2040: 'Vector': 'vec_t [3]' differs in levels of indirection from 'Vector'
\dlls\player.cpp(2075,6): error C2668: 'abs': ambiguous call to overloaded function
```

Should I rewrite some parts of the code to make this buildable?

**Comment by tschumann** [comment]
As per https://github.com/ValveSoftware/halflife/issues/3133 change abs to fabs

Not sure about the mathlib.h error though - what does the rest of the build output say?

**Comment by molecula451** [comment]
Not right, you need to make the project `sln` and then either open up using Visual Studio, or building thru developer console (after installed VS) using `msbuild`

**Comment by WhiteMaterials** [comment]
Also need define NO_MINMAX for disable windows min/max function collision.

**Comment by f1am3d** [comment]
Not relevant anymore. 
I use fork of a guy wasn't lazy and spent some time to prepare the project to be buildable perfectly on latest versions of VS without any redundant manipulations: 
https://github.com/SamVanheer/halflife-updated
