### ISSUE TITLE
You get content from Half-Life when you install some games on GoldSrc.

### ISSUE THREAD

**Issue by Artem13327** [ValveSoftware/halflife#3324]
When installing one of these games:

1. Day of Defeat
2. Team Fortress Classic
3. Deathmatch Classic
4. Counter-Strike
5. Counter-Strike: Condition Zero Deleted Scenes
6. Ricochet
7. Counter-Strike: Condition Zero
8. Half-Life: Opposing Force
9. Half-Life: Blue Shift
Information taken from here https://steamdb.info/depot/1/apps/

You get some unnecessary content from Half-Life (like maps). I propose to make a separate depot for these games, which will contain only models and textures from the original Half-Life, but not maps.

**Comment by kisak-valve** [comment]
Hello @Artem13327, given the size of the shared content, this is not worth the added complexity of reworking the contents of the depots and potentially breaking third party content and mods.
