### ISSUE TITLE
[Counter-Strike] [Feature Request] fps_max 100.0, cl_cmdrate 105, cl_updaterate 102, ex_interp 0 as defaults.

### ISSUE THREAD

**Issue by Player-sudo** [ValveSoftware/halflife#3341]
In my experience this would improve the experience for new players and also for the remaining players who are new to these CVARs.

The reason I'm asking this is because I've had bad experiences with the game in the past due to the default settings at the time. It used to be, shall we say, bitter when you encountered other players with higher values, who mostly had an advantage over me because I was using lower values than them (unknowningly). To this day, I still have fellow players in my Steam Friends, who don't know that these CVARs actually exist and some of the fellow players have even stopped playing the game because of the disadvantages.

It has to be said that the pirated copies of the game use the highest values ​​(keeping "fps_override" unchanged) and this really improves not just the first impression of the game. That's the only reason they do it. I had the same impression when I was younger and I still have it. Nowadays running CS 1.6 at a stable 100 frames per second shouldn't be a problem either. And if so, it should be better to lower the graphics settings as the game is not known and played for the graphics. And having network related issues will decrease interest in the game anyway because of the reasons listed above.

It might be useful to adjust the player's graphics, as in the SRCDS games, but also to keep the values ​​mentioned in the title for competitive-oriented use of the game which is not possible having values like "fps_max 72.0", "cl_cmdrate/cl_updaterate 60", and so forth.

Have a nice day!

**Comment by kisak-valve** [comment]
Hello @Player-sudo, there already are several issue reports to re-evaluate these defaults like #166 / #696 and fragmenting the discussion across yet another issue report is non-productive. Feel free to add a note to one of the older issue reports.

Closing as a duplicate.
