### ISSUE TITLE
User interface coordinates and sizes are incorrectly adjusted for resolution

### ISSUE THREAD

**Issue by SamVanheer** [ValveSoftware/halflife#3344]
The game adjusts user interface coordinates and sizes using these macros:
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/cl_dll/cl_util.h#L80-L81

Since these are macros they are expanded before the code is actually compiled. Because the macro parameters aren't surrounded by parentheses the resulting code is evaluated incorrectly.

The most obvious example of this is in the spectator panel:
![image](https://i.imgur.com/Ox0llqi.png)

The bottom right dropdown button overlaps the other elements because the position and size for these are calculated incorrectly.

For example in this calculation:
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/cl_dll/vgui_SpectatorPanel.cpp#L194

To fix this the macros need to be changed to this:
```cpp
#define XRES(x)					((x)  * ((float)ScreenWidth / 640))
#define YRES(y)					((y)  * ((float)ScreenHeight / 480))
```

**Comment by shawns-valve** [comment]
This issue was addressed in the October 2, 2024 HL Steam update.
