### ISSUE TITLE
[GoldSrc] Non-English characters broken.

### ISSUE THREAD

**Issue by BlackShadow** [ValveSoftware/halflife#3356]
After the latest Steam UI update, non-english characters became invisible 

![image](https://github.com/ValveSoftware/halflife/assets/30868395/fccb0e78-a854-408e-9fe4-b46d68235d3f)

For some reason some of the non-english characters are visible but some of them are not. 

i.e: I've typed "öçşğü" only ş and ğ letters are visible.

System Information: https://gist.github.com/BlackShadow/160fd02505ec86837108478ee7cd863e

**Comment by kisak-valve** [comment]
Hello @BlackShadow, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by BlackShadow** [comment]
@kisak-valve Sure, here you go:

https://gist.github.com/BlackShadow/160fd02505ec86837108478ee7cd863e

**Comment by BlackShadow** [comment]
@kisak-valve Sure, added link on the first post.

**Comment by BlackShadow** [comment]
This issue fixed with anniversary update
