### ISSUE TITLE
[GoldSrc] [Feature Request] Try & port Half-Life: Decay to the PC

### ISSUE THREAD

**Issue by Hubbenobo** [ValveSoftware/halflife#3357]
This has become reasonably possible with the help of [a fan-made PC port](https://www.moddb.com/mods/half-life-decay-v102/downloads/half-life-decay-v1021-full) (that only works on Windows) and [Ghidra](https://github.com/NationalSecurityAgency/ghidra/releases).

The fan-made PC port is so accurate that it may as well be the original (aside from 5-6 minor bugs and a major cross-platform issue). The source code is not available, but you can recreate it with NSA's software reverse engineering framework. Shall you please consider the possibility of following through with this?

**Comment by kisak-valve** [comment]
Hello @Hubbenobo, this request was previously evaluated at #1382, and there's no particular reason to expect that has changed in the 10 years since the previous request.

**Comment by Hubbenobo** [comment]
> Hello @Hubbenobo, this request was previously evaluated at #1382, and there's no particular reason to expect that has changed in the 10 years since the previous request.

I'd appreciate if word gets round' about this request at Valve even if nothing happens in the end (very ambitious, I know). Thanks.

**Comment by tschumann** [comment]
The fan port is now open source: https://github.com/hoaxer/Half-Life-Decay

**Comment by Hubbenobo** [comment]
> The fan port is now open source: https://github.com/hoaxer/Half-Life-Decay

I think that is the source code for the first fan port, which is worse than the 2nd one in terms of accuracy. But good call.
