### ISSUE TITLE
Blue Shift and Opposing Force do not start

### ISSUE THREAD

**Issue by drjames5** [ValveSoftware/halflife#3392]
Although default Half-Life and Uplink work fine, OP and BS don't. I have them both installed and in the half life folder, but when I try to start a campaign with them the game just quits back to menu.

**Comment by sabianroberts** [comment]
What OS are you using
________________________________
From: drjames5 ***@***.***>
Sent: Friday, September 15, 2023 12:56:33 AM
To: ValveSoftware/halflife ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ValveSoftware/halflife] Blue Shift and Opposing Force do not start (Issue #3392)


Although default Half-Life and Uplink work fine, OP and BS don't. I have them both installed and in the half life folder, but when I try to start a campaign with them the game just quits back to menu.

**Comment by drjames5** [comment]
Windows 10

**Comment by drjames5** [comment]
I tried reinstalling OF and BS but it still doesn't work

**Comment by Root-Core** [comment]
Opposing Force is crashing on launch, Blue Shift is working.

----------

OS: Manjaro
Kernel: 6.6.1
GPU: AMD Mesa 23.1.9

**Comment by megakarlach** [comment]
> Blue Shift is crashing on launch, Opposing Force is working.
> 
> OS: Manjaro Kernel: 6.6.1 GPU: AMD Mesa 23.1.9

This issue post was from Sep 20, prior to HL25, so both games should work fine. So it's likely the problem from OP side.
After HL25, only OF works, but Blue Shift isnt.

**Comment by Root-Core** [comment]
> This issue post was from Sep 20, prior to HL25, so both games should work fine. So it's likely the problem from OP side. After HL25, only OF works, but Blue Shift isnt.

True, I missed that. Nonetheless it's an current issue, that should be fixed.
I'm not sure if I should open another issue for it.

Also: Is the issue Linux only or is the Windows version also broken?
@drjames5 - Does your issue persist after the HL25 update?

**Comment by shawns-valve** [comment]
This (along with other mod compatibility issues) was resolved in a patch late last year.
