### ISSUE TITLE
[Half-Life] [Feature Request] How to implement a Chambered Bullet mechanic for the Pistol

### ISSUE THREAD

**Issue by theOneTrueFunniBoi** [ValveSoftware/halflife#3401]
In a demo version of half life 1, a feature existed where (like most games now a days) when reloading the pistol on an empty mag, it refills to 17. however reloading again refills to 18. I would really love to see this feature readded but i can't figure out how.

**Comment by theOneTrueFunniBoi** [comment]
Ok, I've made a system myself.

First:

Load up `glock.cpp`, you may already notice that the lines:

`if (m_iClip == 0)`
		`iResult = DefaultReload( 17, GLOCK_RELOAD, 1.5 );`
	`else`
		`iResult = DefaultReload( 18, GLOCK_RELOAD_NOT_EMPTY, 1.5 );`
Already have remnants of this system.

Find this block of code:

`	p->iMaxAmmo2 = -1;`
`	p->iMaxClip = GLOCK_MAX_CLIP;`

Add this after:

`p->iMaxClipChambered = MAX_CLIP_GLOCK_CHAMBERED;`

Open `weapons.h` and find:

`#define GLOCK_MAX_CLIP			17`

Underneath, Add:

`#define	MAX_CLIP_GLOCK_CHAMBERED	18`

Next, find:

`	int		iMaxClip;`

And define iMaxClipChambered below it

`	int		iMaxClipChambered;`

Now locate:

`int			iMaxClip( void )	{ return ItemInfoArray[ m_iId ].iMaxClip; }`

And follow the theme:

`int			iMaxClipChambered( void )	{ return ItemInfoArray[ m_iId ].iMaxClipChambered; }`

Now, Open `weapons.cpp`.

Inside of `void CBasePlayerWeapon::ItemPostFrame( void )`, find:

`// complete the reload.`
`int j = min( iMaxClip() - m_iClip, m_pPlayer->m_rgAmmo[m_iPrimaryAmmoType]);	`

Replace that block of code with this:
`int j;`

`if (m_iClip != 0 && iMaxClipChambered() > 0)`
`{`
`	j = min(iMaxClipChambered() - m_iClip, m_pPlayer->m_rgAmmo[m_iPrimaryAmmoType]);`
`}`
`else`
`{`
`	j = min(iMaxClip() - m_iClip, m_pPlayer->m_rgAmmo[m_iPrimaryAmmoType]);`
`}`

And there you go. For anyone looking to implement this, this is for you.

**Comment by BlackShadow** [comment]
@kisak-valve  Can be closed
