### ISSUE TITLE
[Half-Life] [Feature Request] WON Menu UI

### ISSUE THREAD

**Issue by theOneTrueFunniBoi** [ValveSoftware/halflife#3402]
Please, if anyone knows how to do this I need to know. The WON ui was so good, i need to add it to my mod.

**Comment by tschumann** [comment]
Some of this code is in the engine at least and some of it is in gameui.dll
(which is unfortunately closed source too) so this can't be done for normal
mods.

**Comment by theOneTrueFunniBoi** [comment]
Is it possible that if I were to obtain release hl’s gameui.dll it may work? Or are they incompatible?

**Comment by theOneTrueFunniBoi** [comment]
Or does it even exists at all?

**Comment by theOneTrueFunniBoi** [comment]
Yeah i tested it, crashes the game. I probably should've expected that considering steam gameui.dll is 600kb larger than release gameui.dll

**Comment by tschumann** [comment]
GameUI.dll from the WON version? I'm not sure if it exists in the WON
version but if it did it would be completely different.

**Comment by theOneTrueFunniBoi** [comment]
Yeah it does exist. Still though, I feel like it should be open source too though because people might want to add this back, or do other things to the menu.

**Comment by BlackShadow** [comment]
If this is a issue/question for "your" mod, i'd recommend visiting Half-Life modding community (such as Discord channels, forums etc...) to get better support. Issue tracking is not the place for asking personal questions.
