### ISSUE TITLE
[MOD] Odd issue.

### ISSUE THREAD

**Issue by theOneTrueFunniBoi** [ValveSoftware/halflife#3403]
Im working on a mod for half life, and it runs just fine on my computer. However when distrubiting the entire mod folder to my friend, his game just throws the standard "Could not load library" error. I know its not the dlls, and all the files are copied from my machine. Any idea why this is happening?

**Comment by tmp64** [comment]
Debug builds of the game DLLs require the user to have Visual Studio installed. If you're building in Debug, that's probably the reason. You should switch Release in that case

**Comment by theOneTrueFunniBoi** [comment]
I am building in release though. Both the client and server DLL. Yet it’s only the client DLL that fails to load.

**Comment by tmp64** [comment]
Does some window that says something like "entry point not found" or "DLL not found" show up? If not, I don't know what might be causing the problem.

Try installing [this tool](https://github.com/lucasg/Dependencies) on your friend's PC. Open the client DLL in it. It will show which dependencies are missing, if any.

**Comment by theOneTrueFunniBoi** [comment]
All it's saying is "Could not load library" followed by "C:\Program Files" (presumably cut off by terrible message box design).

**Comment by theOneTrueFunniBoi** [comment]
But i will try with the tool.

**Comment by theOneTrueFunniBoi** [comment]
Alright, i got it figured out. My spirit of half life source code requires: cg.dll and cgGL.dll to be present, otherwise the game will not run.
