### ISSUE TITLE
[Half-Life] [Bug Fix] How to fix Gluon/Egon Gun's Idle animations.

### ISSUE THREAD

**Issue by theOneTrueFunniBoi** [ValveSoftware/halflife#3404]
Currently, the gluon gun's animations are fundamentally broken. Stuttering before ceasing to play. Only properly playing when alt fire is held down. This is however a very simple fix.

Open `egon.cpp`.

Inside of `void CEgon::WeaponIdle( void )`, find:

`float flRand = RANDOM_FLOAT(0,1);`,

And replace it with:

`float flRand = UTIL_SharedRandomFloat(m_pPlayer->random_seed, 0, 1);`.

There you go, probably the simplest fix to implement.

**Comment by kisak-valve** [comment]
Hello @theOneTrueFunniBoi, this issue is already being tracked at #1077. Since this adds some more insight, I've transferred this issue report to https://github.com/ValveSoftware/halflife/issues/1077#issuecomment-1773964964.

Closing in favor of the older issue report.
