### ISSUE TITLE
[Half-Life] [Question] Holstering when Switching Weapons.

### ISSUE THREAD

**Issue by theOneTrueFunniBoi** [ValveSoftware/halflife#3405]
I've seen mods do it but i'd like to know exactly how.

**Comment by BlackShadow** [comment]
Holstering weapon is a cut "feature" in Half-Life dropped during development. Mods simply recode it back. Valve won't be bringing it back.

**Comment by BlackShadow** [comment]
@kisak-valve Can be closed
