### ISSUE TITLE
HUD appearance issues with AMD Windows drivers

### ISSUE THREAD

**Issue by Erikk26** [ValveSoftware/halflife#3408]
I do never saw these things randomly appearing in my gameplay before, how could i solve it? Maybe its a driver thing from AMD? I have RX 6700 XT, 23.10.2 driver and 2560x1440 resolution if it matters, and i already tried to reinstall completely the game and driver too with ddu program, but neither helped... 

![qLmvWoH](https://github.com/ValveSoftware/halflife/assets/58042653/dfe36d15-fce5-4324-bd6f-874cde6bba66)
![pyMN9wF](https://github.com/ValveSoftware/halflife/assets/58042653/82531531-6693-4c1b-be15-2211ea952cc0)
![X8ghmUo](https://github.com/ValveSoftware/halflife/assets/58042653/841f5212-106b-40f0-89ec-e93f77f980cb)
![2D6ukVf](https://github.com/ValveSoftware/halflife/assets/58042653/9079cae9-d314-4bfc-b55e-3b4dab16d6c5)
![sTUtmHx](https://github.com/ValveSoftware/halflife/assets/58042653/fc5a175e-9c76-4e88-8768-0ffd960ea884)
![e7Avy91](https://github.com/ValveSoftware/halflife/assets/58042653/2bf496e3-8998-423b-bbf4-8e658d1c898a)
![KpsXuo5](https://github.com/ValveSoftware/halflife/assets/58042653/23687475-b7a4-4a67-9e7b-ba3ece05da3b)

These can be affected too especially when item menu is shown:
![b1PXXtW](https://github.com/ValveSoftware/halflife/assets/58042653/61e754f7-3d56-4c6e-bd23-f8694ac8f63c)

And who knows what else which i didn't noticed yet.

**Comment by Erikk26** [comment]
These can be affected too especially when item menu is shown:
![b1PXXtW](https://github.com/ValveSoftware/halflife/assets/58042653/61e754f7-3d56-4c6e-bd23-f8694ac8f63c)

**Comment by kisak-valve** [comment]
#3559 notes that Half-Life and Half-Life: Opposing Force are affected by this issue as well.

**Comment by AlyMar1994** [comment]
Got this myself as well, AMD RX 6700 XT from #3579 .  Happens in pretty much all GldSrc games rn and with no consistency.

**Comment by tangent3D** [comment]
A driver downgrade is a possible workaround. I confirmed on my system (RX 6900 XT) that this issue *does not* occur on the previous 23.8.2 drivers (Aug. 31) and occurs on the latest 23.10.2 driver (Oct. 19).

**Comment by Erikk26** [comment]
Seems to me 23.12.1 driver fixed the issues on my end.
What about the others?

**Comment by boytunp** [comment]
> ### System Info
> ```
> OS: Windows 11 Pro [64-bit]
> Version: 23H2 Build 22631.2792
> CPU: AMD Ryzen 5 5600X 6-Core Processor @ 3.7GHz
> GPU: AMD Radeon RX 6900 XT
> Resolution: 2560x1440
> ```
> 
> @Erikk26 After updating `AMD Software: Adrenalin Edition` from `v23.11.1` to `v23.12.1` I've stopped seeing those UI artifacts on Half-Life and Counter-Strike 1.6. It seems to be resolved for now, there's still a major performance issue with AMD systems, but that's not related to this issue.

I can second that. Fixed with `v23.12.1` drivers.

**Comment by AlyMar1994** [comment]
Can confirm latest AMD drivers solved white HUD elements on RX 6700 XT.

**Comment by kisak-valve** [comment]
Closing as fixed in the video driver.
