### ISSUE TITLE
Launching the game after the 25th Ann. update turns on system mouse acceleration

### ISSUE THREAD

**Issue by grande1900** [ValveSoftware/halflife#3413]
Whenever I launch the game on the latest build, it turns on mouse acceleration (aka "enhance pointer precision") in my settings.
I don't want this to happen.

**Comment by SamVanheer** [comment]
Assuming the game still uses the same command line arguments the options `-noforcemspd`, `-noforcemaccel` and `-noforcemparms` should let you control this.
