### ISSUE TITLE
25th Aniversary patch: 2 more broken mods for the list

### ISSUE THREAD

**Issue by DosMike** [ValveSoftware/halflife#3414]
Half-Life: Blue Shift is not starting anymore
Half-Life: Opposing force is missing the anniamted banner in the main menu
Gunman Chronciles (Steam patched version from ModDB) is crashing in an assert before the main menu

Love the old style menu tho :)

**Comment by SamVanheer** [comment]
Read the anniversary post in full, it addresses mod support: https://www.half-life.com/en/halflife25/

**Comment by SanyaSho** [comment]
CS 1.6 / BSHIFT is using VGUI2 for some HUD elements and valve didn't recompiled it with updated vgui_controls/vgui2

**Comment by DosMike** [comment]
All seems to work with todays patch. Thanks :)
(Besides the animated banners, but that's just a cosmetic)
