### ISSUE TITLE
25th Anniversary Update: Throwing the new grenades causes the game to crash with the following error

### ISSUE THREAD

**Issue by CptFoxer** [ValveSoftware/halflife#3416]
![Grenade_Error](https://github.com/ValveSoftware/halflife/assets/104455743/3f38c36c-dc28-4279-922f-0c6309155776)

**Comment by JoelTroch** [comment]
Can you give more details? I can throw grenades perfectly fine on `crossfire`.

**Comment by CptFoxer** [comment]
> Can you give more details? I can throw grenades perfectly fine on `crossfire`.

Crash happened after picking up grenades on doublecross, game crashed with the error after throwing the 2nd.

**Comment by JoelTroch** [comment]
> > Can you give more details? I can throw grenades perfectly fine on `crossfire`.
> 
> Crash happened after picking up grenades on doublecross, game crashed with the error after throwing the 2nd.

Just tried, could not reproduce the crash on my side.

**Comment by shawns-valve** [comment]
We haven't encountered this internally. Please open a new issue if you still see this in the latest HL Steam build.
