### ISSUE TITLE
25th Anniversary Update: Flipped game icons

### ISSUE THREAD

**Issue by SanyaSho** [ValveSoftware/halflife#3419]
![изображение](https://github.com/ValveSoftware/halflife/assets/68691958/e95ce972-5df4-4fcb-babd-c6d984fd79c8)
![изображение](https://github.com/ValveSoftware/halflife/assets/68691958/d1ba5677-606b-48ea-937d-7ca86d6ac1f4)
![изображение](https://github.com/ValveSoftware/halflife/assets/68691958/aa42362b-201d-4251-86af-cbde4ff6cc5d)

**Comment by CptFoxer** [comment]
Also on Windows 10

**Comment by SamVanheer** [comment]
Those games weren't updated so until they get an update to work on the new engine you'll have to run them on the legacy branch.

**Comment by kisak-valve** [comment]
Hello, per "Fixed window icons drawing inverted for mods." in the [2023-11-19](https://steamcommunity.com/games/70/announcements/detail/6941797558601476249) Half-Life update, please retest this issue.

**Comment by SanyaSho** [comment]
Fixed, i'm closing the issue
