### ISSUE TITLE
[CS 1.6 Beta] hl.exe Error When connecting to server

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/halflife#342]
I Get this error when connecting to server
Server IP: 77.241.194.10:27015
![hl exe Error](https://f.cloud.github.com/assets/3611711/167718/b5e6d2a0-79e2-11e2-813f-ee1c72436a97.JPG)

//Technical information about the error report:
http://199.91.152.91/zxt55szckvrg/a7ih0i398huj3z3/fb29_appcompat.txt

//Steam Information:
Build: Feb 15 2013, at 12:27:32
Steam API: v012
Steam package versions: 1360966494 / 1360966494

//Running up-to-date versions of:
Counter Strike 1.6 opt into Beta
Half Life opt into Beta

Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 14:30:42 Feb 15 2013 (5958)

//System Information
Processor Information:
Vendor: GenuineIntel
Speed: 2793 Mhz
2 logical processors
2 physical processors
HyperThreading: Unsupported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Unsupported

Network Information:
Network Speed:

Operating System Version:
Windows XP (32 bit)
NTFS: Supported
Crypto Provider Codes: Supported 311 0x0 0x0 0x0

Video Card:
Driver: Radeon X300/X550/X1050 Series Secondary

DirectX Driver Name:  ati2dvag.dll
Driver Version:  6.14.10.6925
DirectX Driver Version:  6.14.10.6925
Driver Date: 11 Feb 2010
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
DirectX Card: Radeon X300/X550/X1050 Series
VendorID:  0x1002
DeviceID:  0x5b63
Number of Monitors:  1
Number of Logical Video Cards:  1
No SLI or Crossfire Detected
Primary Display Resolution:  1680 x 1050
Desktop Resolution: 1680 x 1050
Primary Display Size: 17.01" x 10.63"  (20.04" diag)
                                        43.2cm x 27.0cm  (50.9cm diag)
Primary Bus Type Not Detected
Primary VRAM: 256 MB
Supported MSAA Modes:  2x 4x 6x 

Sound card:
Audio device: Realtek HD Audio output

Memory:
RAM: 3323 Mb

Miscellaneous:
UI Language: English
Microphone: Not set
Media Type: DVD
Total Hard Disk Space Available: 953859 Mb
Largest Free Hard Disk Block: 476820 Mb
OS Install Date: Bal 04 2012
Game Controller: None detected

**Comment by shawns-valve** [comment]
Closing due to age. Please create a new issue if this still occurs with the 25th anniversary update (December 2023 Steam build).
