### ISSUE TITLE
25th update - HLTV Segmentation fault on new maps

### ISSUE THREAD

**Issue by larb0b** [ValveSoftware/halflife#3420]
When the HLTV Proxy attempts to connect to a server running pool_party.bsp, it segfaults.

```
>
BUILD 8684 SERVER (0 CRC)
Server # 2

Added 622 resources.
Received baseline with 329 entities.
Couldn't open config file director.cfg.
Director module initialized.
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
CAppInfoCacheReadFromDiskThread took 9 milliseconds to initialize
dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
Setting breakpad minidump AppID = 70
Segmentation fault
```

**Comment by Ch0wW** [comment]
`dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory`

This isn't related to HL1 at all, but on your HLDS installation. You have to link the steamservice library. There are plenty of tutorials available to make it work.

**Comment by larb0b** [comment]
> `dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory`
> 
> This isn't related to HL1 at all, but on your HLDS installation. You have to link the steamservice library. There are plenty of tutorials available to make it work.

That's not the problem - the problem is the segfault which only happens on those specific maps.

**Comment by Ch0wW** [comment]
And you can run any other map properly?

I have absolutely no issue on my server when running this map, other than in displaced and rocket_frenzy, which are absolutely unoptimized for HLDS at the very moment.

**Comment by larb0b** [comment]
> And you can run any other map properly?
> 
> I have absolutely no issue on my server when running this map, other than in displaced and rocket_frenzy, which are absolutely unoptimized for HLDS at the very moment.

It works fine on the server. The problem is when the HLTV Proxy tries to connect.

**Comment by larb0b** [comment]
I'm not able to replicate this with a fresh HLDS install - not sure what the story is there. Perhaps other plugin conflicts.
