### ISSUE TITLE
25th Anniversary Update: Please add Gunman Chronicles on Steam

### ISSUE THREAD

**Issue by DarthMan** [ValveSoftware/halflife#3422]
Hello,

This is not really an issue, but haven't found another place to post it on. It would be really cool if as part of the 25th HL1 anniversary we could finally get Gunman Chronicles on Steam, with proper support and also free to play. In the future, the game should also come to Linux if possible.

Cheers,
DarthMan

**Comment by kisak-valve** [comment]
Hello @DarthMan, without being the IP holder of the game, there's no practical action that could be taken by a Valve developer with this request.

**Comment by DarthMan** [comment]
> Hello @DarthMan, without being the IP holder of the game, there's no practical action that could be taken by a Valve developer with this request.

I though that Valve owns the game now, after the Rewolf company was closed.

**Comment by BlackShadow** [comment]
> Hello @DarthMan, without being the IP holder of the game, there's no practical action that could be taken by a Valve developer with this request.

I'm not too familiar with United States law but isn't a closed company basically loses the IP/Trademarks? They basically expire.
