### ISSUE TITLE
Counter strike cannot run on Windows 10

### ISSUE THREAD

**Issue by piotrekk6** [ValveSoftware/halflife#3425]
Game cannot run after upgrade
![image](https://github.com/ValveSoftware/halflife/assets/9806148/3598731c-07d4-4722-b00d-0aa59ac892a5)

**Comment by MisterSheeple** [comment]
Go to the game properties, select the "Betas" section, and select the "steam_legacy" branch.

**Comment by piotrekk6** [comment]
Thanks, that worked. What is the root cause of the issue?

**Comment by SamVanheer** [comment]
You need to switch the branch on Half-Life, not Counter-Strike. CS uses the same engine as HL.

**Comment by kisak-valve** [comment]
Hello @piotrekk6, this is the same issue as #3411. Closing as a duplicate.
