### ISSUE TITLE
25th Anniversary update: monster_apache is not reporting death when it dies

### ISSUE THREAD

**Issue by ilijapetrusic** [ValveSoftware/halflife#3427]
After an monster_apache dies, the target is not getting fired. This is not an issue from the latest update, but figured that it could get a fix if visibility isn't an issue at the moment.

The only wat to check if it is dead currently is via a regular trigger flagged for "monsters" Which does work but some scenarios make it really difficult, and buggy.

**Comment by kisak-valve** [comment]
Hello @ilijapetrusic, this issue is already being tracked at #3262. Closing as a duplicate.
