### ISSUE TITLE
[CS 1.6] 4-7 fps in menu, OpenGL

### ISSUE THREAD

**Issue by m3x** [ValveSoftware/halflife#343]
First of all I have tried every solution I could find:
gl_vsync, gl_ansio, fps_max, nofbo, nomsaa, nohd, soft etc.
Before update everything was ok (~80 fps). Now I can't play because of low fps in menu and game itself. I think it may be a problem with video card GeForce FX 5200 as it's not the newest one ;) but I never had a problem with it.
Here's what I've got:

Nvidia drivers - I use version 175.19 as they are recommended for this card by nvidia.com. They are not the newest but I never have a problem in any game I want to run.

CS version from console:
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 15:00:41 Feb 13 2013 (5956)

And OS info:
http://pastebin.com/a8hi0Xpm

It's almost fresh install of WinXP and I also reinstalled Steam and CS.

**Comment by akrem2244** [comment]
my fps in cs ... so bad in 10 fixed how can i play with good fps pls
