### ISSUE TITLE
What is the s**t with Half-Life Anniversary 25 years - no 64 Bit?

### ISSUE THREAD

**Issue by DeafMan1983** [ValveSoftware/halflife#3434]
Hello, please change to 64 Bit now!
If you don't care to macOS users?

Please enjoy us anniversary 25 years as 64Bit!!!! If we never use 32 Bit if Linux will drop 32bit soon. That is why I want you recompile all to 64Bit.
![image](https://github.com/ValveSoftware/halflife/assets/57066679/7975ed47-15dc-41dc-98aa-a6a1cf22eb90)

I feel disappointed because Valve Sofwtare disrespect us if anniversary 25 years for 64Bit. Thank you!

I hope you develop into 64 bit and not using 32 bit.

**Comment by kisak-valve** [comment]
Hello @DeafMan1983, this request is already being tracked at #2231.

Closing as a duplicate.

**Comment by DeafMan1983** [comment]
Why? It is closed? But It is for 25 years anniversary and please stop using 32 Bit!
