### ISSUE TITLE
[HL25] Steam achievements

### ISSUE THREAD

**Issue by Asphaltian** [ValveSoftware/halflife#3439]
I know this is probably a stretch, but wouldn't it be nice for achievements to be added as part of the anniversary update (along with other Goldsrc games too)? It would massively increase replayability :)

**Comment by mota-with-a-lambda** [comment]
![The Only Half-life Achievement](https://github.com/ValveSoftware/halflife/assets/140289257/15497e65-744d-41c6-a0b7-bb946503cae2)
[I don't think that'll happen](https://www.half-life.com/en/halflife25)

**Comment by Asphaltian** [comment]
> ![The Only Half-life Achievement](https://user-images.githubusercontent.com/140289257/283977850-15497e65-744d-41c6-a0b7-bb946503cae2.png) [I don't think that'll happen](https://www.half-life.com/en/halflife25)

Hmm, I guess you are right... closing this.
