### ISSUE TITLE
[Counter-Strike 1.6] 25th Half-Life anniversary: Counter-Strike 1.6 does not load with the latest version of Half-Life installed

### ISSUE THREAD

**Issue by MrSlimeDiamond** [ValveSoftware/halflife#3440]
OS: Windows 10 (64-bit)

The following error is presented for a friend and myself upon launching Counter-Strike 1.6 with the latest Half-Life release installed:
![image](https://github.com/ValveSoftware/halflife/assets/43764702/a4d3501d-9bd5-4282-a892-43a45bd7ae7b)
The issue appears to persist without Half-Life installed.

# Steps to reproduce
* Launch Counter-Strike 1.6

# The fix
Switching Half-Life to the steam_legacy branch allows the game to launch fine.

**Comment by n07w3n** [comment]
same here

**Comment by kisak-valve** [comment]
Hello @MrSlimeDiamond, this issue is already being tracked at #3411. Closing as a duplicate.
