### ISSUE TITLE
Engine interfaces updated without a version bump

### ISSUE THREAD

**Issue by tmp64** [ValveSoftware/halflife#3442]
Some of the engine interfaces (e.g. `ISurface VGUI_Surface026` and `IFileSystem VFileSystem009`) were changed in a non-backwards-compatible way without bumping the version number. This breaks mods that use them on the updated engine. IFileSystem in particular was published in [the SDK](https://github.com/ValveSoftware/halflife/blob/master/public/FileSystem.h) so it is a part of the public mod API.

Known updated interfaces:
- https://github.com/tmp64/hl1_source_sdk/commit/b3d558195e8ecd5948c2b5e4d210a199e6881834

Proposed solutions.
1. Bump version numbers (e.g. `VGUI_Surface026` -> `VGUI_Surface027`)
   - This will cause the mods to crash early in the startup instead of randomly when some methods are called.
   - Adapter interface exports for the previous version can be added to the engine to support old mods.
2. Move all new methods to the end of the interface definition. This will maintain backwards-compatibility for most of them.

**Comment by tmp64** [comment]
It appears that new methods in the interfaces I mentioned were moved to the end in build 9886 (solution 2)

**Comment by a1batross** [comment]
I just checked VFileSystem009. Seems the new method is in the end of the vtable now.

**Comment by tmp64** [comment]
Closing as the interfaces were fixed shortly after HL25's release
