### ISSUE TITLE
25th Anniversary Update: Disable HUD/VGui2 scaling for non-steamdeck

### ISSUE THREAD

**Issue by SanyaSho** [ValveSoftware/halflife#3450]
Sometimes it looks weird
![изображение](https://github.com/ValveSoftware/halflife/assets/68691958/9fb300aa-24f7-40bf-8e1c-863510c3882b)
![изображение](https://github.com/ValveSoftware/halflife/assets/68691958/57b07c88-be07-4bd1-9cbb-6efdd8ee213f)

**Comment by CS-PRO1** [comment]
The scaling is a welcome addition, especially on very high resolutions. However it's not being calculated correctly

related:
https://github.com/ValveSoftware/halflife/issues/3449

**Comment by JoelTroch** [comment]
Also related to #3436

**Comment by kisak-valve** [comment]
Hello @SanyaSho, this issue is already being tracked at #3436. Closing in favor of the older issue report.
