### ISSUE TITLE
When expand the limit about models and sound cache and optimize the model which have large amount of faces or vertexes?

### ISSUE THREAD

**Issue by WhiteGiveManTao** [ValveSoftware/halflife#3452]
I also use HLDS and develop the new Goldsrc mod,but I have some trouble in the development because of the engine limit,such as models cache and sound cache,they also limit 512,I suggest that expand the limit with this HL25 annvisery new update.

**Comment by DarthMan** [comment]
The limit needs to be expanded to something like 4096 for sounds, models/sprites, generic. Should be sufficient, I guess.

**Comment by WhiteGiveManTao** [comment]
> The limit needs to be expanded to something like 4096 for sounds, models/sprites, generic. Should be sufficient, I guess.

Yes,just like Sven-Coop,and I suggest that Update the renderer about OpenGL,it is main render mode in most of players.

**Comment by StevenKal** [comment]
Maybe use Xash3D for such "less restricted limits".

**Comment by kisak-valve** [comment]
Hello @WhiteGiveManTao, this issue is already being tracked in various issue reports like #12 / #2705 / #1503.

Closing as a duplicate.
