### ISSUE TITLE
[HL25] Game crashes immediately on Fedora 38.

### ISSUE THREAD

**Issue by giorgi-kiknavelidze** [ValveSoftware/halflife#3455]
The game crashes immediately when trying to run half-life 1.
stdout:
```
Error:/home/user/.local/share/Steam/steamapps/common/Half-Life/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/user/.local/share/Steam/steamapps/common/Half-Life/filesystem_stdio.so)
```
stderr:
```
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 10722 != 10721, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Failed to load filesystem library, exiting...
```

The same data is written in stdout and stderr regardless if I force "Steam Linux Runtime 1.0 (scout)" from the compatability menu.

**Comment by JoelTroch** [comment]
Can you confirm that Steam is NOT running through Flathub? There is apparently an issue on Fedora 38 when Steam is running through FlatHub (see https://discussion.fedoraproject.org/t/steam-from-flathub-might-not-start-on-fedora-38/80839 )

**Comment by giorgi-kiknavelidze** [comment]
I can confirm that I'm not using flatpak to run steam, here's the output of `flatpak ps` while I was running steam
```
Instance   PID  Application       Runtime
1202186589 2685 org.signal.Signal org.freedesktop.Platform
4141575994 2660 org.signal.Signal org.freedesktop.Platform
```

as you can see steam is not on the list.

**Comment by tmp64** [comment]
Do you have HLDS installed on your Steam client? If so, you probably have `libstdc++.so.6` and `steamclient.so` in the game directory. Remove both of them. Do not remove HLDS - it will delete all engine and game files, your saves and configs.

**Comment by giorgi-kiknavelidze** [comment]
@tmp64, thank you! deleting just libstdc++ and steamclient.so wasn't enough so I had remove HLDS. deleting saves/configs wasn't an issue since I lost my origical save file long time ago.
