### ISSUE TITLE
[HL25] UTF-16 LE unsupported ingame (Chinese / Korean)

### ISSUE THREAD

**Issue by libre-x** [ValveSoftware/halflife#3456]
[NOTE: I have my Windows language set to English. This is on Windows 11]

It appears that `titles.txt` in `[GAMEDIR]`/(`valve_schinese`/`valve_tchinese`/`valve_koreana`) is being ignored because it is encoded in UTF-16LE instead of UTF-8, leading to this:

![image](https://github.com/ValveSoftware/halflife/assets/57818633/f9f00128-6efc-4977-92e2-5ef2853b7edb)
If I save `titles.txt` with the UTF-8 encoding or UTF-8 with BOM encoding the game does read the file, however it does not work correctly either:
![image](https://github.com/ValveSoftware/halflife/assets/57818633/395aeeb4-16f2-468d-8432-45cfcc4139da)

Please fix this issue as I want this game to have proper Asian language support, especially considering those translations are officially supported and available for selection on Steam.

**Comment by kisak-valve** [comment]
Hello @libre-x, this issue is already being tracked at #2490. Since this issue report adds some more detail, I've transferred the issue report to https://github.com/ValveSoftware/halflife/issues/2490#issuecomment-1817526372.

Closing in favor of the older issue report.
