### ISSUE TITLE
25th Anniversary Update: Audio delay issues when firing a weapon, walking, etc.

### ISSUE THREAD

**Issue by rtxa** [ValveSoftware/halflife#3460]
With the new update, in Half-Life there are some audio delay issues when you are firing a weapon, walking, turning on/off the flashlight, etc. Basically if you fire a weapon, you can hear the sound some miliseconds later instead of being instant of what you see in the screen. This issue is similar to the one in Half-Life 2 which luckily you can fix by lowering the value of `snd_mixahead` to 0.05 but unfortunately this command is not available. Several players have told me they're experiencing this issue so I'm not the only one.

**Comment by 3doplayer67484** [comment]
> With the new update, in Half-Life there are some audio delay issues when you are firing a weapon, walking, turning on/off the flashlight, etc. Basically if you fire a weapon, you can hear the sound some miliseconds later instead of being instant of what you see in the screen. This issue is similar to the one in Half-Life 2 which luckily you can fix by lowering the value of `snd_mixahead` to 0.05 but unfortunately this command is not available. Several players have told me they're experiencing this issue so I'm not the only one.

you can fix it as its called _snd_mixahead in HL1 and in other GoldSrc games 
just set it to 0 in a config file somewhere or in autoexec to fix it

**Comment by kisak-valve** [comment]
Hello @rtxa, this issue was also reported at #3459. Since this issue report adds a bit more detail, I've transferred it to https://github.com/ValveSoftware/halflife/issues/3459#issuecomment-1817531328.

Closing in favor of the older issue report.
