### ISSUE TITLE
Game starts on wrong monitor under KDE Plasma

### ISSUE THREAD

**Issue by FridgeRacer** [ValveSoftware/halflife#3468]
The game launches on my left monitor (0,0) instead of my middle monitor, which is set as primary in Plasma settings (1920,0)

Also happens in the steam_legacy branch. Tested on Plasma 5.27.9 and Plasma 5.27.80 (Plasma 6 Alpha)

Only tested on Wayland, as I don't have an X11 session available at the moment.

Easily fixed by making a Plasma window rule for Half-Life, or just Meta+left click dragging it onto the middle monitor... but it is inconvenient =)

**Comment by kisak-valve** [comment]
Hello @FridgeRacer, this issue is already being tracked at #7. Closing as a duplicate.
