### ISSUE TITLE
Game launches on the left-most display/on the display with the highest resolution available across different ones connected to a PC

### ISSUE THREAD

**Issue by lsahnicne** [ValveSoftware/halflife#3472]
I'm playing on Linux. 

**Distribution:** Pop!_OS 22.04 LTS
 
**Issue/Bug Description:** I have three displays connected to my PC - a 4K TV, a 2K monitor and a FullHD monitor. The 2K monitor is the primary display. When I launch the game, the TV is off. But the game still uses it to launch - I have to use keyboard shortcut to move game window one display to the left to bring it to the primary display. And then I can't use menu properly because it doesn't fit the screen. So on every launch I have to turn on the TV, change the game video settings there to match the resolution of a primary display and only then can I play. 

**Steps to reproduce:** 

1. Connect three display devices to the PC like this:
![Screenshot from 2023-11-11 09-11-46](https://github.com/pop-os/pop/assets/43319094/03709ed6-ff4a-4f84-b122-85f1d79090d1)
Where:
1 - 4K@120 Hz TV connected via HDMI
3 - 2K@144 Hz monitor connected via DisplayPort, _primary display_
2 - FullHD@60 Hz monitor connected via DisplayPort-DVI adapter
2. Have monitors number 2 and 3 on, number 1 TV is off.
3. Launch Half-Life
4. The game window opens on monitor number 1, which is off, and have to be brought to the vieweing area by pressing super+shift+right arrow key.
5. Menu can't be navigated properly because cursor poisition doesn't align with the rendered buttons.
![Screenshot from 2023-11-18 22-30-13](https://github.com/ValveSoftware/halflife/assets/43319094/2b926cb3-b43e-4895-af2a-3407dd69da92)

**Expected behavior:** The game  opens on primary display in fullscreen mode using primary display's resolution.

**Comment by kisak-valve** [comment]
Hello @lsahnicne, as @FridgeRacer noted this issue is already being tracked at #7. Since this issue report adds some additional details regarding complications from the mixed display resolutions, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/halflife/issues/7#issuecomment-1817628754.

Closing in favor of the older issue report.
