### ISSUE TITLE
[HL25] - [MOD] - Older versions of TrackerScheme.res breaks the menus.

### ISSUE THREAD

**Issue by theOneTrueFunniBoi** [ValveSoftware/halflife#3478]
Playing mods such as echoes that use custom TrackerScheme.res files throws an assertion failed on game start.

Program: `halflife/platform/servers/serverbrowser.dll`
File: `ListPanel.cpp`
Expression: `maxWidth >= width`

Pressing Ignore on the assertion presents you with a blank menu, only the background remains.

The current "fix" is to replace the mod's TrackerScheme.res with the HL25 version.

**Comment by kisak-valve** [comment]
Hello @theOneTrueFunniBoi, this issue is already being tracked at #3412. Closing as a duplicate.
