### ISSUE TITLE
[DMC] DeathMatch Classic crashes when you try to connect to/host the server after 25th anniversary update

### ISSUE THREAD

**Issue by TheESN** [ValveSoftware/halflife#3479]
After 25th anniversary update, DMC cannot start new game or join to the existing game. After loading screen it just closes its own window

**Comment by kisak-valve** [comment]
Hello @TheESN until Deathmatch Classic gets an update, you should be able to workaround this issue by switching Half-Life in your Steam library to the `steam_legacy` beta branch.

**Comment by Ch0wW** [comment]
It looks like the problem is fixed with the Nov 19 update.

**Comment by kisak-valve** [comment]
Closing per the last comment.
