### ISSUE TITLE
[HL25] Hostile vortigaunt does not despawn in "Anomalous materials", kills on start of "Unforeseen Consequences"

### ISSUE THREAD

**Issue by libre-x** [ValveSoftware/halflife#3480]
Could be an old and known issue, but figured I could as well describe it anyway.

Step 1:
Once the cart appears, move it a bit inside and then pull out as much as possible.
![image](https://github.com/ValveSoftware/halflife/assets/57818633/7d724e98-3780-49ad-b428-f26fa8e68e47)
![image](https://github.com/ValveSoftware/halflife/assets/57818633/438aae39-37d6-4fa5-8b7f-b86ce09509ad)
Step 2:
Assuming everything is done "correctly", a vortigaunt does not despawn because it touches the cart. You need to run away from it to escape death.
![image](https://github.com/ValveSoftware/halflife/assets/57818633/ec167f3d-b6e0-414b-8049-cc69f7d3e8bb)
![image](https://github.com/ValveSoftware/halflife/assets/57818633/89794331-7bc5-4a3a-98d9-704a66280a90)
Step 3:
Once the chapter beginning loads, you are greeted with a few electric shocks to the head, forcing you to replay the previous checkpoint.
![image](https://github.com/ValveSoftware/halflife/assets/57818633/5a1593de-3972-4c72-a612-9af682d748bc)

Another observation:
That vortigaunt has a pretty low despawn location (can be seen that the "cloud" is noticeably lower than the cart):
![image](https://github.com/ValveSoftware/halflife/assets/57818633/ee57b5bd-bcb3-4e0a-b20d-80cf49e26394)

**Comment by kisak-valve** [comment]
Hello @libre-x, this issue is already being tracked at #1487. Closing as a duplicate.
