### ISSUE TITLE
[HL25] Black bar at the bottom of viewport in software renderer

### ISSUE THREAD

**Issue by MilkeyWilkey** [ValveSoftware/halflife#3483]
![image](https://github.com/ValveSoftware/halflife/assets/9017336/b47ff6a8-7853-4015-a8ca-26d3d14e3d9a)

**Comment by MrEWhite** [comment]
![20231119103655_1](https://github.com/ValveSoftware/halflife/assets/8465017/1df044b2-beba-4a1e-9475-7732301b94a6)
Not getting this bug on my end.

**Comment by BlinkzFox** [comment]
Press the + key to increase screen size

**Comment by MilkeyWilkey** [comment]
totally forgot about that, yeah issue closed
