### ISSUE TITLE
[HL25] Text overlap on center client print and wrong distance

### ISSUE THREAD

**Issue by DarthMan** [ValveSoftware/halflife#3493]
Hello,

As you'll be able to see from the attached picture, when doing client_print with a type of print_center, the same message is printed twice, once in the correct size and once smaller, just like the menu overlap bug. However, it's not just that as now the distance on the bigger text is incorrect when printing on a new line by using \n.
Link to picture: https://i.imgur.com/VToK5Kr.jpeg

Hope this can be solved as well.

Cheers,
DarthMan

**Comment by shawns-valve** [comment]
We believe this was resolved in a patch late last year.

**Comment by DarthMan** [comment]
> We believe this was resolved in a patch late last year.

Yes, this was fixed, thanks.
Now I hope that the menu bug also gets fixed on Deathmatch Classic, Ricochet, Opposing Force, Blue Shift. (was already fixed for TFC, HL1 and CS), as well as the score hud in Opposing Force.
