### ISSUE TITLE
[HL25] Feedback: Increase hud message channels

### ISSUE THREAD

**Issue by DarthMan** [ValveSoftware/halflife#3496]
Hello,

A nice idea would be to increase the hud message channels from 4 to 8, just like it is the case with the Director's HUD Message (dhud).
On my server this could be really useful, as sometimes a message is displayed on the same channel as the other, clearing the old message and displaying the new one instead.

Cheers,
DarthMan

**Comment by kisak-valve** [comment]
Hello @DarthMan, this feature request is already being tracked at #1988.

Closing as a duplicate.
