### ISSUE TITLE
[ISSUE RESOLVED]

### ISSUE THREAD

**Issue by Comicazelambda** [ValveSoftware/halflife#3501]
Current update broke gl_round_down and textures are now crunchy again, even with texture filtering.
![image](https://github.com/ValveSoftware/halflife/assets/151463430/e09bf1af-180a-4304-8f7a-5e58e4bf7165)
![image](https://github.com/ValveSoftware/halflife/assets/151463430/0749baf8-66b9-465b-ac65-cb6551889466)
A friend of mine made these images and this explanation:
This is the result of "Non-Power-of-two" or "NPOT" textures being squished down to powers-of-two, a graphics card compatibility feature that hasn't been needed for decades
This affects all kinds of textures including on most of the game's models. But it's easiest to debug from my example images.

**Comment by IntriguingTiles** [comment]
Unable to reproduce.
![image](https://github.com/ValveSoftware/halflife/assets/13212984/c871853e-5404-41ed-84b4-521ceac0049c)


Also, `gl_round_down` does nothing on hardware that supports the `GL_ARB_texture_non_power_of_two` extension. If your game looks exactly like your bottom screenshot, then your hardware does not report that it supports the necessary extension for NPOT textures.

**Comment by Comicazelambda** [comment]
Ah, thank you for the informative response.
