### ISSUE TITLE
[HL25/CS] When your nickname in the Steam profile is written in non-standard Latin characters, the game closes without any error when you press the "Create server" button in the main menu

### ISSUE THREAD

**Issue by Evisneffo** [ValveSoftware/halflife#3512]
This is happening in the new update in honor of the 25th anniversary.
![Screenshot_3](https://github.com/ValveSoftware/halflife/assets/62428089/681a4ac7-3c8d-4fad-9f25-82b9a9dbb680)

### Problem identified

You must only use standard ASCII characters in your steam profile!
I believe it's an issue with the hostname option inside "create server" menu, which becomes "<steam profile name>'s server", seems to be an issue parsing non-ASCII characters.

I have confirmed the issue and it crashes only when using non-ASCII characters in my steam profile name, some example "ｒ" (full-width Latin character), "д" (Cyrillic letter), "日" (Japanese Kanji character) etc…

Found the cause of the problem: @0Ky 

The same issue occurs in Counter-Strike when clicking the "New Game" button.
![Screenshot_6](https://github.com/ValveSoftware/halflife/assets/62428089/0b9f6b0b-c6ce-4bac-bde0-92217fb48358)

**Comment by marigi64** [comment]
The same is happening to me though I do get an error message.
![Crash](https://github.com/ValveSoftware/halflife/assets/53112738/235a0e6b-3605-40ed-80b4-4478218534e2)

**Comment by marigi64** [comment]
I found that if the maps folder (tested with maps in the "valve_downloads\maps" folder) has too many maps, it will crash the game upon selecting the Create server button. This didn't seem to be a problem before the 25th update though.

**Comment by Evisneffo** [comment]
> То же самое происходит со мной, хотя я получаю сообщение об ошибке. ![Крушение](https://user-images.githubusercontent.com/53112738/284441367-235a0e6b-3605-40ed-80b4-4478218534e2.png)

I had a similar error when I was clicking the 'Add a Server' button in the 'Favorites' tab while finding servers, but this error has already been fixed.
![Screenshot_2](https://github.com/ValveSoftware/halflife/assets/62428089/011c7792-2791-4786-8be2-81c751fd37aa)
![3tZWC3gvS08](https://github.com/ValveSoftware/halflife/assets/62428089/0ea0baae-6251-4c62-bf27-aad07e2e1ae4)

**Comment by Evisneffo** [comment]
But when I click the 'Create Server' button in the main menu, I don't have any error; the game just closes.

**Comment by Evisneffo** [comment]
> > The same is happening to me though I do get an error message. ![Крушение](https://user-images.githubusercontent.com/53112738/284441367-235a0e6b-3605-40ed-80b4-4478218534e2.png)
> 
> I had a similar error when I was clicking the 'Add a Server' button in the 'Favorites' tab while finding servers, but this error has already been fixed. ![Screenshot_2](https://user-images.githubusercontent.com/62428089/284568425-011c7792-2791-4786-8be2-81c751fd37aa.jpg) ![3tZWC3gvS08](https://user-images.githubusercontent.com/62428089/284568485-0ea0baae-6251-4c62-bf27-aad07e2e1ae4.jpg)

But when I click the 'Create Server' button in the main menu, I don't have any error; the game just closes.

**Comment by 0Ky** [comment]
## Description
I have the same issue, upon clicking the `Create Server` main menu option the game immediately crashes to desktop without throwing any error messages. I've been told that some players are able to create the server with the new _Steam Networking_ feature enabled without ever crashing. Here are the things I've did to troubleshoot: 
* Updated graphics drivers
* Repaired Windows system image and fixed corrupted or missing system files.
* Checked for Windows Update (all up to date)
* Disabled A/V
* Re-installed the game (deleted steamapps\common\Half-Life folder each time and cleared steam download cache)
* Verified the integrity of game files several times
* Switched renderer and changed resolution
* Toggled between all different Steam Networking options from Steam settings
* Switched Steam's download region to Washington, DC / Seattle / Dallas and re-installed HL
* Disabled Steam Cloud to download the default _config.cfg_

## System Environment
System drivers and OS is up-to-date.
```make
OS: Windows 11 Pro [64-bit]
Version: 23H2 Build 22631.2715
CPU: AMD Ryzen 5 5600X 6-Core Processor @ 3.7GHz
GPU: AMD Radeon RX 6900 XT
Memory: 14.6 GiB / 31.93 GiB (45%)

Steam Version: 1700676668
Steam Client Build Date: Thu, Nov 23 4:58 AM UTC -08:00
Steam Web Build Date: Wed, Nov 22 7:51 PM UTC -08:00
Steam API Version: SteamClient021
```

## Half-Life Version
```rust
App ID: 70
Build ID: 12783539
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 01:43:07 Nov 23 2023 (9891)
```

## Console Log
Launch option: `-dev +developer 2 -condebug -console`.
Unfortunately, there are no information related to the crash.
However, it may offer insights into the underlying issue.
```rust
Console initialized.
Base networking initialized.
"sv_cheats" changed to "1"
Initializing deltas
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 01:43:07 Nov 23 2023 (9891)
128.0 Mb heap
GL_VENDOR: ATI Technologies Inc.
GL_RENDERER: AMD Radeon RX 6900 XT
GL_VERSION: 4.6.0 Compatibility Profile Context 23.10.1.230929
GL_SIZES:  r:8 g:8 b:8 a:8 depth:24
ARB Multitexture extensions found.
8 texture units.  Detail texture supported.
Successfully compiled "gl_shaders/vs_world.vert"
Successfully compiled "gl_shaders/fs_world.frag"
Successfully linked program!
Successfully compiled "gl_shaders/vs_world.vert"
Successfully compiled "gl_shaders/fs_world.frag"
Successfully linked program!
Successfully compiled "gl_shaders/vs_world.vert"
Successfully compiled "gl_shaders/fs_world.frag"
Successfully linked program!
Successfully compiled "gl_shaders/vs_world.vert"
Successfully compiled "gl_shaders/fs_world.frag"
Successfully linked program!
Successfully compiled "gl_shaders/vs_world.vert"
Successfully compiled "gl_shaders/fs_world.frag"
Successfully linked program!
Successfully compiled "gl_shaders/vs_world.vert"
Successfully compiled "gl_shaders/fs_world.frag"
Successfully linked program!
Successfully compiled "gl_shaders/vs_world.vert"
Successfully compiled "gl_shaders/fs_world.frag"
Successfully linked program!
Successfully compiled "gl_shaders/vs_world.vert"
Successfully compiled "gl_shaders/fs_world.frag"
Successfully linked program!
Sound Initialization
Set primary sound buffer format: yes
Using secondary sound buffer
   2 channel(s)
   16 bits/sample
   11025 bytes/sec
DirectSound initialized
Loaded library demoplayer.dll.
Loaded library core.dll.
Creating fake network channel.
Server module initialized.
Loaded library core.dll.
World module initialized.
DemoPlayer module initialized.
Parsed 160 text messages
WARNING: failed to locate sequence file global
Unknown command from unsafe location. Ignoring.
execing valve.rc
execing language.cfg
execing controller.cfg
execing autoexec.cfg
execing violence.cfg
execing controller.cfg
execing controller.cfg
execing config.cfg
execing controller.cfg
```

**Comment by Evisneffo** [comment]
> ## Description
> I have the same issue, upon clicking the `Create Server` main menu option the game immediately crashes to desktop without throwing any error messages. I've been told that some players are able to create the server with the new _Steam Networking_ feature enabled without ever crashing. Here are the things I've did to troubleshoot:
> 
> * Updated graphics drivers
> * Repaired Windows system image and fixed corrupted or missing system files.
> * Checked for Windows Update (all up to date)
> * Disabled A/V
> * Re-installed the game (deleted steamapps\common\Half-Life folder each time and cleared steam download cache)
> * Verified the integrity of game files several times
> * Switched renderer and changed resolution
> * Toggled between all different Steam Networking options from Steam settings
> * Switched Steam's download region to Washington, DC / Seattle / Dallas and re-installed HL
> * Disabled Steam Cloud to download the default _config.cfg_
> 
> ## System Environment
> System drivers and OS is up-to-date.
> 
> ```makefile
> OS: Windows 11 Pro [64-bit]
> Version: 23H2 Build 22631.2715
> CPU: AMD Ryzen 5 5600X 6-Core Processor @ 3.7GHz
> GPU: AMD Radeon RX 6900 XT
> Memory: 14.6 GiB / 31.93 GiB (45%)
> 
> Steam Version: 1700676668
> Steam Client Build Date: Thu, Nov 23 4:58 AM UTC -08:00
> Steam Web Build Date: Wed, Nov 22 7:51 PM UTC -08:00
> Steam API Version: SteamClient021
> ```
> 
> ## Half-Life Version
> ```rust
> App ID: 70
> Build ID: 12783539
> Protocol version 48
> Exe version 1.1.2.2/Stdio (valve)
> Exe build: 01:43:07 Nov 23 2023 (9891)
> ```
> 
> ## Console Log
> Launch option: `-dev +developer 2 -condebug -console`. Unfortunately, there are no information related to the crash. However, it may offer insights into the underlying issue.
> 
> ```rust
> Console initialized.
> Base networking initialized.
> "sv_cheats" changed to "1"
> Initializing deltas
> Protocol version 48
> Exe version 1.1.2.2/Stdio (valve)
> Exe build: 01:43:07 Nov 23 2023 (9891)
> 128.0 Mb heap
> GL_VENDOR: ATI Technologies Inc.
> GL_RENDERER: AMD Radeon RX 6900 XT
> GL_VERSION: 4.6.0 Compatibility Profile Context 23.10.1.230929
> GL_SIZES:  r:8 g:8 b:8 a:8 depth:24
> ARB Multitexture extensions found.
> 8 texture units.  Detail texture supported.
> Successfully compiled "gl_shaders/vs_world.vert"
> Successfully compiled "gl_shaders/fs_world.frag"
> Successfully linked program!
> Successfully compiled "gl_shaders/vs_world.vert"
> Successfully compiled "gl_shaders/fs_world.frag"
> Successfully linked program!
> Successfully compiled "gl_shaders/vs_world.vert"
> Successfully compiled "gl_shaders/fs_world.frag"
> Successfully linked program!
> Successfully compiled "gl_shaders/vs_world.vert"
> Successfully compiled "gl_shaders/fs_world.frag"
> Successfully linked program!
> Successfully compiled "gl_shaders/vs_world.vert"
> Successfully compiled "gl_shaders/fs_world.frag"
> Successfully linked program!
> Successfully compiled "gl_shaders/vs_world.vert"
> Successfully compiled "gl_shaders/fs_world.frag"
> Successfully linked program!
> Successfully compiled "gl_shaders/vs_world.vert"
> Successfully compiled "gl_shaders/fs_world.frag"
> Successfully linked program!
> Successfully compiled "gl_shaders/vs_world.vert"
> Successfully compiled "gl_shaders/fs_world.frag"
> Successfully linked program!
> Sound Initialization
> Set primary sound buffer format: yes
> Using secondary sound buffer
>    2 channel(s)
>    16 bits/sample
>    11025 bytes/sec
> DirectSound initialized
> Loaded library demoplayer.dll.
> Loaded library core.dll.
> Creating fake network channel.
> Server module initialized.
> Loaded library core.dll.
> World module initialized.
> DemoPlayer module initialized.
> Parsed 160 text messages
> WARNING: failed to locate sequence file global
> Unknown command from unsafe location. Ignoring.
> execing valve.rc
> execing language.cfg
> execing controller.cfg
> execing autoexec.cfg
> execing violence.cfg
> execing controller.cfg
> execing controller.cfg
> execing config.cfg
> execing controller.cfg
> ```

Have you been able to fix this error using the methods mentioned above?

**Comment by 0Ky** [comment]
## Problem identified

You must only use **_standard ASCII characters_** in your steam profile!
I believe it's an issue with the hostname option inside "create server" menu, which becomes "_\<steam profile name\>'s server_", seems to be an issue parsing non-ASCII characters.

I have confirmed the issue and it crashes only when using non-ASCII characters in my steam profile name, some example "ｒ" (full-width Latin character), "д" (Cyrillic letter), "日" (Japanese Kanji character) etc...

@Evisneffo and @marigi64 Please rename your steam profile to something that's within the standard English character and try again.

**Comment by Evisneffo** [comment]
> ## Problem identified
> You must only use **_standard ASCII characters_** in your steam profile! I believe it's an issue with the hostname option inside "create server" menu, which becomes "_<steam profile name>'s server_", seems to be an issue parsing non-ASCII characters.
> 
> I have confirmed the issue and it crashes only when using non-ASCII characters in my steam profile name, some example "ｒ" (full-width Latin character), "д" (Cyrillic letter), "日" (Japanese Kanji character) etc...
> 
> @Evisneffo and @marigi64 Please rename your steam profile to something that's within the standard English character and try again.
> 
> > Have you been able to fix this error using the methods mentioned above?
> 
> No, it has nothing to do with the maps or the maps folder.

@0Ky Lol, that's really true. But I really want it to be fixed because I play with this nickname in CS 2, and everything works fine there.

**Comment by marigi64** [comment]
Looks like it was a different problem entirely from mine (which explains why only I had the error message).

**Comment by 0Ky** [comment]
> Having too many maps was the cause for me.

@marigi64 If you can reproduce that error with the latest version/build, you might want to create a separate issue if one does not already exist.

**Comment by theanyoneuser** [comment]
Hello, I am theanyoneuser coming from the steam discussions, I must say that emojis in your name affects it as well as it shows up as foreign characters in source and goldsrc games.

**Comment by mlibre2** [comment]
apparently a big bug update is coming, we hope the hornet's nest doesn't get upset.

**Comment by Evisneffo** [comment]
[> The default server name and multiplayer player name are now based on the player's Steam Persona.](https://www.half-life.com/ru/halflife25/#:~:text=The%20default%20server%20name%20and%20multiplayer%20player%20name%20are%20now%20based%20on%20the%20player%27s%20Steam%20Persona.)

**Comment by 0Ky** [comment]
> Dec 12, 2023 update:
> \* Fixed crash when creating a server if the server creator's Steam name was entirely non-ASCII characters.

@Evisneffo The recent update should have fixed this, retest and confirm if it's fixed.
Instead of `<your steam profile name>'s server` for the server hostname, it's now `Someone's Server`.

**Comment by Evisneffo** [comment]
> ASCII

@0Ky Yes, you really fixed this error in Counter-Strike and Half-Life, thank you very much! But there is still error #3599, it is also related to non-ASCII characters.
