### ISSUE TITLE
gl_use_shaders 1 disables underwater fog

### ISSUE THREAD

**Issue by BlinkzFox** [ValveSoftware/halflife#3513]
Underwater fog is broken with this new overbright command enabled. Only tested on windows.

gl_use_shaders 1 (incorrect effect):
![20231119234147_1](https://github.com/ValveSoftware/halflife/assets/99220871/5cd9d20a-a86b-47be-a34e-4c653e331dc9)

gl_use_shaders 0 (working properly):
![20231119234159_1](https://github.com/ValveSoftware/halflife/assets/99220871/2489c26f-1ea9-4090-b35a-373a0f93b204)

**Comment by Matthaiks** [comment]
November 22, 2023 Update
> Fixed underwater fog rendering in OpenGL.

gl_use_shaders 1
![c2a50002](https://github.com/ValveSoftware/halflife/assets/3577122/e71a2cff-5d56-4f82-8cf2-affd716f9e6b)

**Comment by BlinkzFox** [comment]
Can also confirm it is now fixed.
![image](https://github.com/ValveSoftware/halflife/assets/99220871/22a6bd0e-f6ae-4bfb-8860-84722a58ddb8)
