### ISSUE TITLE
[HL1] Add HTML support for MOTD and VGUI2 scoreboard

### ISSUE THREAD

**Issue by andreiseverin** [ValveSoftware/halflife#3515]
Hello,

A good feature we can get on our servers will be HTML support for MOTD. It will help us better interact with player and display data such as statistics in a more modern way. This will also help differentiate better servers, where a lot of works has been done, from those fake ones that are filling the internet list. We can implement various APIs, functions etc with this feature.

Second thing, it will be nice to have an upgraded scoreboard, using VGUI2, that displays players profile pictures, differentiate BOTs from real players and can help you go directly on a player STEAM profile to send him a friend request. There are some patches that do this, I'll let you an example :
![image](https://github.com/ValveSoftware/halflife/assets/39212135/bb7b8ddf-29e5-41fd-9574-da2b68d65ad6)

**Comment by kisak-valve** [comment]
Hello @andreiseverin, these requests were previously evaluated at https://github.com/ValveSoftware/halflife/issues/507#issuecomment-13955611 and https://github.com/ValveSoftware/halflife/issues/1352#issuecomment-24276985.

Sorry, but that makes this feature request a non-starter.
