### ISSUE TITLE
[HL] Implement bigger environmental map size images

### ISSUE THREAD

**Issue by N7P0L3ON** [ValveSoftware/halflife#3516]
Currently the supported size of the "sky" images (/gif/env) is limited to 256x256 pixels.

Please increase the limit for the supported images sizes from 256x256 to 512x512 or 1024x1024 for better and modern experience. 

This will benefit the mappers and the games using the Gold Source engine in general. 

Thanks.

**Comment by SamVanheer** [comment]
Duplicate of #1765

**Comment by kisak-valve** [comment]
Closing as a duplicate.
