### ISSUE TITLE
[HL] Lift the hard limit for textures from 3d models supported by the engine

### ISSUE THREAD

**Issue by N7P0L3ON** [ValveSoftware/halflife#3517]
Currently the engine supports model textures up to 512x512 for use with the 3d models for the game.

If possible raise the limit to 1024x1024 for the Half-Life engine and the Half-Life games used by the engine. 

This one will benefit the community and the overall quality of the 3d models used.

**Comment by kisak-valve** [comment]
Hello @N7P0L3ON, this feature request is already being tracked at #3433.

Closing as a duplicate.
