### ISSUE TITLE
Counter Strike Condition Zero Delected Scenes the world map is completely broken

### ISSUE THREAD

**Issue by Diegoparedeshd1** [ValveSoftware/halflife#3518]
Previously the world map only broke if played in 16:9 but in 4:3 it worked correctly.
But with the 25th anniversary update it breaks completely regardless of the resolution or aspect ratio

16:9
![20231120120333_1](https://github.com/ValveSoftware/halflife/assets/151307139/0369bdda-4d93-4831-ac9d-432887029379)

4:3
![20231120120421_1](https://github.com/ValveSoftware/halflife/assets/151307139/c77a16a8-a648-490c-b315-2b4294043564)

**Comment by kisak-valve** [comment]
Hello @Diegoparedeshd1, this issue is already being tracked at #3489 / #1398. Until there's a game update, you should be able to workaround this issue by switching Half-Life to the `steam_legacy` beta branch.

Closing in favor of the older issue reports.
