### ISSUE TITLE
player death animations affected by fps

### ISSUE THREAD

**Issue by crustypig** [ValveSoftware/halflife#352]
When using fps values above 100, the player death animation can sometimes leave behind a ghost of the player model which floats in the air. At 400fps for example, every time I am killed my corpse is floating in the air. Note: It obviously doesn't occur when a player is gibbed, but when shot with a shotgun or 9mmAR for example.

It seems the death animation isn't executed properly at high values of fps. In this picture you can see the effect.

![ghost_bug](https://f.cloud.github.com/assets/3589010/168741/7c843894-7a06-11e2-88a0-9267520473cf.png)

**Comment by shawns-valve** [comment]
This was resolved for Half-Life Deathmatch in the 25th Anniversary update (November / December 2023 Steam build). The issue may still be present in other mods.

The relevant changes are in dll\player.cpp, changing m_iRespawnFrames to m_flRespawnTimer.
