### ISSUE TITLE
HLDS/HLTV for Mac OS X

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/halflife#353]
Would it possible to release HLDS (and perhaps HLTV) for running either a HLDM or a CS 1.6 dedicated server on OS X?

Since most of the server logic is already in other binaries like engine.dylib, I can't imagine that there would be many changes needed to build it. 

You wouldn't necessarily have to build steamcmd for OS X (though it would be nice). Shipping hlds_osx and hlds_run along with the client might be one way to do it.

There could be a few changes to the hlds_run script to detect OS X via 'uname' in order to use an 'hlds_osx' binary instead of 'hlds_linux' and to set DYLD_LIBRARY_PATH instead of LD_LIBRARY_PATH. This is pretty much what hl.sh already does for the client.

**Comment by krik73** [comment]
app_update 90 -beta beta validate
cstrike, valve , libtier0_s.dylib libvstdlib_s.dylib steamclient.dylib
how to start cs 1.6 Dedicated Server?

**Comment by pcace** [comment]
Any solution?
