### ISSUE TITLE
Half-Life Dedicated Server has not been updated

### ISSUE THREAD

**Issue by SamVanheer** [ValveSoftware/halflife#3531]
Half-Life Dedicated Server, app 90 on Steam has not been updated to the new version: https://steamdb.info/app/90/depots/

The depots that aren't shared with other games are out of date and can cause compatibility issues. Users have reported problems trying to host dedicated servers using this app: https://knockout.chat/thread/55507/15#post-2030223

App 90 is required to host servers without having to log in to a Steam account that owns the game. Is this still the method that server operators need to use today?

Issue related: #2668

**Comment by DarthMan** [comment]
Would be nice to also provide .pdb file for swds.dll on GitHub for coders. Not required for Linux, as the symbols are already exported. A good example is hooking GetEntityInit to create new classnames from a base pointer.

**Comment by SamVanheer** [comment]
HLDS was updated but is once again out of date:
https://steamdb.info/app/70/depots/
https://steamdb.info/app/90/depots/

Looks like it's one update behind.
