### ISSUE TITLE
[HL25] Weapons Glitched Idle Animation

### ISSUE THREAD

**Issue by QuakerCraft** [ValveSoftware/halflife#3532]
Hi, i wanted to do a bug report, I have made a video where you can see all the bug that i found on the weapons of HL1.

https://youtu.be/edJ5Iip1wyg

Hope that can help fix them in future updates.

**Comment by kisak-valve** [comment]
Hello @QuakerCraft, this issue is already being tracked at #2495 / #1585. Feel free to add your experience to an older issue report.

Closing in favor of the older issue reports.
