### ISSUE TITLE
When killing someone, why do they just gradually disappear instead of splattering into pieces?

### ISSUE THREAD

**Issue by Evisneffo** [ValveSoftware/halflife#3533]
Although I have censorship turned off.
![20231121194830_1](https://github.com/ValveSoftware/halflife/assets/62428089/31f441a2-81b3-499b-aed9-07a91acc372b)

**Comment by kisak-valve** [comment]
Heallo @Evisneffo, please give #2362 a read and check if it's relevant to you.

**Comment by Evisneffo** [comment]
> Heallo @Evisneffo, please give #2362 a read and check if it's relevant to you.

Thank you, one of the methods described there did help me. Specifically, changing the 4 parameters in the config.cfg file.

**Comment by Evisneffo** [comment]
> Heallo @Evisneffo, please give #2362 a read and check if it's relevant to you.

Thank you, one of the methods described there did help me. Specifically, changing the 4 parameters in the config.cfg file.
