### ISSUE TITLE
[HL25] No more than 2 decals can be displayed

### ISSUE THREAD

**Issue by DarthMan** [ValveSoftware/halflife#3535]
Hello,

Starting with the new update, only 1 or 2 decals can be displayed to the clients. This affects sprays as well, since they're also decals.
Hope this can be fixed in the next update.

Cheers,
DarthMan

**Comment by SamVanheer** [comment]
What are the values of the cvars `r_decals` and `mp_decals` in your game?

**Comment by DarthMan** [comment]
> What are the values of the cvars `r_decals` and `mp_decals` in your game?

Both are set to 5, it seems.

**Comment by SamVanheer** [comment]
> > What are the values of the cvars `r_decals` and `mp_decals` in your game?
> 
> Both are set to 5, it seems.

In my case it's 4096 and 300, respectively. Change the settings, reload the map and see if it works then.

**Comment by DarthMan** [comment]
> > > What are the values of the cvars `r_decals` and `mp_decals` in your game?
> > 
> > 
> > Both are set to 5, it seems.
> 
> In my case it's 4096 and 300, respectively. Change the settings, reload the map and see if it works then.

This fixes it, thanks. But the values need to be defaulted to those on a fresh installation.

**Comment by SamVanheer** [comment]
Those are the default values. Maybe a config file is changing the values?

**Comment by DarthMan** [comment]
> Those are the default values. Maybe a config file is changing the values?

Don't think so, I did not have this issue before the 25th anniversary update.

**Comment by shawns-valve** [comment]
Closing since this was resolved above and nobody else has reported the issue
