### ISSUE TITLE
"Display multiplayer scores" not working on any server

### ISSUE THREAD

**Issue by WhitleyStriber** [ValveSoftware/halflife#3539]
![2023-11-21_16-55](https://github.com/ValveSoftware/halflife/assets/5761757/49cadacd-7887-4a3b-a478-7d6a4d2337c6)

I'm on Gentoo Linux and the game runs perfectly fine. The only thing that doesn't work is the leaderboard. When you try to press the keybind, nothing shows up at all. Even when the game ends, the leaderboard does not show up at the end of the game.

**Comment by kisak-valve** [comment]
Hello @WhitleyStriber, this issue is already being tracked at #3447.

Closing as a duplicate.
