### ISSUE TITLE
Incorrect HUD Scaling on some Widescreen Resolutions

### ISSUE THREAD

**Issue by K4RT0FALQUE** [ValveSoftware/halflife#3549]
Large HUD on resolutions 1280x768, 1360x768 and 1366x768.

![20231122201557_1](https://github.com/ValveSoftware/halflife/assets/151770578/1e3991fc-84c6-4ac1-83b9-54c4d86ed597)

Below is HUD scaling on 1280x720, the way it should look.
![20231122205721_1](https://github.com/ValveSoftware/halflife/assets/151770578/87cde697-66a8-44ec-abd8-9bd9deaa6d3e)

**Comment by kisak-valve** [comment]
Hello @K4RT0FALQUE, this issue is already being tracked at #3499. Closing as a duplicate.
