### ISSUE TITLE
[HL25] viewsize in software mode

### ISSUE THREAD

**Issue by a1batross** [ValveSoftware/halflife#3554]
This cvar from Quake/Doom days apparently works in current software engine. Don't know if it's supposed to work.

If it is, it must have an UI option for it.

If it isn't, it should be ignored, like in OpenGL.

**Comment by a1batross** [comment]
There was a UI for that in WON launcher: 
![изображение](https://github.com/ValveSoftware/halflife/assets/3213697/0687dc2f-d795-4735-bd01-9596dd1b2075)

**Comment by kisak-valve** [comment]
Hello @a1batross, this issue is already being tracked at #155. Closing as a duplicate.
