### ISSUE TITLE
Detail textures broken with gl_use_shaders

### ISSUE THREAD

**Issue by SirYodaJedi** [ValveSoftware/halflife#3555]
Affects all games, but will be most noticeable in CZero and DoD, as those are the only titles to use detail textures in their vanilla form.

Detail textures do not correctly display when `gl_use_shaders` is enabled (the replacement for `gl_overbright`, as mentioned in #3424). 

gl_use_shaders 1 and r_detailtextures 1
![dod_chemille0001](https://github.com/ValveSoftware/halflife/assets/50331474/35288de8-0b25-4ca9-b170-8e07222b2de8)

gl_use_shaders 0 and r_detailtextures 1
![dod_chemille0002](https://github.com/ValveSoftware/halflife/assets/50331474/1d0ba32d-68e4-4719-a3e3-2ccec4281594)

**Comment by SirYodaJedi** [comment]
Seems to be fixed.

![dod_chemille0000](https://github.com/ValveSoftware/halflife/assets/50331474/33950b37-9c17-4e24-9343-f7b1bd2efd7a)

**Comment by Maharic** [comment]
The new overbright shader isn't working at all in DOD or I think any of the other GoldSrc games.

The issue with DOD is that the new shader was simply enabled which automatically disabled Detailed Textures.  This is legacy behaviour.

The current live version of Half-life allows for everything to work together, which is new.  Hopefully they can get that working for every other game.
