### ISSUE TITLE
[HL25] UI elements don't have designated colors

### ISSUE THREAD

**Issue by HaajPaaj** [ValveSoftware/halflife#3559]
I haven't seen this bug appear in any version prior to the 25th anniversary update. In Half-Life and other mods, a color is assigned to certain GUI elements. However, these colors disappear, seemingly at random and come back just as randomly. I have seen this behavior in Half-Life and Opposing Force. 

![20231122193502_1](https://github.com/ValveSoftware/halflife/assets/68178179/bc98d8d4-610b-455a-b622-affde3b16ee6)
![20231122193510_1](https://github.com/ValveSoftware/halflife/assets/68178179/f473783a-ad22-419a-b2a5-287a901772e7)
![20231122193655_1](https://github.com/ValveSoftware/halflife/assets/68178179/31b7c89c-5a8e-4134-a274-30a6e9ad6c51)

This also happens with the train GUI in On a Rail and the Hazard Course. (which is also slightly off center)

EDIT: this appears to be an OpenGL bug, as the UI icons appear with the colors in the Software Renderer

![20231122194748_1](https://github.com/ValveSoftware/halflife/assets/68178179/ab14b25a-7c5a-4a48-9495-4ef0e8e01e39)

**Comment by kisak-valve** [comment]
Hello @HaajPaaj, this issue is already being tracked at #3408. Closing as a duplicate.
