### ISSUE TITLE
[HL25] Game crashes when tries to open options menu after recent update

### ISSUE THREAD

**Issue by TheESN** [ValveSoftware/halflife#3567]
It worked fine for me before recent update that came out today. Now the game just closes itself when tries to open options menu

**Comment by Maharic** [comment]
I had a previous backup 'valve' folder that I switched to and it fixed this.  So it's probably something in the config that it conflicting with the update.

**Comment by Martyste** [comment]
Same here, I hope this is figured out soon, i'm locked out of testing more things in Software + everytime I boot i have chosen to manually turn off the filtering so that the game starts with filtered HUD ( hides some unexplained distortion ) but unfilters the environment.

**Comment by se7entfc** [comment]
Same here, only started today for some reason

**Comment by Bo9da** [comment]
Same, options in cs still work and crosshair preview background got fixed lol

**Comment by avsar-master** [comment]
Confirm. Also the background image looks like this:
![image](https://github.com/ValveSoftware/halflife/assets/61117050/5ca37054-a8ad-46f6-902e-29470e917474)

**Comment by Lamborge** [comment]
Same here

**Comment by Ch0wW** [comment]
It does crash too on my end, using a Win10 computer along with the Steam Deck.

**Comment by waspennator** [comment]
Tested it earlier today, game crashed on deck If you opened options, got an update and now it doesn't crash anymore on my end

**Comment by Martyste** [comment]
Options can be opened again! The update is a success on my side too.

**Comment by TheESN** [comment]
Yep it works now. Closing as completed
