### ISSUE TITLE
[HL25] The windows version is installed on linux by default, it doesn't start, the issue returns after restarting Steam

### ISSUE THREAD

**Issue by vic-bay** [ValveSoftware/halflife#3568]
The windows version is installed on linux by default, and it is installed incorrectly (doesn't start, tries to use system Wine and just throws some errors).
There are two workarounds on the user side:
1. Enabling compatibility in the game settings and running the windows version of the game. It keeps working after restarting Steam.
2. Toggling on and off the compatibility checkbox, and then the linux version of the game is downloaded (small update with linux binaries), and the game runs normally, **BUT, after restarting steam, the issue returns**: Steam automatically downloads  the windows binaries, deletes linux ones, tries to run the windows version, and the issue has to be worked around again.

Details:

1. Compatibility is **not** enforced in the game properties.
2. Clean installation, with all directories, half-life addons, compatdata and appmanifest for id70 (half-life) are deleted.
3. The file access rights seem to be correct and the manifest is updated when toggling compatibility settings. 
4. The windows version of the game is downloaded with .exe files.
5. The game fails to start, with following error windows:
```
Failed to initialize authentication interface. Exiting...
```
After pressing OK, there is Wine C++ Runtime Library error window:
```
Assertion failed!

Program: Z:\vol\1\local\games\steamapps\common\Half-Life\hl.exe
File: c:\buildslave\goldsrc_win32\build\GoldSrc\filesystem\FileSystem_Stdio\FileSystem\Stdio.cpp
Line: 84

Expression: "!m_bMounted"
```

```
Computer Information:
Manufacturer: ASUSTeK COMPUTER INC.
Model: TUF GAMING X570-PLUS (WI-FI)
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 7 3700X 8-Core Processor
CPU Family: 0x17
CPU Model: 0x71
CPU Stepping: 0x0
CPU Type: 0x0
Speed: 4426 MHz
16 logical processors
8 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
"Manjaro Linux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.6.1-1-MANJARO
X Server Vendor: The X.Org Foundation
X Server Release: 12101009
X Window Manager: KWin
Steam Runtime Version: <Runtime disabled>
Video Card:
Driver: NVIDIA Corporation NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 535.129.03
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x10de
DeviceID: 0x1e84
Revision Not Detected
Number of Monitors: 2
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 3840 x 1080
Primary Display Size: 18.74" x 10.55" (21.50" diag), 47.6cm x 26.8cm (54.6cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 8192 MB
Supported MSAA Modes: 2x 4x 8x 16x
Sound card:
Audio device: Nvidia GPU 92 HDMI/DP
Memory:
RAM: 32005 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_GB.UTF-8
Total Hard Disk Space Available: 488078 MB
Largest Free Hard Disk Block: 161315 MB
Storage:
Number of SSDs: 2
SSD sizes: 4000G,0B
Number of HDDs: 0
Number of removable drives: 0
```

**Comment by kisak-valve** [comment]
Hello @vic-bay, the Steam client is responsible for downloading and managing of game content, not the game itself.

This issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/9875. Closing as a duplicate.
