### ISSUE TITLE
[HL25] After the latest update, the game started closing without any error after pressing the "Options" button in the main menu.

### ISSUE THREAD

**Issue by Evisneffo** [ValveSoftware/halflife#3569]
![Screenshot_4](https://github.com/ValveSoftware/halflife/assets/62428089/fe0fe504-c9cd-4722-9ec6-8862862b04f0)

**Comment by kisak-valve** [comment]
Hello @Evisneffo, this issue is already being tracked at #3567. Closing as a duplicate.
