### ISSUE TITLE
[HL25] Stealing rockets with the red dot of the rocket launcher is now even more severe

### ISSUE THREAD

**Issue by TheStormN** [ValveSoftware/halflife#3570]
The old bug about stealing enemy rockets(and enemy stealing yours) with the read dot seems to be much more severe, compared to before. It would be best if this bug is fixed in general.

**Comment by Maxi605** [comment]
Can you elaborate a bit more about this issue?

**Comment by TheStormN** [comment]
When you and you enemy are both holding a rocket launcher and for example you shoot the rocket, the enemy red dot sometimes(most of the times now) may steal it at turn it back to you, thus hitting you with your own rocket.

**Comment by kisak-valve** [comment]
Hello @TheStormN, this would be better off as a note on the older issue report at #3361 than a separate issue report.

Closing in favor of the older issue report.

**Comment by TheStormN** [comment]
@kisak-valve The thing is this is happening in multiplayer....
