### ISSUE TITLE
[HL25] Move speed no longer lowered while using the E button

### ISSUE THREAD

**Issue by TheStormN** [ValveSoftware/halflife#3571]
This issue greatly impacts using elevators and charging stations as you can very easily disrupt the sequence. For example, on crossfire I often fail to get to the next floor using the elevator, because of my character acceleration which is hitting the sealing, so the elevator just goes back.

**Comment by marigi64** [comment]
Seems to work just fine for me.

**Comment by TheStormN** [comment]
Seems to be fixed in the latest HL25 updates. I will close this issue.
