### ISSUE TITLE
[CS] Favorite servers list not working after changing resolution

### ISSUE THREAD

**Issue by FEDERICOMB96** [ValveSoftware/halflife#3573]
Hi, after changing between resolutions the list of favorite servers stops working. Occurs with any resolution change. I can't verify if it happens with another mod (HL1, TFC, CS:CZ, etc.).

https://youtu.be/ZRYgqk_Z-o0

**Comment by kisak-valve** [comment]
Closing per "Fixed server browser issues after modifying video settings." in the [2023-12-01](https://store.steampowered.com/news/app/70/view/5458988598256170378) Half-Life update.
