### ISSUE TITLE
[HL25] HEV UI appears & flashes white inconsistently

### ISSUE THREAD

**Issue by AlyMar1994** [ValveSoftware/halflife#3579]
**Computer Specs/Game Settings:**
- _Monitor:_ SCEPTRE Y27, 2560x1440/144hz
- [Extra system info as requested by ./halflife/ Readme (STEAM Help -> System Information)...](https://gist.github.com/AlyMar1994/e69f826eeb381ab71a7b8a72e20a5ebf)
_(First time using GitHub Gist, go easy on me.  I think it's public lol)._

![sysinfo](https://github.com/ValveSoftware/halflife/assets/20891893/a4809097-a8cd-4782-b879-e25677cb23dc)

HL VERSION:
- Protocol version 48
- Exe version 1.1.2.2/Stdio (valve)
- Exe build: 01:43:07 Nov 23 2023 (9891)
(Fresh installation of HL25 build).

SETTINGS: (happens even without console commands in the last photo, launch params included):
![sysinfo2](https://github.com/ValveSoftware/halflife/assets/20891893/940f5384-4f4b-45c3-b8b8-38f7fa337056)
`-novid -noborder -noforcemspd -noforcemaccel -noforcemparms`
`fps_override 1` `fps_max 144`

**Description:**
Since HL25, the HEV UI on my end will appear white in spots, and when I get a status effect (electricity, cold, toxic waste, etc.) the status effect icon will flash white and yellow rapidly while fading in and out.  Some of the UI will start off white, then appear yellow as I hover over it, or vice-versa.

This happens no matter what resolution I pick, and as such I took the photos in both small and large resolutions to showcase the issue.  This does happen in Opposing Force and Blue Shift; Op4 is showcased in the last screenshot (taken in low resolution as HL25's UI scaling hasn't been backported yet). In Op4's case, part of the ammo indicator also turns white.

As stated before, this only started happening after HL25.

**Screenshots/Video:**
Half-Life (weapon selection):
![bugproof1](https://github.com/ValveSoftware/halflife/assets/20891893/59963c55-d251-415b-a928-a7ff819a782f)

Half-Life (flashing [freezing] status effect):
![bugproof2](https://github.com/ValveSoftware/halflife/assets/20891893/f33dc1cb-e780-416a-9dbe-2093f6b0d211)

Half-Life: Opposing Force (UI is broken entirely):
![bugproof3](https://github.com/ValveSoftware/halflife/assets/20891893/db79e5ba-bcf1-4628-a814-e613f6c89fd8)

**Comment by AlyMar1994** [comment]
_Monitor:_ SCEPTRE Y27, 2560x1440/144hz
![sysinfo](https://github.com/ValveSoftware/halflife/assets/20891893/a4809097-a8cd-4782-b879-e25677cb23dc)
https://gist.github.com/AlyMar1994/e69f826eeb381ab71a7b8a72e20a5ebf

**Comment by kisak-valve** [comment]
Hello @AlyMar1994, this issue is being tracked at #3408. Closing as a duplicate.

**Comment by AlyMar1994** [comment]
> Hello @AlyMar1994, this issue is being tracked at #3408. Closing as a duplicate.

Woops, sorry about that.  Couldn't find 3408 originally after searching.  Thank you!
