### ISSUE TITLE
[HL25] In-Game Server Browser Limited to 169.254.0.0/16 IP Range

### ISSUE THREAD

**Issue by 0Ky** [ValveSoftware/halflife#3580]
```
App ID: 70
Build ID: 12783539
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 01:43:07 Nov 23 2023 (9891)
```
When using the in-game server browser, it occasionally displays only servers hosted within the `169.254.0.0/16` IP range (assuming it's related to the new Steam Networking feature). Adjusting the filter settings does not seem to influence this limitation. The only workaround I've found so far is restarting the game, which then allows the server browser to display servers outside of this specific IP range. This issue has occurred multiple times and appears to be a bug in the server browser's network discovery mechanism.

## Screenshot:
<img src="https://github.com/ValveSoftware/halflife/assets/16103757/c0cf47fc-bfe0-4aee-ab6c-42fd72dbde7d" width="650">

**Comment by mutezero** [comment]
For the record, this range of address is reserved for [APIPA](https://learn.microsoft.com/en-us/windows-server/troubleshoot/how-to-use-automatic-tcpip-addressing-without-a-dh)

My assumption is that these are listen servers utilizing p2p sessions, as they use SteamIDs to connect instead of IPv4

**Comment by 0Ky** [comment]
I've tested the issue again with the recent update from build version `01:03:30 Dec  1 2023 (9899)` and it appears to be resolved.

**Comment by kisak-valve** [comment]
Closing per the last comment.
