### ISSUE TITLE
[HL25] Incorrect Encoding of Non-ASCII Characters in Scoreboard Names

### ISSUE THREAD

**Issue by 0Ky** [ValveSoftware/halflife#3584]
## Description
When changing the in-game name to include non-ASCII characters (such as `ñßéåğłãЖΘ中のअخ`), these characters are displayed incorrectly on the scoreboard, suggesting an issue with character encoding. However, the same characters are displayed correctly in the chat and console.

## Steps to Reproduce
1. Change the in-game name to include non-ASCII characters: `ñßéåğłãЖΘ中のअخ`.
2. Join a game and observe the name displayed on the scoreboard (press tab).

## Expected Behavior
The non-ASCII characters in the name should be consistently displayed correctly in the scoreboard, chat and console.

## Actual Behavior
The non-ASCII characters are displayed incorrectly on the scoreboard, likely being encoded into a different character set (such as `Windows-1252`), while they are displayed correctly in the chat.

## Build Version
- App ID: 70
- Build ID: 12783539
- Protocol version 48
- Exe version 1.1.2.2/Stdio (valve)
- Exe build: 01:43:07 Nov 23 2023 (9891)

## Screenshot

![image](https://github.com/ValveSoftware/halflife/assets/16103757/8cf3c50d-a2c6-4f2f-a424-57026aafd769)

**Comment by kisak-valve** [comment]
Hello @0Ky, this issue was previously evaluated at #1352. Closing per https://github.com/ValveSoftware/halflife/issues/1352#issuecomment-24276985.

**Comment by 0Ky** [comment]
Hi @kisak-valve, I appreciate your reference to the comment, but it's been more than a decade since the original assessment, and a lot has changed in that time. I believe it might be worthwhile to re-evaluate this situation in light of recent updates _(25th anniversary)_ and developments. This milestone event could be an opportunity to reconsider suggested fixes that were previously set aside, like this character encoding issue.

Additionally, I would like to highlight that there have been open-source projects successfully implementing VGUI2 with the Half-Life 1 SDK, such as [tmp64/BugfixedHL-Rebased](https://github.com/tmp64/BugfixedHL-Rebased/blob/master/src/game/client/vgui/score_panel.cpp). This includes an updated UI utilizing VGUI2, which offers benefits like colored text, better handling of non-ASCII characters, and a more improved overall UI experience compared to VGUI1.

I kindly request that we reopen the discussion on this issue. The integration of VGUI2, as demonstrated by the open-source community, shows promising potential for not only resolving the character encoding problem but also offering additional enhancements.

## Screenshots

### Scoreboard

Below are screenshots of `BugfixedHL-Rebased` demonstrating VGUI2 in action, works with the latest version of HL `11:26:46 Dec 11 2023 (9909)`.

![image](https://github.com/ValveSoftware/halflife/assets/16103757/553f9269-6e85-40aa-83d7-422f8098e9e8)

### Chat

![image](https://github.com/ValveSoftware/halflife/assets/16103757/84d3ad1f-a5b9-400e-8a7f-199387adb3ae)

### Console

![image](https://github.com/ValveSoftware/halflife/assets/16103757/2840d5ac-40b0-41b8-9340-faee86c14e5b)

### Killfeed

![image](https://github.com/ValveSoftware/halflife/assets/16103757/21b2073b-f2d5-43e2-9ad9-a81c9bb97933)

**Comment by di57inct** [comment]
This would add so many improvements to goldsrc games. I get that the goldsrc dev team is overtasked and understaffed but the community should be allowed to contribute. Reviewing some code instead of actually writing it would save a lot of time.

**Comment by 0Ky** [comment]
@shawns-valve Is there any chance this could be looked at again since it was last evaluated over a decade ago?
