### ISSUE TITLE
[HL25] Unable to move sample in Anomalous Materials

### ISSUE THREAD

**Issue by larb0b** [ValveSoftware/halflife#3585]
[Half-Life-162.sav.zip](https://github.com/ValveSoftware/halflife/files/13461657/Half-Life-162.sav.zip)

I started a game of Half-Life on Hard and I'm not able to move the sample in the test chamber in Anomalous Materials. Pressing use on it from the front or back and attempting to drag does nothing. I've attached the save.

**Comment by larb0b** [comment]
I found that if I reload a save before pressing the switch that activates the sequence, it just keeps happening. However, if I change fps_max from 200 to 60 then it works fine, so it seems high fps_max breaks Anomalous Materials.

**Comment by kisak-valve** [comment]
Hello @larb0b, this issue is already being tracked at #2882. Since this adds a bit more detail, I've transferred this issue report to https://github.com/ValveSoftware/halflife/issues/2882#issuecomment-1826010979.

Closing in favor of the older issue report.
