### ISSUE TITLE
[HL25] Request for a server cvar to allow legacy _special behavior

### ISSUE THREAD

**Issue by AltimorTASDK** [ValveSoftware/halflife#3587]
The `special` command appends `_special` to the end of the client command buffer, allowing macro scripts that don't block player input by defining `_special` aliases. This is heavily used in the scripted speedrun category.

https://github.com/ValveSoftware/halflife/blob/master/cl_dll/vgui_TeamFortressViewport.cpp#L1462

However, newer versions of the engine DLL blacklist `_special` aliases in `Cmd_Alias_f`. This is a good default, but it would be best if it could be a toggled similar to `sv_allow_wait_command` in Source.

**Comment by kisak-valve** [comment]
Hello @AltimorTASDK, this issue is already being tracked at #1154. Closing as a duplicate.

**Comment by AltimorTASDK** [comment]
@kisak-valve #1154 has been inactive for 3 years and has not received a Valve response. Regardless, my request is distinct. I don't wish for loop macros to be allowed by default in any game, but for it to be a choice for server operators and singleplayer players, exactly as it is in Source games.

If the fear is backwards compatibility due to GoldSrc's method of replicating movement vars, then it can be tied to `sv_cheats` for singleplayer use.
