### ISSUE TITLE
Counter-Strike: Condition Zero remains broken

### ISSUE THREAD

**Issue by Asphaltian** [ValveSoftware/halflife#3589]
CS:CZ (Not Deleted Scenes) still throws assert errors even after multiple updates.
![Screenshot 2023-11-25 110025](https://github.com/ValveSoftware/halflife/assets/86578963/da1f6467-1249-48a3-b193-e0508477e06b)
![Screenshot 2023-11-25 110040](https://github.com/ValveSoftware/halflife/assets/86578963/0f9cdd7d-9324-4141-b4c7-7b2a80b5ef73)

**Comment by kisak-valve** [comment]
Hello @Asphaltian, this issue is already being tracked at #3412. Until this game gets updated, you should be able to go to Half-Life's settings and opt into the `steam_legacy` beta branch to play this game.

Closing in favor of the older issue report.
