### ISSUE TITLE
[Windows] Binaries are not marked as LAA (Large Address Aware).

### ISSUE THREAD

**Issue by goodusername123** [ValveSoftware/halflife#3590]
On the Microsoft Windows operating system the "EXE" binaries `hl.exe`, `hlds.exe`, and `hltv.exe` are not marked as being large address aware which means they are artificially limited to a maximum of 2GB of memory/ram instead of the max 4GB that 32-bit processes are capable of using/handling.

https://learn.microsoft.com/en-us/windows/win32/memory/memory-limits-for-windows-releases
https://learn.microsoft.com/en-us/cpp/build/reference/largeaddressaware-handle-large-addresses?view=msvc-170

**Comment by gonchik** [comment]
@goodusername123  Do you think that 3 binaries is really needed that parameters /LARGEADDRESSAWARE:YES  
on linker level ?

**Comment by shawns-valve** [comment]
This should be resolved in the October 2, 2024 Steam build.

**Comment by gonchik** [comment]
@shawns-valve thanks! yohoo!
