### ISSUE TITLE
[CS] When entering a server with players, an error occurs

### ISSUE THREAD

**Issue by Evisneffo** [ValveSoftware/halflife#3599]
![Screenshot_5](https://github.com/ValveSoftware/halflife/assets/62428089/5c105190-b3f1-4fc1-bba2-62aaa200e391)

I tried joining empty servers, and there is no error there.

Most likely, it is somehow related to this error #3512 as I changed my nickname to regular Latin characters and was able to join a server with players.

**Comment by mlibre2** [comment]
seems to be related [#3598](https://github.com/ValveSoftware/halflife/issues/3598)

**Comment by namazso** [comment]
@mlibre2 It isn't, that is just the generic assertion failure message. All assertion failures look like that

**Comment by mlibre2** [comment]
everything happened after the update, so I'm not surprised

**Comment by 0Ky** [comment]
@Evisneffo I've also identified the issue for this error, which is caused when a player's model name contains a certain character which throws the assertion failed message. I've already reported this at issue #3693. You can test this by typing `model :` in the console, and then type `kill` in the console to see the same error yourself.
