### ISSUE TITLE
[HL 25] Player already has a weapon and the ammo is less than the full amount, the player cannot pick up the same weapon again

### ISSUE THREAD

**Issue by ChrisCostes** [ValveSoftware/halflife#3612]
Hello,

I am writing to report a bug that I encountered while playing the 25th Anniversary Half-Life Multiplayer. I am creating a new post with one bug per post per "kisak-valve"'s request:

When a player already has a weapon and the ammo is less than the full amount, the player cannot pick up the same weapon again in multiplayer to replenish the ammo. This affects all weapons, such as the pistol, the Rocket Launcher, Egon gun, etc.

Please inform the programmers of these bugs and fix them as soon as possible. Thank you for your attention and your great work on the 25th Anniversary Half-Life Multiplayer.

Thank you for your attention to this isssue,
-Chris C.

**Comment by GTManiK** [comment]
> Hello,
> 
> I am writing to report a bug that I encountered while playing the 25th Anniversary Half-Life Multiplayer. I am creating a new post with one bug per post per "kisak-valve"'s request:
> 
> When a player already has a weapon and the ammo is less than the full amount, the player cannot pick up the same weapon again in multiplayer to replenish the ammo. This affects all weapons, such as the pistol, the Rocket Launcher, Egon gun, etc.
> 
> Please inform the programmers of these bugs and fix them as soon as possible. Thank you for your attention and your great work on the 25th Anniversary Half-Life Multiplayer.
> 
> Thank you for your attention to this isssue, -Chris C.

Did not notice anything like this during days of playing HLDM after the 25th Anniversary Update.
Are you sure server doesn't have 'weapons stay' set? Because what you describe looks exactly like when server sets 'mp_weaponstay 1' - which has two effects: 1) weapon doesn't disappear from the ground when you pick it up 2) you cannot replenish ammo from picking up a weapon you already have

**Comment by ChrisCostes** [comment]
To whom it may concern:

GTManiK is correct in pointing out that the HL Multiplayer “Weapons Stay” option being enabled causes the weapons to not disappear. I was mistaken. This is not a bug. I tested this by creating a server, enabling the “Weapons Stay” option and was able to see how the weapons do not disappear from the ground, and you cannot pick up the weapon if you already have it with “Weapons Stay” enabled. So, this was not a bug after all, therefore I am closing out this issue. Thanks, GTManiK for commenting on this issue.

Thanks,

Chris Costes
