### ISSUE TITLE
[HL25] Can't create server on Steam Deck

### ISSUE THREAD

**Issue by barspinoff** [ValveSoftware/halflife#3618]
I acknowledge the fact that HL25 supports Deck controllers. But has anyone checked the compatibility with the deck, not of the controller, but of the functionality? At the moment it's impossible to host server via steam deck (
Other details in video:
https://youtu.be/12GWGeDI-sU

**Comment by kisak-valve** [comment]
Hello @barspinoff, this issue is already being tracked at #3512. Closing as a duplicate.
