### ISSUE TITLE
[CS] After the HL25 update, the screen will tilt when moving left and right.

### ISSUE THREAD

**Issue by number201724** [ValveSoftware/halflife#3625]
Press A or D will reappear.

**Comment by GordonFreakman** [comment]
You can edit "sv_rollangle" in locally hosted servers to get rid of it,

**Comment by number201724** [comment]
Similarly, there is also a problem with the forward and backward movement of the arms;

**Comment by GordonFreakman** [comment]
that's also intentional

**Comment by MrEWhite** [comment]
> Likewise, there is a problem with the forward and backward movement of the arms.

That is intentional. It was that way on launch and broken in an update, along with viewroll.

**Comment by kisak-valve** [comment]
Restoring viewroll and viewmodel bobbing is an intentional change with the Half-Life 25th anniversary update.

There's a feature request at #3475 for this to have easier config options.

Closing in favor of the feature request.

**Comment by di57inct** [comment]
@kisak-valve the bobbing being different should also be addressed in cs/cz
