### ISSUE TITLE
[CS 1.6 - Bug] spectator  fast switching  

### ISSUE THREAD

**Issue by kraphtee** [ValveSoftware/halflife#363]
With the rapid switching of players, you can see the model
![hl 2013-02-19 01-48-22-10](https://f.cloud.github.com/assets/3601417/169541/67ae9156-7a26-11e2-8fcc-9f315bd75cd2.jpg)

**Comment by Maxi605** [comment]
@mikela-valve This is something else that needs to be addressed for a future update.

**Comment by mikela-valve** [comment]
Thanks @Maxi605, I noted on #258 that I'll look at this after the next release. Closing this as a duplicate.
