### ISSUE TITLE
[Counter-Strike: Condition Zero - Deleted Scenes] Pressing ESC on the World Map crashes the game

### ISSUE THREAD

**Issue by JoelTroch** [ValveSoftware/halflife#3633]
Tested on November 29th 2023 update.

To reproduce:
- Start the game.
- Go to "World Map".
- Press ESC.
- The game will crash and generate a crash dump.

**Comment by Bo9da** [comment]
same

**Comment by IntriguingTiles** [comment]
Fixed as of CZDS Build ID 12834067 which released about two hours ago with no changelog.

**Comment by JoelTroch** [comment]
> Fixed as of CZDS Build ID 12834067 which released about two hours ago with no changelog.

Confirmed, closing.
