### ISSUE TITLE
Servers being removed after changing to software renderer

### ISSUE THREAD

**Issue by HaajPaaj** [ValveSoftware/halflife#3640]
I will choose to find servers from the title menu, but there are a lot of instances where around 500 of the available servers are unable to be connected to. Is there something significant about OpenGL that makes it so the majority of servers don't respond?

**Comment by 0Ky** [comment]
This issue relates to #3580. It's not about OpenGL, it's when you switch those or related settings like resolution, the game restarts which breaks the server browser's functionality. You can try with running `_restart` command in console to test it. I believe it affects all GoldSrc engine games.

**Comment by kisak-valve** [comment]
Closing in favor of the older issue report.
