### ISSUE TITLE
[HL25/Goldsrc General] Server browser doesn't query all servers after game is changed

### ISSUE THREAD

**Issue by OpenRift412** [ValveSoftware/halflife#3642]
I noticed a bug where if you use the change game menu to switch games/mods and then go to the subsequent mod's server browser, it will only query listen servers that have been hosted via the Steam networking functionality.

I know the official games don't have the menu option visible unless you modify the GameMenu.res, but I think it would be wise to fix this (and maybe enable the menu option, but that's a separate issue).

**Comment by kisak-valve** [comment]
Hello @OpenRift412, this issue is already being tracked at #3580. Closing in favor of the older issue report.
