### ISSUE TITLE
[DoD] Scope overlay displays incorrectly when widescreen FOV is enabled.

### ISSUE THREAD

**Issue by OpenRift412** [ValveSoftware/halflife#3652]
I noticed when playing Day of Defeat that the scope overlay with widescreen FOV enabled is not only stretched, but doesn't fill the whole screen like it would in 4:3.

![image](https://github.com/ValveSoftware/halflife/assets/29780788/d048caf7-75bb-43a6-8508-cf00e0217a1e)

**Comment by kisak-valve** [comment]
Hello @OpenRift412, this issue is already being tracked at #3583.

Closing as a duplicate.
