### ISSUE TITLE
[CS1.6] Crash m_PanelList.Count() < WARN_PANEL_NUMBER

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#3655]
A crash occurs when trying to open Options in game client:

![image](https://github.com/ValveSoftware/halflife/assets/31417200/fcb11eeb-55a0-4cc5-a8aa-d2722c600c46)

Tested on build:

> Protocol version 48
> Exe version 1.1.2.7/Stdio (cstrike)
> Exe build: 01:03:30 Dec  1 2023 (9899)

OS Win10 x64

**Comment by Splatt581** [comment]
This error occurs if there are too many files in the `cstrike_downloads` folder:

![image](https://github.com/ValveSoftware/halflife/assets/31417200/317774c2-945a-420f-b114-b076f76ee69a)

I found this condition in `vgui2` code:

```
  if ( *(_WORD *)(v11 + 26) >= 0x1000u ) //4096
    wassert(
      L"m_PanelList.Count() < WARN_PANEL_NUMBER",
      L"c:\\buildslave\\goldsrc_win32\\build\\GoldSrc\\vgui2\\src\\vgui.cpp",
      0x226u);
```

If I patch this code, no error occurs and the options open normally.

@mikela-valve is it possible to fix this? since in the `steam_legacy` branch the game client does not close when trying to open options.

**Comment by chmod1** [comment]
Seems to be fixed in build 9909.

**Comment by Splatt581** [comment]
Yeah, this is fixed in build 9909.
