### ISSUE TITLE
Games won't launch

### ISSUE THREAD

**Issue by TAforever** [ValveSoftware/halflife#3659]
Hello! I'm having problems running cs.16 cs condition zero and cs source games. Operating system archlinux.
I am attaching screenshots with errors.
![cz](https://github.com/ValveSoftware/halflife/assets/52626363/1b1669ac-9d64-4a40-9e94-ba4e141ae219)
![css](https://github.com/ValveSoftware/halflife/assets/52626363/37816dbc-4d75-4440-bdaa-97294a57b19b)
![cs](https://github.com/ValveSoftware/halflife/assets/52626363/3f1c3e33-c8f3-4870-9de9-bc6b7e7978fb)

**Comment by kisak-valve** [comment]
Hello @TAforever, this looks like the issue being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/9875.

Closing in favor of the older issue report.
