### ISSUE TITLE
[HLDM:S] VGUI HUD text not working in HLDM Source

### ISSUE THREAD

**Issue by Zeitgesit** [ValveSoftware/halflife#3684]
The VGUI HUD text messages appear not to be working in HLDM Source.
I take it this is a bug. Please could this be patched?

**Comment by kisak-valve** [comment]
Hello @Zeitgesit, this issue is already being tracked at https://github.com/ValveSoftware/Source-1-Games/issues/1546.

Closing as a duplicate.
