### ISSUE TITLE
[CS /CSCZ] Incorrect Viewmodel Handedness in Software Mode (incl. suggestion/feature request)

### ISSUE THREAD

**Issue by CEOofUnhandledExceptions** [ValveSoftware/halflife#3694]
I understand this may be due to certain limitations, but that was 10 years ago now, and I understand you have since updated software mode to some extent. Will this still remain unaddressed with your current software-mode renderer?

If so, I  am curious if software mode could be removed entirely in favour for a 'software mode' shader which replicates software mode rendering artifacts in OpenGL, similar to the 'retro' shader fx in the quake remasters.

**Comment by kisak-valve** [comment]
Hello @CEOofUnhandledExceptions, this issue was previously evaluated at https://github.com/ValveSoftware/halflife/issues/885#issuecomment-15725633 and there's no particular reason to expect that evaluation to be any less valid today.

Closing as won't fix.

**Comment by CEOofUnhandledExceptions** [comment]
That's too bad. I presume the latter feature request is denied as well.
