### ISSUE TITLE
Headless .dem to video utility

### ISSUE THREAD

**Issue by classicstrike** [ValveSoftware/halflife#3698]
We need a command line tool that can output video from demos in the background, without having to enter the game.

For example:

`match.dem -pov=player -start=00:00:03 -end=01:00:00 outputType=mp4 recordAudio=true recordVoice=true showChat=true showAMXAnnouncements=false`

Then for it to programmatically use the HL engine to build the video quickly instead of having to watch the entire match.

**Comment by kisak-valve** [comment]
Hello @classicstrike, realistically, there will be no new utilities created from scratch utilities created for goldsrc era games. Sorry, but this is unlikely to happen any time in the future.

**Comment by classicstrike** [comment]
> Hello @classicstrike, realistically, there will be no new, from scratch, utilities created for goldsrc era games. Sorry, but this is unlikely to happen any time in the future.

Understood. Would you or someone else who knows goldsrc engine be able to share some insight into the recommended approach if we decide to do this ourselves? It would help a lot and speed up development

**Comment by classicstrike** [comment]
Update: For anyone interested, this already exists: https://github.com/YaLTeR/bxt-rs
