### ISSUE TITLE
HLTV can't start with an error

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#3707]
HLTV can't start with error `ERROR! System::AddModule: couldn't initialize module (null).`

![image](https://github.com/ValveSoftware/halflife/assets/31417200/d34e0f9f-7c2b-415a-b864-e98ebbf022bf)

Judging by the  logs of launch of previous versions of HLTV, this error occurs when trying to load the Network module.

Win10 x64

**Comment by wtfnahmean** [comment]
I'm having the exact same issue. Funny your thread is only 2 days old lol Is this a recent thing or just a coincidence? I'm hosting a lan party this weekend (haven't done one for 10+ years), and no hltv would be a shame

**Comment by Splatt581** [comment]
> I'm having the exact same issue. Funny your thread is only 2 days old lol Is this a recent thing or just a coincidence? I'm hosting a lan party this weekend (haven't done one for 10+ years), and no hltv would be a shame

HLTV broken only in the GoldSrc anniversary update, so you can use the `steam_legacy` version for your lan party.

**Comment by 1337Smithy** [comment]
Yep, I was surprised this wasn't logged sooner. I was planning to do it myself.

**Comment by wtfnahmean** [comment]
> > I'm having the exact same issue. Funny your thread is only 2 days old lol Is this a recent thing or just a coincidence? I'm hosting a lan party this weekend (haven't done one for 10+ years), and no hltv would be a shame
> 
> HLTV broken only in the GoldSrc anniversary update, so you can use the `steam_legacy` version for your lan party.

thank you!

**Comment by RFrappe** [comment]
sad :(

**Comment by pierow** [comment]
Can confirm it's broken. @kisak-valve

**Comment by 1337Smithy** [comment]
I created a copy of the legacy Half-Life folder so I can run HLTV and still have HL25 installed.

**Comment by Splatt581** [comment]
@shawns-valve Please note this serious issue - windows build of HLTV does not start after anniversary updates.

**Comment by sabianroberts** [comment]
bumping this thread and pinging @shawns-valve with hopes of a fix

**Comment by shawns-valve** [comment]
Some fixes went in for the Windows version of HLTV in the October 2, 2024 Steam update. I don't think the Linux update has gone out yet.

**Comment by sabianroberts** [comment]
Thanks for fixing HLTV! And thanks for all the other fixes you've done to both the game and the SDK since after the 25th anniversary update

**Comment by Splatt581** [comment]
Now, with the new build 10185, HLTV launches correctly:

```
status
--- HLTV Status ---
Online 00:02, FPS 47.9, Version 10185 (Win32)
Local IP 192.168.0.2:27020, Network In 0.0, Out 0.0, Loss 0.00
Local Slots 128, Spectators 0 (max 0), Proxies 0
Not connected.
```

So I'm closing the issue.

**Comment by straffi1991** [comment]
@shawns-valve  You say : Some fixes went in for the Windows version of HLTV in the October 2, 2024 Steam update. I don't think the Linux update has gone out yet.

When will there finally be a bug fix for HLTV for Linux?
