### ISSUE TITLE
HL:OF Lift bug

### ISSUE THREAD

**Issue by odeyity** [ValveSoftware/halflife#3711]
In Chapter Welcome to Black Mesa, the lift that takes you down after the room above is exploded leaves you unable to move once it reaches the floor. The only way I managed to continue was by jumping through the door before the lift touches the ground
![image](https://github.com/ValveSoftware/halflife/assets/93200455/3e2afb50-963a-45e3-b6c1-c6015450aab5)

**Comment by kisak-valve** [comment]
Hello @odeyity, this issue is already being tracked at #968. Closing in favor of the older issue report.
