### ISSUE TITLE
Bunnyhop cap should be changeable or disableable altogether

### ISSUE THREAD

**Issue by larb0b** [ValveSoftware/halflife#3717]
Since HL WON 1.1.0.8, there's been a speed cap on bunnyhopping. 
Regardless of subjective opinions on whether this should be the case for HLDM, this should most definitely be toggleable/changeable as it breaks many community maps (kz, bhop, etc.) which has resulted in pretty much no community for these historic modes in HL1/GoldSrc (server-side plugins which work around the cap still result in issues client-side because the client-side expects the speed cap to still be in place).

There is precedent for this in other Valve games: CS: Source and GO have `sv_enablebunnyhopping` which disables the velocity clamp. Something similar would be nice to see in HL, if not a CVAR which controls the cap as shown in #1601.

Here's a brief video that goes into more detail (not by me): https://www.youtube.com/watch?v=gG1gKd_nYX0

**Comment by kisak-valve** [comment]
Hello @larb0b, this issue is already being tracked at #11. Closing as a duplicate.
