### ISSUE TITLE
[TFC] [Linux] When building, the camera snaps to a different direction

### ISSUE THREAD

**Issue by rusted-bucket** [ValveSoftware/halflife#3723]
When building/dismantling as engineer the camera will snap to a completely different direction. I think it's towards the centre of the map but I'm not 100% sure. Switching to the Pre-25th Anniversary Update is the only workaround I can find currently.

EDIT: It only seems to occur when using the mouse in the build menu.

**Comment by Nomad7** [comment]
To add a little clarity/detail to this - it seems like there's two pieces contributing to this:

First is that when a menu is opened (+commandmenu or the class selection menu for example) the starting position of the mouse cursor seems to be based on recent mouse movements. For example if you stand on the 2fort bridge and face one base, then turn right to face the other base, then open a menu, your mouse cursor will appear at the far right hand side of the screen.

Second, whatever mouse movements are made using the cursor appear to be processed in the game as well. For example if you open the class selection menu, then move your mouse towards the upper left corner to click Scout, your view will then snap up and to the left.

Essentially, it seems like all mouse movements are being processed by both the menu cursor and the player's view, regardless of which one is currently active / in focus.

Here's a couple video examples:
build menu: https://streamable.com/m62wga
class selection: https://streamable.com/ys76z3

The legacy client has some weird view-snapping scenarios too, but these specific behaviors seem unique to the anniversary update.

**Comment by Nomad7** [comment]
This is fixed as of today: [October 2, 2024 Update](https://store.steampowered.com/news/app/20/view/4666382742856475396?snr=1_5_9_)

**Comment by shawns-valve** [comment]
As mentioned above, this issue should be resolved in the October 2, 2024 TFC Steam update.
