### ISSUE TITLE
[HL25] Game freezes and crashes after loading a singleplayer map (Ubuntu 22.04.1 LTS)

### ISSUE THREAD

**Issue by Individualised** [ValveSoftware/halflife#3724]
It has became impossible to play singleplayer as of one of the latest updates to 25th Anniversary Edition. This issue did not happen with the initial release of 25th Anniversary Edition in November, and began to happen in a later update, though which update I cannot say for certain. After a short while, the game will not only freeze, but actually cause my entire display or system to lock up, for a few seconds before unfreezing, though the game will freeze again after a short while. This cycle will continue for a while until the game eventually closes. There is nothing in the relevant log files that I'm aware of when the game crashes that signifies any sort of error; the game just seems to suddenly exit. Interestingly the amount of time this takes to happen seems to depend on the map loaded as well as player movement, which makes me think that this is related to scripted events, especially given that it does not happen in multiplayer. In c0a0 for example, it seems to happen almost immediately, often before the Half-Life logo even shows up, but in hldemo1 it only happens after the text intro sequence, usually a bit after part of the wall falls down in the opening corridor, in c1a1 it happens after the player starts moving etc.

This happens on both the native version and the Windows version running through Proton. I found one Reddit post which seems to be reporting the same issue: https://www.reddit.com/r/HalfLife/comments/181p2ru/half_life_crashes_on_linux/ .

`OS: Ubuntu 22.04.1 LTSKERNEL: 5.19.0-41-generic

CPU: 11th Gen Intel Core i5-1135G7 @ 2.40GHz

GPU: Intel Mesa Intel Xe (TGL GT2)

GPU DRIVER: 4.6 Mesa 22.2.5 

RAM: 8 GB `I can provide more specific hardware specifications if necessary.

**Comment by kisak-valve** [comment]
Hello @Individualised, can you test how the game behaves with a current build of mesa from a PPA like [oibaf](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) or [kisak-mesa](https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa)?

This reads like a video driver issue that should also be mentioned to your video driver vendor.

**Comment by Individualised** [comment]
Using the latest kisak-mesa drivers appears to fix the issue. Thank you very much for your help!

**Comment by kisak-valve** [comment]
Thanks, closing as a system (video driver) issue that's already been resolved upstream.
