### ISSUE TITLE
[HL] Implement background .bsp support for the menu

### ISSUE THREAD

**Issue by N7P0L3ON** [ValveSoftware/halflife#3732]
Currently the background for the Half-Life 1 engine games and mods is limited to static .tga files, split in 256x256 pieces and arranged by script. 

Please implement the ability to load compiled half-life 1 map (.bsp files) as Half-Life 1 and mods backgrounds.
It can actually loop trough camera entities placed on the map. "trigger_camera" <-> "info_target"

**Comment by kisak-valve** [comment]
Hello @N7P0L3ON, this is unlikely to be implemented for goldsrc now or any time in the foreseeable future.
