### ISSUE TITLE
[HL] Add support for 3d player model visualization in game settings

### ISSUE THREAD

**Issue by N7P0L3ON** [ValveSoftware/halflife#3734]
Currently the only way of seeing the player model before selecting it and going in the game is to either open the model in model viewer or to trust the preview image that's generated for the given player model.

It would be nice if you can add support for real 3d preview of the player model in the settings tab for multiplayer. this way you can know what the player model is, even if there's no .bmp preview file added for the model.

**Comment by kisak-valve** [comment]
Hello @N7P0L3ON, this is unlikely to be implemented for goldsrc now or any time in the foreseeable future.
