### ISSUE TITLE
[CS1.6] Texture Filtering causes blurry models after HL25-years update

### ISSUE THREAD

**Issue by Haco** [ValveSoftware/halflife#3736]
### Before the Update (on legacy or beta branch) it looked like this:

https://i.imgur.com/TXqlway.png

**gl_texturemode is set to "gl_linear_mipmap_linear"**

The textures on the player and weapon models look clear. Yes, the edges are jacked, but that's intended because I don't use msaa and I'm on 640x480.

### With the 25-years Update:

**With texture filtering checkbox ON (or gl_texturemode gl_linear):**

https://imgur.com/a/DMdRnqI

The player and weapon models are blurry (compare eg. the wooden handle of the ak), The map looks ok.

**With texture filtering OFF (or gl_texturemode gl_nearest):**

https://imgur.com/a/CZZlTYp

The player and weapon models are not that blurry anymore, but the map is **pixelated**.

I've also tried all available combinations of gl_texturemode, but none of them matches the look of "before the update".

**Comment by kisak-valve** [comment]
Hello @Haco, this looks like the same issue as #3658. Closing as a duplicate.
