### ISSUE TITLE
[CS] steam_legacy server browser only shows 169.254.x.x server IPs

### ISSUE THREAD

**Issue by that-is-not-great** [ValveSoftware/halflife#3737]
![Screenshot 2023-12-31 182605](https://github.com/ValveSoftware/halflife/assets/132457555/20338f6f-808c-424a-88fd-2391b462e73a)

repeated refresh all, steam_legacy branch server browser only shows 169.254.x.x server IPs, favorites are fine

**Comment by kisak-valve** [comment]
Hello @that-is-not-great, this reads like #3580. My guess is that newer (shared) functionality is being brought into the game from the Half-Life depot which the older Counter-Strike variant only has a partial understanding.

Can you install Half-Life if it isn't already, then switch Half-Life to the `steam_legacy` beta branch and test how the game behaves?

**Comment by kisak-valve** [comment]
Glad to hear it's behaving for you.

Your follow up issue is being tracked at #2064.
