### ISSUE TITLE
[HL25] Language Error

### ISSUE THREAD

**Issue by Kanadeforever** [ValveSoftware/halflife#3745]
This problem appeared after the 25th anniversary update.

After setting the language to Simplified Chinese and Traditional Chinese in the properties, the game still displays in English. After community discussion, it was found that the problem was caused by file encoding errors in two txt files under the "Half-Life\valve_schinese\resource" folder. Under the Windows version, saving the text encoding as "UTF-16 LE" and the line ending sequence as "CRLF" can solve this problem. However, when using the Linux version of Steam Deck, no text can be displayed using this method.

![Snipaste_2024-01-18_11-31-56](https://github.com/ValveSoftware/halflife/assets/20147029/c295cdc8-f8e6-4246-bffe-dfd0d43b3737)

There is also another problem that existed in this versions. In English settings, when you start a “new game”, the game title, creator’s name, place names, etc. recorded in title.txt will be displayed at the beginning of the game. But when switched to Chinese (Simplified Chinese, Traditional Chinese), it does not display, and the texts displayed are identifiers such as “CR27”, “CR1”, etc. We hope that the official can fix these situations.

![Snipaste_2024-01-18_11-34-31](https://github.com/ValveSoftware/halflife/assets/20147029/aed60322-16ac-4bf2-b714-7cb079f9cb80)

**Comment by kisak-valve** [comment]
Hello @Kanadeforever, this issue is already being tracked at #2490. Closing as a duplicate.
