### ISSUE TITLE
[HL25] Restored High Quality Models option

### ISSUE THREAD

**Issue by Nin10doGMod** [ValveSoftware/halflife#3747]
Hello, I would like to have the [Multiplayer High Quality Models](https://gamebanana.com/mods/483277) option to be restored in the Multiplayer tab.

![](https://images.gamebanana.com/img/ss/mods/65749b94a87cb.jpg)

![](https://images.gamebanana.com/img/ss/mods/65749d1203884.jpg)
[himodels_restoration.zip](https://github.com/ValveSoftware/halflife/files/13999801/himodels_restoration.zip)

**Comment by kisak-valve** [comment]
Hello @Nin10doGMod, this issue is already being tracked at #3526. Closing as a duplicate.
