### ISSUE TITLE
Cs 1.6 / Counter-Strike STEAM motd ISSUE

### ISSUE THREAD

**Issue by PoGdAbz** [ValveSoftware/halflife#3748]
I recently contacted Steam/Valve , and they told me they cant fix it from their end, so they told me to create a topic here, and hopefully this issue can be fixed. 

So basically Im a old Cs 1.6 player and recently ive been dealing with this issue that is a very weird and annoying issue to me and never faced before,Specifically in a server where i play at its called TyS Deathrun (SERVER IP 185.119.91.214:27019 ) : ((((and also have this issue-Bug in another servers , not just this one :D ) The servers has a cmd called "/best" to see the fastest - best records on each map. So basically when i try to open it or write "/best" it just shows a a empty white screen and-or shows "-7" with grey page also /......(NOTE that this is happening not only on this server, but other servers as well and that i ALSO tried my friends's steam and its the same thing, even changed my ip and everything!!!). Now i tried to open the URL MOTD in google and it actually worked with no issues at all. You see now, For (TyS Deathrun) this isnt the main issue. The main issue here for me in that specific server is that when i press the timer and end timer to be included that "/BEST" it doesnt even register me in the /best - top 15 players. I actually spoke to the owner of the server and asked if there could be a BLOCK or BLACKLIST from their end, and he told me no. So what i did was, I tried to RE-install the game couple of times with deleting every single file and then UNINSTALLING the game itself, and also deleting httml cache files. And if that wasnt/isnt enough, i also literally RE-Installed Windows LOL. Whats weird is that all of that didnt even fix NEITHER of the issues. SO, what else possibly can be done from my end? because im so tired of this bullshit issue and i need it fixed asap because its so important for me to see the MOTD - /BEST . Hopefully u guys can fix it from your side or tell me what exactly to do :D PLEASE respond to me asap even if there are no solutions, just reply to me what can possibly be the issue here.

-
-
-
Cs version :
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 19:53:27 Aug 3 2020 (8684)
(Running CS on Beta MODE btw, and tried others., didnt work :D )

**Comment by SamVanheer** [comment]
The game uses Chromium Embedded Framework 1 (CEF1) to handle HTML MOTDs. CEF1 ceased development 11 years ago and isn't supported anymore. #3347 covers the problems resulting from that, basically it can't load websites using modern communication protocols and/or HTML/CSS/Javascript features.

Steam provides an API for games to access its CEF3 library to render HTML so it could be used as a replacement: https://partner.steamgames.com/doc/api/ISteamHTMLSurface

But this would require making some fairly dramatic changes to VGUI2's HTML code. On the plus side this kind of problem shouldn't happen anymore as long as Steam continues to support the API it provides.

Note that if fixed only the anniversary version will work properly. The beta branch uses the `steam_legacy` version of the engine and won't receive fixes like this.

**Comment by PoGdAbz** [comment]
> The game uses Chromium Embedded Framework 1 (CEF1) to handle HTML MOTDs. CEF1 ceased development 11 years ago and isn't supported anymore. #3347 covers the problems resulting from that, basically it can't load websites using modern communication protocols and/or HTML/CSS/Javascript features.
> 
> Steam provides an API for games to access its CEF3 library to render HTML so it could be used as a replacement: https://partner.steamgames.com/doc/api/ISteamHTMLSurface
> 
> But this would require making some fairly dramatic changes to VGUI2's HTML code. On the plus side this kind of problem shouldn't happen anymore as long as Steam continues to support the API it provides.
> 
> Note that if fixed only the anniversary version will work properly. The beta branch uses the `steam_legacy` version of the engine and won't receive fixes like this.

I'm sorry but im kinda confused lol, what exactly shall i do to fix it? i didnt get it, i may be slow or just a pc noob i guess lol. Im kinda baffled because this issue only came after that last update for cs 1.6... idk what was the point of it tbh.

**Comment by SamVanheer** [comment]
> > The game uses Chromium Embedded Framework 1 (CEF1) to handle HTML MOTDs. CEF1 ceased development 11 years ago and isn't supported anymore. #3347 covers the problems resulting from that, basically it can't load websites using modern communication protocols and/or HTML/CSS/Javascript features.
> > Steam provides an API for games to access its CEF3 library to render HTML so it could be used as a replacement: https://partner.steamgames.com/doc/api/ISteamHTMLSurface
> > But this would require making some fairly dramatic changes to VGUI2's HTML code. On the plus side this kind of problem shouldn't happen anymore as long as Steam continues to support the API it provides.
> > Note that if fixed only the anniversary version will work properly. The beta branch uses the `steam_legacy` version of the engine and won't receive fixes like this.
> 
> I'm sorry but im kinda confused lol, what exactly shall i do to fix it? i didnt get it, i may be slow or just a pc noob i guess lol. Im kinda baffled because this issue only came after that last update for cs 1.6... idk what was the point of it tbh.

There's nothing you can do to fix it. Valve needs to update the engine to use, essentially, a newer browser to load HTML pages.

**Comment by PoGdAbz** [comment]
> > I'm sorry but im kinda confused lol, what exactly shall i do to fix it? i didnt get it, i may be slow or just a pc noob i guess lol. Im kinda baffled because this issue only came after that last update for cs 1.6... idk what was the point of it tbh.
> 
> There's nothing you can do to fix it. Valve needs to update the engine to use, essentially, a newer browser to load HTML pages.

Damn.... And do you think they will be able to update it or fix it anytime soon or ever? since many people have this issue, not me only.

**Comment by SamVanheer** [comment]
They said they were going to keep supporting the games and release an SDK update so perhaps they will, but i don't know what their plans are now.

**Comment by tmp64** [comment]
The HTML control code from Source SDK 2013 can be copied almost as-is: https://github.com/tmp64/hl1_source_sdk/blob/master/vgui2/vgui_controls/HTML.cpp

**Comment by PoGdAbz** [comment]
> The HTML control code from Source SDK 2013 can be copied almost as-is: https://github.com/tmp64/hl1_source_sdk/blob/master/vgui2/vgui_controls/HTML.cpp

and that will fix it? if so, how and where to paste it (replace it)

**Comment by SamVanheer** [comment]
Valve has to do that.

**Comment by PoGdAbz** [comment]
Hey guys, today i went and played cs in a “Cyber” place with my Steam cs and everything. The MOTD was working fine on all servers. which is pretty weird. But somehow it worked. So basically this means that the issue is from my home network (wifi). What would u guys recommend to do? any idea?

**Comment by SamVanheer** [comment]
What language is Steam set to on your local computer? Try setting it to English and then check if the MOTD works properly.

**Comment by PoGdAbz** [comment]
Its in English already

**Comment by PoGdAbz** [comment]
Okay you guys can close this thread if u want. Its fixed. Here’s what i did. I simply called my internet (Wifi) Operators. And they fixed it for me. Basically it was a FIREWALL block issue. So yea. Thanks to the ppl who replied to me here with suggestions, and u can close the topic.
