### ISSUE TITLE
[HL] [GS] AllocBlock limit

### ISSUE THREAD

**Issue by DartSerafim** [ValveSoftware/halflife#3750]
The current AllocBlock max value is 64. I suppose it was based on the total memory reserved for a map. Unfortunately, this limit is too low. Considering other map limits as max faces, max planes or max textures it is possible to reach AllocBlock limit having only around 20% of max faces.

**Comment by kisak-valve** [comment]
Hello @DartSerafim, this is the same issue as #2920. Closing as a duplicate.
