### ISSUE TITLE
[HL] "lightgamma" Command Triggers "Hunk_Alloc" Fatal Error

### ISSUE THREAD

**Issue by 0Ky** [ValveSoftware/halflife#3753]
I've encountered a crash in `Half-Life` when executing the `lightgamma` command with a value equal to or less than `1.8`, resulting in the error `Hunk_Alloc: failed on 200 bytes`. This issue occurs consistently on `Linux` and `Windows` version of the game running with `OpenGL` video renderer, suggesting a possible memory allocation problem.

![image](https://github.com/ValveSoftware/halflife/assets/16103757/65d248bb-5cb0-44e0-bed0-0be8ef5bc200)

**Comment by pierow** [comment]
Changing it to a value above 1.8 also has a seemingly random chance of crashing as well.

**Comment by pierow** [comment]
This happens if changing `lightgamma`, `gamma`, or `brightness` multiple times as well.

**Comment by shawns-valve** [comment]
This should be resolved in the October 2, 2024 Half-Life Steam update.
