### ISSUE TITLE
[Windows] [CS1.6] Host_Error: UserMsg: Not Present on Client 66

### ISSUE THREAD

**Issue by GB-YellowJello** [ValveSoftware/halflife#3758]
I've been having trouble with the game kicking me back to the main menu immediately after spawning. This is coming off the coattails of [this thread](https://github.com/ValveSoftware/halflife/issues/3738), the problem is the same. I followed the steps outlined there but the problem persists. I've disabled AMXX and Metamod and added `-dev +developer 2 +fs_perf_warnings 1 -condebug -console -debug` to the launch options. I have tested this on the pre-25th anniversary beta as well as the current build of the game, the same thing occurs. When adding `deathmatch 1` and `maxplayers 32`, it does get me to the team and character model selection screens, but as soon as I spawn, the game kicks me back to the menu and the error code `Host_Error: UserMsg: Not Present on Client 66` or `Host_Error: UserMsg: Not Present on Client 67` pops up in console.

I tried two different maps and the same thing occurred on both. Here's my [qconsole.log](https://github.com/ValveSoftware/halflife/files/14251854/qconsole.log), this was generated using the current build of the game.

Any help on this would be greatly appreciated. I am working on a project to find and archive lost Counter-Strike 1.6 maps, and without the ability to play, it greatly hampers my ability to do.. anything.

**Comment by 0Ky** [comment]
I am unable to reproduce the error by simply running the game and opening a map.
Based on issue #1894, it seems like the map's entity data contains an illegal character.
Are you sure that you've verified the integrity of game files?

**Comment by 0Ky** [comment]
Based on the console log it seems like you're loading `cs_labyrinth` (3rd party map) first and then `de_dust2`. I'm guessing if you load `de_dust2` map first when you initially run the game it will load fine.

The issue most likely comes from the 3rd party map `cs_labyrinth`, which may have a non-ascii/illegal character in its entity data. That also explains the same error on other official maps despite those maps having valid entity data.



starting another map that does have valid entity data

**Comment by GB-YellowJello** [comment]
> Based on the console log it seems like you're loading `cs_labyrinth` (3rd party map) first and then `de_dust2`. I'm guessing if you load `de_dust2` map first when you initially run the game it will load fine.
> 
> The issue most likely comes from the 3rd party map `cs_labyrinth`, which may have a non-ascii/illegal character in its entity data. That also explains the same error occurring on other maps loaded after `cs_labyrinth` that has valid entity data, which is a bug mentioned in issue #1894.

This is happening on numerous maps, regardless of what I try first. cs_labyrinth was working perfectly fine the other day when I made an overview for it.

**Comment by GB-YellowJello** [comment]
And just like that, the problem has resolved itself. None of the maps are doing it anymore. :|
