### ISSUE TITLE
[CS 1.6] Loading singleplayer map with Steam networking ON takes at least 3 seconds

### ISSUE THREAD

**Issue by phayzeeVW** [ValveSoftware/halflife#3764]
On Windows, on the latest build, starting any singleplayer map takes at least 3 seconds to open it, as opposed to almost instantly on the beta version or with steam networking OFF.

**Comment by shawns-valve** [comment]
What do you mean by "singleplayer map" here? The delay is just the time it takes for the connection to be established to the Steam networking backend / relays, so there's probably not much we can do about it at the Half-Life / CS level.
