### ISSUE TITLE
The Specialists still broken (Anniversary update)

### ISSUE THREAD

**Issue by clankill3r** [ValveSoftware/halflife#3767]
I tried the thing with adding:

"ProportionalBaseWidth" "1280"        // if the display resolution is above this,
"ProportionalBaseHeight" "720"        //  ui elements will be scaled.

To `TrackerScheme.res`, as mentioned in https://github.com/ValveSoftware/halflife/issues/3415

In this case the specialists is crashing after loading a map.

Going back to pre Anniversary  works, but a fix would still be welcome.

**Comment by shawns-valve** [comment]
We added a back-compat hack for this mod in the October 2, 2024 Half-Life Steam build.

Basically, the Specialists client DLL appears to have memory corruption issues (somewhere inside the HUD_DrawTransparentTriangles function, and in the TSMOD.net patcher). Previously these would just be ignored, and the game still seemed to run okay. But with the updated MSVC compiler / linker settings in the 25th anniversary HL engine, they generate exceptions and crash the game. We now just catch the heap corruption exceptions for this mod and explicitly ignore them. So it's possible it may still crash at some later point, but generally seems to work now.
