### ISSUE TITLE
Unable to launch the game in 4:3 stretched on AMD Ryzen 5500U iGPU

### ISSUE THREAD

**Issue by yhkuzmenko** [ValveSoftware/halflife#3771]
# Unable to launch the game in 4:3 stretched on AMD Ryzen 5500U iGPU

# Steps to Reproduce
1, Download latest Counter-Strike build from Steam
2. Open AMD Adrenalin driver
3. Select Counter-Strike
4. Set Scaling mode to Full panel
5. Launch Counter-Strike
6. Set Renderer to OpenGL
7. Set Display Mode to Normal
8. Set Resolution to 640x480 / 800x600 / 1024x768
9. Observe that you still have black bars on the left and right sides of the screen

# Version output
```
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 12:23:38 Dec 22 2023 (9920)
```

# System information
<details>
<summary>System information</summary>

## Computer Information:
Manufacturer: Acer
Model: Aspire A515-45
Form Factor: Laptop
No Touch Input Detected

## Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 5 5500U with Radeon Graphics
CPU Family: 0x17
CPU Model: 0x68
CPU Stepping: 0x1
CPU Type: 0x0
Speed: 2096 MHz
12 logical processors
6 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported

## Operating System Version:
Windows 11 (64 bit)
NTFS: Supported
Crypto Provider Codes: Supported 311 0x0 0x0 0x0

## Video Card:
Driver: AMD Radeon(TM) Graphics
DirectX Driver Name: aticfx32.dll
Driver Version: 31.0.21912.14
DirectX Driver Version: 31.0.21912.14
Driver Date: 2 20 2024
OpenGL Version: 4.6
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
DirectX Card: AMD Radeon(TM) Graphics
VendorID: 0x1002
DeviceID: 0x164c
Revision: 0xc2
Number of Monitors: 1
Number of Logical Video Cards: 1
No SLI or Crossfire Detected
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 13.54" x 7.60" (15.51" diag), 34.4cm x 19.3cm (39.4cm diag)
Primary Bus Type Not Detected
Primary VRAM: 512 MB
Supported MSAA Modes: 2x 4x 8x

## Sound card:
Audio device: Headset Earphone (HyperX Virtua

## Memory:
RAM: 15722 Mb

## VR Hardware:
VR Headset: None detected

## Miscellaneous:
UI Language: English
Media Type: Undetermined
Total Hard Disk Space Available: 487244 MB
Largest Free Hard Disk Block: 145427 MB
OS Install Date: Nov 18 2023
Game Controller: None detected
MAC Address hash: 18c0db0396f481210405465e85d5036b3e71a771

## Storage:
Disk serial number hash: 9239032e
Number of SSDs: 1
SSD sizes: 512G
Number of HDDs: 0
Number of removable drives: 0
</details>

# Additional information
Before 25th Anniversary Update video tab of the settings had a checkbox called "Low video quality" and if it was checked the game was stretched.

# Workaround
Use launch options: -nofbo or -stretchaspect

**Comment by exegg** [comment]
I think you can mimic the old behavior of "Low video quality" mode with the launch parameter -nofbo
There's also the launch parameter -stretchaspect which should work right away without even changing settings inside AMD Adrenalin driver

**Comment by yhkuzmenko** [comment]
> I think you can mimic the old behavior of "Low video quality" mode with the launch parameter -nofbo There's also the launch parameter -stretchaspect which should work right away without even changing settings inside AMD Adrenalin driver

Thank you, @exegg! I can confirm that it’s working, so I added this as a workaround to my original message.
However, having black bars shouldn’t be the default behavior and I hope that valve will fix it in the future updates.

**Comment by shawns-valve** [comment]
The letterboxing is the intended default behavior currently; the command line options you mention can be used to get the old stretched behavior if desired.
