### ISSUE TITLE
Cs 1.6 issue

### ISSUE THREAD

**Issue by DeAdmAn-art** [ValveSoftware/halflife#3792]
I can't see any profile picture steam account in cs 1.6. It is difficult to find who is online in game.
2 images are attached for reference. 1st image is without profile picture and 2nd image is with profile picture.
I am facing first image problem.
![IMG_2306](https://github.com/ValveSoftware/halflife/assets/174702478/af1fa07f-0e38-4d70-91be-50761470e260)
![10_screenshots_20240630011016_1](https://github.com/ValveSoftware/halflife/assets/174702478/0d4e29ec-1f96-427f-a891-e492daedc281)

**Comment by ViBE-HU** [comment]
does this happens all the time with much less players too? or it only happens when there are bunch of players on a server? what is the resolution btw?

**Comment by DeAdmAn-art** [comment]
> does this happens all the time with much less players too? or it only happens when there are bunch of players on a server? what is the resolution btw?

Yes it happens all the time. Also i have tried in all resolution, but facing same problem.

**Comment by Splatt581** [comment]
scoreboard_showavatars?

**Comment by DeAdmAn-art** [comment]
> scoreboard_showavatars?

Thanks Splatt581. Problem has been resolved.

**Comment by bearfm** [comment]
you should close the issue

**Comment by wopox1337** [comment]
Please close this issue, @kisak-valve.
