### ISSUE TITLE
[CS 1.6] Linux viewdemo command makes the client to crash or auto close

### ISSUE THREAD

**Issue by Gawnz1** [ValveSoftware/halflife#3800]
CS 1.6, using debian 12 (linux), Half-Life 25th anniversary update, the viewdemo command makes the client to crash or auto close. playdemo works okay, but viewdeo is broken.

**Comment by 0Ky** [comment]
Here are couple of backtraces of the crash for the `viewdemo` command on the post 25th Anniversary build https://github.com/ValveSoftware/halflife/issues/3738#issuecomment-1913793666 and https://github.com/ValveSoftware/halflife/issues/3551#issuecomment-1852495039

**Comment by kisak-valve** [comment]
It would be better to continue to discuss this issue on the older issue report.

Closing as a duplicate of #3738.
