### ISSUE TITLE
[CS 1.6] Linux VGUI Menu doesn't allow the client to buy defuse kit on non de_* maps

### ISSUE THREAD

**Issue by Gawnz1** [ValveSoftware/halflife#3802]
CS 1.6, using debian 12 (linux), Half-Life 25th anniversary update or before that, the VGUI Menu doesn't allow the client to buy defuse kit on non de_* maps.

Reproducing it:
For example, we play on css_cache, when user is with VGUI menu, he will be not able to buy defuse kit. If he switch to the Old style menu, he will be able.

**Comment by kisak-valve** [comment]
Hello @Gawnz1, this issue is already being tracked at #2614. Closing as a duplicate.
