### ISSUE TITLE
[CS 1.6] Remove join game in steam profile like in csgo/cs2

### ISSUE THREAD

**Issue by Gawnz1** [ValveSoftware/halflife#3806]
As title, if you remove join game under user profile @ steam, it can hide the server ip address and avoid ddos in some cases. Such behaviour like csgo/cs2.

View friend game info or in server list in Friends tab can be also listed.

This is already implemented in csgo/cs2, so why not and here?

**Comment by kisak-valve** [comment]
Hello @Gawnz1, this is a request for an anti-feature.
