### ISSUE TITLE
[Linux] Fedora 40 (Plasma, Wayland) seems to be unable to run the game properly under OpenGL

### ISSUE THREAD

**Issue by kelsyduck** [ValveSoftware/halflife#3827]
On the normal branch, the game runs very laggily and only runs "normally" under the software renderer (normally in quotations as it only reaches a height of 50fps). 

Launching without changing any settings runs the menu at 20 fps and crashes when loading into a map.
Launching with the -gl launch option does nothing.
Launching with Steam Linux Runtime enabled shows the error: "Fatal Error: Failed to create SDL window."

I am unsure if this is an issue with Fedora, Half-Life, NVIDIA or any other factor.

Steam system information: https://pastebin.com/4TyQMBrR

**Comment by kisak-valve** [comment]
Hello @kelsyduck, `Driver: Mesa llvmpipe (LLVM 18.1.6, 256 bits)` in your system information is the key detail here. Your NVIDIA driver install is incomplete or broken and Steam is being forced to fallback to llvmpipe (mesa's faster CPU renderer) to run at all.

If you're able to run 64 bit OpenGL applications on your NVIDIA GPU, then focus your troubleshooting effort on verifying that the video driver's 32 bit userspace libraries are installed and working.

This is distro driver install issue and not a game issue.
