### ISSUE TITLE
Showing Counter-Strike server announcement messages

### ISSUE THREAD

**Issue by CJohn1227** [ValveSoftware/halflife#3832]
![cs15](https://github.com/user-attachments/assets/387b2e58-d700-421b-90fe-405f2215d1ea)
Counter-Strike 1.5 had a server notification message displayed on the console at the top, but this feature was removed in Counter-Strike 1.6. Nexon's Counter-Strike Online added this feature separately. I hope Counter-Strike 1.6 will have this feature as well.

**Comment by di57inct** [comment]
can't this be done by setting developer 2?

**Comment by CJohn1227** [comment]
> can't this be done by setting developer 2?

This may look similar to the "developer" command, but it actually has a completely different function.

**Comment by SamVanheer** [comment]
That text area is the notify area. This issue is already being tracked by #949 and #1170.

**Comment by kisak-valve** [comment]
Closing in favor of #1170.
