### ISSUE TITLE
[DOD] Day of Defeat Sniper Rifles not properly scaling with Widescreen Displays

### ISSUE THREAD

**Issue by sonoma-hyenaz** [ValveSoftware/halflife#3836]
Hello, I attached an image of the issue, I consider this quite **game breaking**. When a user has their graphics display mode set to "Widescreen" the Sniper Rifle's scope overlay no longer properly scales to stretch the entire screen, this is not an issue with the "Normal" display mode. I believe this has been an issue since the Half-Life 25th Anniversary Update
![image](https://github.com/user-attachments/assets/ff75c580-35fb-48cf-b7c8-bb3930d0055f)
 Another note is the HUD does not scale up to higher resolutions properly like it does with HL1

**Comment by kisak-valve** [comment]
Hello @sonoma-hyenaz, this issue is already being tracked at #3583. Closing as a duplicate.
