### ISSUE TITLE
[HL25] Enemies take too long to kill (October 2 Update)

### ISSUE THREAD

**Issue by HaajPaaj** [ValveSoftware/halflife#3840]
In Half-Life, the enemies have inflated HP (about five or six times their usual amount). I assumed this to be an error with my installation, so i verified my game files. Sure enough, two files failed to validate. Even after they were reacquired, this bug still persisted. 

I thought that perhaps skill.cfg could have been modifed, so i deleted that file and reacquired it, but the bug still persisted.

I then tried to replicate this in Opposing Force and Blue Shift, which as far as I'm aware don't have the new patches pushed. In those games, the enemies have their normal health values. This leads me to believe that some part of the October 2nd update broke the health values of enemies.

**Comment by shawns-valve** [comment]
I don't think I'm seeing this. Is it all enemies, or just certain ones?

Maybe attach a savegame and your config.cfg file.

**Comment by HaajPaaj** [comment]
I only tested this with early chapters, so zombies and headcrabs were the ones i noticed when the bug was active. 
This issue is seemingly fixed (i didn't test every enemy) by going back to the pre-25th beta, and then reinstalling the current branch.

**Comment by shawns-valve** [comment]
Closing -- possibly related to install issues.
