### ISSUE TITLE
Detail texture feature broken.

### ISSUE THREAD

**Issue by FlyingCaboose** [ValveSoftware/halflife#3855]
When I enable detail textures via GUI or r_detailtextures 1, the mapping is all screwy and changes in size. This applies to all GoldSrc games.

![20241015200611_1](https://github.com/user-attachments/assets/530dfe53-5d00-431a-ba1f-170d6570833c)

**Condition Zero - Office Complex**

![20241015200747_1](https://github.com/user-attachments/assets/27835527-4826-43e5-807f-82d9c538c51e)

**Day of Defeat - Avalanche**

![20241015200918_1](https://github.com/user-attachments/assets/3f02c8e9-fee2-48d9-95a9-80ee2f3a2e18)

**Team Fortress Classic - 2fort**

I made this custom setting, but I just wanted to emphasize that this affects all GoldSrc games.

**Comment by kisak-valve** [comment]
Hello @FlyingCaboose, this issue is already being tracked at #3631. Closing as a duplicate.
