### ISSUE TITLE
CS 1.6/CSGO/CS2 Fake Servers & Redirection Source Code - a fix?

### ISSUE THREAD

**Issue by alexkn262** [ValveSoftware/halflife#3859]
This are fake servers in the Valve Masterserver (CS 1.6). They are working. Somehow, on the nulled version of Counter Strike with all the protection made by other people this method is not working. Can we solve this? There are thousands of fake servers out there.

Source code: https://pastebin.com/YU9QCay4

The size is to big to post the source code here.

**Comment by kisak-valve** [comment]
Hello @alexkn262, this issue is already being tracked at #2064 / https://github.com/ValveSoftware/csgo-osx-linux/issues/2689. Closing as a duplicate.
