### ISSUE TITLE
GoldSrc ingame scruffy fonts

### ISSUE THREAD

**Issue by lazeriux** [ValveSoftware/halflife#386]
Counter-Strike 1.6 for linux has bad performance fps drops to ~50 every ms it never be stable 100 like it is on windows. Fonts are half leggible.
![Screenshot from 2013-02-19 14:46:21](https://f.cloud.github.com/assets/1884221/171251/65d48efa-7a92-11e2-9332-53404acfd761.png)

**Comment by BlackShadow306** [comment]
@kisak-valve This issue can be closed. (Fixed)

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by magynhard** [comment]
The issue persists until now in Counter-Srike 1.6.

So I've created a patch that you can find here:
I've created a patch for Counter-Strike 1.6 and Day of Defeat 1.2 that can be found here:
https://github.com/magynhard/halflife_goldsrc_linux_font_patches
