### ISSUE TITLE
Open Source or Build for Linux SDK Tools

### ISSUE THREAD

**Issue by dk865** [ValveSoftware/halflife#3871]
I would greatly appreciate it (along with thousands of others) if you guys would kindly make the Source SDK tools (Hammer, HLMV, & HLFacePoser) available to linux by either open-sourcing them, or building them for Linux.

**Comment by kisak-valve** [comment]
Hello @dk865, this request is already being tracked at #3740.

Closing as a duplicate of #3740 / https://github.com/ValveSoftware/halflife/issues/1035#issuecomment-16828980.
