### ISSUE TITLE
[HL25] On the map c2a2b1, there is a graphical glitch known as the "Hall of Mirrors" effect.

### ISSUE THREAD

**Issue by Evisneffo** [ValveSoftware/halflife#3872]
### Issue 
https://github.com/user-attachments/assets/4ae0ea88-18f6-4af0-bd91-26cde5d90a0b

As far as I understand, this issue is very old and might have been present since the game's release. It is most likely caused by a gap between brushes in the map's geometry.

### Game version 
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 19:06:31 Oct  7 2024 (10210)

**Comment by kisak-valve** [comment]
Hello @Evisneffo, this issue is already being tracked at #3451. Closing as a duplicate.
