### ISSUE TITLE
[HL]

### ISSUE THREAD

**Issue by JunePark2018** [ValveSoftware/halflife#3875]
I'm playing Korean version of Half-Life and there's a glitch at the beginning of the game where just "CRXX" appears instead of credit roll.
![20241126211537_1](https://github.com/user-attachments/assets/11ea152b-c709-4808-b67c-46573153038a)
![20241126211528_1](https://github.com/user-attachments/assets/36fd6c09-61fd-403c-a9a6-340ed180265a)

**Comment by kisak-valve** [comment]
Hello @JunePark2018, this issue is already being tracked at #2490. Closing as a duplicate.
