### ISSUE TITLE
Cs 1.6-Beta updates fix dont work OR Steam-Beta Does Not Update

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/halflife#408]
Some of the fix you guys made do not solve it or
I`m not receiving Steam-beta updates

Exe build: 17:09:07 Feb 18 2013 (5961)

CS 1.6    -    opt in Beta
HL 1       -    opt in Beta
Steam    -    opt in Beta

/////   AUTO UPDATE IS ON    for      CS 1.6 & HL 1 \\\\\
Steam - Self Updater says: Your steam client is already up-to-date.

I tried restarting steam, rebooting PC and reinstalling steam,
I do receive the CS 1.6 and HL 1 beta updates but I do not receive the Steam-beta updates 
I think that it is steam`s technical problem for some reason
Tell me how to update manually because I want to get rid of bugs like these:

![unfixed](https://f.cloud.github.com/assets/3611711/173585/be29181a-7ae1-11e2-9d9f-5f841f4940e3.JPG)

I found a temporary fix = open console = write net_graph 1 = quit the game =  open the game

![fix](https://f.cloud.github.com/assets/3611711/173601/fc6fbc32-7ae1-11e2-8490-c5a02c5e0249.JPG)
But I have to leave net_graph 1 every time I quit

//GameOverlayRenderer.log
http://205.196.123.184/ajdygnj2n5lg/8sgq9xridtjb578/GameOverlayRenderer.log

//System Information
http://205.196.123.166/e33sfx79scqg/k37yytmaqx1o8mh/System+Information.txt

**Comment by shawns-valve** [comment]
Closing due to age. Please open a new issue if you're having similar issues with a current Steam client / recent updates.
