### ISSUE TITLE
[CS 1.6][REQUEST] Player Avatars in Window Mode

### ISSUE THREAD

**Issue by 911r0ck** [ValveSoftware/halflife#429]
I have tried every possible resolution in windows mode but it doesn't shows avatars in score tab....
I don't know if its a bug or you have not put, but you should put because in full screen mode it shows ... then it should show in window mode in same resolution also.
Thanks.

**Comment by CS-PRO1** [comment]
@kisak-valve This issue was fixed at some point. I tested with exact same settings here:
![cs_assault0005](https://user-images.githubusercontent.com/50755959/62226124-5dc91f80-b3c2-11e9-8a30-6cac61b8b27a.png)
Should be closed as fixed, please.

**Comment by oaus** [comment]
It's already fixed

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
