### ISSUE TITLE
[CS 1.6 beta build 5961] German Keyboard Layout Button Config Problem

### ISSUE THREAD

**Issue by holz81** [ValveSoftware/halflife#431]
Just a small bug.

I cannot bind any of these keys in the keyboard options menu:

![rl1wxtb2](https://f.cloud.github.com/assets/3623657/176227/20390fec-7b6e-11e2-9549-d80947e9e4b7.jpg)

It gets rejected and nothing happens.

Version:
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 17:09:07 Feb 18 2013 (5961)

WindowsXP 32bit ServicePack3 English

German Keyboard Layout

**Comment by Rabtos** [comment]
Year 2013 - when will this be fixxed?
