### ISSUE TITLE
[CS 1.6 BETA] m_rawinput and acceleration

### ISSUE THREAD

**Issue by nekitz0r** [ValveSoftware/halflife#432]
Hello everyone! I have a problem whit "m_rawinput" settings.

Motherboard   : ASUS SABERTOOTH Z77
CPU              : Intel Core i7-2600 (3.40Ghz Socket1155)
RAM              : Kingston DSRAM 2x2Gb "Hyper X" KHX2133C9AD3T1K2/4GX
Video             : ZOTAC GeForce GTX 470 AMP! Edition 1280Mb
HDD               : SSD 60Gb OCZ "Agility 2"
Display           : Samsung 2233rz (120Hz)
OS                 : Windows 7 Ultimate PS 1 (64bit)
Mice               : Zowie AM

Half-Life and CS 1.6 fully installed and upgraded,
and select "Beta" for BOTH games.

Check my screenshots in MouseMovementRecorder:

1) http://filepic.ru/1361370797    in Windows   -> everything is working fine (no acceleration) 

2) http://filepic.ru/1361370854    in CS (m_rawinput = 0)   -> Goes back to old sensivity, but lags/don't respond correctly/breaking movement/etc

3) http://filepic.ru/1361370877    in CS (m_rawinput = 1)   -> The mouse works fine but with alot of acceleration (shooting far or close, seems I have negative and positive acceleration and it's impossible to play like that)

If I started CS with launch options (-w 800 -nofbo) I always have acceleration in game.

http://filepic.ru/1361370854  (m_rawinput = 0)
http://filepic.ru/1361370877  (m_rawinput = 1) 

If I started CS with launch options (-w 800 -noforcemparms -noforcemaccel -nofbo) I don't have acceleration. (not always). But Check screenshots:

http://filepic.ru/1361371802  (m_rawinput = 0)
http://filepic.ru/1361371817  (m_rawinput = 1)

m_rawinput = 0  and m_rawinput = 1  -> not correctly movement for my mice.

Dear developers, can you make it looks like a ( http://filepic.ru/1361370797  in Windows) ? I think it's the only correctly movement for mice ( bit to bit). It's very need for normal playing.

**Comment by CloudHaze** [comment]
:/

**Comment by jb304** [comment]
up
still having accel with rinput 1

**Comment by Karaulov** [comment]
Windows 10 i can't attack! Mouse1/Mouse3 buttons works only in 80% cases.

with m_rawinput i can't play. Its make delay and i can't kill nothing.

**Comment by OneJc1** [comment]
still
