### ISSUE TITLE
Half Life 1: Door won't open in Level "Power Up"

### ISSUE THREAD

**Issue by MitchK** [ValveSoftware/halflife#433]
Hi,
in the Level "Power-Up" the door is locked. The power supply is turned on.

Edit: Sys specs and all my saved games are attached here: https://www.dropbox.com/sh/aomr19lwhl8nh55/pmgxJrPVSC

![hl_screenshot](https://f.cloud.github.com/assets/2472064/176345/b129eeca-7b70-11e2-984e-95213013fccc.png)

**Comment by ApeWithCompiler** [comment]
Just for anyone stumbling upon this:
In the connection section before the silo and this, mostly at the end, there is a valve you are supposed to use. This valve moves the pipe so they connect over open ground. If you are like me you probably yolo jump over this and ignore the valve.

As far as I figured, this valve counts also as an trigger for the gate open event to happen. So reload, use the valve, skim trough this section again and you should be good to go.
