### ISSUE TITLE
After the update has been released WHAT CVARS SHOULD BE SET IN SERVER.CFG ??

### ISSUE THREAD

**Issue by killigor** [ValveSoftware/halflife#439]
//That is old CStrike Server cfg

hostname "<[ LeGeNdA ]> 18+ "
rcon_password ""

mp_autokick "0" 
mp_autoteambalance "1" 
mp_buytime "0.25" 
mp_c4timer "35" 
mp_consistency "1"
mp_fadetoblack "0"
mp_flashlight "1" 
mp_footsteps "1" 
mp_forcecamera "2" 
mp_forcechasecam "2" 
mp_freezetime "0" 
mp_friendlyfire "1" 
mp_hostagepenalty "0" 
mp_limitteams "0" 
mp_maxrounds "0"
mp_playerid "0"
mp_roundtime "2.35" 
mp_startmoney "1000" 
mp_timelimit "20" 
mp_tkpunish "0" 
mp_winlimit "0" 
sv_aim "0"
sv_airaccelerate "10"
sv_airmove "1"
sv_allowdownload "1"
sv_allowupload "1"
sv_alltalk "1"
sv_cheats "0"
sv_clienttrace "1"
sv_clipmode "0"
sv_friction "4"
sv_gravity "800"
sv_maxrate "25000" - changed by Valve up to 100000
sv_maxspeed "320"
sv_maxunlag "0.5"
sv_maxupdaterate "101"
sv_minrate "10000"
sv_minupdaterate "20"
sv_proxies "0"
sv_restartround "0" 
sv_send_logos "1"
sv_send_resources "1"
sv_stepsize "18"
sv_stopspeed "75"
sv_timeout "200"
sv_unlag "1"
sv_unlagsamples "1"
sv_unlagpush "0"
sv_voiceenable "1" 
pausable "0"
sys_ticrate "1100"  - still exist This command sets the maximum "frames" per second the server can calculate.
fps_max "1000"  - do not work for server settings
allow_spectators "3"     - still exists Allows players to join as spectator.
decalfrequency "60"

edgefriction "2" - still exist This is used to add slowdown when jumping off of an edge. When jumping off of a           platform            that is 70 units from the ground, the effect of edge friction is greatly increased. When set higher, the              force pulling you down is greater. (Gravity in a sense)

host_framerate "0"
sv_voicequality "4"
sv_rcon_banpenalty "0"\ban in minutes
sv_rcon_minifailures "1"\min failures
sv_rcon_maxfailures "1" \ max failures
sv_rcon_minifailuretime "30" \seconds for next try
sv_voicecodec "voice_speex"
sv_downloadurl "http://www.example.com/cstrike/"
mm_insane "2"
log on
sv_logbans 1
sv_logecho 1
sv_logfile 1
sv_log_onefile 0
mp_logdetail 0
mp_logmessages 1
mp_logecho "1"
mp_logfile "1"

mapchangecfgfile server.cfg
vac2 "1"
metamod_active "1"
vac "1"

con_log hlds.log

**Comment by shawns-valve** [comment]
Closing due to age. Please open a new issue if you have a similar question regarding the current version of Half-Life / CS.
