### ISSUE TITLE
re-enable r_shadows as cheat-protected cvar

### ISSUE THREAD

**Issue by tschumann** [ValveSoftware/halflife#451]
Way back when, the r_shadows cvar was removed from the engine. I don't know why (I think I read that the shadows sometimes go through walls which probably isn't ideal in multiplayer games).
Could it be re-enabled but require sv_cheats to be 1 so that it can at least be enjoyed in single player?

**Comment by SamVanheer** [comment]
@mikela-valve If this wouldn't cause any problems this would be nice to have. Looks like it's a oneliner to re-enable this.

**Comment by theOneTrueFunniBoi** [comment]
It's probably not me looking hard enough, but I can't find code for the shadows anywhere. Nor do I know the way to properly re-enable it.

**Comment by tschumann** [comment]
It's in the engine, not in game code.
I think there are tutorials to re-enable it using assembly and declspec
naked (at least for Visual Studio).

**Comment by theOneTrueFunniBoi** [comment]
Nah it’s all good, I already found a tutorial that worked for my needs.

**Comment by 3doplayer67484** [comment]
It has been added in the latest update the thread can closed

**Comment by kisak-valve** [comment]
Closing per the last comment.
