### ISSUE TITLE
[HL] - Is possible to return old physics?

### ISSUE THREAD

**Issue by PrcoKillerSK** [ValveSoftware/halflife#461]
We are playing HL Hockey on map ,,hockey-life" and since the update, we have the issue that puck there is moving diferently! I would like to ask, if there is any chance to return an old physics by cvar or anything else. (It is a pushable entity like crates, but unbreakable).
Thanks for quick responding.

**Comment by BlackShadow306** [comment]
@kisak-valve This issue can be closed. (Fixed)

**Comment by kisak-valve** [comment]
Closing per the last comment.
