### ISSUE TITLE
[CS 1.6 Beta build 5961] Motd dont work

### ISSUE THREAD

**Issue by Kremnev** [ValveSoftware/halflife#474]
After the last update said that joining the server "welcome screen" (MOTD) disappeared.
![motd](https://f.cloud.github.com/assets/3663463/182300/75bde5e2-7c6c-11e2-8152-3750453a508b.JPG)
Resolution changes also do not affect it.
Tried to play to the old and update server, also do not affect it.

p.s.
Sorry my english)

**Comment by jabirakss** [comment]
This Will work 
**cl_disablehtmlmotds "0"**
