### ISSUE TITLE
[HL1] Support for HTML in MOTD window

### ISSUE THREAD

**Issue by et-nik** [ValveSoftware/halflife#507]
In CS you can use HTML to build colorful and very interesting MOTD windows.
In HL there is not. If you try to put HTML code to motd you just see html markup tags in the MOTD window as just text.

I would be nice if you maded only static HTML, no scripts or meta tags processing, cos there is kind of stupid servers, which try to hack your PC with HTML scripts (instant file virus download confirmation, stupid radio players and much more).

**Comment by jairoiglesias** [comment]
Alfred, could guide us what it would take to modify the HL MOTD that interprets HTML equal to Counter Strike 1.6? There are still many servers and mods being made in GoldSrc. Many experimental tests are still made in this engine. And it is difficult for this part. Plain text in MOTD not help much. I would like to guidance on how to modify the HTML MOTD is possible in HL. Nothing more than that. Thank U :)
