### ISSUE TITLE
[CS 1.6 Problem] Special characters not being displayed right

### ISSUE THREAD

**Issue by di57inct** [ValveSoftware/halflife#514]
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 10:34:27 Feb 21 2013 (5964)

When using special characters like "âăîșț ÂĂÎȘȚ", "넥슨", "ру́сский язы́к", the HUD font doesn't fully display them, or just has an awful mode of doing it. It cuts off a part of the characters, it's bolded, which makes it even worse, etc...
Also, found a new problem where if you write special characters, the message is displayed twice in the console: once with the characters and once empty.

Here are some pictures that show what I'm talking about:

http://i50.tinypic.com/152ox84.jpg
http://i50.tinypic.com/zpk46.jpg

http://i45.tinypic.com/20auyyd.jpg
http://i48.tinypic.com/2chavwj.jpg

http://i48.tinypic.com/24yo65y.jpg
http://i50.tinypic.com/110b2fc.jpg

**Comment by BlackShadow306** [comment]
@kisak-valve This issue can be closed. (Fixed)

**Comment by kisak-valve** [comment]
Closing per the last comment.
