### ISSUE TITLE
[GoldSrc Suggestion] Add unicode support to name and HUD text

### ISSUE THREAD

**Issue by di57inct** [ValveSoftware/halflife#515]
So players will be able to use characters like "♪ |ılıl.lılı.ıllı.lııl| ♫", etc in chat, name and HUD messages(like when you aim on a player, etc).
Thanks in advance.

**Comment by BlackShadow306** [comment]
@kisak-valve This issue can be closed. (Fixed)

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by AoiKagase** [comment]
This issue has not been fixed in HL1.
![20200603224248_1](https://user-images.githubusercontent.com/26139931/83699287-9a972000-a63e-11ea-954d-41fa39d1703c.jpg)

**Comment by AoiKagase** [comment]
@kisak-valve @alfred-valve

**Comment by GabeIggy** [comment]
@mikela-valve Would be possible to see this?
