### ISSUE TITLE
[CS 1.6 Problem] New game settings not being remembered

### ISSUE THREAD

**Issue by di57inct** [ValveSoftware/halflife#520]
Started a map with the following settings:
http://i46.tinypic.com/2ns2d74.jpg

Then, when I wanted to start a New Game again, default settings appeared:
http://i47.tinypic.com/2d106et.jpg

EDIT:
This problem wasn't occuring before the BETA.

**Comment by BlackShadow306** [comment]
@kisak-valve This issue can be closed.  (Fixed)

**Comment by kisak-valve** [comment]
Closing per https://github.com/ValveSoftware/halflife/issues/520#issuecomment-37637830.
