### ISSUE TITLE
[CS/CZ/HL request] Special location for custom content. Ex: models sound etc...

### ISSUE THREAD

**Issue by Dasani** [ValveSoftware/halflife#533]
Would it be possible to allow the use of custom content without having to overwrite the original game content? Before with the GCF files the base content was packed away neatly and custom models found in the cstrike or czero directories would take over the base content. Now it seems to be all scramble and it is kind of confusing to use.

Some of the base content I have overwritten in the CS directory is being used in CZ, for example sprites I changed in CS are being used in CZ. Not that this is a huge issue, for me that is, since I use the same sprites content in both games. I think it would allow for a cleaner experience if we could just have a folder that each game looks in to use for custom material instead of the having to overwrite the original content. It would make integrity checks a lot easier as well. I hope this can be consider for Source title that will make their way to the Steam Pipe as well.

**Comment by SamVanheer** [comment]
This issue can be closed, Alfred's solution is how players should add content.

**Comment by kisak-valve** [comment]
Closing per the last comment.
