### ISSUE TITLE
[CS1.6] Error when i connect to a server use T models

### ISSUE THREAD

**Issue by revo4ever** [ValveSoftware/halflife#545]
Hii, shortly before, I try to connect to a Zombie server but it's refusing 
Because the server use the T models

IP : 63.251.20.47:27015

Connecting to 63.251.20.47:27015...
Connection accepted by 63.251.20.47:27015
Server tried to send invalid command:"Connect 63.251.20.47:27017
"\* Privileges set 

BUILD 5758 SERVER (0 CRC)
Server # 10
Mod_LoadBrushModel: models/player/z_rubber/z_rubberT.mdl has wrong version number (1329865020 should be 30)

Client world model is NULL
Client world model is NULL

![2013-02-23_00001](https://f.cloud.github.com/assets/3428035/187975/11dffce8-7dae-11e2-82fc-d9be013e1f13.jpg)

Processor Information:
    Vendor:  GenuineIntel
    Speed: 3067 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu Raring Ringtail (development branch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-7-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11302000
    X Window Manager:  Compiz
    Steam Runtime Version:  <Runtime enabled>

Video Card:
    Driver:  NVIDIA Corporation GeForce G210/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 313.18
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xa60
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1600 x 900
Desktop Resolution: 1600 x 900
Primary Display Size: 17,44" x 9,80"  (20,00" diag)
                                        44,3cm x 24,9cm  (50,8cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 512 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC888

Memory:
    RAM:  3817 Mb

Miscellaneous:
    UI Language:  English
    LANG:  fr_FR.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  147848 Mb
    Largest Free Hard Disk Block:  115177 Mb

Installed software:

Recent Failure Reports:

**Comment by BlackShadow306** [comment]
@kisak-valve This issue can be closed. (Fixed)

**Comment by kisak-valve** [comment]
Closing per the last comment.
