### ISSUE TITLE
Install location moved

### ISSUE THREAD

**Issue by Ejz85** [ValveSoftware/halflife#55]
When my game recieved the update my gamefolder changed to: \common\Half-Life\cstrike.

But Ive seen more than 10 players that dont seem to have the folder moved. I dont know what the problem could be there.

**Comment by shawns-valve** [comment]
Closing due to age / not sure if this is relevant anymore. Please reopen / create a new issue if there are still issues with the 25th anniversary update (December 2023 Steam build).
