### ISSUE TITLE
[CS 1.6 & CZ Problem] Shotgun shell reload being delayed or canceled when holding +attack

### ISSUE THREAD

**Issue by di57inct** [ValveSoftware/halflife#555]
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 10:34:27 Feb 21 2013 (5964)

When the clip is empty and the shotgun is trying to automatically reload, if you hold +attack, it will hang the reload process by 1 or 2 seconds, making it very annoying and possibly getting you killed.

This applies to both manual and auto shotguns(m3 and xm1014).

CS 1.6 demo with the bug here: http://www2.zippyshare.com/v/96009378/file.html

**Comment by mikela-valve** [comment]
This is fixed in the latest CS beta (not CZ yet as I haven't updated the beta for it). Shell reloading should proceed at the same rate whether +attack is held or not and it should fire each time a shell is loaded while you continue holding it.

**Comment by mikela-valve** [comment]
Closing as fixed.
