### ISSUE TITLE
Non-US characters don't print on their own in chat, and print incorrectly in the developer message line

### ISSUE THREAD

**Issue by Adambean** [ValveSoftware/halflife#565]
If you enter a non-US character (I used £) on its' own in chat, it will not transmit the message.

Also if you add a US character to make it transmit (I typed £1) then it doesn't appear correctly in the top-left developer message, as shown here:

![shattered__23-02-13_19-18-57](https://f.cloud.github.com/assets/1108717/188598/95296e98-7dfb-11e2-9b90-056dbd5565b4.jpg)

**Comment by SamVanheer** [comment]
UTF support is working in the public version:
![bounce0000](https://user-images.githubusercontent.com/5501383/57184786-f84bbc80-6ec0-11e9-8c4e-ee587725ee26.jpg)

The console also prints them properly. I think this one can be closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
