### ISSUE TITLE
[CS 1.6] Terrible performance issues (100% cpu usage)

### ISSUE THREAD

**Issue by HexC** [ValveSoftware/halflife#57]
Hi, after the update CS, which used to run very well on my PC, now uses 100% of cpu all the time even when I'm in the main game menu. Everything is sluggish, sound is stuttering, when I try to pop different menu items they do so with significant delay, just moving the options window around shows off terribly low fps. net_graph 1 says it's ~4 with fullscreen 1280x1024 and ~6 with windowed 640x480. All that is just about the menu.
However, when I try to join a server sometimes I get a weird error "You have been disconected from the server. Reason: Fake client. Connection was in idle state for 8 second" which might be connected to the performance problem. I tested it with different resolutions and fullscreen/windowed mode and got this:

640x480
fullscreen: 35 fps
windowed: 100 fps

800x600
fullscreen: error at "validating game resources..."
windowed 70-100 fps

1024x768
fullscreen: error at "establishing network connection to server"
windowed: 60-100 fps

1280x1024
fullscreen: error at "establishing network connection to server"
windowed: error at "establishing network connection to server"

So yeah, even when I'm able to connect I still get extremely low fps at extremely low resolutions (like 35 at 640x480), not to mention that now it's dropping in fights to the point when it becomes noticeable whether prior to the patch I've had the game running smoothly at 1280x1024 fullscreen with 100 fps and no visible framerate lowerings.
One more thing to say about the in-game performance: no sound stuttering, no delay with actions like buying or choosing weapons; just low framerate (still much higher than when I'm in the menu, though), fps dropping in fights and 100% cpu usage.

It seems to be either the game has become MUCH more demanding on computer specs or just some nasty bug in the new rendering system which makes CS use 100% of CPU therefore giving me poor performance.

My computer (it's old, but it should be more than enough for Counter-Strike):
Intel Pentium 4 (Northwood revision, 2.8 GHz)
512 mb DDR
Nvidia Geforce FX 5600XT (driver version 175.19 or 6.14.11.7519)
Windows XP SP3.

**Comment by shawns-valve** [comment]
Closing due to age. Please reopen / create a new issue if you're still having problems with the 25th anniversary updates (December 2023 Steam build of Half-Life / Counter-Strike).

**Comment by ELpotato321** [comment]
I have the same problem 
Very strange problem?
Not long ago I noticed that cs 1.6 all the time loads 2 threads or 2 cores at 100%.
This happens all the time no matter where I am (main menu, while playing on the server).
I have looked at the messages in the debug file, but I don't understand anything (maybe these errors are a consequence of the constant loading of 2 cores or 2 threads 100%.


I'm thinking of trying to clean the registry associated with cs 1.6, but I'm not sure.
I have a 12650h processor.



https://ibb.co/cKBGVz0D

https://ibb.co/zTCmzz5W

**Comment by tschumann** [comment]
Looks like an issue with the picjj.com server not supporting TLS.

**Comment by ELpotato321** [comment]
Only I don't understand why in the main menu I have 1 core and 2 threads or 2 cores 100% loaded and this only happens when the window is in the minimized state. When I minimize it all load stops.To confirm this I can record a video through obs.
