### ISSUE TITLE
[CS1.6 Build 5961] Loading Dialog Problems

### ISSUE THREAD

**Issue by revo4ever** [ValveSoftware/halflife#582]
Hii all, There are some bugs related to loading Dialog

![2013-02-24_00001](https://f.cloud.github.com/assets/3428035/189752/95a9b8b0-7ea9-11e2-9698-60ccefbf69ac.jpg)

1- When someone connect to server, it tries to download. Sometimes it succeeds to download files [i don't no why]. This problem appears in all servers and also with the updated servers (596X)

2- Countdown to download files is not working probably, It only works when downloading more than one file. In other cases does not work, it shows only 1 second 

Processor Information:
Vendor: GenuineIntel
Speed: 3067 Mhz
4 logical processors
2 physical processors
HyperThreading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported

Network Information:
Network Speed:

Operating System Version:
Ubuntu Raring Ringtail (development branch) (64 bit)
Kernel Name: Linux
Kernel Version: 3.8.0-7-generic
X Server Vendor: The X.Org Foundation
X Server Release: 11302000
X Window Manager: Compiz
Steam Runtime Version: steam-runtime-release-i386_2013-02-22

Video Card:
Driver: NVIDIA Corporation GeForce G210/PCIe/SSE2

Driver Version:  3.3.0 NVIDIA 313.18
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xa60
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1600 x 900
Desktop Resolution: 1600 x 900
Primary Display Size: 17,44" x 9,80"  (20,00" diag)
                                        44,3cm x 24,9cm  (50,8cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 512 MB
Supported MSAA Modes:  2x 4x 8x 16x 
Sound card:
Audio device: Realtek ALC888

Memory:
RAM: 3817 Mb

Miscellaneous:
UI Language: English
LANG: fr_FR.UTF-8
Microphone: Not set
Total Hard Disk Space Available: 147848 Mb
Largest Free Hard Disk Block: 114781 Mb

Installed software:

Recent Failure Reports:

**Comment by shawns-valve** [comment]
It looks like these issues have been resolved at various points in the past. If you still experience similar issues on the current Steam build of Counter-Strike, please open a new issue.
