### ISSUE TITLE
Cannot change spray logo or color

### ISSUE THREAD

**Issue by 3DG-XP** [ValveSoftware/halflife#588]
Hii all, in Multiplayer tab Logo and color don't change... watch this video and see

http://videobam.com/ERPgP
WinXP SP3 Update to date.

thanks.
[CS1.6 Build 5961]

**Comment by SamVanheer** [comment]
I'm able to change both logo and color. If somebody else can confirm this issue can be closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
