### ISSUE TITLE
[CS 1.6] Slow Movements & Mouse behaivor

### ISSUE THREAD

**Issue by ketch1nators** [ValveSoftware/halflife#59]
Hello, After solving my performance issues with adding -nofbo to launch options and using gl_vsync 0 my game shows me that i'm running on constant 100 FPS via cl_showfps 1 and 101 fps via net_graph commands.. but! there is a but.. still the movement feels like if i'm playing source based game not goldsrc based game! it's like i'm running around but i'm not.. the feeling is like i'm in middle of somewhere between Running (not using walk key) and Walking (using walk key) .. it's not a placeboo or something the game feels just to slow and the other oponents without the update moves faster, and if i'm using my other PC without the update it's great i can jump around, do bunnyhoping strafe jumping and stuff like that without any issues at all! what's up with that valve? I even ignored the part where -freq and -refresh commands does nothing and installed 3rd part app called "refreshlock" to use 75hz on my FULLHD 24' inch screen to not tear my eyes apart playing on 640x..

Ok that's it for the movement part..

I assume that the CS 1.6 is ported to another engine mb even the source one, and with the BIG SCREEN stuff on steam and the Console coming out in near future there will be more changes to my beloved game.

Let's start with the mouse part!

After this UPDATE thing on 14.02.2013
Mouse movement feels different too.. why? Cuz i see that you made the CS 1.6 to use DIRECT INPUT THING or the RAW INPUT thing that you allready done to CSS and CSGO. OK, that's cool.. but it isn't cool that you don't mentioned it to all of us CS 1.6 players that do play the game today and there isn't any command to control that like in CSGO or CSS where you can turn it on and off just by clicking the option in-game! Now cs ignores all the -noforcem mouse options and uses proper mouse/cs communication thing HALLELUJAAH to that!

One thing that you didn't think about is, that we - CS players that are somehow used to lame acceleration thing for the past 10 years (even with the noforcem commands intruduced in CS 1.6) are going to notice the difference?!?!?!

It's like having learned and used to how to drive a car, and now somehow the steering-wheel spins different with no explanation nor statement why!?

Make some statements about it or please fix it asap!

Best regards, ketch e.g. gotyu @ steam

Forgot to mention:
Tested it on WINDOWS XP SP3 (64bit) and WINDOWS 7 SP1 Ultimate (64bit) on a rig
AMD X2 6000+, 4GB of RAM, Ge Force GS7100 (no the greatest one but for the 10 years old game it does the trick)
Using latest available Nvidia graphic drivers from their website!

Mouse thing:
Tested with -noforcemparms -noforcemaccel then -noforcemparms -noforcemaccel -noforcemspd, then with no noforcem commands at all, then i installed windows 7 and even with the "ENHANCE mouse pointer precission thing" turned on by default! My mouse still moves like it is ignoring windows settings!

**Comment by ReduxRown** [comment]
> Not sure if stupid or just retarded.
> 
> THIS RAW input or what ever yow want to call it it is not =/ removing mouse FILTER.
> 
> Ok try this.
> 
> Instal cs 1.6 non-steam with the latest updates = prior to 24.02.2013 put -noforce commands and compare with steam 1.6 AFTER the update with -noforce removed.
> Set Sensitivity to 1.5 on both no-steam and steam and then MOVE the mosue around and you will se the diference.
> 
> Steam 1.6 feels like it has positive / negative acceleration
> No-steam with -noforce does not have positive/negative acceleration :)

STFU. What else do you need ?! Valve still updating the game and fix some bugs and glitch as well. The game is still fine as ever.
