### ISSUE TITLE
[CS 1.6] autobuy

### ISSUE THREAD

**Issue by LaurentiuAndrei** [ValveSoftware/halflife#61]
It just doesn't work, neither by manual typing in the console or by bind.

] version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 15:02:07 Feb 13 2013 (5956)

Processor Information:
    Vendor:  GenuineIntel
    Speed: 2000 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.2 LTS (32 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-37-generic-pae
    X Server vendor:  The X.Org Foundation
    X Server release:  11103000

Video Card:
    Driver:  NVIDIA Corporation GeForce 9500 GT/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 310.14
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 75 Hz
VendorID:  0x10de
DeviceID:  0x640
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 1024
Desktop Resolution: 1280 x 1024
Primary Display Size: 14.96" x 11.81"  (19.06" diag)
                                        38.0cm x 30.0cm  (48.4cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC888

Memory:
    RAM:  2013 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  23509 Mb
    Largest Free Hard Disk Block:  5621 Mb

Installed software:

Recent Failure Reports:
    Fri Feb 15 12:06:37 2013 GMT: file ''/tmp/dumps/assert_20130215140635_1.dmp'', upload yes: ''CrashID=bp-c0c8fe8f-ba46-4e84-b690-5a28e2130215''
    Fri Feb 15 12:12:56 2013 GMT: file ''/tmp/dumps/assert_20130215141255_1.dmp'', upload yes: ''CrashID=bp-56f2fe09-4bb9-454f-a02e-c0a3e2130215''

**Comment by shawns-valve** [comment]
Closing due to age. Please reopen / create a new issue if this still occurs with the 25th anniversary update (December 2023 Steam build) on a current Linux distribution.
