### ISSUE TITLE
[HL beta linux] libSDL2.so cosmetic

### ISSUE THREAD

**Issue by BigBadWulf** [ValveSoftware/halflife#624]
After todays update there is a new file: SteamApps/common/Half-Life/libSDL2.so
But only 17 byte size, with the text content "libsdl2-2.0.so.0".
Asuming it should be a symlink to libsdl2-2.0.so.0 but the steam-updater, or an other component in the update process, can not handle unix symlinks.
However, this 'bug' has no effect on HL at all, therfore its a cosmetic bug.

Maybe a sideeffect from #604

btw nice compatiblity update, sound now works with SDL_AUDIODRIVER set to alsa, pulse and pulseaudio

**Comment by SamVanheer** [comment]
The current public version properly creates this file as a symlink to the actual library.
Output of `ls -l`:
```
-rwxrwxr-x  1 sam sam   923556 Okt  9  2016 libSDL2-2.0.so.0
lrwxrwxrwx  1 sam sam           16 Mai  4 22:52 libSDL2.so -> libSDL2-2.0.so.0
```

This issue can be closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
