### ISSUE TITLE
[GoldSrc] Is it MSAA or FSAA?

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/halflife#626]
I still can't understand what's wrong with the new renderer (what brought us MSAA). If MSAA is ON, my fps drops when I look at a smoke or turn on my nightvision.
But then, suddenly, I found another place where my fps drops. When I get a closer look at detail textures in CS:CZ.
4 screens (pay attention to netgraph in the lower right corner):
![](http://s019.radikal.ru/i643/1302/1f/ce7feaf21979.jpg)
![](http://s018.radikal.ru/i525/1302/ce/349c21dd4106.jpg)
![](http://s019.radikal.ru/i631/1302/1d/aff5ca8d3cdb.jpg)
![](http://s018.radikal.ru/i512/1302/9a/e984f82d2e26.jpg)
When I get a closer look at detail textures my fps drops by 10. When I turn on my nightvision, I get ~70fps instead of 100.

Same screens with `-nomsaa` (I used a recorded demo)
![](http://s019.radikal.ru/i627/1302/6d/fda22a7cd2de.jpg)
![](http://s020.radikal.ru/i722/1302/08/a7c3ba26cf50.jpg)
![](http://s51.radikal.ru/i134/1302/7c/925dc9b03e57.jpg)
![](http://s019.radikal.ru/i620/1302/91/95bb46d68cb3.jpg)
It looks like the renderer is trying to apply antialiasing to the whole picture. Not just to the edges. So it works like FSAA (full-scene anti-aliasing), but I assume it shouldn't. I'm sorry if I'm wrong and it is a waste of time.

**Comment by satnatantas** [comment]
I have FPS drops when using night vision with my Core2Duo E8500 and it specifically affects dark parts of map. It looks like a CPU-bound scenario because it worsens when I play online and not on listenserver. My FPS drops wit My GPU is HD6950 and it stays below 5% usage in all cases.

**Comment by satnatantas** [comment]
For example, I have fps drops on cs_assault_1337 in the top window room.
