### ISSUE TITLE
CS 1.6 flickering Monitor after big update

### ISSUE THREAD

**Issue by HandSolo** [ValveSoftware/halflife#63]
hi together,
after yesterdays big update my monitor flickers when i start cs.
I used to fix it with the following steps:

-nofbo
-freq 60 (cause i use a laptop with 60 Hz)
gl_vsync 0
gl_async 0

unfortunately the flickering is still there. Has anyone more hints or a solution for my problem?

thank u!

**Comment by maro555** [comment]
I have Same problem in my ATI 1150
any solutions?

**Comment by sjain882** [comment]
@maro555

Fixed by using win7 compatibility mode

Steps: https://steamcommunity.com/app/70/discussions/0/135511027317318123/

**Comment by GBCS-PRO** [comment]
It used to happen on my Toshiba Qosmio F20-138 with Geforce Go 6600 and in Windows 7 .. other versions  before that update worked without problems. Well the gpu there is mostly dead so I can't confirm if that fixes the issue on my end..

**Comment by shawns-valve** [comment]
Closing due to age. Please reopen / create a new issue if this still occurs with the 25th anniversary update (December 2023 Steam build) with current graphics drivers.
