### ISSUE TITLE
[CS 1.6] Demo playback using 'viewdemo' command causes crash and error.

### ISSUE THREAD

**Issue by myhrr** [ValveSoftware/halflife#637]
As the title says, the error displayed in the screenshot below is what pops up. I had heard the problem had been fixed, but upon trying to view a demo that's what I got.

Not sure if it's of note but it's a HLTV demo.

The playdemo command works fine, but sitting through an hour long demo to watch the 20 seconds you want is rather tedious. Perhaps the demo manipulation interface could work independently from the viewdemo command? No idea.

My apologies if this was already reported, I only found 2 week old issues that had been already closed.

![untitled](https://f.cloud.github.com/assets/563742/201085/bc553e34-80e4-11e2-9110-e67d49dda739.JPG)

**Comment by dominicholt** [comment]
This is definitely not closed. The whole reason we want to use viewdemo is to watch OLD videos.
