### ISSUE TITLE
[CS1.6] r_drawviewmodel "0"

### ISSUE THREAD

**Issue by f4k3** [ValveSoftware/halflife#64]
Currently r_drawviewmodel is locked to 1.
Actually we can use custom models to achive effect of that cvar, even clanbase have models that give you such effect.

It's pretty annoing to copypaste models or delete them if you switching between mix and ladder that have rule about custom models.
And it's helpful for machines with low fps.

update:
same as with m_pitch, why need to lock that if we have workaround. You will disable custom weapon models? So why lock this?

**Comment by kisak-valve** [comment]
Closing in favor of #1985.
