### ISSUE TITLE
mouse acceleration Cs 1.6 HELP!!!

### ISSUE THREAD

**Issue by alexan23** [ValveSoftware/halflife#66]
After the upgrade, terrible speed mouse.
Before you update the attributes in start stim-noforcemaccel-noforcemparms-noforcemspd played on SENS 1.5 was all fast and rezko.A after updatings on SENS 1.5 to do 5 to 10 laps that would lead one to the goal. Team -noforcemaccel-noforcemparms-noforcemspd not help.

**Comment by djdallmann** [comment]
Can you guys try m_side 0, default is 0.800 and to me makes the sensitivity more consistent.

**Comment by shawns-valve** [comment]
Closing due to age. Please reopen / create a new issue if this still occurs with the 25th anniversary update (December 2023 Steam build). Also try toggling the "Raw mouse input" setting in the Aim options.
