### ISSUE TITLE
[CS 1.6] game_team_master entity issue

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/halflife#667]
game_team_master and game_team_set are available in counter-strike, but those entities works just in half-life. The reason behind it is that half-life use different team identification rather counter-strike afaik. I wonder if this can be fixed to work with terrorist and counter-terrorist teams in counter-strike? The only entity that is able to distinguish counter-strike teams is func_buyzone, so I assume it should be somewhat possible to alternate work of mentioned entities (for cs 1.6). Best regards!

**Comment by SamVanheer** [comment]
Duplicate of #197

**Comment by kisak-valve** [comment]
Closing per the last comment.
