### ISSUE TITLE
Host_Error: CL_ParseServerMessage: Illegible server message - svc_bad

### ISSUE THREAD

**Issue by fred0r** [ValveSoftware/halflife#678]
It happend the 3rd time all player dropped with that in the console - no errorwindow

Error: server failed to transmit file 'AY&SY0`>'
Last 32 messages parsed.
629728 0134 SetFOV
629728 0136 Health
629728 0138 Battery
629728 0141 Damage
629728 0154 FlashBat
629728 0156 Train
629728 0158 CurWeapon
629728 0162 WeapPickup
629728 0164 WeapPickup
629728 0166 AmmoPickup
629728 0169 ScoreAttrib
629728 0172 ScreenFade
629728 0183 RoundTime
629728 0186 ScoreAttrib
629728 0189 ScoreAttrib
629728 0192 ScoreAttrib
629728 0195 ScoreAttrib
629728 0198 ScoreAttrib
629728 0201 ScoreAttrib
629728 0204 ScoreAttrib
629728 0207 ScoreAttrib
629728 0210 ScoreAttrib
629728 0213 ScoreAttrib
629728 0216 ScoreAttrib
629728 0219 ScoreAttrib
629728 0222 ScoreAttrib
629728 0225 svc_event_reliable
629728 0228 ScoreAttrib
629728 0231 CurWeapon
629728 0235 CurWeapon
629728 0239 svc_filetxferfailed
BAD:  250:svc_bad
Host_Error: CL_ParseServerMessage: Illegible server message - svc_bad

**Comment by jaycs1723658** [comment]
seem problem

**Comment by fred0r** [comment]
since using [rehlds](https://github.com/dreamstalker/rehlds/) with [regamedll_cs](https://github.com/s1lentq/ReGameDLL_CS) and [this](https://www.amxmodx.org/downloads-new.php?branch=master) amxmodx, i never had that error again.
