### ISSUE TITLE
Why sv_voicequality and sv_voicecodec got removed?

### ISSUE THREAD

**Issue by Khalid1997** [ValveSoftware/halflife#743]
I were using low voice quality for my server as I didn't want any extra unneeded extra bandwidth to be used, and now it got removed, so how will I lower the quality, or it won't even affect my bandwidth?

**Comment by rx1983** [comment]
after the new update when someone speaks, the server lag.
hlds: Protocol version 48
Exe version 1.1.2.7 (cstrike)
Exe build: 13:13:29 Aug 29 2013 (6153)

sv_voicequality is disable ?
