### ISSUE TITLE
Problem with OpenGL Counter Strike 1.6

### ISSUE THREAD

**Issue by bene89** [ValveSoftware/halflife#754]
Hello.
I play counter Strike since 2004, and I've never had any problems but now I change my operating system to Windows 7 and now when I launch counter strike, in the menu that can see "New Game, Search games, Options..." I see in the bottom part a blank section and if I put OpenGL in Video Options, the game go too slow, if I change this option to "Software" the game works fine but I cant play so.

I have the same hardware with no problems playing six months ago.

I have the same hardware that I playing without problems six months ago.

I downloaded the lastest drivers for my graphic card to Windows 7.

I try to verify counter strike's files but it dont resolve anything.

If I launch half life, I have the same problem.

I try to change the launch values to:
- nofbo -noforcemaccel -noforcemparms -noforcemspd

I upload a screenshot with the problem. 
http://imageshack.us/photo/my-images/59/csopengl.jpg/

My System specifications:

Processor: Core 2 Duo E6550 - 2,33 GHz
RAM: 3 GB
Graphic card: ATI Radeon HD 2600 Pro
Operating System: Windows 7 Enterprise, 32bits

Sorry for my English level and thank you very much for your Help.

**Comment by Debjit50716** [comment]
I have another problem in opengl mod in play time some time fps drop into 14 or7 from 300. Please help i m non steam player, pc requirments win7 64x,4gb ram,500gb Intel core 2, zebronics mother board G41
