### ISSUE TITLE
[CS1.6] Bullet vector calculation is wrong (REG)

### ISSUE THREAD

**Issue by MPNumB** [ValveSoftware/halflife#83]
Not many know, but bullet vectors are calculated kind of wrong.

What is happening is, that m_flAccuracy variable is updated after the shot is fired. Not before, what is the reason for the glitch.

This effects the gameplay quite much. You can attempt to see it yourself by typing cl_lw 0 (so it will show actual bullet location decals), buy ak47, fire about 20 shots non-stop, wait for recoil to cool down (make sure you don't reload or switch weapons), duck, don't move, make sure you are on ground, and fire one single bullet. Now you will see that this bullet is highly off target.

---

While on this subject, I also must say that scout is quite inaccurate on long range if ducked. It would be really appreciated if standing accuracy would be changed from 0.007 to at least 0.003.

---

Plus sg550 has really bad math (the worse the spread should be, the better it gets). I'd recommend to check code of this amxmodx plugin what fixes this accuracy based issues: http://forums.alliedmods.net/showthread.php?p=1549133
with testing I found that best fix for this weapon is:
{
m_flAccuracy = ( 0.65 + ( gpGlobals->time - m_flLastFire ) ) \* 0.725;
if( m_flAccuracy > 0.98 )
m_flAccuracy = 0.98;
}

---

And I don't want to report too much, but g3sg1 has no active accuracy calculation at all. I mean the m_flAccuracy variable does get updated, but it's never used. I also would recommend to check/test the code/math of it, cause it seems to be have the same glitch as sg550 (the more spread you should get, the more accurate it becomes).

**Comment by drag1c** [comment]
So basically you dont want to update this because it is old bug and it's GAME now?
But just update that first bullet after rifle shot.

**Comment by i486** [comment]
Please fix it and add cvar

**Comment by sergiopoverony** [comment]
LOL

**Comment by wopox1337** [comment]
@mikela-valve it's will it be fixed?

**Comment by SamVanheer** [comment]
Alfred already explained why this won't be fixed.

**Comment by i486** [comment]
> "Use accuracy from last bullet fired earlier" glitch.

This one will be very welcome "change to the game feel" update if it gets fixed. I'd appreciate if @mikela-valve takes his own look at this.

**Comment by BUXPb** [comment]
This is not a bug, this is a feature. This should not be fixed in the 1.6 version never. Do not turn this unique and unique game into a dull likeness of CSGO
