### ISSUE TITLE
HL:BS Training 7th sec. Glass does not break

### ISSUE THREAD

**Issue by ChrisLauinger77** [ValveSoftware/halflife#889]
In Training of HL:BS when shooting the 7 targets, the 7th one is not doable. 
The glass does not break and the training can not be completed. 

Debian wheezy amd64 nvidia 660 gtx

**Comment by NRobot10Modding** [comment]
> Alt fire also did not help. I tried it already.

Jump and alt fire to throw a grenade over the glass
