### ISSUE TITLE
[HL:OF] frozen movement - mouselook and shooting possible

### ISSUE THREAD

**Issue by ChrisLauinger77** [ValveSoftware/halflife#968]
In some parts of the game after an elevator is stopped, I have the problem that I can move my mouse and shoot but I cannot move.
I could workaround this with moving in the elevator araound and when the door opens, run out of it. 
When entering "Pit Worm's Nest" the movement freezes. I have sound, I can mouselook and shoot - but I am stuck.

Its reproducible - I tried many times. I started with -dev and here is the console output:

Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 13:55:36 Mar 28 2013 (5999)
40.0 Mb heap
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce GTX 660/PCIe/SSE2
GL_VERSION: 4.3.0 NVIDIA 313.30
GL_SIZES:  r:8 g:8 b:8 a:0 depth:24
Sound Initialization
Loaded library demoplayer.so.
Loaded library core.so.
Creating fake network channel.
Loaded library core.so.
DemoPlayer module initialized.
Parsed 158 text messages
WARNING: failed to locate sequence file global
joystick not found -- driver not present

execing hw/geforce.cfg
execing valve.rc
execing language.cfg
execing autoexec.cfg
execing violence.cfg
execing hw/geforce.cfg
execing config.cfg
warning: MP3_InitStream(29, media/gamestartup.mp3) failed

Adding:  gearbox/dlls/opfor.so
Dll loaded for mod Opposing Force
Can't register variable mapcyclefile, already defined
Can't register variable servercfgfile, already defined
Can't register variable lservercfgfile, already defined
execing skill.cfg
execing skillopfor.cfg
Loading game from SAVE/quick01.sav...
Spawn Server of4a3
Clearing memory
Using WAD File: xeno.wad
Using WAD File: halflife.wad
Using WAD File: liquids.wad
Using WAD File: opfor.wad
Using WAD File: decals.wad
Texture load:   23.0ms
WARNING: failed to locate sequence file of4a3
Loading game from SAVE/of4a3.HL1...

GAME SKILL LEVEL:2

_Graph Loaded!
*_Graph Pointers Set!
Can't instance func_breakable
Can't instance func_breakable
Can't instance func_breakable
Game started
Local connection.
Connection accepted.
Compressing split packet (7835 -> 4306 bytes)

BUILD 5999 SERVER (0 CRC)
Server # 1
Serverinfo packet received.
Remote host:  Half-Life
Spooling demo header.
Compressing split packet (22455 -> 8016 bytes)
Verifying and downloading resources...
Setting up renderer...
Verifying and uploading resources...
Custom resources total 6.15K

**Comment by JoelTroch** [comment]
Confirming that the elevator issue also happens on Windows (Seven x64 Pro SP1 to be more precise).
```version``` output:
```
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 13:14:12 Aug 29 2013 (6153)
```

[Link to a save of the issue](http://www.mediafire.com/download/9tjd2zcfrdlhr03/OpFor_elevator_bug_save.zip)
